if GetLocale() ~= 'deDE' then return end
SexyLib:InitLocalization('Anniversary Achievements', {
    achievement_earned = '&aErfolg von %s am %d.%d.%d errungen',
    achievement_in_progress = '&aErfolg wird von %s erarbeitet',

    ICON_DESCRIPTION = '&7Linksklick: &eErfolge anzeigen oder schließen\n&7Rechtsklick: &eEinstellungen öffnen\n',

    OPTION_SHARING = 'Erfolge teilen',
    OPTION_SHARING_DESC = 'Neue Erfolge werden im Chat geteilt.',
    OPTION_MICROBUTTON = 'Micromenu Button',
    OPTION_MICROBUTTON_DESC = 'Wird diese Option aktiviert, so wird ein Addon-Button im Menü an der unteren Leiste angezeigt. Dies kann zu Anzeigefehlern führen, wenn andere Addons das Interface verändern. Alternativ wird ein Button an der Minimap angezeigt. Ändern dieser Option benötigt ein /reload des User-Interfaces.',
    OPTION_UPDATE_MAP_EXPLORATION = 'Erkundete Gebiete überprüfen',
    OPTION_UPDATE_MAP_EXPLORATION_DESC = 'Überprüft alle bereits erkundeten Gebiete für Erfolge.',
    OPTION_RESET_ACHIEVEMENTS = 'Erfolge zurücksetzen',
    OPTION_RESET_ACHIEVEMENTS_DESC = 'Setzt alle Erfolge auf diesem Charakter zurück. Dies kann nicht rückgängig gemacht werden!',
    OPTION_TRACKER = 'Ziele beobachten',
    OPTION_TRACKER_DESC = 'Aktiviert oder deaktiviert den Tracker für Erfolge und Quests. Ändern dieser Option benötigt ein /reload des User-Interfaces.',

    GOT_ACHIEVEMENT_MESSAGE_MALE = 'Ich habe folgenden Erfolg erhalten: %s!',
    GOT_ACHIEVEMENT_MESSAGE_FEMALE = 'Ich habe folgenden Erfolg erhalten: %s!',

    COMPARE_ACHIEVEMENTS = 'Erfolge vergleichen',
    TARGET_DOES_NOT_HAVE_ADDON = 'Ziel hat das Addon nicht installiert.',

    UPDATING_EXPLORED_AREAS = 'Aktualisieren der erkundeten Gebiete. Dies kann ein paar Sekunden dauern.',
    UPDATED_EXPLORED_AREAS = '&aErkundete Gebiete wurden aktualisiert!',

    GEAR_SLOT_HEAD = 'Kopf',
    GEAR_SLOT_NECK = 'Hals',
    GEAR_SLOT_SHOULDER = 'Schulter',
    GEAR_SLOT_CHEST = 'Brust',
    GEAR_SLOT_WAIST = 'Taille',
    GEAR_SLOT_LEGS = 'Beine',
    GEAR_SLOT_FEET = 'Füße',
    GEAR_SLOT_WRIST = 'Handgelenke',
    GEAR_SLOT_HANDS = 'Hände',
    GEAR_SLOT_FIRST_RING = 'Linker Ring',
    GEAR_SLOT_SECOND_RING = 'Rechter Ring',
    GEAR_SLOT_FIRST_TRINKET = 'Erstes Schmuckstück',
    GEAR_SLOT_SECOND_TRINKET = 'Zweites Schmuckstück',
    GEAR_SLOT_CLOAK = 'Umhang',
    GEAR_SLOT_WEAPON = 'Waffe',

    NPC_3444 = 'Grubenratte',
    NPC_620 = 'Huhn',
    NPC_1420 = 'Kröte',
    NPC_13321 = 'Frosch',
    NPC_2620 = 'Präriehund',
    NPC_9600 = 'Papagei',
    NPC_883 = 'Reh',
    NPC_9699 = 'Feuerkäfer',
    NPC_4953 = 'Mokassin',
    NPC_721 = 'Hase',
    NPC_9700 = 'Lavakrebs',
    NPC_15476 = 'Skorpion',
    NPC_2914 = 'Natter',
    NPC_16030 = 'Made',
    NPC_4075 = 'Ratte',
    NPC_1412 = 'Eichhörnchen',
    NPC_7390 = 'Nymphensittich',
    NPC_15475 = 'Käfer',
    NPC_15010 = 'Dschungelkröte',
    NPC_4076 = 'Schabe',
    NPC_13016 = 'Untergrundratte',
    NPC_14881 = 'Spinne',
    NPC_2110 = 'Schwarze Ratte',
    NPC_4166 = 'Gazelle',
    NPC_1933 = 'Schaf',
    NPC_890 = 'Rehkitz',
    NPC_2098 = 'Widder',
    NPC_2442 = 'Kuh',
    NPC_6368 = 'Katze',
    NPC_10582 = 'Hund <Vater>',
    NPC_385 = 'Pferd',
    NPC_10685 = 'Schwein',
    NPC_3300 = 'Otter',    
    NPC_15065 = 'Lady',
    NPC_15066 = 'Cleo',
    NPC_15071 = 'Schleicherpfote',
    NPC_15072 = 'Spike',

    CATEGORY_GENERAL = 'Allgemein',
    CATEGORY_QUESTS = 'Quests',
	CATEGORY_PVP = 'Spieler gegen Spieler',
    CATEGORY_KALIMDOR = 'Kalimdor',
    CATEGORY_EASTERN_KINGDOMS = 'Östliche Königreiche',
    CATEGORY_OUTLAND = 'Scherbenwelt',
    CATEGORY_VANILLA = 'Classic',
    CATEGORY_TBC = 'The Burning Crusade',
    CATEGORY_EXPLORATION = 'Erkundung',
    CATEGORY_PVE = 'Dungeons & Schlachtzüge',
    CATEGORY_BG_ALTERAC = 'Alteractal',
    CATEGORY_BG_WARSONG = 'Warsongschlucht',
    CATEGORY_BG_ARATHI = 'Arathibecken',
    CATEGORY_BG_EYE = 'Auge des Sturms',
    CATEGORY_PROFESSIONS = 'Berufe',
    CATEGORY_REPUTATION = 'Ruf',
	CATEGORY_EVENTS = 'Weltereignisse',
	CATEGORY_HALLOWSEND = 'Schlotternächte',
    CATEGORY_WINTERVEIL = 'Winterhauch',
    CATEGORY_FEATS_OF_STRENGTH = 'Heldentaten',
	
	AN_DRUID_T1 = 'Gewänder des Cenarius',
	AN_WARLOCK_T1 = 'Teufelsherzroben',
	AN_PRIEST_T1 = 'Gewänder der Prophezeiung',
	AN_MAGE_T1 = 'Ornat des Arkanisten',
	AN_ROGUE_T1 = 'Der Nachtmeuchler',
	AN_HUNTER_T1 = 'Rüstung des Riesenjägers',
	AN_PALADIN_T1 = 'Rüstung der Gerechtigkeit',
	AN_WARRIOR_T1 = 'Schlachtrüstung der Macht',
	AN_SHAMAN_T1 = 'Die Wut der Erde',
	
	AN_DRUID_T2 = 'Gewänder des Stormrage',
	AN_WARLOCK_T2 = 'Roben der Nemesis',
	AN_PRIEST_T2 = 'Gewänder der Erhabenheit',
	AN_MAGE_T2 = 'Ornat des Netherwinds',
	AN_ROGUE_T2 = 'Blutfangrüstung',
	AN_HUNTER_T2 = 'Rüstung des Drachenjägers',
	AN_PALADIN_T2 = 'Rüstung des Richturteils',
	AN_WARRIOR_T2 = 'Schlachtrüstung des Zorns',
	AN_SHAMAN_T2 = 'Die zehn Stürme',
	
	AN_DRUID_T3 = 'Gewandung des Traumwandlers',
	AN_WARLOCK_T3 = 'Roben des verseuchten Herzens',
	AN_PRIEST_T3 = 'Gewänder des Glaubens',
	AN_MAGE_T3 = 'Frostfeuerornat',
	AN_ROGUE_T3 = 'Rüstung der Knochensense',
	AN_HUNTER_T3 = 'Rüstung des Gruftpirschers',
	AN_PALADIN_T3 = 'Rüstung der Erlösung',
	AN_WARRIOR_T3 = 'Schlachtrüstung des Schreckenspanzers',
	AN_SHAMAN_T3 = 'Der Erdspalter',
	
	AD_SET = 'Sammelt alle Gegenstände des genannten Sets.',		

    AN_LVL = 'Level %d',
    AD_LVL = 'Erreicht Level %d.',

    AN_BANK = 'Sicher angelegt',
    AD_BANK = 'Kauft 6 zusätzliche Bankplätze.',
    AC_BANK = 'Kauft 6 zusätzliche Bankplätze.',

    AN_QUESTS = '%d Quests abgeschlossen',
    AD_QUESTS = 'Schließt %d Quests ab.',
    AC_QUESTS = 'Schließt %d Quests ab.',

    AN_QUEST_GOLD5 = 'Glitzernde Belohnung',
    AN_QUEST_GOLD10 = 'Sammler geprägter Münzen',
    AN_QUEST_GOLD25 = 'Täglich Brot',
    AN_QUEST_GOLD50 = 'Wohlverdientes Gold',
    AN_QUEST_GOLD100 = 'Verdient durch Schweiß und Blut',
    AN_QUEST_GOLD250 = 'Golddrucker',
    AN_QUEST_GOLD500 = 'Angemessene Entlohnung',
    AD_QUEST_GOLD = 'Erhaltet %d Gold durch Questbelohnungen.',
    AC_QUEST_GOLD = 'Erhaltet %d Gold durch Questbelohnungen.',

    AN_QUESTS_ZONE = 'Meister der Lehren - %s',
    AD_QUESTS_ZONE = 'Schließt die Quest "%s" in %s ab.',
    AD_QUESTS_ZONE_MULTI = 'Schließt die folgenden Quests in %s ab.',
    AC_QUESTS_ZONE = 'Schließt die Quest "%s" ab.',

    AZSHARA_1 = 'Azshara',
    AZSHARA_2 = 'Azshara',
    QUEST_3602 = 'Azsharit',

    FELWOOD_1 = 'Teufelswald',
    FELWOOD_2 = 'Teufelswald',
    QUEST_5165 = 'Übergießen der Flammen des Schutzes',
    QUEST_5385 = 'Die Überreste von Trey Lightforge',

    DESOLACE_1 = 'Desolace',
    DESOLACE_2 = 'Desolace',
    QUEST_6027 = 'Buch der Uralten',

    DUSTWALLOW_1 = 'Düstermarschen',
    DUSTWALLOW_2 = 'Düstermarschen',
    QUEST_1203 = 'Jarl braucht eine Klinge',

    SILITHUS_1 = 'Silithus',
    SILITHUS_2 = 'Silithus',
    QUEST_8287 = 'Ein teuflischer Plan',
    QUEST_8352 = 'Szepter des Rates',
    QUEST_8321 = 'Vyral der Üble',
    QUEST_8281 = 'Verstärkte Sicherheit',

    DUROTAR_1 = 'Durotar',
    DUROTAR_2 = 'Durotar',
    QUEST_835 = 'Sicherung der Linien',

    BARRENS_1 = 'Das Brachland',
    BARRENS_2 = 'Das Brachland',
    QUEST_888 = 'Gestohlene Beute',
    QUEST_902 = 'Samophlang',

    WINTERSPRING_1 = 'Winterspring',
    WINTERSPRING_2 = 'Winterspring',
    QUEST_975 = 'Behälter von Mau\'ari',
    QUEST_5082 = 'Bedrohung durch die Winterfelle',
    QUEST_5121 = 'Oberhäuptling der Winterfelle',
    QUEST_5163 = 'Sind wir endlich da, Yeti?',
    QUEST_4842 = 'Sonderbare Quellen',

    TANARIS_1 = 'Tanaris',
    TANARIS_2 = 'Tanaris',
    QUEST_2662 = 'Noggenfogger-Elixier',
    QUEST_2874 = 'Lieferung für MacKinley',
    QUEST_1691 = 'Noch mehr Wüstenläufergerechtigkeit',
    QUEST_113 = 'Insektenteil-Analyse',

    STONETALON_1 = 'Steinkrallengebirge',
    STONETALON_2 = 'Steinkrallengebirge',
    QUEST_1096 = 'Gerenzo Wrenchwhistle',

    UNGORO_1 = 'Un\'Goro Krater',
    UNGORO_2 = 'Un\'Goro Krater',
    QUEST_3962 = 'Allein ist es gefährlich',
    QUEST_4245 = 'Chasing A-Me 01',
    QUEST_4292 = 'Ein Köder für Lar\'korwi',

    THOUSAND_NEEDLES_1 = 'Tausend Nadeln',
    THOUSAND_NEEDLES_2 = 'Tausend Nadeln',
    QUEST_1189 = 'Sicherheit zuerst',

    ARATHI_1 = 'Arathihochland',
    ARATHI_2 = 'Arathihochland',
    QUEST_652 = 'Den Hauptstein zerbrechen',

    BADLANDS_1 = 'Ödland',
    BADLANDS_2 = 'Ödland',
    QUEST_737 = 'Verbotenes Wissen',
    QUEST_778 = 'Das wird schwierig',
    QUEST_656 = 'Beschwören der Prinzessin',
	QUEST_793 = 'Zerbrochene Allianzen',
	QUEST_717 = 'Erdbeben',
    
    EASTERN_PLAGUELANDS_1 = 'Östliche Pestländer',
    EASTERN_PLAGUELANDS_2 = 'Östliche Pestländer',
    QUEST_5942 = 'Versteckte Schätze',
    QUEST_6148 = 'Das Scharlachrote Orakel Demetria',
    QUEST_6187 = 'Ordnung muss wieder hergestellt werden',
    QUEST_5265 = 'Der Argentumtresor',

    BLASTED_LANDS_1 = 'Verwüstete Lande',
    BLASTED_LANDS_2 = 'Verwüstete Lande',
    QUEST_3628 = 'Ihr seid Rakh\'likh, Dämon',

    STRANGLETHORN_VALLEY_1 = 'Schlingendorntal',
    STRANGLETHORN_VALLEY_2 = 'Schlingendorntal',
    QUEST_208 = 'Großwildjagd',
    QUEST_600 = 'Venture Company-Bergbau',
    QUEST_613 = 'Maurys Fuß aufbrechen',
    QUEST_628 = 'Exzelsior',
    QUEST_338 = 'Die Grünen Hügel des Schlingendorntals',
	
	AN_NESINGWARY = 'Die Grünen Hügel des Schlingendorntals',
	AD_NESINGWARY = 'Schließt alle Hemet Nesingwary-Quests im Schlingendorntal ab, bis hin zu \'Die Grünen Hügel des Schlingendorntals\' und \'Großwildjäger\'.',

    WESTERN_PLAGUELANDS_1 = 'Westliche Pestländer',
    WESTERN_PLAGUELANDS_2 = 'Westliche Pestländer',
    QUEST_5944 = 'In den Träumen',
    QUEST_5051 = 'Zwei Hälften vereint',
    QUEST_4985 = 'Die Tierwelt leidet auch',

    SEARING_GORGE_1 = 'Sengende Schlucht',
    SEARING_GORGE_2 = 'Sengende Schlucht',
    QUEST_3481 = 'Plunder...',

    BLACK_ROCK_1 = 'Blackrock',
    BLACK_ROCK_2 = 'Blackrock',
    QUEST_8996 = 'Rückkehr zu Bodley',

    AN_WISDOM_KEEPER = 'Der Meister der Lehren',
    AD_WISDOM_KEEPER = 'Schließt die unten aufgelisteten Questerfolge ab.',
    AN_WISDOM_KEEPER_AZEROTH = 'Meister der Lehren von Azeroth',
    AD_WISDOM_KEEPER_AZEROTH = 'Schließt die unten aufgelisteten Questerfolge ab.',
    AN_WISDOM_KEEPER_KALIMDOR = 'Meister der Lehren in Kalimdor',
    AD_WISDOM_KEEPER_KALIMDOR = 'Schließt die unten aufgelisteten Questerfolge in Kalimdor ab.',
    AN_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Meister der Lehren der östlichen Königreiche',
    AD_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Schließt die unten aufgelisteten Questerfolge in den östlichen Königreichen ab.',
    AN_WISDOM_KEEPER_OUTLAND = 'Meister der Lehren der Scherbenwelt',
    AD_WISDOM_KEEPER_OUTLAND = 'Schließt die unten aufgelisteten Scherbenwelt-Questerfolge ab.',
    AR_WISDOM_KEEPER = 'Meister der Lehren',
	
	AN_SKELETON_KEY = 'Der Schlüssel zur Scholomance',
	AD_SKELETON_KEY = 'Erhaltet den Skelettschlüssel.',

    AN_RAGEFIRE_CHASM = 'Flammenschlund',
    AD_RAGEFIRE_CHASM = 'Bezwingt Taragaman den Hungerleider.',
    AN_WAILING_CAVERNS = 'Die Höhlen des Wehklagens',
    AD_WAILING_CAVERNS = 'Bezwingt Mutanus den Verschlinger.',
    AN_DEAD_MINES = 'Die Todesminen',
    AD_DEAD_MINES = 'Bezwingt Edwin van Cleef.',
    AN_SHADOWFANG_KEEP = 'Burg Shadowfang',
    AD_SHADOWFANG_KEEP = 'Bezwingt Erzmagier Arugal.',
    AN_BLACKFATHOM_DEEPS = 'Blackfathom-Tiefe',
    AD_BLACKFATHOM_DEEPS = 'Bezwingt Aku\'mai.',
    AN_JAIL = 'Verlies von Sturmwind',
    AD_JAIL = 'Bezwingt Bazil Thredd.',
    AN_GNOMREGAN = 'Gnomeregan',
    AD_GNOMREGAN = 'Bezwingt Robogenieur Thermaplugg.',
    AN_RAZORFEN_KRAUL = 'Der Kral von Razorfen',
    AD_RAZORFEN_KRAUL = 'Bezwingt Charlga Razorflank.',
	
    AN_SCARLET_MONASTERY = 'Das Scharlachrote Kloster',
    AD_SCARLET_MONASTERY = 'Bezwingt den Scharlachroten Kreuzzug im Scharlachroten Kloster.',
    AC_SCARLET_MONASTERY1 = 'Blutmagier Thalnos',
    AC_SCARLET_MONASTERY2 = 'Arkanist Doan',
    AC_SCARLET_MONASTERY3 = 'Herod',
    AC_SCARLET_MONASTERY4 = 'Hochinquisitorin Weißsträhne',
    AC_SCARLET_MONASTERY5 = 'Scharlachroter Kommandant Mograine',
	
    AN_RAZORFEN_DOWNS = 'Die Hügel von Razorfen',
    AD_RAZORFEN_DOWNS = 'Bezwingt Amnennar den Kältebringer.',
    AN_ULDAMAN = 'Uldaman',
    AD_ULDAMAN = 'Bezwingt Archaedas.',
    AN_ZULFARRAK = 'Zul\'Farrak',
    AD_ZULFARRAK = 'Bezwingt Häuptling Ukorz Sandscalp.',
    AN_MARAUDON = 'Maraudon',
    AD_MARAUDON = 'Bezwingt Prinzessin Theradras',
    AN_SUNKEN_TEMPLE = 'Versunkener Tempel',
    AD_SUNKEN_TEMPLE = 'Bezwingt Eranikus\' Schemen.',
	
    AN_NEW_EMPEROR = 'Blackrocktiefen',
    AD_NEW_EMPEROR = 'Bezwingt Imperator Dagran Thaurissan.',
    AN_BLACKROCK_DEPTHS = 'Die Tiefen säubern',
    AD_BLACKROCK_DEPTHS = 'Tötet die folgenden Bosse in den Blackrocktiefen.',
    AC_BLACKROCK_DEPTHS1 = 'Verhörmeisterin Gerstahn',
    AC_BLACKROCK_DEPTHS2 = 'Hundemeister Grebmar',
    AC_BLACKROCK_DEPTHS3 = 'General Zornesschmied',
    AC_BLACKROCK_DEPTHS4 = 'Golemlord Argelmach',
    AC_BLACKROCK_DEPTHS5 = 'Lord Incendius',
    AC_BLACKROCK_DEPTHS6 = 'Wärter Stilgiss',
    AC_BLACKROCK_DEPTHS7 = 'Bael\'Gar',
    AN_BLACKROCK_PARTY = 'Party in den Tiefen',
    AD_BLACKROCK_PARTY = 'Bezwingt die folgenden Gegner im Grimmigen Säufer',
    AC_BLACKROCK_PARTY1 = 'Ribbly Screwspigot',
    AC_BLACKROCK_PARTY2 = 'Plugger Spazzring',
    AC_BLACKROCK_PARTY3 = 'Hurley Pestatem',
    AC_BLACKROCK_PARTY4 = 'Phalanx',
    AN_BLACKROCK_DEPTHS_FULL = 'Blackrocktiefen',
    AD_BLACKROCK_DEPTHS_FULL = 'Schließt die unten aufgelisteten Erfolge in den Blackrocktiefen ab.',
    AN_ARMOR_SWORD = 'Angriff ist die bessere Verteidigung',
    AD_ARMOR_SWORD = 'Plündert den Stein der Erde von Panzor den Unbesiegbaren in den Blackrocktiefen.',
	
    AN_BLACKROCK_SPIRE_BOTTOM = 'Untere Blackrockspitze',
    AD_BLACKROCK_SPIRE_BOTTOM = 'Bezwingt Oberanführer Wyrmthalak.',
    AN_BLACKROCK_SPIRE_UPPER = 'Obere Blackrockspitze ',
    AD_BLACKROCK_SPIRE_UPPER = 'Bezwingt General Drakkisath.',
    AN_BLACKROCK_SPIRE = 'Eindringling der Blackrockspitze',
    AD_BLACKROCK_SPIRE = 'Schließt die unten aufgelisteten Erfolge in der Blackrockspitze ab.',
    AN_DIRE_MAUL = 'König des Düsterbruchs',
    AD_DIRE_MAUL = 'Schließt erfolgreich alle Düsterbruch-Dungeons ab.',
    AC_DIRE_MAUL1 = 'Bezwingt Alzzin den Windformer',
    AC_DIRE_MAUL2 = 'Bezwingt Immol\'thar',
    AC_DIRE_MAUL3 = 'Bezwingt König Gordok',
    AN_STRATHOLME = 'Stratholme',
    AD_STRATHOLME = 'Bezwingt die bösen Drahtzieher der Invasion von Stratholme.',
	AC_STRATHOLME1 = 'Baron Rivendare',
	AC_STRATHOLME2 = 'Balnazzar',	
    AN_SCHOLOMANCE = 'Scholomance',
    AD_SCHOLOMANCE = 'Bezwingt die Anführer von Scholomance.',
	AC_SCHOLOMANCE1 = 'Dunkelmeister Gandling',
	AC_SCHOLOMANCE2 = 'Ras Frostraunen',
    AN_YOUNG_DEFENDER = 'Klassischer Dungeonmeister',
    AD_YOUNG_DEFENDER = 'Schließt die unten aufgelisteten Dungeon-Erfolge ab.',
    AN_DEFENDER = 'Verteidiger von Azeroth',
    AD_DEFENDER = 'Schließt die unten aufgelisteten Dungeon-Erfolge ab.',
    AR_DEFENDER = 'Verteidiger von Azeroth',

    AN_ONYXIA = 'Onyxias Hort',
    AD_ONYXIA = 'Bezwingt Onyxia.',
    AN_AQ20 = 'Ruinen von Ahn\'Qiraj',
    AD_AQ20 = 'Bezwingt Ossirian den Narbenlosen.',
    AN_ZULGURUB = 'Zul\'Gurub',
    AD_ZULGURUB = 'Bezwingt Hakkar.',
    AN_RAGNAROS = 'Geschmolzener Kern',
    AD_RAGNAROS = 'Bezwingt Ragnaros.',
    AN_BLACK_WING_LAIR = 'Pechschwingenhort',
    AD_BLACK_WING_LAIR = 'Bezwingt Nefarian.',
    AN_AQ40 = 'Tempel von Ahn\'Qiraj',
    AD_AQ40 = 'Bezwingt C\'Thun.',
    AN_NAXXRAMAS_SPIDERS = 'Das Arachnidenviertel',
    AD_NAXXRAMAS_SPIDERS = 'Bezwingt die Bosse im Arachnidenviertel von Naxxramas',
    AC_NAXXRAMAS_SPIDERS1 = 'Anub\'Rekhan',
    AC_NAXXRAMAS_SPIDERS2 = 'Großwitwe Faerlina',
    AC_NAXXRAMAS_SPIDERS3 = 'Maexxna',
    AN_NAXXRAMAS_PLAGUE = 'Das Seuchenviertel',
    AD_NAXXRAMAS_PLAGUE = 'Bezwingt die Bosse im Seuchenviertel von Naxxramas.',
    AC_NAXXRAMAS_PLAGUE1 = 'Noth der Seuchenfürst',
    AC_NAXXRAMAS_PLAGUE2 = 'Heigan der Unreine',
    AC_NAXXRAMAS_PLAGUE3 = 'Loatheb',
    AN_NAXXRAMAS_MILITARY = 'Das Militärviertel',
    AD_NAXXRAMAS_MILITARY = 'Bezwingt die Bosse im Militärviertel von Naxxramas.',
    AC_NAXXRAMAS_MILITARY1 = 'Instrukteur Razuvious',
    AC_NAXXRAMAS_MILITARY2 = 'Gothik der Ernter',
    AC_NAXXRAMAS_MILITARY3 = 'Die Vier Reiter',
    AN_NAXXRAMAS_CONSTRUCT = 'Das Konstruktviertel',
    AD_NAXXRAMAS_CONSTRUCT = 'Bezwingt die Bosse im Konstruktviertel von Naxxramas.',
    AC_NAXXRAMAS_CONSTRUCT1 = 'Flickwerk',
    AC_NAXXRAMAS_CONSTRUCT2 = 'Grobbulus',
    AC_NAXXRAMAS_CONSTRUCT3 = 'Gluth',
    AC_NAXXRAMAS_CONSTRUCT4 = 'Thaddius',    
    AN_NAXXRAMAS_SAPPHIRON = 'Saphirons Ableben',
    AD_NAXXRAMAS_SAPPHIRON = 'Bezwingt Saphiron in Naxxramas.',
    AN_NAXXRAMAS_LAIR = 'Kel\'Thuzads Niederlage',
    AD_NAXXRAMAS_LAIR = 'Bezwingt Kel\'Thuzad in Naxxramas.',
    AN_NAXXRAMAS = 'Der Fall Naxxramas\'',
    AD_NAXXRAMAS = 'Schließt die unten aufgelisteten Erfolge in Naxxramas ab.',
    AN_YOUNG_HERO = 'Aufstrebender Held von Azeroth',
    AD_YOUNG_HERO = 'Schließt die unten aufgelisteten Schlachtzugserfolge ab.',
    AN_BLACKROCK_MASTER = 'Herr des Blackrock',
    AD_BLACKROCK_MASTER = 'Schließt die unten aufgelisteten Erfolge im Blackrock ab.',
    AN_HERO = 'Held von Azeroth',
    AD_HERO = 'Schließt die unten aufgelisteten Schlachtzugserfolge ab.',
    AR_HERO = 'Held von Azeroth',
    AN_GREAT_HERO = 'Großartiger Held von Azeroth',
    AD_GREAT_HERO = 'Schließt die unten aufgelisteten Dungeon- und Schlachtzugserfolge ab.',
    AR_GREAT_HERO = 'Großartiger Held von Azeroth',

    AN_PVP_RANK_A1 = 'Gefreiter',
    AN_PVP_RANK_A2 = 'Fußknecht',
    AN_PVP_RANK_A3 = 'Landsknecht',
    AN_PVP_RANK_A4 = 'Feldwebel',
    AN_PVP_RANK_A5 = 'Fähnrich',
    AN_PVP_RANK_A6 = 'Leutnant',
    AN_PVP_RANK_A7 = 'Hauptmann',
    AN_PVP_RANK_A8 = 'Kürassier',
    AN_PVP_RANK_A9 = 'Ritter der Allianz',
    AN_PVP_RANK_A10 = 'Feldkommandant',
    AN_PVP_RANK_A11 = 'Rittmeister',
    AN_PVP_RANK_A12 = 'Marschall',
    AN_PVP_RANK_A13 = 'Feldmarschall',
    AN_PVP_RANK_A14 = 'Großmarschall',
    AN_PVP_RANK_H1 = 'Späher',
    AN_PVP_RANK_H2 = 'Grunzer',
    AN_PVP_RANK_H3 = 'Waffenträger',
    AN_PVP_RANK_H4 = 'Schlachtrufer',
    AN_PVP_RANK_H5 = 'Rottenmeister',
    AN_PVP_RANK_H6 = 'Steingardist',
    AN_PVP_RANK_H7 = 'Blutgardist',
    AN_PVP_RANK_H8 = 'Zornbringer',
    AN_PVP_RANK_H9 = 'Klinge der Horde',
    AN_PVP_RANK_H10 = 'Feldherr',
    AN_PVP_RANK_H11 = 'Sturmreiter',
    AN_PVP_RANK_H12 = 'Kriegsherr',
    AN_PVP_RANK_H13 = 'Kriegsfürst',
    AN_PVP_RANK_H14 = 'Oberster Kriegsfürst',
    AD_PVP_RANK = 'Den gleichnamigen Titel erhalten.',
    AN_PVP_FIRST_KILL = 'Ein ehrenhafter Sieg',
    AD_PVP_FIRST_KILL = 'Erringt einen ehrenhaften Sieg.',
    AC_PVP_FIRST_KILL = 'Erringt einen ehrenhaften Sieg',
    AN_PVP_KILLS = '%d ehrenhafte Siege',
    AD_PVP_KILLS = 'Erringt %d ehrenhafte Siege.',
    AC_PVP_KILLS = 'Erringt %d ehrenhafte Siege',

    AN_MOB_KILLS_1 = 'Totschläger',
    AN_MOB_KILLS_2 = 'Zerstörer',
    AN_MOB_KILLS_3 = 'Brecher',
    AN_MOB_KILLS_4 = 'Kopfgeldjäger',
    AN_MOB_KILLS_5 = 'Gewittersturm aller Monster',
    AN_MOB_KILLS_6 = 'Gewittersturm allen Lebens',
    AN_MOB_KILLS_7 = 'Allgegenwärtiger Tod',
    AD_MOB_KILLS = 'Tötet %d Gegner.',
    AC_MOB_KILLS = 'Tötet %d Gegner',

    AN_REPS_1 = 'Jemand mag mich!',
    AD_REPS_1 = 'Erreicht einen ehrfürchtigen Ruf.',
    AC_REPS_1 = 'Erreicht einen ehrfürchtigen Ruf',
    AN_REPS_X = ' ehrfürchtige Fraktionen',
    AD_REPS = 'Erreicht bei %d Fraktionen einen ehrfürchtigen Ruf.',
    AC_REPS = 'Erreicht bei %d Fraktionen einen ehrfürchtigen Ruf.',
    AR_REPS = 'Der Ehrfurchtgebietende',

    AN_HORDE_REPS = 'Botschafter der Horde',
    AD_HORDE_REPS = 'Erreicht einen ehrfürchtigen Ruf in 4 Heimatstädten.',
    AC_HORDE_REPS_1 = 'Ehrfürchtig in Orgrimmar.',
    AC_HORDE_REPS_2 = 'Ehrfürchtig bei den Darkspeartrollen.',
    AC_HORDE_REPS_3 = 'Ehrfürchtig in Undercity.',
    AC_HORDE_REPS_4 = 'Ehrfürchtig in Thunder Bluff.',
    AC_HORDE_REPS_5 = 'Ehrfürchtig in Silbermond.',

    AN_ALLIANCE_REPS = 'Botschafter der Allianz',
    AD_ALLIANCE_REPS = 'Erreicht einen ehrfürchtigen Ruf in 4 Heimatstädten.',
    AC_ALLIANCE_REPS_1 = 'Ehrfürchtig in Stormwind.',
    AC_ALLIANCE_REPS_2 = 'Ehrfürchtig in Darnassus.',
    AC_ALLIANCE_REPS_3 = 'Ehrfürchtig bei den Gnomeregangnomen.',
    AC_ALLIANCE_REPS_4 = 'Ehrfürchtig in Ironforge.',
    AC_ALLIANCE_REPS_5 = 'Ehrfürchtig in der Exodar.',

    AN_ARGENT_DAWN = 'Argentumdämmerung',
    AD_ARGENT_DAWN = 'Erreicht bei der Argentumdämmerung den Status ehrfürchtig.',
    AN_BROOD_OF_NOZDORMU = 'Brut von Nozdormu',
    AD_BROOD_OF_NOZDORMU = 'Erreicht bei der Brut Nozdormus den Status ehrfürchtig.',
    AN_DARKMOON_FAIRE = 'Dunkelmond-Jahrmarkt',
    AD_DARKMOON_FAIRE = 'Erreicht beim Dunkelmond-Jahrmarkt den Status ehrfürchtig.',
    AN_ZANDALAR_TRIBE = 'Stamm der Zandalar',
    AD_ZANDALAR_TRIBE = 'Erreicht beim Stamm der Zandalar den Status ehrfürchtig.',
    AN_HYDRAXIANS = 'Die Hydraxianer',
    AD_HYDRAXIANS = 'Erreicht bei den Hydraxianern den Status ehrfürchtig.',
    AN_TIMBERMAW_HOLD = 'Die stehen auf mich in diesem Tunnel',
    AD_TIMBERMAW_HOLD = 'Erreicht bei der Holzschlundfeste den Status ehrfürchtig.',
    AN_THORIUM = 'Thoriumbruderschaft',
    AD_THORIUM = 'Erreicht bei der Thoriumbruderschaft den Status ehrfürchtig.',
    AN_SHENDRALAR = 'Agent der Shen\'dralar',
    AD_SHENDRALAR = 'Erreicht bei den Shen\'dralar den Status ehrfürchtig.',

    AN_DEFILERS = 'Der Entweihte',
    AD_DEFILERS = 'Erreicht einen ehrfürchtigen Ruf bei den Entweihten.',
    AN_FROSTWOLF_CLAN = 'Held des Frostwolfklans',
    AD_FROSTWOLF_CLAN = 'Erreicht einen ehrfürchtigen Ruf beim Frostwolfklan.',
    AN_WARSONG_OUTRIDERS = 'Warsongvorhut',
    AD_WARSONG_OUTRIDERS = 'Erreicht einen ehrfürchtigen Ruf bei der Warsongvorhut.',
    AN_HORDE_PVP_FRACTIONS = 'Der Eroberer',
    AD_HORDE_PVP_FRACTIONS = 'Erhöht Euren Ruf in der Warsongschlucht, dem Arathibecken und dem Alteractal auf ehrfürchtig.',

    AN_LEAGUE_OF_ARATHOR = 'Ritter von Arathor',
    AD_LEAGUE_OF_ARATHOR = 'Erreicht einen ehrfürchtigen Ruf beim Bund von Arathor.',
    AN_STORMSPIKE_GUARD = 'Held der Sturmlanzengarde',
    AD_STORMSPIKE_GUARD = 'Erreicht einen ehrfürchtigen Ruf bei der Sturmlanzengarde.',
    AN_SILVERWING_SENTINELS = 'Schildwache der Silberschwingen',
    AD_SILVERWING_SENTINELS = 'Erreicht einen ehrfürchtigen Ruf bei der Schildwache der Silberschwingen.',
    AN_ALLIANCE_PVP_FRACTIONS = 'Der Vollstrecker',
    AD_ALLIANCE_PVP_FRACTIONS = 'Erhöht Euren Ruf in der Warsongschlucht, dem Arathibecken und dem Alteractal auf ehrfürchtig.',

    AN_BOLVAR_SLAYER = 'Sturm auf Sturmwind',
    AD_BOLVAR_SLAYER = 'Tötet Hochlord Bolvar Fordragon in Stormwind.',
    AN_MAGNI_SLAYER = 'Tod dem König!',
    AD_MAGNI_SLAYER = 'Tötet König Magni Bronzebart.',
    AN_TYRANDE_SLAYER = 'Von wegen unsterblich',
    AD_TYRANDE_SLAYER = 'Tötet die Hohepriesterin Tyrande Wisperwind.',
    AN_VELEN_SLAYER = 'Das Licht ausmachen',
    AD_VELEN_SLAYER = 'Tötet den Propheten Velen.',

    AN_ALLIANCE_KINGS_SLAYER = 'Für die Horde!',
    AD_ALLIANCE_KINGS_SLAYER = 'Tötet die Anführer der Allianz.',

    AN_THRALL_SLAYER = 'Tod dem Kriegshäuptling!',
    AD_THRALL_SLAYER = 'Tötet Thrall.',
    AN_SYLVANAS_SLAYER = 'Nieder mit der dunklen Fürstin',
    AD_SYLVANAS_SLAYER = 'Tötet Fürstin Sylvanas Windläufer.',
    AN_CAIRNE_SLAYER = 'Blutender Bluthuf',
    AD_CAIRNE_SLAYER = 'Tötet Cairne Bluthuf.',
    AN_LORTHEMAR_SLAYER = 'In Quel\'Thalas getötet',
    AD_LORTHEMAR_SLAYER = 'Tötet Lor\'themar Theron.',

    AN_HORDE_KINGS_SLAYER = 'Für die Allianz!',
    AD_HORDE_KINGS_SLAYER = 'Tötet die Anführer der Horde.',

    AN_RACES_KILLER = 'Kenne deinen Feind',
    AD_ALLIANCE_RACES_KILLER = 'Erringt einen ehrenhaften Todesstoß bei vier verschiedenen Völkern.',
    AD_HORDE_RACES_KILLER = 'Erringt einen ehrenhaften Todesstoß bei vier verschiedenen Völkern.',
    AC_HUMAN_KILLED = 'Mensch',
    AC_NIGHTELF_KILLED = 'Nachtelf',
    AC_DWARF_KILLED = 'Zwerg',
    AC_GNOME_KILLED = 'Gnom',
    AC_ORC_KILLED = 'Orc',
    AC_TROLL_KILLED = 'Troll',
    AC_SCOURGE_KILLED = 'Untoter',
    AC_TAUREN_KILLED = 'Tauren',
    AC_DRAENEI_KILLED = 'Draenei',
    AC_BLOODELF_KILLED = 'Blutelf',

    AN_CLASSES_KILLER = 'Klasse & Stil',
    AD_CLASSES_KILLER = 'Erreicht einen ehrenhaften Todesstoß gegen einen Vertreter jeder Klasse.',
    AC_WARRIOR_KILLED = 'Krieger',
    AC_HUNTER_KILLED = 'Jäger',
    AC_ROGUE_KILLED = 'Schurken',
    AC_PRIEST_KILLED = 'Priester',
    AC_MAGE_KILLED = 'Magier',
    AC_WARLOCK_KILLED = 'Hexenmeister',
    AC_DRUID_KILLED = 'Druide',
    AC_PALADIN_KILLED = 'Paladin',
    AC_SHAMAN_KILLED = 'Schamane',

    AN_ALTERAC_WIN = 'Sieg im Alteractal',
    AD_ALTERAC_WIN = 'Gewinnt im Alteractal.',
    AN_ALTERAC_WINS = 'Veteran des Alteractals',
    AD_ALTERAC_WINS = 'Erringt %d Siege im Alteractal.',
    AN_WARSONG_WIN = 'Sieg in der Warsongschlucht',
    AD_WARSONG_WIN = 'Gewinnt in der Warsongschlucht.',
    AN_WARSONG_WINS = 'Veteran der Warsongschlucht',
    AD_WARSONG_WINS = 'Erringt %d Siege in der Warsongschlucht.',
    AN_ARATHI_WIN = 'Sieg im Arathibecken',
    AD_ARATHI_WIN = 'Gewinnt im Arathibecken.',
    AN_ARATHI_WINS = 'Veteran des Arathibeckens',
    AD_ARATHI_WINS = 'Erringt %d Siege im Arathibecken.',
    AN_EYE_WIN = 'Sieg im Auge des Sturms',
    AD_EYE_WIN = 'Gewinnt im Auge des Sturms.',
    AN_EYE_WINS = 'Veteran im Auge des Sturms',
    AD_EYE_WINS = 'Erringt %d Siege im Auge des Sturms.',

    AN_ALTERAC_KILLING_BLOWS = 'Fleischwolf des Alteractals',
    AD_ALTERAC_KILLING_BLOWS = 'Erreicht %d Todesstöße während einer einzigen Schlacht im Alteractal und bleibt bis zu deren Ende.',
    AN_ALTERAC_GRAVEYARD_ASSAULT = 'Alterac-Grabjäger',
    AD_ALTERAC_GRAVEYARD_ASSAULT = 'Nehmt einen Friedhof während einer einzigen Schlacht im Alteractal ein und bleibt bis zu deren Ende.',
    AN_ALTERAC_GRAVEYARD_ASSAULTS = 'Es fehlt an Särgen',
    AD_ALTERAC_GRAVEYARD_ASSAULTS = 'Nehmt %d Friedhöfe während einer einzigen Schlacht im Alteractal ein und bleibt bis zu deren Ende.',
    AN_ALTERAC_GRAVEYARD_DEFEND = 'Verteidiger der Verstorbenen',
    AD_ALTERAC_GRAVEYARD_DEFEND = 'Verteidigt einen Friedhof während einer einzigen Schlacht im Alteractal und bleibt bis zu deren Ende.',
    AN_ALTERAC_GRAVEYARD_DEFENDS = 'Verteidiger der Toten',
    AD_ALTERAC_GRAVEYARD_DEFENDS = 'Verteidigt %d Friedhöfe während einer einzigen Schlacht im Alteractal und bleibt bis zu deren Ende.',
    AN_ALTERAC_TOWER_ASSAULT = 'Nun gehört er mir!',
    AD_ALTERAC_TOWER_ASSAULT = 'Nehmt einen Turm während einer einzigen Schlacht im Alteractal ein und und bleibt bis zu deren Ende.',
    AN_ALTERAC_TOWER_ASSAULTS = 'Nun gehört ALLES mir!',
    AD_ALTERAC_TOWER_ASSAULTS = 'Nehmt %d Türme während einer einzigen Schlacht im Alteractal ein und bleibt bis zu deren Ende.',
    AN_ALTERAC_TOWER_DEFEND = 'Turmwächter',
    AD_ALTERAC_TOWER_DEFEND = 'Verteidigt einen Turm während einer einzigen Schlacht im Alteractal und bleibt bis zu deren Ende.',
    AN_ALTERAC_TOWER_DEFENDS = 'Turmverteidiger',
    AD_ALTERAC_TOWER_DEFENDS = 'Verteidigt %d Türme während einer einzigen Schlacht im Alteractal und bleibt bis zu deren Ende.',
    AN_ALTERAC_MINE_CAPTURE = 'Gefrorener Bergmann',
    AD_ALTERAC_MINE_CAPTURE = 'Nehmt eine Mine während einer einzigen Schlacht im Alteractal ein und bleibt bis zu deren Ende.',
    AN_ALTERAC_MINE_CAPTURES = 'Gefrorener Pikenier',
    AD_ALTERAC_MINE_CAPTURES = 'Nehmt %d Minen während einer einzigen Schlacht im Alteractal ein und bleibt bis zu deren Ende.',

    AN_WARSONG_KILLS = 'Militärische Auszeichnung',
    AD_WARSONG_KILLS = 'Erreicht %d ehrenhafte Siege während einer einzigen Schlacht in der Warsongschlucht und bleibt bis zu deren Ende.',
    AN_WARSONG_FLAG_CAPTURE = 'Flaggenträger',
    AD_WARSONG_FLAG_CAPTURE = 'Ergreift und erobert die gegnerische Flagge während einer einzigen Schlacht in der Warsongschlucht und bleibt bis zu deren Ende.',
    AN_WARSONG_FLAG_CAPTURES = 'Großartiger Flaggenträger',
    AD_WARSONG_FLAG_CAPTURES = 'Ergreift und erobert %d gegnerische Flaggen während einer einzigen Schlacht in der Warsongschlucht und bleibt bis zu deren Ende.',
    AN_WARSONG_FLAG_RETURN = 'Fasst das nicht an!',
    AD_WARSONG_FLAG_RETURN = 'Bringt als Verteidiger eine Flagge während einer einzigen Schlacht in der Warsongschlucht zurück und bleibt bis zu deren Ende.',
    AN_WARSONG_FLAG_RETURNS = 'Hartnäckiger Verteidiger',
    AD_WARSONG_FLAG_RETURNS = 'Bringt als Verteidiger %d Flaggen während einer einzigen Schlacht in der Warsongschlucht zurück und bleibt bis zu deren Ende.',

    AN_ARATHI_BASE_ASSAULT = 'Konquistador',
    AD_ARATHI_BASE_ASSAULT = 'Erobert eine Basis während einer einzigen Schlacht im Arathibecken und bleibt bis zu deren Ende.',
    AN_ARATHI_BASE_ASSAULTS = 'Flaggenjagd',
    AD_ARATHI_BASE_ASSAULTS = 'Erobert %d Basen während einer einzigen Schlacht im Arathibecken und bleibt bis zu deren Ende.',
    AN_ARATHI_BASE_DEFEND = 'Wächter',
    AD_ARATHI_BASE_DEFEND = 'Verteidigt eine Basis während einer einzigen Schlacht im Arathibecken und bleibt bis zu deren Ende.',
    AN_ARATHI_BASE_DEFENDS = 'Ehrenhafter Wächter',
    AD_ARATHI_BASE_DEFENDS = 'Verteidigt %d Basen während einer einzigen Schlacht im Arathibecken und bleibt bis zu deren Ende.',

    AN_EYE_CAPTURE = 'Sturmeroberer',
    AD_EYE_CAPTURE = 'Ergreift und erobert persönlich die Flagge im Auge des Sturms und bleibt bis zum Ende der Schlacht.',
    AD_EYE_CAPTURES = 'Ergreift und erobert persönlich %d Flaggen im Auge des Sturms und bleibt bis zum Ende der Schlacht.',
    AN_EYE_GLORY = 'Für den Ruhm',
    AD_EYE_GLORY = 'Erobert in einem einzigen Auge des Sturm-Kampfes die Flagge 3-mal, ohne zu sterben.',
    AN_EYE_FAST_WIN = 'Der Sturm',
    AD_EYE_FAST_WIN = 'Gewinnt im Auge des Sturms in weniger als 6 Minuten.',
    AN_EYE_BERSERK = 'Blutrünstiger Berserker',
    AD_EYE_BERSERK = 'Erteilt einen Todesstoß, während Ihr im Auge des Sturms unter dem Stärkungszauber Berserker steht.',
    AN_EYE_IDEAL_VICTORY = 'Der perfekte Sturm',
    AD_EYE_IDEAL_VICTORY = 'Gewinnt im Auge des Sturms mit einem Ergebnis von 1.600 zu 0.',

    AN_BGS_KILLING_BLOWS = 'Todbringer',
    AD_BGS_KILLING_BLOWS = 'Erringt %d Todesstöße auf einem beliebigen Schlachtfeld.',
    AN_BGS_KILLS = 'Todesengel',
    AD_BGS_KILLS = 'Erringt %d ehrenhafte Siege auf einem beliebigen Schlachtfeld.',

    PROF_FIRST_AID = 'Erste Hilfe',
    PROF_FISHING = 'Angeln',
    PROF_COOKING = 'Kochkunst',
    PROF_ENCHANTING = 'Verzauberkunst',
    PROF_TAILORING = 'Schneiderei',
    PROF_ENGINEERING = 'Ingenieurskunst',
    PROF_LEATHERWORKING = 'Lederverarbeitung',
    PROF_ALCHEMY = 'Alchimie',
    PROF_BLACKSMITHING = 'Schmiedekunst',
    PROF_HERBALISM = 'Kräuterkunde',
    PROF_MINING = 'Bergbau',
    PROF_SKINNING = 'Kürschnerei',
    PROF_JEWELCRAFTING = 'Juwelenschleifen',
    SKILL_UNARMED = 'Unbewaffnet',
    SKILL_RIDING = 'Reiten',

    AN_PROFS_JOURNEYMAN = 'Lehrlingsprüfung',
    AD_PROFS_JOURNEYMAN = 'Erlangt 75 Fertigkeitspunkte in einem Beruf.',
    AN_PROFS_EXPERT = 'Gesellenprüfung',
    AD_PROFS_EXPERT = 'Erlangt 150 Fertigkeitspunkte in einem Beruf.',
    AN_PROFS_ARTISAN = 'Professioneller Experte',
    AD_PROFS_ARTISAN = 'Erlangt 225 Fertigkeitspunkte in einem Beruf.',
    AN_PROFS_ONE = 'Professioneller Fachmann',
    AD_PROFS_ONE = 'Erlangt 300 Fertigkeitspunkte in einem Beruf.',
    AN_PROFS_ONE_OUTLAND = 'Meisterprüfung',
    AD_PROFS_ONE_OUTLAND = 'Erlangt 375 Fertigkeitspunkte in einem Beruf.',
    AN_PROFS_TWO = 'Handwerker',
    AD_PROFS_TWO = 'Werdet gleichzeitig in zwei Berufen Fachmann.',
    AC_PROFS_TWO = 'Werdet gleichzeitig in zwei Berufen Fachmann.',
    AN_PROFS_TWO_OUTLAND = 'Handwerker der Scherbenwelt',
    AD_PROFS_TWO_OUTLAND = 'Werdet gleichzeitig in zwei Berufen Meister.',
    AC_PROFS_TWO_OUTLAND = 'Werdet gleichzeitig in zwei Berufen Meister.',

    AN_FIRST_AID_JOURNEYMAN = 'Lehrling in Erster Hilfe',
    AD_FIRST_AID_JOURNEYMAN = 'Erlangt 75 Fertigkeitspunkte in Erster Hilfe.',
    AN_FIRST_AID_EXPERT = 'Geselle in Erster Hilfe',
    AD_FIRST_AID_EXPERT = 'Erlangt 150 Fertigkeitspunkte in Erster Hilfe.',
    AN_FIRST_AID_ARTISAN = 'Experte in Erster Hilfe',
    AD_FIRST_AID_ARTISAN = 'Erlangt 225 Fertigkeitspunkte in Erster Hilfe.',
    AN_FIRST_AID_MASTER = 'Fachmann in Erster Hilfe',
    AD_FIRST_AID_MASTER = 'Erlangt 300 Fertigkeitspunkte in Erster Hilfe.',
    AN_FIRST_AID_OUTLAND_MASTER = 'Meister der Ersten Hilfe',
    AD_FIRST_AID_OUTLAND_MASTER = 'Erlangt 375 Fertigkeitspunkte in Erster Hilfe.',
	
    AN_FISHING_JOURNEYMAN = 'Anglerlehrling',
    AD_FISHING_JOURNEYMAN = 'Erlangt 75 Fertigkeitspunkte im Angeln.',
    AN_FISHING_EXPERT = 'Anglergeselle',
    AD_FISHING_EXPERT = 'Erlangt 150 Fertigkeitspunkte im Angeln.',
    AN_FISHING_ARTISAN = 'Expertenangler',
    AD_FISHING_ARTISAN = 'Erlangt 225 Fertigkeitspunkte im Angeln.',
    AN_FISHING_MASTER = 'Anglerfachmann',
    AD_FISHING_MASTER = 'Erlangt 300 Fertigkeitspunkte im Angeln.',
    AN_FISHING_OUTLAND_MASTER = 'Meisterangler',
    AD_FISHING_OUTLAND_MASTER = 'Erlangt 375 Fertigkeitspunkte im Angeln.',
	
    AN_COOKING_JOURNEYMAN = 'Kochlehrling',
    AD_COOKING_JOURNEYMAN = 'Erlangt 75 Fertigkeitspunkte im Kochen.',
    AN_COOKING_EXPERT = 'Kochgeselle',
    AD_COOKING_EXPERT = 'Erlangt 150 Fertigkeitspunkte im Kochen.',
    AN_COOKING_ARTISAN = 'Expertenkoch',
    AD_COOKING_ARTISAN = 'Erlangt 225 Fertigkeitspunkte im Kochen.',
    AN_COOKING_MASTER = 'Der Kochfachmann',
    AD_COOKING_MASTER = 'Erlangt 300 Fertigkeitspunkte im Kochen.',
    AN_COOKING_OUTLAND_MASTER = 'Meisterkoch',
    AD_COOKING_OUTLAND_MASTER = 'Erlangt 375 Fertigkeitspunkte im Kochen.',
	
    AN_PROFS_SECONDARY = 'Außergewöhnliche Fähigkeiten',
    AD_PROFS_SECONDARY = 'Werdet gleichzeitig Fachmann des Angelns, der Ersten Hilfe und der Kochkunst.',
    AN_PROFS_SECONDARY_OUTLAND = 'Außergewöhnliche Fähigkeiten der Scherbenwelt',
    AD_PROFS_SECONDARY_OUTLAND = 'Werdet gleichzeitig Meister des Angelns, der Ersten Hilfe und der Kochkunst.',
    AN_PROFS_FIVE = 'Genie',
    AN_PROFS_FIVE_OUTLAND = 'Genie der Scherbenwelt',
    AD_PROFS_FIVE = 'Erlangt die unten aufgelisteten Berufserfolge.',
    AN_UNARMED_SKILL = 'Hat jemand ein Veilchen bestellt?',
    AD_UNARMED_SKILL = 'Erreicht eine unbewaffnete Fertigkeit von 300.',

    AN_EXPLORE_AZEROTH = 'Weltenbummler',
    AD_EXPLORE_AZEROTH = 'Erforscht die östlichen Königreiche, Kalimdor und die Scherbenwelt.',
	AR_EXPLORER = 'Entdecker',
    AN_EXPLORE_KALIMDOR = 'Erforscht Kalimdor',
    AD_EXPLORE_KALIMDOR = 'Erforscht die Regionen Kalimdors.',
    AN_EXPLORE_EASTERN_KINGDOMS = 'Erforscht die östlichen Königreiche',
    AD_EXPLORE_EASTERN_KINGDOMS = 'Erforscht die Regionen der östlichen Königreiche.',
	AN_EXPLORE = 'Erforscht %s',
    AD_EXPLORE = 'Erforscht %s und enthüllt die verdeckten Gebiete auf der Weltkarte.',

    AN_SULFURAS = 'Sulfuras, Hand von Ragnaros',
    AD_SULFURAS = 'Träger von Sulfuras, Hand von Ragnaros.',
    AN_THUNDER_FURY = 'Donnerzorn, Gesegnete Klinge des Windsuchers',
    AD_THUNDER_FURY = 'Träger von Donnerzorn, Gesegnete Klinge des Windsuchers.',
    AN_ATIESH = 'Atiesh, Hohestab des Wächters',
    AD_ATIESH = 'Träger von Atiesh, Hohestab des Wächters.',
    AN_BLACK_SCARAB = 'Skarabäusfürst',
    AD_BLACK_SCARAB = 'Die Tore von Ahn\'Qiraj geöffnet.',
    AN_RED_SCARAB = 'Warum? Weil er rot ist!',
    AD_RED_SCARAB = 'Erhaltet einen roten Qirajiresonanzkristall.',
	AN_TIGER_MOUNT = 'Schneller zulianischer Tiger',
    AD_TIGER_MOUNT = 'Erhaltet den schnellen zulianischen Tiger vom Hohepriester Thekal in Zul\'Gurub.',
	AN_RAPTOR_MOUNT = 'Schneller Razzashiraptor',
    AD_RAPTOR_MOUNT = 'Erhaltet den schnellen Razzashiraptor von Blutfürst Mandokir in Zul\'Gurub.',
	AN_BARON_MOUNT = 'Die Zügel des Todesstreitrosses',
    AD_BARON_MOUNT = 'Erhaltet die Zügel des Todesstreitrosses von Totenschwur in Stratholme.',
	AN_SABER_MOUNT = 'Frostsäbler aus Winterquell',
    AD_SABER_MOUNT = 'Erhaltet einen Frostsäbler aus Winterquell.',
    
    AN_UNCOMMON_GEAR = 'Selten',
    AD_UNCOMMON_GEAR = 'Legt an jedem Platz einen Gegenstand von seltener Qualität an.',
    AN_RARE_GEAR = 'Überlegen',
    AD_RARE_GEAR = 'Legt an jedem Platz einen Gegenstand von überragender Qualität an.',
    AN_EPIC_GEAR = 'Episch',
    AD_EPIC_GEAR = 'Legt an jedem Platz einen epischen Gegenstand an.',

    AN_STOCKING_UP = 'Vorrat aufstocken',
    AD_STOCKING_UP = 'Stellt 100 schwere Runenstoffverbände her.',
    AC_STOCKING_UP = 'Stellt 100 schwere Runenstoffverbände her',
    AN_STOCKING_UP_2 = 'Vorrat aufstocken',
    AD_STOCKING_UP_2 = 'Stellt 500 schwere Runenstoffverbände her.',
    AC_STOCKING_UP_2 = 'Stellt 500 schwere Runenstoffverbände her',
    AN_STOCKING_UP_OUTLAND = 'Vorbereitung für die Leere',
    AD_STOCKING_UP_OUTLAND = 'Stellt 100 schwere Netherstoffverbände her.',
    AC_STOCKING_UP_OUTLAND = 'Stellt 100 schwere Netherstoffverbände her',
    AN_STOCKING_UP_2_OUTLAND = 'Vorbereitung für die Leere',
    AD_STOCKING_UP_2_OUTLAND = 'Stellt 500 schwere Netherstoffverbände her.',
    AC_STOCKING_UP_2_OUTLAND = 'Stellt 500 schwere Netherstoffverbände her',

    AN_BOOTY_BAY_CONTEST = 'Für\'s Angeln nur das Beste!',
    AD_BOOTY_BAY_CONTEST = 'Gewinnt den Angelwettbewerb in der Beutebucht und wählt die Arkanitangel oder den Angelhaken des Anglermeisters als Belohnung.',
    AN_BOOTY_BAY_FISH = 'Echter Fischliebhaber',
    AD_BOOTY_BAY_FISH = 'Angelt einen der besonderen Fische während des Angelwettbewerbs in der Beutebucht.',

    AN_FISHING_COLLECTION = 'Fischsammlung',
    AD_FISHING_COLLECTION = 'Fangt die unten aufgelisteten Fische in Azeroth.',
    AN_FISHING_OUTLAND_COLLECTION = 'Fischsammlung der Scherbenwelt',
    AD_FISHING_OUTLAND_COLLECTION = 'Fangt die unten aufgelisteten Fische in der Scherbenwelt.',
    AN_FISHING_WATER = 'Wasser aus Wasser',
    AD_FISHING_WATER = 'Angelt eine Essenz des Wassers.',
    AN_FISHING_RUM = 'Aufhören unmöglich',
    AD_FISHING_RUM = 'Angelt die folgenden Rumsorten.',
    AN_FISHING_RING = 'Geschenk von Mordor',
    AD_FISHING_RING = 'Angelt den Einen Ring.',
    AN_FISHING_SKULL = 'Bote eines traurigen Endes',
    AD_FISHING_SKULL = 'Angelt Old Teamsters Schädel.',
    AN_FISHING_SNAPPER = 'Großer Schnapperfanger',
    AD_FISHING_SNAPPER = 'Angelt Matschschnapper der folgenden Größen.',
    AC_FISHING_SNAPPER = '%d-pfündiger Matschschnapper',
    AN_FISHING_SEA_BASS = 'Barschfänger',
    AD_FISHING_SEA_BASS = 'Angelt Barsche der folgenden Größen.',
    AC_FISHING_SEA_BASS = '%d-pfündiger Barsch',
    AN_FISHING_SALMON = 'Lachsliebhaber',
    AD_FISHING_SALMON = 'Angelt Lachse der folgenden Größen.',
    AC_FISHING_SALMON = '%d-pfündiger Lachs',
    AN_FISHING_LOBSTER = 'Hummerjäger',
    AD_FISHING_LOBSTER = 'Angelt Hummer der folgenden Größen.',
    AC_FISHING_LOBSTER = '%d-pfündiger Hummer',
    AN_FISHING_BIG_SIZE = 'Der größte Angler von Azeroth',
    AD_FISHING_BIG_SIZE = 'Schließt die unten aufgelisteten Angel-Erfolge ab.',
    AR_FISHING_BIG_SIZE = 'Der größte Angler von Azeroth',
	
	AN_FISHING_COUNT = '%d Fische',
	AC_FISHING_COUNT = 'Angelt %d Gegenstände oder Fische.',
	AD_FISHING_COUNT = 'Angelt %d Gegenstände oder Fische.',

    AN_COOKING_RECIPES_5 = 'Freizeitkoch',
    AN_COOKING_RECIPES_10 = 'Commis de Cuisine',
    AN_COOKING_RECIPES_25 = 'Chef de Partie',
    AN_COOKING_RECIPES_50 = 'Sous Chef',
    AN_COOKING_RECIPES_75 = 'Chef de Cuisine',
    AR_COOKING_RECIPES = 'Chefkoch',
    AD_COOKING_RECIPES = 'Lernt %d Kochrezepte.',
    AC_COOKING_RECIPES = 'Lernt %d Kochrezepte',

    AN_COOKING_SOUP = 'Suppenkocher',
    AN_COOKING_DESSERT = 'Konditormeister',
    AN_COOKING_SQUID = 'Fang des Tages',
    AN_COOKING_DUMPLINGS = 'Omas Knödel',
    AN_COOKING_CHOPS = 'Super nahrhafte Koteletts',
    AD_COOKING_CREATE = 'Kocht %s %d-mal.',
    AC_COOKING_CREATE = 'Kocht %s %d-mal',
    AN_COOKING_BIG_TABLE = 'Große Festtafel',
    AD_COOKING_BIG_TABLE = 'Schließt die unten aufgelisteten Kocherfolge ab.',

    AN_COOKING_FISHERMANS_FEAST = 'Fischerschmaus',
    AN_COOKING_SPICY_HOT_TALBUK = 'Feuriger Würztalbuk',
    AN_COOKING_SKULLFISH_SOUP = 'Schädelfischsuppe',
    AN_COOKING_RAVAGER_DOG = 'Heißer Hetzer',

    AN_WB_AZUREGOS = 'Das Geheimnis des blauen Drachens',
    AD_WB_AZUREGOS = 'Bezwingt Azuregos.',
    AN_WB_KAZZAK = 'Dämonen können nicht vorbei',
    AD_WB_KAZZAK = 'Bezwingt Lord Kazzak.',
    AN_WB_KAZZAK_OUTLAND = ' Ich bin der Meister meines Schicksals',
    AD_WB_KAZZAK_OUTLAND = 'Bezwingt Verdammnislord Kazzak auf der Höllenfeuerhalbinsel.',
    AN_WB_DOOMWALKER = 'Kaputter Verdammniswandler',
    AD_WB_DOOMWALKER = 'Bezwingt den Verdammniswandler im Schattenmondtal.',
    AN_WB_YSONDRE = 'Kein Platz für Mädchen in einem Albtraum',
    AD_WB_YSONDRE = 'Bezwingt Ysondre.',
    AN_WB_LETHON = 'Kind des Smaragdgrünen Albtraums',
    AD_WB_LETHON = 'Bezwingt Lethon.',
    AN_WB_EMERISS = 'Emeriss, Verräter des Lebens',
    AD_WB_EMERISS = 'Bezwingt Emeriss.',
    AN_WB_TAERAR = 'Albtraumhafte Taerar',
    AD_WB_TAERAR = 'Bezwingt Taerar.',
    AN_WB_EMERALD_DRAGONS = 'Smaragdgrüner Wächter',
    AD_WB_EMERALD_DRAGONS = 'Bezwingt alle Drachen des Smaragdgrünen Albtraums.',
    AR_WB_EMERALD_DRAGONS = 'Smaragdgrüner Wächter',

    AN_DUEL = 'Duell-ikat',
    AD_DUEL = 'Gewinnt ein Duell gegen einen anderen Spieler.',
    AN_DUELS_10 = 'Duellist',
    AN_DUELS_25 = 'Geübter Duellist',
    AN_DUELS_100 = 'Meister-Duellist',
    AD_DUELS = 'Gewinnt in %d Duellen.',
    AC_DUELS = 'Gewinnt in %d Duellen',
    AN_GURUBASHI_1 = 'Gurubashi Arenameister',
    AD_GURUBASHI_1 = 'Plündert den Schmuck des Arenameisters in der Arena der Gurubashi.',
    AN_GURUBASHI_2 = 'Gurubashi Arenagroßmeister',
    AD_GURUBASHI_2 = 'Schließt die Quest von Störtebrecher ab, um den Schmuck des Arenagroßmeisters zu erhalten.',
    AN_PARTICIPATE_IN_BGS = 'Ruf zu den Waffen!',
    AD_PARTICIPATE_IN_BGS = 'Schließt %d Schlachtfelder ab.',
    AC_PARTICIPATE_IN_BGS = 'Schließt %d Schlachtfelder ab.',

    EMOTE_LOVE1 = 'Ihr liebt %s.',
    AN_LOVE = 'Ob groß, ob klein, Tiere sind alle fein',
    AD_LOVE = 'Zeigt den Tieren in Azeroth, wie sehr Ihr sie liebt (/liebe).',
    EMOTE_PAT1 = 'Ihr streichelt %s.',
    AN_ARATHI_CATS = 'Katzen sind am wichtigsten',
    AD_ARATHI_CATS = 'Streichelt die angegebenen Haustiere im Arathibecken (/streicheln).',

    AN_ALTERAC_FAST_WIN = 'Der Alteracblitz',
    AD_ALTERAC_FAST_WIN = 'Gewinnt im Alteractal innerhalb von 6 Minuten.',
    AN_WARSONG_FAST_WIN = 'Motivation der Warsong',
    AD_WARSONG_FAST_WIN = 'Gewinnt in der Warsongschlucht in weniger als 7 Minuten.',
    AN_ARATHI_FAST_WIN = 'Auf die Schnelle',
    AD_ARATHI_FAST_WIN = 'Gewinnt im Arathibecken in 6 Minuten.',

    AN_ALTERAC_TOWER_DEFEND_TOTAL = 'Turmverteidigung',
    AD_ALTERAC_TOWER_DEFEND_TOTAL = 'Verteidigt %d Türme im Alteractal.',
    AN_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Alterac-Grabjäger',
    AD_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Nehmt %d Friedhöfe im Alteractal ein.',
    AN_WARSONG_FLAG_CAPTURE_TOTAL = 'Erobert die Flagge',
    AD_WARSONG_FLAG_CAPTURE_TOTAL = 'Ergreift und erobert persönlich %d Flaggen in der Warsongschlucht.',
    AN_WARSONG_FLAG_RETURN_TOTAL = 'Hartnäckiger Verteidiger',
    AD_WARSONG_FLAG_RETURN_TOTAL = 'Bringt als Verteidiger in der Warsongschlucht %d Flaggen zurück.',
    AN_ARATHI_BASE_ASSAULT_TOTAL = 'Flaggenjagd',
    AD_ARATHI_BASE_ASSAULT_TOTAL = 'Erobert %d Flaggen im Arathibecken.',
    AN_ARATHI_BASE_DEFEND_TOTAL = 'Rettungseinsatz',
    AD_ARATHI_BASE_DEFEND_TOTAL = 'Eilt im Arathibecken %d-mal zur Verteidigung einer Basis, indem Ihr die Flagge zurückerobert.',
    AN_ALTERAC_MOUNT_HORDE = 'Frostwolfheuler',
    AD_ALTERAC_MOUNT_HORDE = 'Erhaltet einen Frostwolfheuler.',
    AN_ALTERAC_MOUNT_ALLIANCE = 'Streitwidder der Sturmlanzen',
    AD_ALTERAC_MOUNT_ALLIANCE = 'Erhaltet einen Streitwidder der Sturmlanzen.',

    AN_ALTERAC_BOSS = 'Meister des Alteractals',
    AD_ALTERAC_BOSS = 'Schließt die unten aufgelisteten Questerfolge im Alteractal ab.',
    AN_WARSONG_BOSS = 'Meister der Warsongschlucht',
    AD_WARSONG_BOSS = 'Schließt die unten aufgelisteten Questerfolge in der Warsongschlucht ab.',
    AN_ARATHI_BOSS = 'Meister des Arathibeckens',
    AD_ARATHI_BOSS = 'Schließt die unten aufgelisteten Arathibeckenerfolge ab.',
    AN_EYE_BOSS = 'Meister des Auge des Sturms',
    AD_EYE_BOSS = 'Schließt die unten aufgelisteten Erfolge im Auge des Sturms ab.',
    AN_BATTLEMASTER = 'Kampfmeister',
    AD_BATTLEMASTER = 'Schließt die unten aufgelisteten Schlachtfeld-Erfolge ab.',
    AR_BATTLEMASTER = 'Kampfmeister',

    AN_LEEROY = 'Leeeeeeeeeeeeeeeroy!',
    AD_LEEROY = 'Tötet 50 Krähenhorstwelpen innerhalb von 15 Sekunden.',
    AR_LEEROY = 'Jenkins',
    AN_BWL_DUO = 'Doppelter Atem',
    AD_BWL_DUO = 'Bezwingt Schattenschwinge und Flammenmaul innerhalb von 45 Sekunden.',
    AN_ANUBREKHAN_WITHOUT_MOBS = 'Der böse Spinnenlord',
    AD_ANUBREKHAN_WITHOUT_MOBS = 'Bezwingt Anub\'Rekhan in Naxxramas, während beide Gruftwachen am Leben sind.',
    AN_FAERLINA_WITHOUT_MOBS = 'Witwenjäger',
    AD_FAERLINA_WITHOUT_MOBS = 'Bezwingt Großwitwe Faerlina in Naxxramas, während alle Anhänger und Jünger von Naxxramas am Leben sind.',
    AN_SAPPHIRONE_WITH_ALL_ALIVE = 'Ziemlich frostig hier',
    AD_SAPPHIRONE_WITH_ALL_ALIVE = 'Bezwingt Saphiron in Naxxramas, ohne dass jemand aus dem Schlachtzug stirbt.',
    AN_ARACHNOPHOBIA = 'Arachnophobie',
    AD_ARACHNOPHOBIA = 'Bezwingt Maexxna in Naxxramas innerhalb von 20 Minuten nach Anub\'Rekhans Tod.',
    AN_FOUR_TOGETHER = 'Zusammen bis in den Tod',
    AD_FOUR_TOGETHER = 'Bezwingt die Vier Reiter in Naxxramas, wobei sie im Abstand von höchstens 15 Sekunden hintereinander sterben müssen.',
	AN_HEIGAN_DANCE = 'Auf Nummer sicher',
    AD_HEIGAN_DANCE = 'Bezwingt Heigan den Unreinen in Naxxramas, ohne dass jemand aus dem Schlachtzug stirbt.',
	AN_PATCHWERK = 'Legt Flickwerk schnell das Handwerk',
    AD_PATCHWERK = 'Bezwingt Flickwerk in Naxxramas in höchstens 3 Minuten.',
    AN_KELTHUZAD_ABOMINATIONS = 'Ich krieg\' einfach nicht genug',
    AD_KELTHUZAD_ABOMINATIONS = 'Bezwingt Kel\'Thuzad in Naxxramas, nachdem ihr mindestens 18 Monstrositäten in seiner Kammer besiegt habt.',
	
	AN_PIRATES_HAT = 'Segel setzen, Admiral!',
	AD_PIRATES_HAT = 'Erhaltet den Blutsegeladmiralshut... und versucht, zwischendurch etwas frische Luft zu tanken.',
	AR_PIRATES_HAT = 'Blutsegeladmiral',	
	AN_PALADIN_MOUNT = 'Streitross',
	AD_PALADIN_MOUNT = 'Die Paladinquest zur Erlangung eines Streitrosses abgeschlossen.',
	AN_WARLOCK_MOUNT = 'Schreckensross von Xoroth',
	AD_WARLOCK_MOUNT = 'Die Hexenmeisterquest zur Beschwörung eines Schreckensrosses von Xoroth abgeschlossen.',
	
	AN_HALLOWSEND = 'Geschlottert werde dein Name',
	AD_HALLOWSEND = 'Schließt die unten aufgelisteten Schlotternächte-Erfolge ab.',
	AR_HALLOWSEND = 'Nachtschrecken',
	
	AN_PUMPKIN = 'Ziemlich gruselig',
	AD_PUMPKIN = 'Erhaltet eine Kürbistasche während der Schlotternächte.',
	AN_HALLOWSEND_ALLIANCE_QUEST1 = 'Fauliges Schlottern',
	AD_HALLOWSEND_ALLIANCE_QUEST1 = 'Ruiniert die Schlotternächte für die Horde. Schließt dafür die Quests für Unteroffizier Hartman ab, die das Bespitzeln des Fests des Weidenmanns und das Aufräumen Süderstades von den Stinkbomben vorsehen.',
	AC_HALLOWSEND_ALLIANCE_QUEST1_CRITERIA1 = 'Bespitzelt das Fest des Weidenmanns',
	AC_HALLOWSEND_ALLIANCE_QUEST1_CRITERIA2 = 'Die Kraft der Pinie',
	AN_HALLOWSEND_HORDE_QUEST1 = 'Fauliges Schlottern',
	AD_HALLOWSEND_HORDE_QUEST1 = 'Ruiniert die Schlotternächte für die Allianz. Schließt dafür die Quests für die Ruferin der Dunkelheit, Yanka, ab, die Euch nach Süderstade führen, damit Ihr dort die Fässer mit faulen Eiern ruiniert und Stinkbomben in die Stadt werft.',
	AC_HALLOWSEND_HORDE_QUEST1_CRITERIA1 = 'Faule Eier und verdorbenes Bier',
	AC_HALLOWSEND_HORDE_QUEST1_CRITERIA2 = 'Die Verpestung von Süderstade',
	
	AN_HALLOWSEND_ALLIANCE_QUEST2 = 'Schlotternachtssüßigkeiten für Jesper!',
	AD_HALLOWSEND_ALLIANCE_QUEST2 = 'Sammelt die gewünschten Süßigkeiten für Jesper.',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA1 = 'Nugat aus Stormwind',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA2 = 'Kaugummikugel aus Gnomeregan',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA3 = 'Pfefferminzbonbon aus Ironforge',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA4 = 'Marzipan aus Darnassus',
	AN_HALLOWSEND_HORDE_QUEST2 = 'Schlotternachtssüßigkeiten für Spoops!',
	AD_HALLOWSEND_HORDE_QUEST2 = 'Sammelt die gewünschten Süßigkeiten für Spoops.',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA1 = 'Nugat aus Orgrimmar',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA2 = 'Kaugummikugel der Darkspear',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA3 = 'Pfefferminzbonbon aus Undercity',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA4 = 'Marzipan aus Thunder Bluff',
	
	AN_HALLOWSEND_INVOCATION_BUFF = 'Anrufung des Weidenmanns',
	AD_HALLOWSEND_INVOCATION_BUFF = 'Erhaltet während der Schlotternächte den Stärkungszauber "Anrufung des Weidenmanns".',
	
	AN_HALLOWSEND_TREATS = 'Süßes oder Saures!',
	AD_HALLOWSEND_TREATS = 'Erhaltet einen Schlotterbeutel von einem Gastwirt.',
	
	AN_HALLOWSEND_MASK = 'Maskiert',
	AD_HALLOWSEND_MASK = 'Erhaltet während der Schlotternächte eine leichte Maske.',
	
	AN_HALLOWSEND_MASKS = 'Eine Maske für jede Gelegenheit',
	AD_HALLOWSEND_MASKS = 'Sammelt die 16 unten aufgelisteten einzigartigen leichten Masken.',
	
	AN_HALLOWSEND_TRANSFORM = 'Die Maskerade',
	AD_HALLOWSEND_TRANSFORM = 'Lasst Euch von den unten aufgelisteten Stäben der Verwandlung transformieren.',
	AC_HALLOWSEND_GHOST = 'Durch den Stab der Verwandlung transformiert - Geist',
	AC_HALLOWSEND_GNOME = 'Durch den Stab der Verwandlung transformiert - Lepragnom',
	AC_HALLOWSEND_WISP = 'Durch den Stab der Verwandlung transformiert - Irrwisch',
	AC_HALLOWSEND_NINJA = 'Durch den Stab der Verwandlung transformiert - Ninja',
	AC_HALLOWSEND_SKELETON = 'Durch den Stab der Verwandlung transformiert - Skelett',
	AC_HALLOWSEND_PIRATE = 'Durch den Stab der Verwandlung transformiert - Pirat',
	AC_HALLOWSEND_BAT = 'Durch den Stab der Verwandlung transformiert - Fledermaus',

    --WINTERVEIL
    AN_WINTERVEIL = 'Winterhauchengel',
	AD_WINTERVEIL = 'Schließt die unten aufgelisteten Winterhaucherfolge ab.',
	AR_WINTERVEIL = 'Winterhauchengel',

    AN_WINTERVEIL_METZEN = 'Auf Metzen!',
	AD_WINTERVEIL_METZEN = 'Rettet Metzen das Rentier.',

    AN_WINTERVEIL_SMOKEYWOOD = 'Einfach grässlich',
	AD_WINTERVEIL_SMOKEYWOOD = 'Schließt die Quest zur Wiederbeschaffung von Kokelwälders gestohlenen Leckereien ab und erhaltet ein Dankeschön von Kokelwälder.',

    AN_WINTERVEIL_GOURMET = 'Der Winterhauch-Gourmet',
	AD_WINTERVEIL_GOURMET = 'Nutzt während des Winterhauchfests Eure kulinarische Expertise, um einen Lebkuchen und einen Eierflip herzustellen.',
    AC_WINTERVEIL_GOURMET_CRITERIA1 = 'Lebkuchen',
    AC_WINTERVEIL_GOURMET_CRITERIA2 = 'Eierflip',

    AN_WINTERVEIL_PRESENTS = 'Waren wir brav dieses Jahr?',
	AD_WINTERVEIL_PRESENTS = 'Öffnet eines der Geschenke unter dem Winterhauchbaum, sobald sie verfügbar sind.',

    AN_WINTERVEIL_SNOWBALL_ALLIANCE = 'Mitten ins Gesicht',
	AD_WINTERVEIL_SNOWBALL_ALLIANCE = 'Werft während des Winterhauchfests einen Schneeball auf König Magni Bronzebeard.',

    AN_WINTERVEIL_SNOWBALL_HORDE = 'Mitten ins Gesicht',
	AD_WINTERVEIL_SNOWBALL_HORDE = 'Werft während des Winterhauchfests einen Schneeball auf Cairne Bloodhof.',

    AN_WINTERVEIL_PVP = 'Kleiner Helfer in der Not',
    AD_WINTERVEIL_PVP = 'Erringt 50 ehrenhafte Siege als kleiner Helfer der Winterwundervolt-Maschine.',

	--BURNING CRUSADE
    AN_QUESTS_HELLFIRE_PENINSULA = 'Durchs Höllenfeuer und zurück',
    AD_QUESTS_HELLFIRE_PENINSULA = 'Schließt die folgenden Geschichtsstränge auf der Höllenfeuerhalbinsel ab.',
    TBC_QUEST_10388 = 'Haltet die Brennende Legion auf',
    TBC_QUEST_10389 = 'Grausame Pläne',
    TBC_QUEST_10876 = 'Die Hand von Kargath',
    TBC_QUEST_10258 = 'Rückenbrecherposten',
    TBC_QUEST_9406 = 'Die Mag\'har',
    TBC_QUEST_9370 = 'Falkenwacht',
    TBC_QUEST_10351 = 'Posten des Cenarius',

    TBC_QUEST_10397 = 'Haltet die Brennende Legion auf',
    TBC_QUEST_10400 = 'Stürzt den Oberanführer',
    TBC_QUEST_9545 = 'Die Suche nach Sedai',
    TBC_QUEST_10935 = 'Der Exorzismus des Oberst Jules',
    TBC_QUEST_10937 = 'Die Züchtigung des Drillmeisters',
    TBC_QUEST_9383 = 'Tempel von Telhamat',
    TBC_QUEST_10630 = 'Grün, aber kein Orc',
    
    AN_QUESTS_ZANGARMASH = 'Mysterien der Marschen',
    AD_QUESTS_ZANGARMASH = 'Schließt die folgenden Geschichtsstränge in den Zangarmarschen ab.',
    TBC_QUEST_9772 = 'Sumpfrattenposten',
    TBC_QUEST_9904 = 'Zabra\'jin',
    TBC_QUEST_10118 = 'Die Verteidigung von Zabra\'jin',
    TBC_QUEST_9803 = 'Draeneidiplomatie',
    TBC_QUEST_9783 = 'Telredor',
    TBC_QUEST_9902 = 'Oreborzuflucht',
    TBC_QUEST_9709 = 'DIESE Pilze solltet Ihr nicht essen!',
    TBC_QUEST_9732 = 'Trockenlegung der Marschen',
    TBC_QUEST_9788 = 'Rettung der Sporloks',
    TBC_QUEST_9726 = 'Ein Ausflug mit dem Sporlingen',
    
    AN_QUESTS_TERROKAR = 'Terror in Terokkar',
    AD_QUESTS_TERROKAR = 'Schließt die folgenden Geschichtsstränge in den Wäldern von Terrokkar ab.',
    TBC_QUEST_10879 = 'Offensive aus Skettis',
    TBC_QUEST_10881 = 'Flüchtlingskarawane',
    TBC_QUEST_10915 = 'Basislager der Sha\'tari',
    TBC_QUEST_9951 = 'Das Geheimnis des Aufsehers',
    TBC_QUEST_10042 = 'Allerias Feste',
    TBC_QUEST_10043 = 'Steinbrecherfeste',
    
    AN_QUESTS_NAGRAND = 'Nagrand Slam',
    AD_QUESTS_NAGRAND = 'Schließt die folgenden Geschichtsstränge in Nagrand ab.',
    TBC_QUEST_10172 = 'Geburt eines Kriegshäuptlings',
    TBC_QUEST_9977 = 'Der Ring des Blutes',
    TBC_QUEST_9853 = 'Thron der Elemente',
    TBC_QUEST_9934 = 'Lantresor von der Klinge',
    TBC_QUEST_9868 = 'Die Finsterblutzerschlagenen',
    TBC_QUEST_9937 = 'Bedrohungen für Nagrand',
    TBC_QUEST_9852 = 'Die ultimative Beute',
    TBC_QUEST_9925 = 'Begegnung mit den Astralen',
    TBC_QUEST_9955 = 'Die Abenteuer von Corki',
    TBC_QUEST_9933 = 'Lantresor von der Klinge',
    TBC_QUEST_9873 = 'Die Finsterblutzerschlagenen',
    TBC_QUEST_10011 = 'Bedrohungen für Nagrand',
    
    AN_QUESTS_BLADES_EDGE_MTNS = 'Auf schmalem Grat',
    AD_QUESTS_BLADES_EDGE_MTNS = 'Schließt die folgenden Geschichtsstränge im Schergrat ab.',
    TBC_QUEST_10504 = 'Sylvanaar',
    TBC_QUEST_10671 = 'Toshleys Station',
    TBC_QUEST_10806 = 'Die Gronnbedrohung',
    TBC_QUEST_10505 = 'Donnerfeste',
    TBC_QUEST_10742 = 'Zusammenführung',
    TBC_QUEST_10867 = 'Die Mok\'Nathal',
    TBC_QUEST_10748 = 'Der Ruuanwald',
    
    AN_QUESTS_NETHERSTORM = 'In den Nether',
    AD_QUESTS_NETHERSTORM = 'Schließt die folgenden Geschichtsstränge im Nethersturm ab.',
    TBC_QUEST_10409 = 'Socrethar',
    TBC_QUEST_10240 = 'Der Violette Turm',
    TBC_QUEST_10249 = 'Beschützt Area 52!',
    TBC_QUEST_10439 = 'Zerstörung des Allesverschlingenden',
    TBC_QUEST_10221 = 'Bau der X-52 Netherrakete',
    TBC_QUEST_10276 = 'Das Konsortium',
    
    AN_QUESTS_SHADOWMOON = 'Schatten des Verräters',
    AD_QUESTS_SHADOWMOON = 'Schließt die folgenden Geschichtsstränge im Schattenmondtal ab.',
    TBC_QUEST_10744 = 'Nachricht vom Sieg',
    TBC_QUEST_11041 = 'Netherschwingenscherbe',
    TBC_QUEST_10645 = 'Der erste Todesritter',
    TBC_QUEST_10651 = 'Geliehene Macht',
    TBC_QUEST_11052 = 'Akamas Versprechen',
    TBC_QUEST_10588 = 'Die Litanei der Verdammnis',
    TBC_QUEST_10679 = 'Antidämonenwaffen',
    TBC_QUEST_10808 = 'Der Dunkle Rat',
	
	AN_HEMET_QUESTS_NAGRAND = 'Hügel wie weiße Elekk',
	AD_HEMET_QUESTS_NAGRAND = 'Schließt alle Hemet Nesingwary-Quests in Nagrand bis hin zu und inklusive \'Die ultimative Beute\' ab.',

    HEROIC_NAME_PATTERN = 'Heroisch: %s',
    HEROIC_DESCRIPTION_PATTERN = '%s auf dem Schwierigkeitsgrad \'Heroisch\'',

    AN_HELLFIRE_RAMPARTS = 'Höllenfeuerbollwerk',
    AD_HELLFIRE_RAMPARTS = 'Bezwingt die Anführer im Höllenfeuerbollwerk',
    AC_BOSS_17308 = 'Omor den Narbenlosen',
    AC_BOSS_17537 = 'Vazruden der Herold',
	AC_BOSS_17536 = 'Nazan',

    AN_BLOOD_FURNACE = 'Der Blutkessel',
    AD_BLOOD_FURNACE = 'Bezwingt Keli\'dan den Zerstörer',

    AN_SLAVE_PENS = 'Die Sklavenunterkünfte',
    AD_SLAVE_PENS = 'Bezwingt Quagmirran',

    AN_UNDERBOG = 'Tiefensumpf',
    AD_UNDERBOG = 'Bezwingt die Schattenmutter',

    AN_MANA_TOMBS = 'Managruft',
    AD_MANA_TOMBS = 'Bezwingt den Nexusprinzen Shaffar',

    AN_AUCHENAI_CRYPTS = 'Auchenaikrypta',
    AD_AUCHENAI_CRYPTS = 'Bezwingt Exarch Maladaar',

    AN_OLD_HILLSBRAD = 'Die Flucht aus Durnholde',
    AD_OLD_HILLSBRAD = 'Bezwingt den Epochenjäger',

    AN_SETHEKK_HALLS = 'Sethekkhallen',
    AD_SETHEKK_HALLS = 'Bezwingt den Klauenkönig Ikiss',

    AN_STEAMVAULT = 'Die Dampfkammer',
    AD_STEAMVAULT = 'Bezwingt den Kriegsherrn Kalithresh',

    AN_SHADOW_LABYRINTH = 'Schattenlabyrinth',
    AD_SHADOW_LABYRINTH = 'Bezwingt Murmur',

    AN_SHATTERED_HALLS = 'Die Zerschmetterten Hallen',
    AD_SHATTERED_HALLS = 'Bezwingt den Kriegshäuptling Kargath Messerfaust',

    AN_BLACK_MORASS = 'Öffnung des Dunklen Portals',
    AD_BLACK_MORASS = 'Bezwingt Aeonus',

    AN_BOTANICA = 'Die Botanika',
    AD_BOTANICA = 'Bezwingt Warpzweig',

    AN_MECHANAR = 'Die Mechanar',
    AD_MECHANAR = 'Bezwingt Pathaleon den Kalkulator',

    AN_ARCATRAZ = 'Die Arkatraz',
    AD_ARCATRAZ = 'Bezwingt Herold Horizontiss',
	
	AN_MAGISTERS_TERRACE = 'Terrasse der Magister',
    AD_MAGISTERS_TERRACE = 'Bezwingt Kael\'thas Sonnenwanderer',
	
	AN_TBC_DUNGEONS = 'Dungeonmeister der Scherbenwelt',
    AD_TBC_DUNGEONS = 'Schließt die unten aufgelisteten "Burning Crusade"-Dungeonerfolge ab.',

    AN_TBC_DUNGEONS_HERO = 'Dungeonheld der Scherbenwelt',
    AD_TBC_DUNGEONS_HERO = 'Schließt die unten aufgelisteten heroischen "Burning Crusade"-Dungeonerfolge ab.',

    AN_RAVEN_LORD = 'Die Zügel des Rabenfürsten',
    AD_RAVEN_LORD = 'Erhaltet die Zügel des Rabenfürsten von Anzu in den Sethekkhallen.',

    AN_KARAZHAN = 'Karazhan',
    AD_KARAZHAN = 'Bezwingt Prinz Malchezaar in Karazhan.',

    AN_GRUUL = 'Gruuls Unterschlupf',
    AD_GRUUL = 'Bezwingt Gruul den Drachenschlächter in Gruuls Unterschlupf.',

    AN_MAGTHERIDON = 'Magtheridons Kammer',
    AD_MAGTHERIDON = 'Bezwingt Magtheridon in Magtheridons Kammer.',
	
	AN_ZULAMAN = 'Zul\'Aman',
	AD_ZULAMAN = 'Bezwingt Zul\'jin in Zul\'Aman.',
	
	AN_SUNWELL = 'Das Sonnenbrunnenplateau',
	AD_SUNWELL = 'Bezwingt Kil\'jaeden auf dem Sonnenbrunnenplateau.',

    AN_TBC_PHASE_1 = 'Scherbenwelt-Schlachtzugsmeister - Phase 1',
    AD_TBC_PHASE_1 = 'Schließt die unten aufgelisteten Schlachtzugserfolge der Scherbenwelt ab.',
    AN_TBC_PHASE_2 = 'Scherbenwelt-Schlachtzugsmeister - Phase 2',
    AD_TBC_PHASE_2 = 'Schließt die unten aufgelisteten Schlachtzugserfolge der Scherbenwelt ab.',
    AN_TBC_PHASE_3 = 'Scherbenwelt-Schlachtzugsmeister - Phase 3',
    AD_TBC_PHASE_3 = 'Schließt die unten aufgelisteten Schlachtzugserfolge der Scherbenwelt ab.',
	AN_TBC_PHASE_4 = 'Scherbenwelt-Schlachtzugsmeister - Phase 4',
    AD_TBC_PHASE_4 = 'Schließt die unten aufgelisteten Schlachtzugserfolge der Scherbenwelt ab.',
	AN_TBC_PHASE_5 = 'Scherbenwelt-Schlachtzugsmeister - Phase 5',
    AD_TBC_PHASE_5 = 'Schließt die unten aufgelisteten Schlachtzugserfolge der Scherbenwelt ab.',
	
    FACTION_946 = 'Ehrenfeste',
    FACTION_947 = 'Thrallmar',
    FACTION_942 = 'Expedition des Cenarius',
    FACTION_1011 = 'Unteres Viertel ',
    FACTION_989 = 'Hüter der Zeit ',
    FACTION_935 = 'Die Sha\'tar',
	FACTION_609 = 'Zirkel des Cenarius',

    AN_TBC_DUNGEON_REPUTATIONS = 'Der brennende Kreuzritter',
    AD_TBC_DUNGEON_REPUTATIONS = 'Bringt alle Rufe der Burning-Crusade-Dungeons auf Ehrfürchtig.',
	
	AN_CENARION_CIRCLE = 'Wächter des Cenarius',
    AD_CENARION_CIRCLE = 'Erreicht beim Zirkel des Cenarius und der Expedition des Cenarius den Status ehrfürchtig.',

    AN_SHATTRATH_REP = 'Geteiltes Shattrath',
    AD_SHATTRATH_REP = 'Erreicht bei den Sehern oder den Aldor den Status ehrfürchtig.',

    AN_OGRILA = 'Jeden Tag eine gute Tat für die Oger',
    AD_OGRILA = 'Erreicht in Ogri\'la den Status ehrfürchtig.',

    AN_SPOREGGAR = 'Der Zar von Sporeggar',
    AD_SPOREGGAR = 'Erreicht bei den Sporeggar den Status ehrfürchtig.',

    AN_CONSORTIUM = 'Ehrfurchtgebietender Offizier',
    AD_CONSORTIUM = 'Erreicht beim Konsortium den Status ehrfürchtig.',

    AN_MAGHAR = 'Mag\'har von Draenor',
    AD_MAGHAR = 'Erreicht bei den Mag\'har den Status ehrfürchtig.',

    AN_KURENAI = 'Owei, Kurenai',
    AD_KURENAI = 'Erreicht bei den Kurenai den Status ehrfürchtig.',

    AN_NETHERWINGS = 'Auf den Schwingen der Nether',
    AD_NETHERWINGS = 'Erreicht bei den Netherschwingen den Status ehrfürchtig.',

    AN_SKYSHATTERED = 'Aus dem Himmel gedonnert',
    AD_SKYSHATTERED = 'Bezwingt Hauptmann Himmelsdonner im Drachenmalrennen auf der Netherschwingenscherbe.',

    AN_AMETHYST_EYE = 'Das Violette Auge',
    AD_AMETHYST_EYE = 'Erreicht beim Violetten Auge den Status ehrfürchtig.',

    AN_SCALE_OF_THE_SANDS = 'Die Wächter der Sande',
    AD_SCALE_OF_THE_SANDS = 'Erreicht bei den Wächtern der Sande den Status ehrfürchtig.',

    AN_ASHTONGUE_DEATHSWORN = 'Höriger der Todeshörigen',
    AD_ASHTONGUE_DEATHSWORN = 'Erreicht bei den Todeshörigen der Aschenzungen den Status ehrfürchtig.',

    AN_SHATTERED_SUN = 'Welch eine Offensive',
    AD_SHATTERED_SUN = 'Erreicht bei der Offensive der zerschmetterten Sonne den Status ehrfürchtig.',

    AN_MR_PINCHY = 'Dr. Zwicky!',
    AD_MR_PINCHY = 'Angelt Dr. Zwicky in der Scherbenwelt.',

    AN_EXPLORE_OUTLAND = 'Erforscht die Scherbenwelt',
    AD_EXPLORE_OUTLAND = 'Erforscht die Regionen der Scherbenwelt.',    

    AN_MIDDLE_RARE = 'Ziemlich selten',
    AD_MIDDLE_RARE = 'Tötet eine der unten aufgelisteten, extrem seltenen und schwer zu findenden Kreaturen der Scherbenwelt.',
    AN_BLOODY_RARE = 'Verflucht selten',
    AD_BLOODY_RARE = 'Tötet jede der unten aufgelisteten, extrem seltenen und schwer zu findenden Kreaturen der Scherbenwelt.',
    TBC_NPC_18695 = 'Botschafter Jerrikar',
    TBC_NPC_18682 = 'Sumpflauerer',
    TBC_NPC_18697 = 'Chefingenieur Lorthander',
    TBC_NPC_18681 = 'Abgesandte des Echsenkessels',
    TBC_NPC_18694 = 'Collidus der Sphärenwächter',
    TBC_NPC_18689 = 'Verkrüppler',
    TBC_NPC_18686 = 'Verdammnisverkünder Jurim',
    TBC_NPC_18698 = 'Steinherz der Bestrafer',
    TBC_NPC_18678 = 'Gierschlund',
    TBC_NPC_17144 = 'Bluthauer',
    TBC_NPC_18692 = 'Hemathion',
    TBC_NPC_18696 = 'Kraator',
    TBC_NPC_18680 = 'Marticar',
    TBC_NPC_18677 = 'Mekthorg der Wilde',
    TBC_NPC_18690 = 'Mordruck',
    TBC_NPC_20932 = 'Nuramoc',
    TBC_NPC_18685 = 'Okrek',
    TBC_NPC_18693 = 'Sprecher Mar\'grom',
    TBC_NPC_18683 = 'Leerjäger Yar',
    TBC_NPC_18679 = 'Vorakem Unheilsbote',

    AN_PREPATCH_QUEST = 'Auf in den Kampf!',
    AD_PREPATCH_QUEST = 'Hat am Kampf um das Dunkle Portal teilgenommen. Träger des Wappenrock des Beschützers.',

    AN_RIDING_75 = 'Aufsatteln!',
    AD_RIDING_75 = 'Erlernt die Fähigkeit \'Unerfahrener Reiter\'.',
    AN_RIDING_150 = 'Traber',
    AD_RIDING_150 = 'Erlernt die Fähigkeit \'Geübter Reiter\'.',
    AN_RIDING_225 = 'Galopper',
    AD_RIDING_225 = 'Erlernt die Fähigkeit \'Erfahrener Reiter\'.',
    AN_RIDING_300 = 'Wie der Wind',
    AD_RIDING_300 = 'Erlernt die Fähigkeit \'Gekonnter Reiter\'.',

    AN_ATTUNE_SHATTERED_HALLS = 'Heißer als die Hölle',
    AD_ATTUNE_SHATTERED_HALLS = 'Erhaltet den Schlüssel zu den Zerschmetterten Hallen.',
    AN_ATTUNE_ARCATRAZ = 'Wie man in Arkatraz einbricht',
    AD_ATTUNE_ARCATRAZ = 'Erhaltet den Schlüssel zur Arkatraz.',
    AN_ATTUNE_KARAZHAN = 'Die Berührung des Meisters',
    AD_ATTUNE_KARAZHAN = 'Erhaltet den Schlüssel des Meisters.',
    AN_ATTUNE_NIGHT_BANE = 'Die Vergangenheit aufwühlen',
    AD_ATTUNE_NIGHT_BANE = 'Erhaltet die Geschwärzte Urne.',
    AN_ATTUNE_SSC = 'Der Knüppel von Kar\'desh',
    AD_ATTUNE_SSC = 'Erhaltet Zugang zur Höhle des Schlangenschreins.',
    AN_ATTUNE_EYE = 'Der Schlüssel der Stürme',
    AD_ATTUNE_EYE = 'Erhaltet den Schlüssel der Stürme.',
    AN_ATTUNE_HYJAL = 'Die Phiolen der Ewigkeit',
    AD_ATTUNE_HYJAL = 'Soridormi in den Höhlen der Zeit möchte, dass Ihr die Überreste von Vashjs Phiole von Lady Vashj im Echsenkessel und die Überreste von Kaels Phiole von Kael\'thas Sonnenwanderer in der Festung der Stürme besorgt.',
    AN_ATTUNE_BLACK_TEMPLE = 'Ein Ablenkungsmanöver für Akama',
    AD_ATTUNE_BLACK_TEMPLE = 'Erhaltet das Medaillon von Karabor.',

    AN_SSC = 'Höhle des Schlangenschreins',
    AD_SSC = 'Bezwingt die folgenden Bosse in der Höhle des Schlangenschreins.',
    AC_KILL_HYDROS = 'Hydross der Unstete',
    AC_KILL_LURKER = 'Das Grauen aus der Tiefe',
    AC_KILL_LEOTHERAS = 'Leotheras der Blinde',
    AC_KILL_KARATHRESS = 'Tiefenlord Karathress',
    AC_KILL_MOROGRIM = 'Morogrim Gezeitenwandler',
    AC_KILL_VASHJ = 'Lady Vashj',
	
    AN_TK = 'Die Festung der Stürme',
    AD_TK = 'Bezwingt die folgenden Bosse in der Festung der Stürme.',
    AC_KILL_ALAR = 'Al\'ar',
    AC_KILL_VOID_REAVER = 'Leerhäscher',
    AC_KILL_SOLARIAN = 'Hochastromantin Solarian',
    AC_KILL_KAELTHAS = 'Kael\'thas Sonnenwanderer',

    AN_HYJAL = 'Die Schlacht um den Hyjal',
    AD_HYJAL = 'Bezwingt Archimonde in der Schlacht um den Hyjal.',

    AN_BT_ENTRANCE = 'Infiltration',
    AD_BT_ENTRANCE = 'Dringt über die Kanäle von Karabor in den Schwarzen Tempel ein, indem ihr nachfolgende Bosse bezwingt.',
    AC_KILL_NAJENTUS = 'Oberster Kriegsfürst Naj\'entus',
    AC_KILL_SUPREMUS = 'Supremus',

    AN_BT_SECOND_WING = 'Akolyth von Karabor ',
    AD_BT_SECOND_WING = 'Reinigt die Hallen des Schwarzen Tempels, indem ihr nachfolgende Bosse bezwingt.',
    AC_KILL_SHADOW_OF_AKAMA = 'Akamas Schemen',
    AC_KILL_THERON = 'Teron Blutschatten',
    AC_KILL_GURTOGG = 'Gurtogg Siedeblut',
    AC_KILL_RELIQUARY = 'Reliquiar der Seelen',

    AN_BT_LAST_WING = 'Tempelspitze',
    AD_BT_LAST_WING = 'Infiltriert die oberen Stockwerke des Schwarzen Tempels, indem ihr nachfolgende Bosse bezwingt.',
    AC_KILL_MOTHER_SHAHRAZ = 'Mutter Shahraz',
    AC_KILL_BT_COUNCIL = 'Der Rat der Illidari',
    AC_KILL_ILLIDAN = 'Illidan Sturmgrimm',

    AN_BLACK_TEMPLE = 'Der Schwarze Tempel',
    AD_BLACK_TEMPLE = 'Schließt die unten aufgelisteten Erfolge im Schwarzen Tempel ab.',
    AR_BLACK_TEMPLE = 'Bezwinger des Schwarzen Tempels',

    AN_AZZINOTH = 'Kriegsgleven von Azzinoth',
    AD_AZZINOTH = 'Träger eines Sets der Kriegsgleven von Azzinoth.',
	AN_THORIDAL = 'Thori\'dal, Furor der Sterne',
    AD_THORIDAL = 'Träger von Thori\'dal, Furor der Sterne.',
    AC_OBTAIN_MAINHAND_AZZINOTH = 'Rechte Kriegsgleve von Azzinoth',
    AC_OBTAIN_OFFHAND_AZZINOTH = 'Linke Kriegsgleve von Azzinoth',
	AN_BEAR_MOUNT = 'Kriegsbär der Amani',
    AD_BEAR_MOUNT = 'Besitzer des Kriegsbären der Amani.',
	AN_HAWK_MOUNT = 'Schneller weißer Falkenschreiter',
    AD_HAWK_MOUNT = 'Erhaltet den schnellen weißen Falkenschreiter von Kael\'thas Sonnenwanderer auf der Terrasse der Magister.',
	AN_ALAR_MOUNT = 'Al\'ars Asche',
    AD_ALAR_MOUNT = 'Erhaltet Al\'ars Asche von Kael\'thas Sonnenwanderer in der Festung der Stürme.',
	AN_HORSEMAN_MOUNT = 'Die Zügel des Reiters',
	AD_HORSEMAN_MOUNT = 'Erhaltet während der Schlotternächte die Zügel des Reiters vom kopflosen Reiter im Scharlachroten Kloster.',
	AN_HERO_SHATTRATH = 'Der Held Shattraths',
	AD_HERO_SHATTRATH = 'Bei den Sehern und den Aldor den Status ehrfürchtig erreicht.',
	AN_HERO_SCRYER = 'Die Seher',
	AN_HERO_ALDOR = 'Die Aldor',
	AN_CHAMPION_NAARU = 'Champion der Naaru',
	AD_CHAMPION_NAARU = 'Den Titel "Champion der Naaru" erhalten.',
	AR_CHAMPION_NAARU = 'Champion der Naaru',
	AN_HAND_ADAL = 'Hand von A\'dal',
	AD_HAND_ADAL = 'Den Titel "Hand von A\'dal" erhalten.',
	AR_HAND_ADAL = 'Hand von A\'dal',

    AN_P3_FIRST_WEEK = 'Eroberer der Scherbenwelt',
    AD_P3_FIRST_WEEK = 'Bezwingt Archimonde und Illidan Sturmgrimm in der ersten Woche von Phase 3.',
    AC_KILL_ARCHIMONDE = 'Archimonde',
    AR_P3_FIRST_WEEK = 'Eroberer der Scherbenwelt',
	
	AN_FLIGHFORM = 'Schnelle Fluggestalt',
	AD_FLIGHFORM = 'Die Druidenquest zum Erlernen einer schnellen Fluggestalt abgeschlossen.'
})