SexyLib:InitLocalization('Classic Achievements', {
    achievement_earned = '&aAchievement earned by %s on %d/%d/%d',
    achievement_in_progress = '&7Achievement in progress by %s',

    ICON_DESCRIPTION = '&7Left mouse button: &eopen/hide achievements window\n&7Right mouse button: &eopen Classic Achievements settings\n\n&3With love from Maxich :)',

    OPTION_SHARING = 'Erfolge teilen',
    OPTION_SHARING_DESC = 'Whether to write messages in chats when receiving new achievement.',
    OPTION_MICROBUTTON = 'Micromenu button',
    OPTION_MICROBUTTON_DESC = 'If enabled, an addon button will be added to the micromenu, and the interface may break if you are using any addon to modify it. If disabled, the icon will be added to the minimap. Toggling this option requires you to do /reload or rejoin your character.',
    OPTION_UPDATE_MAP_EXPLORATION = 'Check explored locations',
    OPTION_UPDATE_MAP_EXPLORATION_DESC = 'Counts already explored locations for achievements.',
    OPTION_RESET_ACHIEVEMENTS = 'Reset achievements',
    OPTION_RESET_ACHIEVEMENTS_DESC = 'Reset all achievements progressions on this character. This can not be undone!',

    GOT_ACHIEVEMENT_MESSAGE_MALE = 'I\'ve just earned achievement %s!',
    GOT_ACHIEVEMENT_MESSAGE_FEMALE = 'I\'ve just earned achievement %s!',

    COMPARE_ACHIEVEMENTS = 'Compare achievements',
    TARGET_DOES_NOT_HAVE_ADDON = 'Target does not have this addon installed.',

    UPDATING_EXPLORED_AREAS = 'Updating locations exploration data. This action will take a few seconds.',
    UPDATED_EXPLORED_AREAS = '&aInformation about explored locations has been updated!',

    NOT_WORKING = 'das funktioniert nicht',

    GEAR_SLOT_HEAD = 'Kopf',
    GEAR_SLOT_NECK = 'Hals',
    GEAR_SLOT_SHOULDER = 'Schulter',
    GEAR_SLOT_CHEST = 'Brust',
    GEAR_SLOT_WAIST = 'Taille',
    GEAR_SLOT_LEGS = 'Beine',
    GEAR_SLOT_FEET = 'Füße',
    GEAR_SLOT_WRIST = 'Handgelenke',
    GEAR_SLOT_HANDS = 'Hände',
    GEAR_SLOT_FIRST_RING = 'Linker Ring',
    GEAR_SLOT_SECOND_RING = 'Rechter Ring',
    GEAR_SLOT_FIRST_TRINKET = 'Erstes Schmuckstück',
    GEAR_SLOT_SECOND_TRINKET = 'Zweites Schmuckstück',
    GEAR_SLOT_CLOAK = 'Umhang',
    GEAR_SLOT_WEAPON = 'Waffe',

    NPC_3444 = 'Grubenratte',
    NPC_620 = 'Huhn',
    NPC_1420 = 'Kröte',
    NPC_13321 = 'Frosch',
    NPC_2620 = 'Präriehund',
    NPC_9600 = 'Papagei',
    NPC_5951 = 'Hase',
    NPC_9699 = 'Feuerkäfer',
    NPC_4953 = 'Mokassin',
    NPC_721 = 'Kaninchen',
    NPC_9700 = 'Lavakrebs',
    NPC_15476 = 'Skorpion',
    NPC_2914 = 'Schlange',
    NPC_16030 = 'Made',
    NPC_4075 = 'Ratte',
    NPC_1412 = 'Eichhörnchen',
    NPC_7390 = 'Nymphensittich',
    NPC_15475 = 'Käfer',
    NPC_15010 = 'Dschungelkröte',
    NPC_4076 = 'Schabe',
    NPC_13016 = 'Untergrundratte',
    NPC_14881 = 'Spinne',
    NPC_2110 = 'Schwarze Ratte',
    NPC_4166 = 'Gazelle',
    NPC_1933 = 'Schaf',
    NPC_890 = 'Rehkitz',
    NPC_2098 = 'Widder',
    NPC_2442 = 'Kuh',
    NPC_6368 = 'Katze',
    NPC_10582 = 'Hund',
    NPC_385 = 'Pferd',
    NPC_10685 = 'Schwein',
    NPC_3300 = 'Otter',
    NPC_15066 = 'Cleo',
    NPC_15071 = 'Schleicherpfote',

    CATEGORY_GENERAL = 'Allgemein',
    CATEGORY_QUESTS = 'Quests',
    CATEGORY_KALIMDOR = 'Kalimdor',
    CATEGORY_EASTERN_KINGDOMS = 'Östliche Königreiche',
    CATEGORY_OUTLAND = 'Scherbenwelt',
    CATEGORY_VANILLA = 'Classic',
    CATEGORY_TBC = 'Scherbenwelt',
    CATEGORY_EXPLORATION = 'Erkundung',
    CATEGORY_PVE = 'Dungeons & Schlachtzüge',
    CATEGORY_BATTLEGROUNDS = 'Schlachtfelder',
    CATEGORY_BG_ALTERAC = 'Alteractal',
    CATEGORY_BG_WARSONG = 'Warsongschlucht',
    CATEGORY_BG_ARATHI = 'Arathibecken',
    CATEGORY_BG_EYE = 'Auge des Sturms',
    CATEGORY_OPEN_WORLD = 'Welt-PvP',
    CATEGORY_PROFESSIONS = 'Berufe',
    CATEGORY_REPUTATION = 'Ruf',
    CATEGORY_FEATS_OF_STRENGTH = 'Heldentaten',
    CATEGORY_EVENTS = 'Weltereignisse',

    AN_LVL = 'Level %d',
    AD_LVL = 'Erreicht Level %d.',

    AN_BANK = 'Sicher angelegt',
    AD_BANK = 'Kauft 6 zusätzliche Bankplätze.',
    AC_BANK = 'Kauft 6 zusätzliche Bankplätze.',

    AN_QUESTS = '%d Quests',
    AD_QUESTS = 'Schließt %d Quests ab.',
    AC_QUESTS = 'Schließt %d Quests ab.',

    AN_QUEST_GOLD5 = 'Glitzernde Belohnung',
    AN_QUEST_GOLD10 = 'Sammler geprägter Münzen',
    AN_QUEST_GOLD25 = 'Täglich Brot',
    AN_QUEST_GOLD50 = 'Wohlverdientes Gold',
    AN_QUEST_GOLD100 = 'Verdient durch Schweiß und Blut',
    AN_QUEST_GOLD250 = 'Golddrucker',
    AN_QUEST_GOLD500 = 'Angemessene Entlohnung',
    AD_QUEST_GOLD = 'Erhaltet %d Gold durch Questbelohnungen.',
    AC_QUEST_GOLD = 'Erhaltet %d Gold durch Questbelohnungen.',

    AN_QUESTS_ZONE = 'Meister der Lehren - %s',
    AD_QUESTS_ZONE = 'Schließt die Quest "%s" in %s ab.',
    AD_QUESTS_ZONE_MULTI = 'Schließt die folgenden Quests in %s ab.',
    AC_QUESTS_ZONE = 'Schließt die Quest "%s" ab.',

    AZSHARA_1 = 'Azshara',
    AZSHARA_2 = 'Azshara',
    QUEST_3602 = 'Azsharit',

    FELWOOD_1 = 'Teufelswald',
    FELWOOD_2 = 'Teufelswald',
    QUEST_5165 = 'Übergießen der Flammen des Schutzes',
    QUEST_5385 = 'Die Überreste von Trey Lightforge',

    DESOLACE_1 = 'Desolace',
    DESOLACE_2 = 'Desolace',
    QUEST_6027 = 'Buch der Uralten',

    DUSTWALLOW_1 = 'Marschen von Dustwallow',
    DUSTWALLOW_2 = 'Marschen von Dustwallow',
    QUEST_1203 = 'Jarl braucht eine Klinge',

    SILITHUS_1 = 'Silithus',
    SILITHUS_2 = 'Silithus',
    QUEST_8287 = 'Ein teuflischer Plan',
    QUEST_8352 = 'Szepter des Rates',
    QUEST_8321 = 'Vyral der Üble',
    QUEST_8281 = 'Verstärkte Sicherheit',

    DUROTAR_1 = 'Durotar',
    DUROTAR_2 = 'Durotar',
    QUEST_835 = 'Sicherung der Linien',

    BARRENS_1 = 'Das Brachland',
    BARRENS_2 = 'Das Brachland',
    QUEST_888 = 'Gestohlene Beute',
    QUEST_902 = 'Samophlang',

    WINTERSPRING_1 = 'Winterspring',
    WINTERSPRING_2 = 'Winterspring',
    QUEST_975 = 'Behälter von Mau\'ari',
    QUEST_5082 = 'Bedrohung durch die Winterfelle',
    QUEST_5121 = 'Oberhäuptling der Winterfelle',
    QUEST_5163 = 'Sind wir endlich da, Yeti?',
    QUEST_4842 = 'Sonderbare Quellen',

    TANARIS_1 = 'Tanaris',
    TANARIS_2 = 'Tanaris',
    QUEST_2662 = 'Noggenfogger-Elixier',
    QUEST_2874 = 'Lieferung für MacKinley',
    QUEST_1691 = 'Noch mehr Wüstenläufergerechtigkeit',
    QUEST_113 = 'Insektenteil-Analyse',

    STONETALON_1 = 'Steinkrallengebirge',
    STONETALON_2 = 'Steinkrallengebirge',
    QUEST_1096 = 'Gerenzo Wrenchwhistle',

    UNGORO_1 = 'Un\'Goro Krater',
    UNGORO_2 = 'Un\'Goro Krater',
    QUEST_3962 = 'Allein ist es gefährlich',
    QUEST_4245 = 'Chasing A-Me 01',
    QUEST_4292 = 'Ein Köder für Lar\'korwi',

    THOUSAND_NEEDLES_1 = 'Tausend Nadeln',
    THOUSAND_NEEDLES_2 = 'Tausend Nadeln',
    QUEST_1189 = 'Sicherheit zuerst',

    ARATHI_1 = 'Arathihochland',
    ARATHI_2 = 'Arathihochland',
    QUEST_652 = 'Den Hauptstein zerbrechen',

    BADLANDS_1 = 'Ödland',
    BADLANDS_2 = 'Ödland',
    QUEST_737 = 'Verbotenes Wissen',
    QUEST_778 = 'Das wird schwierig',
    QUEST_656 = 'Beschwören der Prinzessin',
    
    EASTERN_PLAGUELANDS_1 = 'Östliche Pestländer',
    EASTERN_PLAGUELANDS_2 = 'Östliche Pestländer',
    QUEST_5942 = 'Versteckte Schätze',
    QUEST_6041 = 'When Smokey Sings, I Get Violent',
    QUEST_5265 = 'Der Argentumtresor',

    BLASTED_LANDS_1 = 'Verwüstete Lande',
    BLASTED_LANDS_2 = 'Verwüstete Lande',
    QUEST_3628 = 'Ihr seid Rakh\'likh, Dämon',

    STRANGLETHORN_VALLEY_1 = 'Schlingendorntal',
    STRANGLETHORN_VALLEY_2 = 'Schlingendorntal',
    QUEST_208 = 'Großwildjagd',
    QUEST_600 = 'Venture Company-Bergbau',
    QUEST_613 = 'Maurys Fuß aufbrechen',
    QUEST_628 = 'Exzelsior',
    QUEST_338 = 'Die Grünen Hügel des Schlingendorntals',

    WESTERN_PLAGUELANDS_1 = 'Westliche Pestländer',
    WESTERN_PLAGUELANDS_2 = 'Westliche Pestländer',
    QUEST_5944 = 'In den Träumen',
    QUEST_5051 = 'Zwei Hälften vereint',
    QUEST_4985 = 'Die Tierwelt leidet auch',

    SEARING_GORGE_1 = 'Sengende Schlucht',
    SEARING_GORGE_2 = 'Sengende Schlucht',
    QUEST_3481 = 'Plunder...',

    BLACK_ROCK_1 = 'Blackrock',
    BLACK_ROCK_2 = 'Blackrock',
    QUEST_8996 = 'Rückkehr zu Bodley',

    AN_WISDOM_KEEPER = 'Meister der Lehren',
    AD_WISDOM_KEEPER = 'Schließt die unten aufgelisteten Questerfolge ab.',
    AN_WISDOM_KEEPER_AZEROTH = 'Meister der Lehren von Azeroth',
    AD_WISDOM_KEEPER_AZEROTH = 'Schließt die unten aufgelisteten Questerfolge ab.',
    AN_WISDOM_KEEPER_KALIMDOR = 'Meister der Lehren in Kalimdor',
    AD_WISDOM_KEEPER_KALIMDOR = 'Schließt die unten aufgelisteten Questerfolge in Kalimdor ab.',
    AN_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Meister der Lehren der Östlichen Königreiche',
    AD_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Schließt die unten aufgelisteten Questerfolge in den Östlichen Königreichen ab.',
    AN_WISDOM_KEEPER_OUTLAND = 'Meister der Lehren der Scherbenwelt',
    AD_WISDOM_KEEPER_OUTLAND = 'Schließt die unten aufgelisteten Questerfolge in der Scherbenwelt ab.',
    AR_WISDOM_KEEPER = 'Titel \'Meister der Lehren\'.',

    AN_RAGEFIRE_CHASM = 'Ragefireabgrund',
    AD_RAGEFIRE_CHASM = 'Bezwingt Jergosh den Herbeirufer',
    AN_WAILING_CAVERNS = 'Die Höhlen des Wehklagens',
    AD_WAILING_CAVERNS = 'Bezwingt Mutanus den Verschlinger.',
    AN_DEAD_MINES = 'Die Todesminen',
    AD_DEAD_MINES = 'Bezwingt Edwin van Cleef.',
    AN_SHADOWFANG_KEEP = 'Burg Shadowfang',
    AD_SHADOWFANG_KEEP = 'Bezwingt Erzmagier Arugal.',
    AN_BLACKFATHOM_DEEPS = 'Blackfathom-Tiefe',
    AD_BLACKFATHOM_DEEPS = 'Bezwingt Aku\'mai.',
    AN_JAIL = 'Das Verlies',
    AD_JAIL = 'Bezwingt Kam Deepfury.',
    AN_GNOMREGAN = 'Gnomeregan',
    AD_GNOMREGAN = 'Bezwingt Robogenieur Thermaplugg.',
    AN_RAZORFEN_KRAUL = 'Der Kral von Razorfen',
    AD_RAZORFEN_KRAUL = 'Bezwingt Charlga Razorflank.',
	
    AN_SCARLET_MONASTERY = 'Das Scharlachrote Kloster',
    AD_SCARLET_MONASTERY = 'Bezwingt die Kommandanten im Scharlachrote Kloster.',
    AC_SCARLET_MONASTERY1 = 'Blutmagier Thalnos getötet',
    AC_SCARLET_MONASTERY2 = 'Arkanist Doan getötet',
    AC_SCARLET_MONASTERY3 = 'Herod getötet',
    AC_SCARLET_MONASTERY4 = 'Hochinquisitor Whitemane getötet',
	
    AN_RAZORFEN_DOWNS = 'Die Hügel von Razorfen',
    AD_RAZORFEN_DOWNS = 'Bezwingt Amnennar der Kältebringer und Plaguemaw den Faulenden.',
    AC_RAZORFEN_DOWNS1 = 'Amnennar der Kältebringer getötet',
    AC_RAZORFEN_DOWNS2 = 'Plaguemaw der Faulende getötet',
    AN_ULDAMAN = 'Uldaman',
    AD_ULDAMAN = 'Bezwingt Archaedas.',
    AN_ZULFARRAK = 'Zul\'Farrak',
    AD_ZULFARRAK = 'Bezwingt Häuptling Ukorz Sandscalp.',
    AN_MARAUDON = 'Maraudon',
    AD_MARAUDON = 'Bezwingt Prinzessin Theradras',
    AN_SUNKEN_TEMPLE = 'Der Tempel von Atal\'Hakkar',
    AD_SUNKEN_TEMPLE = 'Bezwingt Eranikus\' Schemen.',
	
    AN_NEW_EMPEROR = 'Blackrocktiefen',
    AD_NEW_EMPEROR = 'Bezwingt Imperator Dagran Thaurissan.',
    AN_BLACKROCK_DEPTHS = 'Die Tiefen säubern',
    AD_BLACKROCK_DEPTHS = 'Tötet die folgenden Bosse in den Blackrocktiefen.',
    AC_BLACKROCK_DEPTHS1 = 'Verhörmeisterin Gerstahn getötet',
    AC_BLACKROCK_DEPTHS2 = 'Hundemeister Grebmar getötet',
    AC_BLACKROCK_DEPTHS3 = 'General Zornesschmied getötet',
    AC_BLACKROCK_DEPTHS4 = 'Golemlord Argelmach getötet',
    AC_BLACKROCK_DEPTHS5 = 'Lord Incendius getötet',
    AC_BLACKROCK_DEPTHS6 = 'Wärter Stilgiss getötet',
    AC_BLACKROCK_DEPTHS7 = 'Bael\'Gar getötet',
    AN_BLACKROCK_PARTY = 'Party in den Tiefen',
    AD_BLACKROCK_PARTY = 'Bezwingt die folgenden Gegner im Grimmigen Säufer',
    AC_BLACKROCK_PARTY1 = 'Ribbly Screwspigot getötet',
    AC_BLACKROCK_PARTY2 = 'Plugger Spazzring getötet',
    AC_BLACKROCK_PARTY3 = 'Hurley Pestatem getötet',
    AC_BLACKROCK_PARTY4 = 'Phalanx getötet',
    AN_BLACKROCK_DEPTHS_FULL = 'Blackrocktiefen',
    AD_BLACKROCK_DEPTHS_FULL = 'Schließt die unten aufgelisteten Erfolge in den Blackrocktiefen ab.',
    AN_ARMOR_SWORD = 'Angriff ist die bessere Verteidigung',
    AD_ARMOR_SWORD = 'Plündert den Stein der Erde von Panzor den Unbesiegbaren in den Blackrocktiefen.',
	
    AN_BLACKROCK_SPIRE_BOTTOM = 'Untere Blackrockspitze',
    AD_BLACKROCK_SPIRE_BOTTOM = 'Bezwingt Oberanführer Wyrmthalak.',
    AN_BLACKROCK_SPIRE_UPPER = 'Obere Blackrockspitze ',
    AD_BLACKROCK_SPIRE_UPPER = 'Bezwingt General Drakkisath.',
    AN_BLACKROCK_SPIRE = 'Eindringling der Blackrockspitze',
    AD_BLACKROCK_SPIRE = 'Schließt die unten aufgelisteten Erfolge in der Blackrockspitze ab.',
    AN_DIRE_MAUL = 'Herrscher der vergessenen Stadt',
    AD_DIRE_MAUL = 'Befreit alle Düsterbruch-Abschnitte von Gegnern.',
    AC_DIRE_MAUL1 = 'Bezwingt Alzzin den Windformer',
    AC_DIRE_MAUL2 = 'Bezwingt Prinz Tortheldrin',
    AC_DIRE_MAUL3 = 'Bezwingt König Gordok.',
    AN_STRATHOLME_LIVE = 'Stratholme (Haupttor)',
    AD_STRATHOLME_LIVE = 'Bezwingt Balnazzar.',
    AN_STRATHOLME_DEAD = 'Stratholme (Dienstbotentor)',
    AD_STRATHOLME_DEAD = 'Bezwingt Baron Totenschwur.',
    AN_STRATHOLME = '"Retter" von Stratholme',
    AD_STRATHOLME = 'Schließt die unten aufgelisteten Erfolge in Stratholme ab.',
    AN_SCHOLOMANCE = 'Scholomance',
    AD_SCHOLOMANCE = 'Bezwingt Dunkelmeister Gandling.',
    AN_YOUNG_DEFENDER = 'Klassischer Dungeonmeister',
    AD_YOUNG_DEFENDER = 'Schließt die unten aufgelisteten Dungeon-Erfolge ab.',
    AN_DEFENDER = 'Verteidiger von Azeroth',
    AD_DEFENDER = 'Schließt die unten aufgelisteten Dungeon-Erfolge ab.',
    AR_DEFENDER = 'Titel \'Verteidiger von Azeroth\'.',

    AN_ONYXIA = 'Onyxias Hort',
    AD_ONYXIA = 'Bezwingt Onyxia.',
    AN_AQ20 = 'Ruinen von Ahn\'Qiraj',
    AD_AQ20 = 'Bezwingt Ossirian den Narbenlosen.',
    AN_ZULGURUB = 'Zul\'Gurub',
    AD_ZULGURUB = 'Bezwingt Hakkar.',
    AN_RAGNAROS = 'Geschmolzener Kern',
    AD_RAGNAROS = 'Bezwingt Ragnaros.',
    AN_BLACK_WING_LAIR = 'Pechschwingenhort',
    AD_BLACK_WING_LAIR = 'Bezwingt Nefarian.',
    AN_AQ40 = 'Tempel von Ahn\'Qiraj',
    AD_AQ40 = 'Bezwingt C\'Thun.',
    AN_NAXXRAMAS_SPIDERS = 'Das Arachnidenviertel',
    AD_NAXXRAMAS_SPIDERS = 'Bezwingt Maexxna.',
    AN_NAXXRAMAS_PLAGUE = 'Das Seuchenviertel',
    AD_NAXXRAMAS_PLAGUE = 'Bezwingt Loatheb.',
    AN_NAXXRAMAS_MILITARY = 'Das Militärviertel',
    AD_NAXXRAMAS_MILITARY = 'Bezwingt die vier Reiter.',
    AN_NAXXRAMAS_CONSTRUCT = 'Das Konstruktviertel',
    AD_NAXXRAMAS_CONSTRUCT = 'Bezwingt Thaddius.',
    AN_NAXXRAMAS_LAIR = 'Frostwyrm Hort',
    AD_NAXXRAMAS_LAIR = 'Bezwingt Kel\'Thuzad.',
    AN_NAXXRAMAS = 'Bezwinger von Naxxramas',
    AD_NAXXRAMAS = 'Schließt die unten aufgelisteten Erfolge in Naxxramas ab.',
    AN_YOUNG_HERO = 'Aufstrebender Held von Azeroth',
    AD_YOUNG_HERO = 'Schließt die unten aufgelisteten Schlachtzugserfolge ab.',
    AN_BLACKROCK_MASTER = 'Herr des Blackrock',
    AD_BLACKROCK_MASTER = 'Schließt die unten aufgelisteten Erfolge im Blackrock ab.',
    AN_HERO = 'Held von Azeroth',
    AD_HERO = 'Schließt die unten aufgelisteten Schlachtzugserfolge ab.',
    AR_HERO = 'Titel \'Held von Azeroth\'.',
    AN_GREAT_HERO = 'Großartiger Held von Azeroth',
    AD_GREAT_HERO = 'Schließt die unten aufgelisteten Dungeon- und Schlachtzugserfolge ab.',
    AR_GREAT_HERO = 'Titel \'Großartiger Held von Azeroth\'.',

    AN_PVP_RANK_A1 = 'Gefreiter',
    AN_PVP_RANK_A2 = 'Fußknecht',
    AN_PVP_RANK_A3 = 'Landsknecht',
    AN_PVP_RANK_A4 = 'Feldwebel',
    AN_PVP_RANK_A5 = 'Fähnrich',
    AN_PVP_RANK_A6 = 'Leutnant',
    AN_PVP_RANK_A7 = 'Hauptmann',
    AN_PVP_RANK_A8 = 'Kürassier',
    AN_PVP_RANK_A9 = 'Ritter der Allianz',
    AN_PVP_RANK_A10 = 'Feldkommandant',
    AN_PVP_RANK_A11 = 'Rittmeister',
    AN_PVP_RANK_A12 = 'Marschall',
    AN_PVP_RANK_A13 = 'Feldmarschall',
    AN_PVP_RANK_A14 = 'Großmarschall',
    AN_PVP_RANK_H1 = 'Späher',
    AN_PVP_RANK_H2 = 'Grunzer',
    AN_PVP_RANK_H3 = 'Waffenträger',
    AN_PVP_RANK_H4 = 'Schlachtrufer',
    AN_PVP_RANK_H5 = 'Rottenmeister',
    AN_PVP_RANK_H6 = 'Steingardist',
    AN_PVP_RANK_H7 = 'Blutgardist',
    AN_PVP_RANK_H8 = 'Zornbringer',
    AN_PVP_RANK_H9 = 'Klinge der Horde',
    AN_PVP_RANK_H10 = 'Feldherr',
    AN_PVP_RANK_H11 = 'Sturmreiter',
    AN_PVP_RANK_H12 = 'Kriegsherr',
    AN_PVP_RANK_H13 = 'Kriegsfürst',
    AN_PVP_RANK_H14 = 'Oberster Kriegsfürst',
    AD_PVP_RANK = 'Den gleichnamigen Titel erhalten.',
    AN_PVP_FIRST_KILL = 'Ein ehrenhafter Sieg',
    AD_PVP_FIRST_KILL = 'Erringt einen ehrenhaften Sieg.',
    AC_PVP_FIRST_KILL = 'Erringt einen ehrenhaften Sieg',
    AN_PVP_KILLS = '%d ehrenhafte Siege',
    AD_PVP_KILLS = 'Erringt %d ehrenhafte Siege.',
    AC_PVP_KILLS = 'Erringt %d ehrenhafte Siege',

    AN_MOB_KILLS_1 = 'Totschläger',
    AN_MOB_KILLS_2 = 'Zerstörer',
    AN_MOB_KILLS_3 = 'Brecher',
    AN_MOB_KILLS_4 = 'Kopfgeldjäger',
    AN_MOB_KILLS_5 = 'Gewittersturm aller Monster',
    AN_MOB_KILLS_6 = 'Gewittersturm allen Lebens',
    AN_MOB_KILLS_7 = 'Allgegenwärtiger Tod',
    AD_MOB_KILLS = 'Tötet %d Gegner.',
    AC_MOB_KILLS = 'Tötet %d Gegner',

    AN_REPS_1 = 'Jemand mag mich!',
    AD_REPS_1 = 'Erreicht einen ehrfürchtigen Ruf.',
    AC_REPS_1 = 'Erreicht einen ehrfürchtigen Ruf',
    AN_REPS_2 = 'Zwei Fraktionen',
    AN_REPS_3 = 'Liebling',
    AN_REPS_4 = 'Bewundert',
    AN_REPS_5 = 'Ehrfürchtig',
    AN_REPS_6 = 'Verehrenswert',
    AN_REPS_7 = 'Hoch angesehen',
    AN_REPS_MORE = '%d Fraktionen ehrfürchtig',
    AD_REPS = 'Erreicht bei %d Fraktionen einen ehrfürchtigen Ruf.',
    AC_REPS = 'Erreicht bei %d Fraktionen einen ehrfürchtigen Ruf.',
    AR_REPS = 'Titel \'der Ehrfurchtgebietende\'',

    AN_HORDE_REPS = 'Botschafter der Horde',
    AD_HORDE_REPS = 'Erreicht einen ehrfürchtigen Ruf in 5 Heimatstädten.',
    AC_HORDE_REPS_1 = 'Ehrfürchtig in Orgrimmar.',
    AC_HORDE_REPS_2 = 'Ehrfürchtig bei den Darkspeartrollen.',
    AC_HORDE_REPS_3 = 'Ehrfürchtig in Undercity.',
    AC_HORDE_REPS_4 = 'Ehrfürchtig in Thunder Bluff.',
    AC_HORDE_REPS_5 = 'Ehrfürchtig in Silbermond.',

    AN_ALLIANCE_REPS = 'Botschafter der Allianz',
    AD_ALLIANCE_REPS = 'Erreicht einen ehrfürchtigen Ruf in 5 Heimatstädten.',
    AC_ALLIANCE_REPS_1 = 'Ehrfürchtig in Stormwind.',
    AC_ALLIANCE_REPS_2 = 'Ehrfürchtig in Darnassus.',
    AC_ALLIANCE_REPS_3 = 'Ehrfürchtig bei den Gnomeregangnomen.',
    AC_ALLIANCE_REPS_4 = 'Ehrfürchtig in Ironforge.',
    AC_ALLIANCE_REPS_5 = 'Ehrfürchtig in der Exodar.',

    AN_ARGENT_DAWN = 'Argentumdämmerung',
    AD_ARGENT_DAWN = 'Erreicht bei der Argentumdämmerung den Status ehrfürchtig.',
    AN_BROOD_OF_NOZDORMU = 'Brut von Nozdormu',
    AD_BROOD_OF_NOZDORMU = 'Erreicht bei der Brut Nozdormus den Status ehrfürchtig.',
    AN_CENARION_CIRCLE = 'Zirkel des Cenarius',
    AD_CENARION_CIRCLE = 'Erreicht beim Zirkel des Cenarius den Status ehrfürchtig.',
    AN_DARKMOON_FAIRE = 'Dunkelmond-Jahrmarkt',
    AD_DARKMOON_FAIRE = 'Erreicht beim Dunkelmond-Jahrmarkt den Status ehrfürchtig.',
    AN_ZANDALAR_TRIBE = 'Stamm der Zandalar',
    AD_ZANDALAR_TRIBE = 'Erreicht beim Stamm der Zandalar den Status ehrfürchtig.',
    AN_HYDRAXIANS = 'Die Hydraxianer',
    AD_HYDRAXIANS = 'Erreicht bei den Hydraxianern den Status ehrfürchtig.',
    AN_TIMBERMAW_HOLD = 'Holzschlundfeste',
    AD_TIMBERMAW_HOLD = 'Erreicht bei der Holzschlundfeste den Status ehrfürchtig.',
    AN_PIRATES = 'Yar-r-r!',
    AD_PIRATES = 'Erreicht den Status Wohlwollend bei den Blutsegelbukaniere.',
    AN_SHENDRALAR = 'Agent der Shen\'dralar',
    AD_SHENDRALAR = 'Erreicht bei den Shen\'dralar den Status ehrfürchtig.',

    AN_DEFILERS = 'Der Entweihte',
    AD_DEFILERS = 'Erreicht einen ehrfürchtigen Ruf bei den Entweihten.',
    AN_FROSTWOLF_CLAN = 'Held des Frostwolfklans',
    AD_FROSTWOLF_CLAN = 'Erreicht einen ehrfürchtigen Ruf beim Frostwolfklan.',
    AN_WARSONG_OUTRIDERS = 'Vorhut des Kriegshymnenklans',
    AD_WARSONG_OUTRIDERS = 'Erreicht einen ehrfürchtigen Ruf bei der Vorhut des Kriegshymnenclans.',
    AN_HORDE_PVP_FRACTIONS = 'Der Eroberer',
    AD_HORDE_PVP_FRACTIONS = 'Erhöht Euren Ruf in der Kriegshymnenschlucht, dem Arathibecken und dem Alteractal auf ehrfürchtig.',

    AN_LEAGUE_OF_ARATHOR = 'Ritter von Arathor',
    AD_LEAGUE_OF_ARATHOR = 'Erreicht einen ehrfürchtigen Ruf beim Bund von Arathor.',
    AN_STORMSPIKE_GUARD = 'Held der Sturmlanzengarde',
    AD_STORMSPIKE_GUARD = 'Erreicht einen ehrfürchtigen Ruf bei der Sturmlanzengarde.',
    AN_SILVERWING_SENTINELS = 'Schildwache der Silberschwingen',
    AD_SILVERWING_SENTINELS = 'Erreicht einen ehrfürchtigen Ruf bei der Schildwache der Silberschwingen.',
    AN_ALLIANCE_PVP_FRACTIONS = 'Der Vollstrecker',
    AD_ALLIANCE_PVP_FRACTIONS = 'Erhöht Euren Ruf in der Kriegshymnenschlucht, dem Arathibecken und dem Alteractal auf ehrfürchtig.',

    AN_BOLVAR_SLAYER = 'Sturm auf Stormwind',
    AD_BOLVAR_SLAYER = 'Tötet Hochlord Bolvar Fordragon in Stormwind.',
    AN_MAGNI_SLAYER = 'Tod dem König!',
    AD_MAGNI_SLAYER = 'Tötet König Magni Bronzebart.',
    AN_MEKKATORQUE_SLAYER = 'Goblins > Gnome',
    AD_MEKKATORQUE_SLAYER = 'Tötet Hochtüftler Mekkatorque in Ironforge.',
    AN_TYRANDE_SLAYER = 'Von wegen unsterblich',
    AD_TYRANDE_SLAYER = 'Tötet die Hohepriesterin Tyrande Wisperwind.',
    AN_VELEN_SLAYER = 'Das Licht ausmachen',
    AD_VELEN_SLAYER = 'Tötet den Propheten Velen.',

    AN_ALLIANCE_KINGS_SLAYER = 'Für die Horde!',
    AD_ALLIANCE_KINGS_SLAYER = 'Tötet die Anführer der Allianz.',

    AN_THRALL_SLAYER = 'Tod dem Kriegshäuptling!',
    AD_THRALL_SLAYER = 'Tötet Thrall.',
    AN_VOLJIN_SLAYER = 'Tod dem Geistersprecher',
    AD_VOLJIN_SLAYER = 'Tötet Vol\'jin.',
    AN_SYLVANAS_SLAYER = 'Nieder mit der dunklen Fürstin',
    AD_SYLVANAS_SLAYER = 'Tötet Fürstin Sylvanas Windläufer.',
    AN_CAIRNE_SLAYER = 'Blutender Bluthuf',
    AD_CAIRNE_SLAYER = 'Tötet Cairne Bluthuf.',
    AN_LORTHEMAR_SLAYER = 'In Quel\'Thalas getötet',
    AD_LORTHERMAR_SLAYER = 'Tötet Lor\'themar Theron.',

    AN_HORDE_KINGS_SLAYER = 'Für die Allianz!',
    AD_HORDE_KINGS_SLAYER = 'Tötet die Anführer der Horde.',

    AN_RACES_KILLER = 'Kenne deinen Feind',
    AD_ALLIANCE_RACES_KILLER = 'Erreicht einen ehrenhaften Todesstoß bei allen Völkern der Allianz.',
    AD_HORDE_RACES_KILLER = 'Erreicht einen ehrenhaften Todesstoß bei allen Völkern der Horde.',
    AC_HUMAN_KILLED = 'Mensch getötet',
    AC_NIGHTELF_KILLED = 'Nachtelf getötet',
    AC_DWARF_KILLED = 'Zwerg getötet',
    AC_GNOME_KILLED = 'Gnom getötet',
    AC_ORC_KILLED = 'Orc getötet',
    AC_TROLL_KILLED = 'Troll getötet',
    AC_SCOURGE_KILLED = 'Untoter getötet',
    AC_TAUREN_KILLED = 'Tauren getötet',
    AC_DRAENEI_KILLED = 'Draenei getötet',
    AC_BLOODELF_KILLED = 'Blutelf getötet',

    AN_CLASSES_KILLER = 'Klasse & Stil',
    AD_CLASSES_KILLER = 'Erreicht einen ehrenhaften Todesstoß gegen einen Vertreter jeder Klasse.',
    AC_WARRIOR_KILLED = 'Krieger getötet',
    AC_HUNTER_KILLED = 'Jäger getötet',
    AC_ROGUE_KILLED = 'Schurken getötet',
    AC_PRIEST_KILLED = 'Priester getötet',
    AC_MAGE_KILLED = 'Magier getötet',
    AC_WARLOCK_KILLED = 'Hexenmeister getötet',
    AC_DRUID_KILLED = 'Druide getötet',
    AC_PALADIN_KILLED = 'Paladin getötet',
    AC_SHAMAN_KILLED = 'Schamane getötet',

    AN_ALTERAC_WIN = 'Sieg im Alteractal',
    AD_ALTERAC_WIN = 'Gewinnt im Alteractal.',
    AN_ALTERAC_WINS = 'Veteran des Alteractals',
    AD_ALTERAC_WINS = 'Erringt %d Siege im Alteractal',
    AN_WARSONG_WIN = 'Sieg in der Warsongschlucht',
    AD_WARSONG_WIN = 'Gewinnt in der Warsongschlucht',
    AN_WARSONG_WINS = 'Veteran der Warsongschlucht',
    AD_WARSONG_WINS = 'Erringt %d Siege in der Warsongschlucht',
    AN_ARATHI_WIN = 'Sieg im Arathibecken',
    AD_ARATHI_WIN = 'Gewinnt im Arathibecken.',
    AN_ARATHI_WINS = 'Veteran des Arathibeckens',
    AD_ARATHI_WINS = 'Erringt %d Siege im Arathibecken.',
    AN_EYE_WIN = 'Sieg im Aug des Sturms',
    AD_EYE_WIN = 'Gewinnt im Auge des Sturms',
    AN_EYE_WINS = 'Veteran des Auge des Sturms',
    AD_EYE_WINS = 'Erringt %d Siege im Auge des Sturms.',

    AN_ALTERAC_KILLING_BLOWS = 'Fleischwolf des Alteractals',
    AD_ALTERAC_KILLING_BLOWS = 'Erreicht %d Todesstöße während einer Schlacht im Alteractal und bleibt bis zum Ende der Schlacht.',
    AN_ALTERAC_GRAVEYARD_ASSAULT = 'Alterac-Grabjäger',
    AD_ALTERAC_GRAVEYARD_ASSAULT = 'Nehmt einen Friedhof während der Schlacht im Alteractal ein und bleibt bis zum Ende der Schlacht.',
    AN_ALTERAC_GRAVEYARD_ASSAULTS = 'Es fehlt an Särgen',
    AD_ALTERAC_GRAVEYARD_ASSAULTS = 'Nehmt %d Friedhöfe ein während ihr im Alteractal kämpft und bleibt bis zum Ende der Schlacht.',
    AN_ALTERAC_GRAVEYARD_DEFEND = 'Verteidiger der Verstorbenen',
    AD_ALTERAC_GRAVEYARD_DEFEND = 'Verteidigt einen Friedhof während der Schlacht im Alteractal ein und bleibt bis zum Ende der Schlacht.',
    AN_ALTERAC_GRAVEYARD_DEFENDS = 'Verteidiger der Toten',
    AD_ALTERAC_GRAVEYARD_DEFENDS = 'Verteidigt %d Friedhöfe während ihr im Alteractal kämpft und bleibt bis zum Ende der Schlacht.',
    AN_ALTERAC_TOWER_ASSAULT = 'Nun gehört er mir!',
    AD_ALTERAC_TOWER_ASSAULT = 'Nehmt einen Turm während der Schlacht im Alteractal ein und und bleibt bis zum Ende der Schlacht.',
    AN_ALTERAC_TOWER_ASSAULTS = 'Nun gehört ALLES mir!',
    AD_ALTERAC_TOWER_ASSAULTS = 'Nehmt %d Türme ein während ihr im Alteractal kämpft und bleibt bis zum Ende der Schlacht.',
    AN_ALTERAC_TOWER_DEFEND = 'Turmwächter',
    AD_ALTERAC_TOWER_DEFEND = 'Verteidigt einen Turm während der Schlacht im Alteractal ein und bleibt bis zum Ende der Schlacht.',
    AN_ALTERAC_TOWER_DEFENDS = 'Turmverteidiger',
    AD_ALTERAC_TOWER_DEFENDS = 'Verteidigt %d Türme während ihr im Alteractal kämpft und bleibt bis zum Ende der Schlacht.',
    AN_ALTERAC_MINE_CAPTURE = 'Gefrorener Bergmann',
    AD_ALTERAC_MINE_CAPTURE = 'Nehmt eine Mine während der Schlacht im Alteractal ein und bleibt bis zum Ende der Schlacht.',
    AN_ALTERAC_MINE_CAPTURES = 'Gefrorener Pikenier',
    AD_ALTERAC_MINE_CAPTURES = 'Nehmt %d Minen ein während ihr im Alteractal kämpft und bleibt bis zum Ende der Schlacht.',

    AN_WARSONG_KILLS = 'Military honor',
    AD_WARSONG_KILLS = 'Erreicht %d ehrenhafte Siege während einer Schlacht in der Warsongschlucht und bleibt bis zum Ende der Schlacht.',
    AN_WARSONG_FLAG_CAPTURE = 'Flaggenträger',
    AD_WARSONG_FLAG_CAPTURE = 'Ergreift und erobert die gegnerische Flagge während ihr in der Warsongschlucht kämpft und bleibt bis zum Ende der Schlacht.',
    AN_WARSONG_FLAG_CAPTURES = 'Großartiger Flaggenträger',
    AD_WARSONG_FLAG_CAPTURES = 'Ergreift und erobert %d gegnerische Flaggen während ihr in der Warsongschlucht kämpft und bleibt bis zum Ende der Schlacht.',
    AN_WARSONG_FLAG_RETURN = 'Fasst das nicht an!',
    AD_WARSONG_FLAG_RETURN = 'Bringt als Verteidiger eine Flagge während einer Schlacht in der Warsongschlucht zurück und bleibt bis zum Ende der Schlacht.',
    AN_WARSONG_FLAG_RETURNS = 'Hartnäckiger Verteidiger',
    AD_WARSONG_FLAG_RETURNS = 'Bringt als Verteidiger %d Flaggen zurück während ihr in der Warsongschlucht kämpft und bleibt bis zum Ende der Schlacht.',

    AN_ARATHI_BASE_ASSAULT = 'Konquistador',
    AD_ARATHI_BASE_ASSAULT = 'Erobert eine Basis während ihr im Arathibecken kämpft und bleibt bis zum Ende der Schlacht.',
    AN_ARATHI_BASE_ASSAULTS = 'Flaggenjagd',
    AD_ARATHI_BASE_ASSAULTS = 'Erobert %d Basen während ihr im Arathibecken kämpft und bleibt bis zum Ende der Schlacht.',
    AN_ARATHI_BASE_DEFEND = 'Wächter',
    AD_ARATHI_BASE_DEFEND = 'Verteidigt eine Basis während ihr im Arathibecken kämpft und bleibt bis zum Ende der Schlacht.',
    AN_ARATHI_BASE_DEFENDS = 'Ehrenhafter Wächter',
    AD_ARATHI_BASE_DEFENDS = 'Verteidigt %d Basen während ihr im Arathibecken kämpft und bleibt bis zum Ende der Schlacht.',

    AN_EYE_CAPTURE = 'Sturmeroberer',
    AD_EYE_CAPTURE = 'Ergreift und erobert persönlich die Flagge im Auge des Sturms kämpft und bleibt bis zum Ende der Schlacht.',
    AD_EYE_CAPTURES = 'Ergreift und erobert persönlich %d Flaggen im Auge des Sturms kämpft und bleibt bis zum Ende der Schlacht.',
    AN_EYE_GLORY = 'Für den Ruhm',
    AD_EYE_GLORY = 'Erobert in einem einzigen Auge des Sturm-Kampfes die Flagge 3-mal, ohne zu sterben.',
    AN_EYE_FAST_WIN = 'Der Sturm',
    AD_EYE_FAST_WIN = 'Gewinnt im Auge des Sturms in weniger als 6 Minuten.',
    AN_EYE_BERSERK = 'Blutrünstiger Berserker',
    AD_EYE_BERSERK = 'Erteilt einen Todesstoß, während Ihr im Auge des Sturms unter dem Stärkungszauber Berserker steht.',
    AN_EYE_IDEAL_VICTORY = 'Der perfekte Sturm',
    AD_EYE_IDEAL_VICTORY = 'Gewinnt im Auge des Sturms mit einem Ergebnis von 1.600 zu 0.',

    AN_BGS_KILLING_BLOWS = 'Todbringer',
    AD_BGS_KILLING_BLOWS = 'Erringt %d Todesstöße auf einem Schlachtfeld und bleibt bis zum Ende der Schlacht.',
    AN_BGS_KILLS = 'Todesengel',
    AD_BGS_KILLS = 'Erringt %d ehrenhafte Siege in einer einzigen Schlacht auf einem beliebigen Schlachtfeld.',

    PROF_FIRST_AID = 'Erste Hilfe',
    PROF_FISHING = 'Angeln',
    PROF_COOKING = 'Kochen',
    PROF_ENCHANTING = 'Verzauberkunst',
    PROF_TAILORING = 'Schneiderei',
    PROF_ENGINEERING = 'Ingenierskunst',
    PROF_LEATHERWORKING = 'Lederverarbeitung',
    PROF_ALCHEMY = 'Alchimie',
    PROF_BLACKSMITHING = 'Schmiedekunst',
    PROF_HERBALISM = 'Kräuterkunde',
    PROF_MINING = 'Bergbau',
    PROF_SKINNING = 'Kürschnerei',
    PROF_JEWELCRAFTING = 'Juwelierskunst',
    SKILL_UNARMED = 'Unbewaffnet',
    SKILL_RIDING = 'Reiten',

    AN_PROFS_JOURNEYMAN = 'Lehrling',
    AD_PROFS_JOURNEYMAN = 'Erlangt 75 Fertigkeitspunkte in einem Beruf.',
    AN_PROFS_EXPERT = 'Geselle',
    AD_PROFS_EXPERT = 'Erlangt 150 Fertigkeitspunkte in einem Beruf.',
    AN_PROFS_ARTISAN = 'Experte',
    AD_PROFS_ARTISAN = 'Erlangt 225 Fertigkeitspunkte in einem Beruf.',
    AN_PROFS_ONE = 'Fachmann',
    AD_PROFS_ONE = 'Erlangt 300 Fertigkeitspunkte in einem Beruf.',
    AN_PROFS_ONE_OUTLAND = 'Meister',
    AD_PROFS_ONE_OUTLAND = 'Erlangt 375 Fertigkeitspunkte in einem Beruf.',
    AN_PROFS_TWO = 'Handwerker',
    AD_PROFS_TWO = 'Werdet gleichzeitig in zwei Berufen Fachmann.',
    AC_PROFS_TWO = 'Werdet gleichzeitig in zwei Berufen Fachmann.',
    AN_PROFS_TWO_OUTLAND = 'Handwerker der Scherbenwelt',
    AD_PROFS_TWO_OUTLAND = 'Werdet gleichzeitig in zwei Berufen Meister.',
    AC_PROFS_TWO_OUTLAND = 'Werdet gleichzeitig in zwei Berufen Meister.',

    AN_FIRST_AID_JOURNEYMAN = 'Lehrling in Erster Hilfe',
    AD_FIRST_AID_JOURNEYMAN = 'Erlangt 75 Fertigkeitspunkte in Erster Hilfe.',
    AN_FIRST_AID_EXPERT = 'Geselle in Erster Hilfe',
    AD_FIRST_AID_EXPERT = 'Erlangt 150 Fertigkeitspunkte in Erster Hilfe.',
    AN_FIRST_AID_ARTISAN = 'Experte in Erster Hilfe',
    AD_FIRST_AID_ARTISAN = 'Erlangt 225 Fertigkeitspunkte in Erster Hilfe.',
    AN_FIRST_AID_MASTER = 'Fachmann in Erster Hilfe',
    AD_FIRST_AID_MASTER = 'Erlangt 300 Fertigkeitspunkte in Erster Hilfe.',
    AN_FIRST_AID_OUTLAND_MASTER = 'Meister in Erster Hilfe',
    AD_FIRST_AID_OUTLAND_MASTER = 'Erlangt 375 Fertigkeitspunkte in Erster Hilfe.',
	
    AN_FISHING_JOURNEYMAN = 'Lehrling im Angeln',
    AD_FISHING_JOURNEYMAN = 'Erlangt 75 Fertigkeitspunkte im Angeln.',
    AN_FISHING_EXPERT = 'Geselle im Angeln',
    AD_FISHING_EXPERT = 'Erlangt 150 Fertigkeitspunkte im Angeln.',
    AN_FISHING_ARTISAN = 'Experte im Angeln',
    AD_FISHING_ARTISAN = 'Erlangt 225 Fertigkeitspunkte im Angeln.',
    AN_FISHING_MASTER = 'Fachmann im Angeln',
    AD_FISHING_MASTER = 'Erlangt 300 Fertigkeitspunkte im Angeln.',
    AN_FISHING_OUTLAND_MASTER = 'Meister im Angeln',
    AD_FISHING_OUTLAND_MASTER = 'Erlangt 375 Fertigkeitspunkte im Angeln.',
	
    AN_COOKING_JOURNEYMAN = 'Lehrling im Kochen',
    AD_COOKING_JOURNEYMAN = 'Erlangt 75 Fertigkeitspunkte im Kochen.',
    AN_COOKING_EXPERT = 'Geselle im Kochen',
    AD_COOKING_EXPERT = 'Erlangt 150 Fertigkeitspunkte im Kochen.',
    AN_COOKING_ARTISAN = 'Experte im Kochen',
    AD_COOKING_ARTISAN = 'Erlangt 225 Fertigkeitspunkte im Kochen.',
    AN_COOKING_MASTER = 'Fachmann im Kochen',
    AD_COOKING_MASTER = 'Erlangt 300 Fertigkeitspunkte im Kochen.',
    AN_COOKING_OUTLAND_MASTER = 'Meister im Kochen',
    AD_COOKING_OUTLAND_MASTER = 'Erlangt 375 Fertigkeitspunkte im Kochen.',
	
    AN_PROFS_SECONDARY = 'Außergewöhnliche Fähigkeiten',
    AD_PROFS_SECONDARY = 'Werdet gleichzeitig Fachmann des Angelns, der Ersten Hilfe und der Kochkunst.',
    AN_PROFS_SECONDARY_OUTLAND = 'Außergewöhnliche Fähigkeiten, auch in der Scherbenwelt',
    AD_PROFS_SECONDARY_OUTLAND = 'Werdet gleichzeitig Meister des Angelns, der Ersten Hilfe und der Kochkunst.',
    AN_PROFS_FIVE = 'Genie',
    AN_PROFS_FIVE_OUTLAND = 'Genie der Scherbenwelt',
    AD_PROFS_FIVE = 'Erlangt die unten aufgelisteten Berufserfolge.',
    AN_UNARMED_SKILL = 'Hat jemand ein Veilchen bestellt?',
    AD_UNARMED_SKILL = 'Erreicht eine unbewaffnete Fertigkeit von 300.',

    AN_EXPLORE_AZEROTH = 'Erforscher von Azeroth',
    AD_EXPLORE_AZEROTH = 'Erkundet die Welt von Azeroth!',
    AN_EXPLORE_KALIMDOR = 'Erforscher Kalimdors',
    AD_EXPLORE_KALIMDOR = 'Erkundet die Regionen Kalimdors.',
    AN_EXPLORE_EASTERN_KINGDOMS = 'Erforscher der Östlichen Königreiche',
    AD_EXPLORE_EASTERN_KINGDOMS = 'Erkundet die Regionen der Östlichen Königreiche.',
    AD_EXPLORE = 'Erkundet %s.',

    AN_SULFURAS = 'Sulfuras, Hand von Ragnaros',
    AD_SULFURAS = 'Träger von Sulfuras, Hand von Ragnaros.',
    AN_THUNDER_FURY = 'Donnerzorn, Gesegnete Klinge des Windsuchers',
    AD_THUNDER_FURY = 'Träger von Donnerzorn, Gesegnete Klinge des Windsuchers.',
    AN_ATIESH = 'Atiesh, Hohestab des Wächters',
    AD_ATIESH = 'Träger von Atiesh, Hohestab des Wächters.',
    AN_BLACK_SCARAB = 'Skarabäusfürst',
    AD_BLACK_SCARAB = 'Die Tore von Ahn\'Qiraj geöffnet.',
    AN_RED_SCARAB = 'Warum? Weil es rot ist!',
    AD_RED_SCARAB = 'Besitzer eines Roter Qirajiresonanzkristall.',
    
    AN_UNCOMMON_GEAR = 'Selten',
    AD_UNCOMMON_GEAR = 'Legt an jedem Platz einen Gegenstand von seltener Qualität an.',
    AN_RARE_GEAR = 'Überlegen',
    AD_RARE_GEAR = 'Legt an jedem Platz einen Gegenstand von überragender Qualität an.',
    AN_EPIC_GEAR = 'Episch',
    AD_EPIC_GEAR = 'Legt an jedem Platz einen epischen Gegenstand an.',

    AN_STOCKING_UP = 'Vorräte aufstocken',
    AD_STOCKING_UP = 'Stellt 100 schwere Runenstoffverbände her.',
    AC_STOCKING_UP = 'Stellt 100 schwere Runenstoffverbände her',
    AN_STOCKING_UP_2 = 'Doppelte Vorratshaltung',
    AD_STOCKING_UP_2 = 'Stellt 500 schwere Runenstoffverbände her.',
    AC_STOCKING_UP_2 = 'Stellt 500 schwere Runenstoffverbände her',
    AN_STOCKING_UP_OUTLAND = 'Vorbereitung für die Leere',
    AD_STOCKING_UP_OUTLAND = 'Stellt 100 schwere Netherstoffverbände her.',
    AC_STOCKING_UP_OUTLAND = 'Stellt 100 schwere Netherstoffverbände her',
    AN_STOCKING_UP_2_OUTLAND = 'Ernsthafte Vorbereitung für die Leere',
    AD_STOCKING_UP_2_OUTLAND = 'Stellt 500 schwere Netherstoffverbände her.',
    AC_STOCKING_UP_2_OUTLAND = 'Stellt 500 schwere Netherstoffverbände her',

    AN_FISHING_ROD = 'Für\'s Angeln nur das Beste!',
    AD_FISHING_ROD = 'Gewinnt den Angelwettbewerb in der Beutebucht und wählt die Arkanitangel als Belohnung.',
    AN_FISHING_TRINKET = 'Echter Fischliebhaber',
    AD_FISHING_TRINKET = 'Gewinnt den Angelwettbewerb in der Beutebucht und wählt den Angelhaken des Anglermeisters als Belohnung.',

    AN_FISHING_COLLECTION = 'Fischsammlung',
    AD_FISHING_COLLECTION = 'Fangt die unten aufgelisteten Fische in Azeroth.',
    AN_FISHING_OUTLAND_COLLECTION = 'Fischsammlung der Scherbenwelt',
    AD_FISHING_OUTLAND_COLLECTION = 'Fangt die unten aufgelisteten Fische in der Scherbenwelt.',
    AN_FISHING_WATER = 'Wasser aus Wasser',
    AD_FISHING_WATER = 'Angelt eine Essenz des Wassers.',
    AN_FISHING_RUM = 'Aufhören unmöglich',
    AD_FISHING_RUM = 'Angelt die folgenden Rumsorten.',
    AC_FISHING_RUM_BLACK = 'Schwarzer Rumsey Rum',
    AC_FISHING_RUM_WHITE = 'Rumsey-Rum Light',
    AN_FISHING_RING = 'Geschenk von Mordor',
    AD_FISHING_RING = 'Angelt den Einen Ring.',
    AN_FISHING_SKULL = 'Bote eines traurigen Endes',
    AD_FISHING_SKULL = 'Angelt Old Teamsters Schädel.',
    AN_FISHING_SNAPPER = 'Großer Schnapperfanger',
    AD_FISHING_SNAPPER = 'Angelt Matschschnapper der folgenden Größen.',
    AC_FISHING_SNAPPER = '%d-pfündiger Matschschnapper',
    AN_FISHING_SEA_BASS = 'Barschfänger',
    AD_FISHING_SEA_BASS = 'Angelt Barsche der folgenden Größen.',
    AC_FISHING_SEA_BASS = '%d-pfündiger Barsch',
    AN_FISHING_SALMON = 'Lachsliebhaber',
    AD_FISHING_SALMON = 'Angelt Lachse der folgenden Größen.',
    AC_FISHING_SALMON = '%d-pfündiger Lachs',
    AN_FISHING_LOBSTER = 'Hummerjäger',
    AD_FISHING_LOBSTER = 'Angelt Hummer der folgenden Größen.',
    AC_FISHING_LOBSTER = '%d-pfündiger Hummer',
    AN_FISHING_BIG_SIZE = 'Der größte Angler von Azeroth',
    AD_FISHING_BIG_SIZE = 'Schließt die unten aufgelisteten Angel-Erfolge ab.',
    AR_FISHING_BIG_SIZE = 'Titel \'größter Angler von Azeroth\'.',

    AN_COOKING_RECIPES_30 = 'Freizeitkoch',
    AN_COOKING_RECIPES_50 = 'Commis de Cuisine',
    AN_COOKING_RECIPES_60 = 'Chef de Partie',
    AN_COOKING_RECIPES_70 = 'Sous Chef',
    AN_COOKING_RECIPES_80 = 'Chef de Cuisine',
    AR_COOKING_RECIPES = 'Titel \'Chefkoch\'.',
    AD_COOKING_RECIPES = 'Lernt %d Kochrezepte.',
    AC_COOKING_RECIPES = 'Lernt %d Kochrezepte',

    AN_COOKING_SOUP = 'Suppenkocher',
    AN_COOKING_DESSERT = 'Konditormeister',
    AN_COOKING_SQUID = 'Fang des Tages',
    AN_COOKING_DUMPLINGS = 'Omas Knödel',
    AN_COOKING_CHOPS = 'Super nahrhafte Koteletts',
    AD_COOKING_CREATE = 'Kocht %s %d-mal.',
    AC_COOKING_CREATE = 'Kocht %s %d-mal',
    AN_COOKING_BIG_TABLE = 'Große Festtafel',
    AD_COOKING_BIG_TABLE = 'Schließt die unten aufgelisteten Koch-Erfolge ab.',

    AN_COOKING_FISHERMANS_FEAST = 'Fischerschmaus',
    AN_COOKING_SPICY_HOT_TALBUK = 'Feuriger Würztalbuk',
    AN_COOKING_SKULLFISH_SOUP = 'Schädelfischsuppe',
    AN_COOKING_RAVAGER_DOG = 'Heißer Hetzer',

    AN_WB_AZUREGOS = 'Das Geheimnis des blauen Drachens',
    AD_WB_AZUREGOS = 'Bezwingt Azuregos.',
    AN_WB_KAZZAK = 'Dämonen können nicht vorbei',
    AD_WB_KAZZAK = 'Bezwingt Lord Kazzak.',
    AN_WB_KAZZAK_OUTLAND = ' Ich bin der Meister meines Schicksals',
    AD_WB_KAZZAK_OUTLAND = 'Bezwingt Verdammnislord Kazzak auf der Höllenfeuerhalbinsel.',
    AN_WB_DOOMWALKER = 'Kaputter Verdammniswandler',
    AD_WB_DOOMWALKER = 'Bezwingt den Verdammniswandler im Schattenmondtal.',
    AN_WB_YSONDRE = 'Kein Platz für Mädchen in einem Albtraum',
    AD_WB_YSONDRE = 'Bezwingt Ysondre.',
    AN_WB_LETHON = 'Kind des Smaragdgrünen Albtraums',
    AD_WB_LETHON = 'Bezwingt Lethon.',
    AN_WB_EMERISS = 'Emeriss, der Verräter des Lebens',
    AD_WB_EMERISS = 'Bezwingt Emeriss.',
    AN_WB_TAERAR = 'Albtraumhafte Taerar',
    AD_WB_TAERAR = 'Bezwingt Taerar.',
    AN_WB_EMERALD_DRAGONS = 'Smaragdgrüner Wächter',
    AD_WB_EMERALD_DRAGONS = 'Bezwingt alle Drachen des Smaragdgrünen Albtraums.',
    AR_WB_EMERALD_DRAGONS = 'Titel \'Smaragdgrüner Wächter\'.',

    AN_DUEL = 'Duell-ikat',
    AD_DUEL = 'Gewinnt ein Duell gegen einen anderen Spieler.',
    AN_DUELS_10 = 'Duellist',
    AN_DUELS_25 = 'Geübter Duellist',
    AN_DUELS_100 = 'Meister-Duellist',
    AD_DUELS = 'Gewinnt in %d Duellen.',
    AC_DUELS = 'Gewinnt in %d Duellen',
    AN_GURUBASHI_1 = 'Gurubashi Arenameister',
    AD_GURUBASHI_1 = 'Plündert den Schmuck des Arenagroßmeisters aus der Gurubashi Arena.',
    AN_GURUBASHI_2 = 'Gurubashi Arenagroßmeister',
    AD_GURUBASHI_2 = 'Schließt die Quest von Störtebrecher ab, um den Schmuck des Arenagroßmeisters zu erhalten.',
    AN_PARTICIPATE_IN_BGS = 'Ruf zu den Waffen!',
    AD_PARTICIPATE_IN_BGS = 'Schließt %d Schlachtfelder auf dem maximalen Level ab.',
    AC_PARTICIPATE_IN_BGS = 'Schließt %d Schlachtfelder auf dem maximalen Level ab.',

    EMOTE_LOVE1 = 'Ihr liebt love %s.',
    AN_LOVE = 'Ob groß, ob klein, Tiere sind alle fein',
    AD_LOVE = 'Zeigt den Tieren in Azeroth, wie sehr Ihr sie liebt (/liebe).',
    EMOTE_PAT1 = 'Ihr streichelt %s.',
    AN_ARATHI_CATS = 'Katzen kommen zuerst',
    AD_ARATHI_CATS = 'Streichelt die angegebenen Katzen im Arathibecken (/streicheln).',

    AN_ALTERAC_FAST_WIN = 'Der Alteracblitz',
    AD_ALTERAC_FAST_WIN = 'Gewinnt im Alteractal innerhalb von 6 Minuten.',
    AN_WARSONG_FAST_WIN = 'Motivation der Kriegshymne',
    AD_WARSONG_FAST_WIN = 'Gewinnt in der Kriegshymnenschlucht in weniger als 7 Minuten.',
    AN_ARATHI_FAST_WIN = 'Auf die Schnelle',
    AD_ARATHI_FAST_WIN = 'Gewinnt im Arathibecken in 6 Minuten.',

    AN_ALTERAC_TOWER_DEFEND_TOTAL = 'Turmverteidigung',
    AD_ALTERAC_TOWER_DEFEND_TOTAL = 'Verteidigt %d Türme im Alteractal.',
    AN_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Alterac-Grabjäger',
    AD_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Nehmt %d Friedhöfe im Alteractal ein.',
    AN_WARSONG_FLAG_CAPTURE_TOTAL = 'Erobert die Flagge',
    AD_WARSONG_FLAG_CAPTURE_TOTAL = 'Ergreift und erobert persönlich %d Flaggen in der Kriegshymnenschlucht.',
    AN_WARSONG_FLAG_RETURN_TOTAL = 'Hartnäckiger Verteidiger',
    AD_WARSONG_FLAG_RETURN_TOTAL = 'Bringt als Verteidiger in der Kriegshymnenschlucht %d Flaggen zurück.',
    AN_ARATHI_BASE_ASSAULT_TOTAL = 'Flaggenjagd',
    AD_ARATHI_BASE_ASSAULT_TOTAL = 'Erobert %d Flaggen im Arathibecken.',
    AN_ARATHI_BASE_DEFEND_TOTAL = 'Rettungseinsatz',
    AD_ARATHI_BASE_DEFEND_TOTAL = 'Eilt im Arathibecken %d-mal zur Verteidigung einer Basis, indem Ihr die Flagge zurückerobert.',
    AN_ALTERAC_MOUNT_HORDE = 'Frostwolfheuler',
    AD_ALTERAC_MOUNT_HORDE = 'Erhaltet einen Frostwolfheuler.',
    AN_ALTERAC_MOUNT_ALLIANCE = 'Streitwidder der Sturmlanzen',
    AD_ALTERAC_MOUNT_ALLIANCE = 'Erhaltet einen Streitwidder der Sturmlanzen.',

    AN_ALTERAC_BOSS = 'Meister des Alteractals',
    AD_ALTERAC_BOSS = 'Schließt die unten aufgelisteten Questerfolge im Alteractal ab.',
    AN_WARSONG_BOSS = 'Meister der Warsongschlucht',
    AD_WARSONG_BOSS = 'Schließt die unten aufgelisteten Questerfolge in der Warsongschlucht ab.',
    AN_ARATHI_BOSS = 'Meister des Arathibeckens',
    AD_ARATHI_BOSS = 'Schließt die unten aufgelisteten Arathibeckenerfolge ab.',
    AN_EYE_BOSS = 'Meister des Auge des Sturms',
    AD_EYE_BOSS = 'Schließt die unten aufgelisteten Erfolge im Auge des Sturms ab.',
    AN_BATTLEMASTER = 'Kampfmeister',
    AD_BATTLEMASTER = 'Schließt die unten aufgelisteten Schlachtfeld-Erfolge ab.',
    AR_BATTLEMASTER = 'Title \Kampfmeister\'.',

    AN_LEEROY = 'Leeeeeeeeeeeeeeeroy!',
    AD_LEEROY = 'Tötet 50 Krähenhorstwelpen innerhalb von 15 Sekunden.',
    AR_LEEROY = 'Titel \'Jenkins\'',
    AN_BWL_DUO = 'Doppelter Atem',
    AD_BWL_DUO = 'Bezwingt Schattenschwinge und Flammenmaul innerhalb von 45 Sekunden.',
    AN_ANUBREKHAN_WITHOUT_MOBS = 'Eine große Spinne',
    AD_ANUBREKHAN_WITHOUT_MOBS = 'Bezwingt Anub\'Rekhan in Naxxramas, während beide Gruftwachen am Leben sind.',
    AN_FAERLINA_WITHOUT_MOBS = 'Witwenjäger',
    AD_FAERLINA_WITHOUT_MOBS = 'Bezwingt Großwitwe Faerlina in Naxxramas, während alle Anhänger und Jünger von Naxxramas am Leben sind.',
    AN_SAPPHIRONE_WITH_ALL_ALIVE = 'Sapphirons Ableben',
    AD_SAPPHIRONE_WITH_ALL_ALIVE = 'Bezwingt Sapphiron in Naxxramas während alle 40 Schlachtzugsmitglieder am Leben sind.',
    AN_ARACHNOPHOBIA = 'Arachnophobie',
    AD_ARACHNOPHOBIA = 'Bezwingt Maexxna in Naxxramas innerhalb von 20 Minuten nach Anub\'Rekhans Tod.',
    AN_FOUR_TOGETHER = 'Zusammen bis in den Tod',
    AD_FOUR_TOGETHER = 'Bezwingt die Vier Reiter in Naxxramas, wobei sie im Abstand von höchstens 15 Sekunden hintereinander sterben müssen.',

    AN_THANKS = 'I\'m myself, you know, a developer',
    AD_THANKS = 'Was especially helpful in developing, testing, translating or promoting Classic Achievements.',
    AR_THANKS = 'Infinite gratitude :)',

	--BURNING CRUSADE

    AN_QUESTS_HELLFIRE_PENINSULA = 'To Hellfire and Back',
    AD_QUESTS_HELLFIRE_PENINSULA = 'Complete the Hellfire Peninsula storylines listed below.',
    TBC_QUEST_10388 = 'Disrupt the Burning Legion',
    TBC_QUEST_10389 = 'Cruel\'s Intentions',
    TBC_QUEST_10876 = 'The Hand of Kargath',
    TBC_QUEST_10258 = 'Spinebreaker Post',
    TBC_QUEST_9406 = 'The Mag\'har',
    TBC_QUEST_9370 = 'Falcon Watch',
    TBC_QUEST_10351 = 'Cenarion Post',

    TBC_QUEST_10397 = 'Disrupt the Burning Legion',
    TBC_QUEST_10400 = 'Overthrow the Overlord',
    TBC_QUEST_9545 = 'In Search of Sedai',
    TBC_QUEST_10935 = 'The Exorcism of Colonel Jules',
    TBC_QUEST_10937 = 'Drill the Drillmaster',
    TBC_QUEST_9383 = 'Temple of Telhamat',
    TBC_QUEST_10630 = 'Green, But Not Orcs',
    
    AN_QUESTS_ZANGARMASH = 'Mysteries of the Marsh',
    AD_QUESTS_ZANGARMASH = 'Complete the Zangarmarsh storylines listed below.',
    TBC_QUEST_9772 = 'Swamprat Post',
    TBC_QUEST_9904 = 'Zabra\'jin',
    TBC_QUEST_10118 = 'The Defense of Zabra\'jin',
    TBC_QUEST_9803 = 'Draenei Diplomacy',
    TBC_QUEST_9783 = 'Telredor',
    TBC_QUEST_9902 = 'Orebor Harborage',
    TBC_QUEST_9709 = 'Don\'t Eat THOSE Mushrooms!',
    TBC_QUEST_9732 = 'Draining the Marsh',
    TBC_QUEST_9788 = 'Saving the Sporeloks',
    TBC_QUEST_9726 = 'A Trip With the Sporelings',
    
    AN_QUESTS_TERROKAR = 'Terror of Terokkar',
    AD_QUESTS_TERROKAR = 'Complete the Terokkar Forest storylines listed below.',
    TBC_QUEST_10879 = 'The Skettis Offensive',
    TBC_QUEST_10881 = 'Refugee Caravan',
    TBC_QUEST_10915 = 'Sha\'tari Base Camp',
    TBC_QUEST_9951 = 'The Warden\'s Secret',
    TBC_QUEST_10042 = 'Allerian Stronghold',
    TBC_QUEST_10043 = 'Stonebreaker Hold',
    
    AN_QUESTS_NAGRAND = 'Nagrand Slam',
    AD_QUESTS_NAGRAND = 'Complete the Nagrand storylines listed below.',
    TBC_QUEST_10172 = 'Birth of a Warchief',
    TBC_QUEST_9977 = 'The Ring of Blood',
    TBC_QUEST_9853 = 'Throne of the Elements',
    TBC_QUEST_9934 = 'Lantresor of the Blade',
    TBC_QUEST_9868 = 'The Murkblood',
    TBC_QUEST_9937 = 'Threats to Nagrand',
    TBC_QUEST_9852 = 'The Ultimate Bloodsport',
    TBC_QUEST_9925 = 'Encountering the Ethereals',
    TBC_QUEST_9955 = 'The Adventures of Corki',
    TBC_QUEST_9933 = 'Lantresor of the Blade',
    TBC_QUEST_9873 = 'The Murkblood',
    TBC_QUEST_10011 = 'Threats to Nagrand',
    
    AN_QUESTS_BLADES_EDGE_MTNS = 'On the Blade\'s Edge',
    AD_QUESTS_BLADES_EDGE_MTNS = 'Complete the Blade\'s Edge Mountains storylines listed below..',
    TBC_QUEST_10504 = 'Sylvanaar',
    TBC_QUEST_10671 = 'Toshley\'s Station',
    TBC_QUEST_10806 = 'The Gronn Threat',
    TBC_QUEST_10505 = 'Thunderlord Stronghold',
    TBC_QUEST_10742 = 'Reunion',
    TBC_QUEST_10867 = 'The Mok\'Nathal',
    TBC_QUEST_10748 = 'Ruuan Weald',
    
    AN_QUESTS_NETHERSTORM = 'Into the Nether',
    AD_QUESTS_NETHERSTORM = 'Complete the Netherstorm storylines listed below.',
    TBC_QUEST_10409 = 'Socrethar',
    TBC_QUEST_10240 = 'The Violet Tower',
    TBC_QUEST_10249 = 'Protect Area 52!',
    TBC_QUEST_10439 = 'Destroying the All-Devouring',
    TBC_QUEST_10221 = 'Building the X-52 Nether-Rocket',
    TBC_QUEST_10276 = 'The Consortium',
    
    AN_QUESTS_SHADOWMOON = 'Shadow of the Betrayer',
    AD_QUESTS_SHADOWMOON = 'Complete the Shadowmoon Valley storylines listed below.',
    TBC_QUEST_10744 = 'News of Victory',
    TBC_QUEST_11041 = 'Netherwing Ledge',
    TBC_QUEST_10645 = 'The First Death Knight',
    TBC_QUEST_10651 = 'Borrowed Power',
    TBC_QUEST_11052 = 'Akama\'s Promise',
    TBC_QUEST_10588 = 'The Cipher of Damnation',
    TBC_QUEST_10679 = 'Anti-Demon Weapons',
    TBC_QUEST_10808 = 'The Dark Conclave',

    HEROIC_NAME_PATTERN = 'Heroic: %s',
    HEROIC_DESCRIPTION_PATTERN = '%s on Heroic Difficulty',

    AN_HELLFIRE_RAMPARTS = 'Hellfire Ramparts',
    AD_HELLFIRE_RAMPARTS = 'Defeat the leaders of Hellfire Ramparts',
    AC_BOSS_17308 = 'Omor the Unscarred',
    AC_BOSS_17537 = 'Vazruden the Herald',

    AN_BLOOD_FURNACE = 'The Blood Furnace',
    AD_BLOOD_FURNACE = 'Defeat Keli\'dan the Breaker',

    AN_SLAVE_PENS = 'The Slave Pens',
    AD_SLAVE_PENS = 'Defeat Quagmirran',

    AN_UNDERBOG = 'Underbog',
    AD_UNDERBOG = 'Defeat The Black Stalker',

    AN_MANA_TOMBS = 'Mana-Tombs',
    AD_MANA_TOMBS = 'Defeat Nexus-Prince Shaffar',

    AN_AUCHENAI_CRYPTS = 'Auchenai Crypts',
    AD_AUCHENAI_CRYPTS = 'Defeat Exarch Maladaar',

    AN_OLD_HILLSBRAD = 'The Escape From Durnholde',
    AD_OLD_HILLSBRAD = 'Defeat Epoch Hunter',

    AN_SETHEKK_HALLS = 'Sethekk Halls',
    AD_SETHEKK_HALLS = 'Defeat Talon King Ikiss',

    AN_STEAMVAULT = 'The Steamvault',
    AD_STEAMVAULT = 'Defeat Warlord Kalithresh',

    AN_SHADOW_LABYRINTH = 'Shadow Labyrinth',
    AD_SHADOW_LABYRINTH = 'Defear Murmur',

    AN_SHATTERED_HALLS = 'The Shattered Halls',
    AD_SHATTERED_HALLS = 'Defeat Warchief Kargath Bladefist',

    AN_BLACK_MORASS = 'Opening of the Dark Portal',
    AD_BLACK_MORASS = 'Defeat Aeonus',

    AN_BOTANICA = 'The Botanica',
    AD_BOTANICA = 'Defeat Warp Splinter',

    AN_MECHANAR = 'The Mechanar',
    AD_MECHANAR = 'Defeat Pathaleon the Calculator',

    AN_ARCATRAZ = 'The Arcatraz',
    AD_ARCATRAZ = 'Defeat Harbringer Skyriss',

    AN_TBC_DUNGEONS = 'Outland Dungeon Hero',
    AD_TBC_DUNGEONS = 'Complete the Burning Crusade Heroic dungeon achievements listed below.',

    AN_RAVEN_LORD = 'Raven Lord',
    AD_RAVEN_LORD = 'Obtain the very rare Reins of the Raven Lord.',

    AN_KARAZHAN = 'Karazhan',
    AD_KARAZHAN = 'Defeat Prince Malchezaar in Karazhan.',

    AN_GRUUL = 'Gruul\'s Lair',
    AD_GRUUL = 'Defeat Gruul the Dragonkiller in Gruul\'s Lair.',

    AN_MAGTHERIDON = 'Magtheridon\'s Lair',
    AD_MAGTHERIDON = 'Defeat Magtheridon in Magtheridon\'s Lair.',

    AN_TBC_PHASE_1 = 'Outland Phase One Raider',
    AD_TBC_PHASE_1 = 'Complete the Burning Crusade phase one raid achievements listed below.',
    AN_TBC_PHASE_2 = 'Outland Phase Two Raider',
    AD_TBC_PHASE_2 = 'Complete the Burning Crusade phase two raid achievements listed below.',
    AN_TBC_PHASE_2 = 'Outland Phase Three Raider',
    AD_TBC_PHASE_2 = 'Complete the Burning Crusade phase three raid achievements listed below.',

    FACTION_946 = 'Honor Hold',
    FACTION_947 = 'Thrallmar',
    FACTION_942 = 'Cenarion Expedition',
    FACTION_1011 = 'Lower City',
    FACTION_989 = 'Keepers of Time',
    FACTION_935 = 'The Sha\'tar',

    AN_TBC_DUNGEON_REPUTATIONS = 'The Burning Crusader',
    AD_TBC_DUNGEON_REPUTATIONS = 'Raise all of The Burning Crusade dungeon reputations to Exalted.',

    AN_SHATTRATH_REP = 'Shattrath Divided',
    AD_SHATTRATH_REP = 'Earn Exalted status with The Scryers or The Aldor.',

    AN_OGRILA = 'A Quest a Day Keeps the Ogres at Bay',
    AD_OGRILA = 'Earn Exalted status within Ogri\'la.',

    AN_SPOREGGAR = 'The Czar of Sporeggar',
    AD_SPOREGGAR = 'Earn Exalted status with Sporeggar.',

    AN_CONSORTIUM = 'Chief Exalted Officer',
    AD_CONSORTIUM = 'Earn Exalted status with The Consortium.',

    AN_MAGHAR = 'Mag\'har of Draenor',
    AD_MAGHAR = 'Earn Exalted status with The Mag\'har.',

    AN_KURENAI = 'Oh My, Kurenai',
    AD_KURENAI = 'Earn Exalted status with the Kurenai.',

    AN_NETHERWINGS = 'On Wings of Nether',
    AD_NETHERWINGS = 'Earn Exalted status with Netherwing.',

    AN_SKYSHATTERED = 'Skyshattered',
    AD_SKYSHATTERED = 'Defeat Captain Skyshatter in the Dragonmaw race on Netherwing Ledge.',

    AN_AMETHYST_EYE = 'The Violet Eye',
    AD_AMETHYST_EYE = 'Earn Exalted status with The Violet Eye.',

    AN_SCALE_OF_THE_SANDS = 'The Scale of the Sands',
    AD_SCALE_OF_THE_SANDS = 'Earn Exalted status with The Scale of the Sands.',

    AN_ASHTONGUE_DEATHSWORN = 'Sworn to the Deathsworn',
    AD_ASHTONGUE_DEATHSWORN = 'Earn Exalted status with the Ashtongue Deathsworn.',

    AN_SHATTERED_SUN = 'You\'re So Offensive',
    AD_SHATTERED_SUN = 'Earn Exalted status with the Shattered Sun Offensive.',

    AN_MR_PINCHY = 'Dr. Zwicky!',
    AD_MR_PINCHY = 'Angelt Dr. Zwicky in der Scherbenwelt.',

    EXPLORE_OUTLAND_NAME_PATTERN = '%s',
    AD_EXPLORE_HELLFIRE_PENINSULA = 'Erkundet Höllenfeuerhalbinsel.',
    AD_EXPLORE_ZANGARMASH = 'Erkundet Zangarmarsche.',
    AD_EXPLORE_NAGRAND = 'Erkundet Nagrand.',
    AD_EXPLORE_TERROKAR = 'Erkundet Wälder von Terokkar.',
    AD_EXPLORE_BLADES_EDGE_MTNS = 'Erkundet Schergrat.',
    AD_EXPLORE_NETHERSTORM = 'Erkundet Netherstorm.',
    AD_EXPLORE_SHADOWMOON = 'Erkundet Schattenmondtal.',
    AN_EXPLORE_OUTLAND = 'Outland Explorer',
    AD_EXPLORE_OUTLAND = 'Explore the regions of Outland.',
    AN_EXPLORER = 'Universal Explorer',
    AD_EXPLORER = 'Explore all the lands of Azeroth and Outland.',
    AR_EXPLORER = 'The unspoken title of The Explorer.',

    AD_EXPLORE_EVERSONG_WOODS = 'Erkundet Immersangwald.',
    AD_EXPLORE_GHOSTLANDS = 'Erkundet Geisterlande.',
    AD_EXPLORE_AZUREMYST_ISLE = 'Erkundet Azurmythosinsel.',
    AD_EXPLORE_BLOODMYST_ISLE = 'Erkundet Blutmythosinsel.',

    AN_MIDDLE_RARE = 'Medium Rare',
    AD_MIDDLE_RARE = 'Kill one of the extremely rare and hard to find Outland creatures listed below.',
    AN_BLOODY_RARE = 'Bloody Rare',
    AD_BLOODY_RARE = 'Kill all of the extremely rare and hard to find Outland creatures listed below.',
    TBC_NPC_18695 = 'Ambassador Jerrikar',
    TBC_NPC_18682 = 'Bog Lurker',
    TBC_NPC_18697 = 'Chief Engineer Lorthander',
    TBC_NPC_18681 = 'Coilfang Emissary',
    TBC_NPC_18694 = 'Collidus the Warp-Watcher',
    TBC_NPC_18689 = 'Crippler',
    TBC_NPC_18686 = 'Doomsayer Jurim',
    TBC_NPC_18698 = 'Ever-Core the Punisher',
    TBC_NPC_18678 = 'Fulgorge',
    TBC_NPC_17144 = 'Goretooth',
    TBC_NPC_18692 = 'Hemathion',
    TBC_NPC_18696 = 'Kraator',
    TBC_NPC_18680 = 'Marticar',
    TBC_NPC_18677 = 'Mekthorg the Wild',
    TBC_NPC_18690 = 'Morcrush',
    TBC_NPC_20932 = 'Nuramoc',
    TBC_NPC_18685 = 'Okrek',
    TBC_NPC_18693 = 'Speaker Mar\'grom',
    TBC_NPC_18683 = 'Voidhunter Yar',
    TBC_NPC_18679 = 'Vorakem Doomspeaker',

    AN_PREPATCH_QUEST = 'Battle for the Dark Portal',
    AD_PREPATCH_QUEST = 'Participant in the Battle for the Dark Portal. Wielder of the Tabard of the Protector.',

    AN_RIDING_75 = 'Aufsatteln!',
    AD_RIDING_75 = 'Erlernt die Fähigkeit \'Unerfahrener Reiter\'.',
    AN_RIDING_150 = 'Traber',
    AD_RIDING_150 = 'Erlernt die Fähigkeit \'Geübter Reiter\'.',
    AN_RIDING_225 = 'Galopper',
    AD_RIDING_225 = 'Erlernt die Fähigkeit \'Erfahrener Reiter\'.',
    AN_RIDING_300 = 'Wie der Wind',
    AD_RIDING_300 = 'Erlernt die Fähigkeit \'Gekonnter Reiter\'.',

    AN_ATTUNE_SHATTERED_HALLS = 'Hotter than Hell',
    AD_ATTUNE_SHATTERED_HALLS = 'Obtain the Shattered Halls Key.',
    AN_ATTUNE_ARCATRAZ = 'Infiltrating the Arcatraz',
    AD_ATTUNE_ARCATRAZ = 'Obtain the Key to the Arcatraz.',
    AN_ATTUNE_KARAZHAN = 'The Master\'s Touch',
    AD_ATTUNE_KARAZHAN = 'Obtain The Master\'s Key.',
    AN_ATTUNE_NIGHT_BANE = 'Digging Up the Past',
    AD_ATTUNE_NIGHT_BANE = 'Obtain the Blackened Urn.',
    AN_ATTUNE_SSC = 'Access to the Serpentshrine Cavern',
    AD_ATTUNE_SSC = 'Get access to the Serpentshrine Cavern.',
    AN_ATTUNE_EYE = 'The Eye',
    AD_ATTUNE_EYE = 'Obtain The Tempest Key.',
    AN_ATTUNE_HYJAL = 'The Vials of Eternity',
    AD_ATTUNE_HYJAL = 'Feed Soridormi from the Vials of Eternity and gain access to the Hujal Summit.',
    AN_ATTUNE_BLACK_TEMPLE = 'Entry Into the Black Temple',
    AD_ATTUNE_BLACK_TEMPLE = 'Obtain the Medallion of Karabor.',

    AN_SSC = 'Serpentshrine Cavern',
    AD_SSC = 'Defeat bosses listed below inside Serpentshrine Cavern.',
    AC_KILL_HYDROS = 'Hydross the Unstable',
    AC_KILL_LURKER = 'The Lurker Below',
    AC_KILL_LEOTHERAS = 'Leotheras the Blind',
    AC_KILL_KARATHRESS = 'Fathom-Lord Karathress',
    AC_KILL_MOROGRIM = 'Morogrim Tidewalker',
    AC_KILL_VASHJ = 'Lady Vashj',
    AN_TK = 'Tempest Keep',
    AD_TK = 'Defeat bosses listed below inside The Eye raid instance.',
    AC_KILL_ALAR = 'Al\'ar',
    AC_KILL_VOID_REAVER = 'Void Reader',
    AC_KILL_SOLARIAN = 'High Astromancer Solarian',
    AC_KILL_KAELTHAS = 'Kael\'thas Sunstrider',

    AN_HYJAL = 'The Battle for Mount Hyjal',
    AD_HYJAL = 'Defeat Archimonde in The Battle for Mount Hyjal.',

    AN_BT_ENTRANCE = 'Infiltration',
    AD_BT_ENTRANCE = 'Make your way to the Black Temple from the sewers by defeating the listed bosses.',
    AC_KILL_NAJENTUS = 'High Warlord Naj\'entus',
    AC_KILL_SUPREMUS = 'Supremus',

    AN_BT_SECOND_WING = 'Acolyte of Karabor',
    AD_BT_SECOND_WING = 'Cleanse the main halls of the Black Temple from the evil that has settled in there by defeating the listed bosses.',
    AC_KILL_SHADOW_OF_AKAMA = 'Shade of Akama',
    AC_KILL_THERON = 'Teron Gorefiend',
    AC_KILL_GURTOGG = 'Gurtogg Bloodboil',
    AC_KILL_RELIQUARY = 'Reliquary of Souls',

    AN_BT_LAST_WING = 'Top of the Temple',
    AD_BT_LAST_WING = 'Infiltrate the upper floors of the Black Temple and defeat the listed bosses.',
    AC_KILL_MOTHER_SHAHRAZ = 'Mother Shahraz',
    AC_KILL_BT_COUNCIL = 'The Illidari Council',
    AC_KILL_ILLIDAN = 'Illidan Stormrage',

    AN_BLACK_TEMPLE = 'The Black Temple',
    AD_BLACK_TEMPLE = 'Earn the achievements listed below by defeating all the bosses in the Black Temple.',
    AR_BLACK_TEMPLE = 'Unspoken title "from the Black Temple" :)',

    AN_AZZINOTH = 'Warglaives of Azzinoth',
    AD_AZZINOTH = 'Wielder of the Warglaives of Azzinoth.',
    AC_OBTAIN_MAINHAND_AZZINOTH = 'Right blade of Azzinoth',
    AC_OBTAIN_OFFHAND_AZZINOTH = 'Left blade of Azzinoth',

    AN_P3_FIRST_WEEK = 'Conqueror of the Outland',
    AD_P3_FIRST_WEEK = 'Defeat Archimonde and Illidan Stormrage in their respective raids within the first week of the release of phase three.',
    AC_KILL_ARCHIMONDE = 'Archimonde',
    AR_P3_FIRST_WEEK = 'Unspoken title of the Conqueror of the Outland.'

})
