SexyLib:InitLocalization('Anniversary Achievements', {
    achievement_earned = '&aAchievement earned by %s on %d/%d/%d',
    achievement_in_progress = '&7Achievement in progress by %s',

    ICON_DESCRIPTION = '&7Left mouse button: &eopen/hide achievements window\n&7Right mouse button: &eopen Anniversary Achievements settings',

    OPTION_SHARING = 'Share achievements',
    OPTION_SHARING_DESC = 'Write messages in chat when completing a new achievement.',
    OPTION_MICROBUTTON = 'Micromenu button',
    OPTION_MICROBUTTON_DESC = 'If enabled, an addon button will be added to the micromenu, and the interface may break if you are using any addon to modify it. If disabled, the icon will be added to the minimap. Toggling this option requires you to do /reload your interface.',
    OPTION_UPDATE_MAP_EXPLORATION = 'Check explored areas',
    OPTION_UPDATE_MAP_EXPLORATION_DESC = 'Counts already explored areas for achievements.',
    OPTION_RESET_ACHIEVEMENTS = 'Reset achievements',
    OPTION_RESET_ACHIEVEMENTS_DESC = 'Reset all achievements progressions on this character. This can not be undone!',

    GOT_ACHIEVEMENT_MESSAGE_MALE = 'I\'ve just earned achievement %s!',
    GOT_ACHIEVEMENT_MESSAGE_FEMALE = 'I\'ve just earned achievement %s!',

    COMPARE_ACHIEVEMENTS = 'Compare achievements',
    TARGET_DOES_NOT_HAVE_ADDON = 'Target does not have this addon installed.',

    UPDATING_EXPLORED_AREAS = 'Updating area exploration data. This action will take a few seconds.',
    UPDATED_EXPLORED_AREAS = '&aInformation about explored areas has been updated!',

    GEAR_SLOT_HEAD = 'Head',
    GEAR_SLOT_NECK = 'Neck',
    GEAR_SLOT_SHOULDER = 'Shoulder',
    GEAR_SLOT_CHEST = 'Chest',
    GEAR_SLOT_WAIST = 'Waist',
    GEAR_SLOT_LEGS = 'Legs',
    GEAR_SLOT_FEET = 'Feet',
    GEAR_SLOT_WRIST = 'Wrist',
    GEAR_SLOT_HANDS = 'Hands',
    GEAR_SLOT_FIRST_RING = 'Right Ring',
    GEAR_SLOT_SECOND_RING = 'Left Ring',
    GEAR_SLOT_FIRST_TRINKET = 'First Trinket',
    GEAR_SLOT_SECOND_TRINKET = 'Second Trinket',
    GEAR_SLOT_CLOAK = 'Cloak',
    GEAR_SLOT_WEAPON = 'Weapon',

    NPC_3444 = 'Dig Rat',
    NPC_620 = 'Chicken',
    NPC_1420 = 'Toad',
    NPC_13321 = 'Frog',
    NPC_2620 = 'Prairie Dog',
    NPC_9600 = 'Parrot',
    NPC_883 = 'Deer',
    NPC_9699 = 'Fire Beetle',
    NPC_4953 = 'Moccasin',
    NPC_721 = 'Rabbit',
    NPC_9700 = 'Lava Crab',
    NPC_15476 = 'Scorpion',
    NPC_2914 = 'Snake',
    NPC_16030 = 'Maggot',
    NPC_4075 = 'Rat',
    NPC_1412 = 'Squirrel',
    NPC_7390 = 'Cockatiel',
    NPC_15475 = 'Beetle',
    NPC_15010 = 'Jungle Toad',
    NPC_4076 = 'Roach',
    NPC_13016 = 'Deeprun Rat',
    NPC_14881 = 'Spider',
    NPC_2110 = 'Black Rat',
    NPC_4166 = 'Gazelle',
    NPC_1933 = 'Sheep',
    NPC_890 = 'Fawn',
    NPC_2098 = 'Ram',
    NPC_2442 = 'Cow',
    NPC_6368 = 'Cat',
    NPC_10582 = 'Dog <Sire>',
    NPC_385 = 'Horse',
    NPC_10685 = 'Swine',
    NPC_3300 = 'Adder',
    NPC_15066 = 'Cleo',
    NPC_15071 = 'Underfoot',

    CATEGORY_GENERAL = 'General',
    CATEGORY_QUESTS = 'Quests',
	CATEGORY_PVP = 'Player vs. Player',
    CATEGORY_KALIMDOR = 'Kalimdor',
    CATEGORY_EASTERN_KINGDOMS = 'Eastern Kingdoms',
    CATEGORY_OUTLAND = 'Outland',
    CATEGORY_VANILLA = 'Classic',
    CATEGORY_TBC = 'The Burning Crusade',
    CATEGORY_EXPLORATION = 'Exploration',
    CATEGORY_PVE = 'Dungeons & Raids',
    CATEGORY_BG_ALTERAC = 'Alterac Valley',
    CATEGORY_BG_WARSONG = 'Warsong Gulch',
    CATEGORY_BG_ARATHI = 'Arathi Basin',
    CATEGORY_BG_EYE = 'Eye of the Storm',
    CATEGORY_PROFESSIONS = 'Professions',
    CATEGORY_REPUTATION = 'Reputation',
	CATEGORY_EVENTS = 'World Events',
	CATEGORY_HALLOWSEND = 'Hallow\'s End',
    CATEGORY_FEATS_OF_STRENGTH = 'Feats of Strength',
	
	AN_DRUID_T1 = 'Cenarion Raiment',
	AN_WARLOCK_T1 = 'Felheart Raiment',
	AN_PRIEST_T1 = 'Vestments of Prophecy',
	AN_MAGE_T1 = 'Arcanist Regalia',
	AN_ROGUE_T1 = 'Nightslayer Armor',
	AN_HUNTER_T1 = 'Giantstalker Armor',
	AN_PALADIN_T1 = 'Lawbringer Armor',
	AN_WARRIOR_T1 = 'Battlegear of Might',
	AN_SHAMAN_T1 = 'Earthfury Raiment',
	
	AN_DRUID_T2 = 'Stormrage Raiment',
	AN_WARLOCK_T2 = 'Nemesis Raiment',
	AN_PRIEST_T2 = 'Vestments of Transcendence',
	AN_MAGE_T2 = 'Netherwind Regalia',
	AN_ROGUE_T2 = 'Bloodfang Armor',
	AN_HUNTER_T2 = 'Dragonstalker Armor',
	AN_PALADIN_T2 = 'Judgement Armor',
	AN_WARRIOR_T2 = 'Battlegear of Wrath',
	AN_SHAMAN_T2 = 'The Ten Storms',

	AN_DRUID_T3 = 'Dreamwalker Raiment',
	AN_WARLOCK_T3 = 'Plagueheart Raiment',
	AN_PRIEST_T3 = 'Vestments of Faith',
	AN_MAGE_T3 = 'Frostfire Regalia',
	AN_ROGUE_T3 = 'Bonescythe Armor',
	AN_HUNTER_T3 = 'Cryptstalker Armor',
	AN_PALADIN_T3 = 'Redemption Armor',
	AN_WARRIOR_T3 = 'Dreadnaught\'s Battlegear',
	AN_SHAMAN_T3 = 'The Earthshatterer',	
	
	AD_SET = 'Collect all items of the mentioned set.',
	
	AN_SKELETON_KEY = 'The Key to Scholomance',
	AD_SKELETON_KEY = 'Obtain the Skeleton Key.',

    AN_LVL = 'Level %d',
    AD_LVL = 'Reach level %d.',

    AN_BANK = 'Safe Deposit',
    AD_BANK = 'Buy 6 additional bank slots.',
    AC_BANK = 'Buy 6 additional bank slots.',

    AN_QUESTS = '%d Quests Completed',
    AD_QUESTS = 'Complete %d quests.',
    AC_QUESTS = 'Complete %d quests.',

    AN_QUEST_GOLD5 = 'Glittering Reward',
    AN_QUEST_GOLD10 = 'Collector of minted Coins',
    AN_QUEST_GOLD25 = 'Breadwinner',
    AN_QUEST_GOLD50 = 'Well-deserved Gold',
    AN_QUEST_GOLD100 = 'Earned with Sweat and Blood',
    AN_QUEST_GOLD250 = 'Golden Printer',
    AN_QUEST_GOLD500 = 'I\'m Mint Myself',
    AD_QUEST_GOLD = 'Make %d gold from quest rewards.',
    AC_QUEST_GOLD = 'Make %d gold from quest rewards.',

    AN_QUESTS_ZONE = 'Loremaster of %s',
    AD_QUESTS_ZONE = 'Complete quest "%s" in %s.',
    AD_QUESTS_ZONE_MULTI = 'Complete the following quests in %s.',
    AC_QUESTS_ZONE = 'Completed quest "%s".',

    AZSHARA_1 = 'Azshara',
    AZSHARA_2 = 'Azshara',
    QUEST_3602 = 'Azsharite',

    FELWOOD_1 = 'Felwood',
    FELWOOD_2 = 'Felwood',
    QUEST_5165 = 'Dousing the Flames of Protection',
    QUEST_5385 = 'The Remains of Trey Lightforge',

    DESOLACE_1 = 'Desolace',
    DESOLACE_2 = 'Desolace',
    QUEST_6027 = 'Book of the Ancients',

    DUSTWALLOW_1 = 'Dustwallow marsh',
    DUSTWALLOW_2 = 'Dustwallow marsh',
    QUEST_1203 = 'Jarl Needes a Blade',

    SILITHUS_1 = 'Silithus',
    SILITHUS_2 = 'Silithus',
    QUEST_8287 = 'A Terrible Purpose',
    QUEST_8352 = 'Scepter of the Council',
    QUEST_8321 = 'Vyral the Vile',
    QUEST_8281 = 'Stepping Up Security',

    DUROTAR_1 = 'Durotar',
    DUROTAR_2 = 'Durotar',
    QUEST_835 = 'Securing the Lines',

    BARRENS_1 = 'The Barrens',
    BARRENS_2 = 'The Barrens',
    QUEST_888 = 'Stolen Booty',
    QUEST_902 = 'Samophlange',

    WINTERSPRING_1 = 'Winterspring',
    WINTERSPRING_2 = 'Winterspring',
    QUEST_975 = 'Cache of Mau\'ari',
    QUEST_5082 = 'Threat of the Winterfall',
    QUEST_5121 = 'High Chief Winterfall',
    QUEST_5163 = 'Are We There, Yeti?',
    QUEST_4842 = 'Strange Sources',

    TANARIS_1 = 'Tanaris',
    TANARIS_2 = 'Tanaris',
    QUEST_2662 = 'Noggenfogger Elixir',
    QUEST_2874 = 'Deliver to MacKinley',
    QUEST_1691 = 'More Wastewander Justice',
    QUEST_113 = 'Inspect Part Analysis',

    STONETALON_1 = 'Stonetalon Mountains',
    STONETALON_2 = 'Stonetalon Mountains',
    QUEST_1096 = 'Gerenzo Wrenchwhistle',

    UNGORO_1 = 'Un\'Goro Crater',
    UNGORO_2 = 'Un\'Goro Crater',
    QUEST_3962 = 'It\'s Dangerous to Go Alone',
    QUEST_4245 = 'Chasing A-Me 01',
    QUEST_4292 = 'The Bait for Lar\'korwi',

    THOUSAND_NEEDLES_1 = 'Thousand Needles',
    THOUSAND_NEEDLES_2 = 'Thousand Needles',
    QUEST_1189 = 'Safety First',

    ARATHI_1 = 'Arathi Highlands',
    ARATHI_2 = 'Arathi Highlands',
    QUEST_652 = 'Breaking the Keystone',

    BADLANDS_1 = 'Badlands',
    BADLANDS_2 = 'Badlands',
    QUEST_737 = 'Forbidden Knowledge',
    QUEST_778 = 'This Is Going to Be Hard',
    QUEST_656 = 'Summoning the Princess',
    
    EASTERN_PLAGUELANDS_1 = 'Eastern Plaguelands',
    EASTERN_PLAGUELANDS_2 = 'Eastern Plaguelands',
    QUEST_5942 = 'Hidden Treasures',
    QUEST_6148 = 'The Scarlet Oracle, Demetria',
    QUEST_6187 = 'Order Must Be Restored',
    QUEST_5265 = 'The Argent Hold',

    BLASTED_LANDS_1 = 'Blasted Lands',
    BLASTED_LANDS_2 = 'Blasted Lands',
    QUEST_3628 = 'You Are Rakh\'likh, Demon',

    STRANGLETHORN_VALLEY_1 = 'Stranglethorn Vale',
    STRANGLETHORN_VALLEY_2 = 'Stranglethorn Vale',
    QUEST_208 = 'Big Game Hunter',
    QUEST_600 = 'Venture Company Mining',
    QUEST_613 = 'Cracking Maury\'s Foot',
    QUEST_628 = 'Excelsior',
    QUEST_338 = 'The Green Hills of Stranglethorn',
	
	AN_NESINGWARY = 'The Green Hills of Stranglethorn',
	AD_NESINGWARY = 'Complete all of Hemet Nesingwary quests in Stranglethorn Vale up to and including The Green Hills of Stranglethorn and Big Game Hunter.',

    WESTERN_PLAGUELANDS_1 = 'Western Plaguelands',
    WESTERN_PLAGUELANDS_2 = 'Western Plaguelands',
    QUEST_5944 = 'In Dreams',
    QUEST_5051 = 'Two Halves Become One',
    QUEST_4985 = 'The Wildlife Suffers Too',

    SEARING_GORGE_1 = 'Searing Gorge',
    SEARING_GORGE_2 = 'Searing Gorge',
    QUEST_3481 = 'Trinkets...',

    BLACK_ROCK_1 = 'Blackrock Mountain',
    BLACK_ROCK_2 = 'Blackrock Mountain',
    QUEST_8996 = 'Return to Bodley',

    AN_WISDOM_KEEPER = 'The Loremaster',
    AD_WISDOM_KEEPER = 'Complete the quest achievements listed below.',
    AN_WISDOM_KEEPER_AZEROTH = 'Loremaster of Azeroth',
    AD_WISDOM_KEEPER_AZEROTH = 'Complete the quest achievements listed below.',
    AN_WISDOM_KEEPER_KALIMDOR = 'Loremaster of Kalimdor',
    AD_WISDOM_KEEPER_KALIMDOR = 'Complete the Kalimdor quest achievements in  listed below.',
    AN_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Loremaster of Eastern Kingdoms',
    AD_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Complete the Eastern Kingdoms quest achievements in listed below.',
    AN_WISDOM_KEEPER_OUTLAND = 'Loremaster of Outland',
    AD_WISDOM_KEEPER_OUTLAND = 'Complete the Outland quest achievements listed below.',
    AR_WISDOM_KEEPER = 'The Loremaster',

    AN_RAGEFIRE_CHASM = 'Ragefire Chasm',
    AD_RAGEFIRE_CHASM = 'Defeat Taragaman the Hungerer.',
    AN_WAILING_CAVERNS = 'Wailing Caverns',
    AD_WAILING_CAVERNS = 'Defeat Mutanus the Devourer.',
    AN_DEAD_MINES = 'Deadmines',
    AD_DEAD_MINES = 'Defeat Edwin VanCleef.',
    AN_SHADOWFANG_KEEP = 'Shadowfang Keep',
    AD_SHADOWFANG_KEEP = 'Defeat Archmage Arugal.',
    AN_BLACKFATHOM_DEEPS = 'Blackfathom Deeps',
    AD_BLACKFATHOM_DEEPS = 'Defeat Aku\'mai.',
    AN_JAIL = 'Stormwind Stockade',
    AD_JAIL = 'Defeat Bazil Thredd.',
    AN_GNOMREGAN = 'Gnomeregan',
    AD_GNOMREGAN = 'Defeat Mekgineer Thermaplugg.',
    AN_RAZORFEN_KRAUL = 'Razorfen Kraul',
    AD_RAZORFEN_KRAUL = 'Defeat Charlga Razorflank.',
    AN_SCARLET_MONASTERY = 'Scarlet Monastery',
    AD_SCARLET_MONASTERY = 'Defeat the Scarlet Crusade within the Scarlet Monastery.',
    AC_SCARLET_MONASTERY1 = 'Bloodmage Thalnos',
    AC_SCARLET_MONASTERY2 = 'Arcanist Doan',
    AC_SCARLET_MONASTERY3 = 'Herod',
    AC_SCARLET_MONASTERY4 = 'High Inquisitor Whitemane',
	AC_SCARLET_MONASTERY5 = 'Scarlet Commander Mograine',
	
    AN_RAZORFEN_DOWNS = 'Razorfen Downs',
    AD_RAZORFEN_DOWNS = 'Defeat Amnennar the Coldbringer.',
    AN_ULDAMAN = 'Uldaman',
    AD_ULDAMAN = 'Defeat Archaedas.',
    AN_ZULFARRAK = 'Zul\'Farrak',
    AD_ZULFARRAK = 'Defeat Chief Ukorz Sandscalp.',
    AN_MARAUDON = 'Maraudon',
    AD_MARAUDON = 'Defeat Princess Theradras.',
    AN_SUNKEN_TEMPLE = 'Sunken Temple',
    AD_SUNKEN_TEMPLE = 'Defeat Shade of Eranikus.',
	
    AN_NEW_EMPEROR = 'Blackrock Depths',
    AD_NEW_EMPEROR = 'Defeat Emperor Dagran Thaurissan.',
    AN_BLACKROCK_DEPTHS = 'Clearing the depths',
    AD_BLACKROCK_DEPTHS = 'Defeat the following bosses in Black Rock Depths.',
    AC_BLACKROCK_DEPTHS1 = 'High Interrogator Gerstahn killed',
    AC_BLACKROCK_DEPTHS2 = 'Houndmaster Grebmar',
    AC_BLACKROCK_DEPTHS3 = 'General Angerforge',
    AC_BLACKROCK_DEPTHS4 = 'Golem Lord Argelmach',
    AC_BLACKROCK_DEPTHS5 = 'Lord Incendius',
    AC_BLACKROCK_DEPTHS6 = 'Water Stilgiss',
    AC_BLACKROCK_DEPTHS7 = 'Bael\'Gar',
    AN_BLACKROCK_PARTY = 'Party at the deep',
    AD_BLACKROCK_PARTY = 'Defeat all listed opponents in the Grim Guzzler',
    AC_BLACKROCK_PARTY1 = 'Ribbly Screwspigot',
    AC_BLACKROCK_PARTY2 = 'Plugger Spazzring',
    AC_BLACKROCK_PARTY3 = 'Hurley Blackbreath',
    AC_BLACKROCK_PARTY4 = 'Phalanx',
    AN_BLACKROCK_DEPTHS_FULL = 'Black Rock Depths',
    AD_BLACKROCK_DEPTHS_FULL = 'Earn following achievements related to Black Rock Depths.',
    AN_ARMOR_SWORD = 'Best defense is an attack',
    AD_ARMOR_SWORD = 'Loot Stone of the Earth from the body of defeated Panzor the Invincible in Black Rock Depths.',
	
    AN_BLACKROCK_SPIRE_BOTTOM = 'Lower Blackrock Spire',
    AD_BLACKROCK_SPIRE_BOTTOM = 'Defeat Overlord Wyrmthalak.',
    AN_BLACKROCK_SPIRE_UPPER = 'Upper Blackrock Spire',
    AD_BLACKROCK_SPIRE_UPPER = 'Defeat General Drakkisath.',
    AN_BLACKROCK_SPIRE = 'Invader of the Black Rock Spire',
    AD_BLACKROCK_SPIRE = 'Earn the following achievements related to Blackrock Spire.',
    AN_DIRE_MAUL = 'King of Dire Maul',
    AD_DIRE_MAUL = 'Defeat each wing of Dire Maul.',
    AC_DIRE_MAUL1 = 'Alzzin the Wildshaper',
    AC_DIRE_MAUL2 = 'Immol\'thar',
    AC_DIRE_MAUL3 = 'King Gordok',
    AN_STRATHOLME = 'Stratholme',
    AD_STRATHOLME = 'Defeat the evil masterminds inhabiting Stratholme.',
	AC_STRATHOLME1 = 'Baron Rivendare',
	AC_STRATHOLME2 = 'Balnazzar',	
    AN_SCHOLOMANCE = 'Scholomance',
    AD_SCHOLOMANCE = 'Defeat the leaders of Scholomance.',
	AC_SCHOLOMANCE1 = 'Darkmaster Gandling',
	AC_SCHOLOMANCE2 = 'Ras Frostwhisper',
    AN_YOUNG_DEFENDER = 'Young Defender of Azeroth',
    AD_YOUNG_DEFENDER = 'Earn the low-level dungeon achievements listed below.',
    AN_DEFENDER = 'Defender of Azeroth',
    AD_DEFENDER = 'Earn the dungeon achievements listed below.',
    AR_DEFENDER = 'Defender of Azeroth',

    AN_ONYXIA = 'Onyxia\'s Lair',
    AD_ONYXIA = 'Defeat Onyxia.',
    AN_AQ20 = 'Ruins of Ahn\'Qiraj',
    AD_AQ20 = 'Defeat Ossirian the Unscarred.',
    AN_ZULGURUB = 'Zul\'Gurub',
    AD_ZULGURUB = 'Defeat Hakkar.',
    AN_RAGNAROS = 'Molten Core',
    AD_RAGNAROS = 'Defeat Ragnaros.',
    AN_BLACK_WING_LAIR = 'Blackwing Lair',
    AD_BLACK_WING_LAIR = 'Defeat Nefarian.',
    AN_AQ40 = 'Temple of Ahn\'Qiraj',
    AD_AQ40 = 'Defeat C\'Thun.',
    AN_NAXXRAMAS_SPIDERS = 'The Arachnid Quarter',
    AD_NAXXRAMAS_SPIDERS = 'Defeat Maexxna.',
    AN_NAXXRAMAS_PLAGUE = 'The Plague Quarter',
    AD_NAXXRAMAS_PLAGUE = 'Defeat Loatheb.',
    AN_NAXXRAMAS_MILITARY = 'The Military Quarter',
    AD_NAXXRAMAS_MILITARY = 'Defeat the Four Horsemen.',
    AN_NAXXRAMAS_CONSTRUCT = 'The Construct Quarter ',
    AD_NAXXRAMAS_CONSTRUCT = 'Defeat Thaddius.',
    AN_NAXXRAMAS_LAIR = 'Frostwyrm Lair',
    AD_NAXXRAMAS_LAIR = 'Defeat Kel\'Thuzad.',
    AN_NAXXRAMAS = 'The Fall of Naxxramas',
    AD_NAXXRAMAS = 'Earn the following Naxxramas related achievements.',
    AN_YOUNG_HERO = 'Young Hero of Azeroth',
    AD_YOUNG_HERO = 'Earn the raid achievements listed below.',
    AN_BLACKROCK_MASTER = 'Lord of the Blackrock',
    AD_BLACKROCK_MASTER = 'Earn the following achievements related to the Blackrock dungeons and raids.',
    AN_HERO = 'Hero of the Azeroth',
    AD_HERO = 'Earn the raid achievements listed below.',
    AR_HERO = 'Hero of Azeroth.',
    AN_GREAT_HERO = 'Great Hero of Azeroth',
    AD_GREAT_HERO = 'Earn the raid and dungeon achievements listed below.',
    AR_GREAT_HERO = 'Great Hero of Azeroth',

    AN_PVP_RANK_A1 = 'Private (Legacy)',
    AN_PVP_RANK_A2 = 'Corporal (Legacy)',
    AN_PVP_RANK_A3 = 'Sergeant (Legacy)',
    AN_PVP_RANK_A4 = 'Master Sergeant (Legacy)',
    AN_PVP_RANK_A5 = 'Sergeant Major (Legacy)',
    AN_PVP_RANK_A6 = 'Knight (Legacy)',
    AN_PVP_RANK_A7 = 'Knight-Lieutenant (Legacy)',
    AN_PVP_RANK_A8 = 'Knight-Captain (Legacy)',
    AN_PVP_RANK_A9 = 'Knight-Champion (Legacy)',
    AN_PVP_RANK_A10 = 'Lieutenant Commander (Legacy)',
    AN_PVP_RANK_A11 = 'Commander (Legacy)',
    AN_PVP_RANK_A12 = 'Marshal (Legacy)',
    AN_PVP_RANK_A13 = 'Field Marshal (Legacy)',
    AN_PVP_RANK_A14 = 'Grand Marshal (Legacy)',
    AN_PVP_RANK_H1 = 'Scout (Legacy)',
    AN_PVP_RANK_H2 = 'Grunt (Legacy)',
    AN_PVP_RANK_H3 = 'Sergeant (Legacy)',
    AN_PVP_RANK_H4 = 'Senior Sergeant (Legacy)',
    AN_PVP_RANK_H5 = 'First Sergeant (Legacy)',
    AN_PVP_RANK_H6 = 'Stone Guard (Legacy)',
    AN_PVP_RANK_H7 = 'Blood Guard (Legacy)',
    AN_PVP_RANK_H8 = 'Legionnaire (Legacy)',
    AN_PVP_RANK_H9 = 'Centurion (Legacy)',
    AN_PVP_RANK_H10 = 'Champion (Legacy)',
    AN_PVP_RANK_H11 = 'Lieutenant General (Legacy)',
    AN_PVP_RANK_H12 = 'General (Legacy)',
    AN_PVP_RANK_H13 = 'Warlord (Legacy)',
    AN_PVP_RANK_H14 = 'High Warlord (Legacy)',
    AD_PVP_RANK = 'Get the rank of the same name with this achievement.',
    AN_PVP_FIRST_KILL = 'An Honorable Kill',
    AD_PVP_FIRST_KILL = 'Achieve an honorable kill.',
    AC_PVP_FIRST_KILL = 'Achieve an honorable kill.',
    AN_PVP_KILLS = '%d Honorable Kills',
    AD_PVP_KILLS = 'Get %d honorable kills.',
    AC_PVP_KILLS = 'Get %d honorable kills',

    AN_MOB_KILLS_1 = 'Killer',
    AN_MOB_KILLS_2 = 'Destroyer',
    AN_MOB_KILLS_3 = 'Crusher',
    AN_MOB_KILLS_4 = 'Headhunter',
    AN_MOB_KILLS_5 = 'Thunderstorm of the monsters',
    AN_MOB_KILLS_6 = 'Thunderstorm of all living things',
    AN_MOB_KILLS_7 = 'Omnipresent Death',
    AD_MOB_KILLS = 'Kill %d monsters.',
    AC_MOB_KILLS = 'Kill %d monsters.',

    AN_REPS_1 = 'Somebody Likes Me',
    AD_REPS_1 = 'Raise a reputation to Exalted.',
    AC_REPS_1 = 'Raised a reputation to Exalted.',
    AN_REPS_X = ' Exalted Reputations',
    AD_REPS = 'Raise %d reputations to Exalted.',
    AC_REPS = 'Raised %d reputations to Exalted.',
    AR_REPS = 'The Exalted',

    AN_HORDE_REPS = 'Ambassador of the Horde',
    AD_HORDE_REPS = 'Earn exalted reputation with 5 home cities.',
    AC_HORDE_REPS_1 = 'Exalted Orgrimmar.',
    AC_HORDE_REPS_2 = 'Exalted Darkspear Tribe.',
    AC_HORDE_REPS_3 = 'Exalted Undercity.',
    AC_HORDE_REPS_4 = 'Exalted Thunder Bluff.',
    AC_HORDE_REPS_5 = 'Exalted Silvermoon.',

    AN_ALLIANCE_REPS = 'Ambassador of the Alliance',
    AD_ALLIANCE_REPS = 'Earn exalted reputation with 5 home cities.',
    AC_ALLIANCE_REPS_1 = 'Exalted Stormwind.',
    AC_ALLIANCE_REPS_2 = 'Exalted Darnassus.',
    AC_ALLIANCE_REPS_3 = 'Exalted Gnomeregan Exiles.',
    AC_ALLIANCE_REPS_4 = 'Exalted Ironforge.',
    AC_ALLIANCE_REPS_5 = 'Exalted Exodar.',

    AN_ARGENT_DAWN = 'The Argent Dawn',
    AD_ARGENT_DAWN = 'Earn exalted status with the Argent Dawn.',
    AN_BROOD_OF_NOZDORMU = 'Brood of Nozdormu',
    AD_BROOD_OF_NOZDORMU = 'Earn exalted status with the Brood of Nozdormu.',
    AN_DARKMOON_FAIRE = 'Fulldarkmoon',
    AD_DARKMOON_FAIRE = 'Reach Exalted with the faction of Darkmoon Faire.',
    AN_ZANDALAR_TRIBE = 'Hero of the Zandalar Tribe',
    AD_ZANDALAR_TRIBE = 'Earn exalted status with the Zandalar Tribe.',
    AN_HYDRAXIANS = 'Hydraxian Waterlords',
    AD_HYDRAXIANS = 'Earn exalted status with the Hydraxian Waterlords.',
    AN_TIMBERMAW_HOLD = 'They Love Me In That Tunnel',
    AD_TIMBERMAW_HOLD = 'Earn exalted status with Timbermaw Hold.',
    AN_THORIUM = 'Thorium Brotherhood',
    AD_THORIUM = 'Earn exalted status with the Thorium Brotherhood.',
    AN_SHENDRALAR = 'Agent of the Shen\'dralar',
    AD_SHENDRALAR = 'Earn exalted status with Shen\'dralar.',

    AN_DEFILERS = 'The Defiler',
    AD_DEFILERS = 'Gain exalted reputation with The Forsaken Defilers.',
    AN_FROSTWOLF_CLAN = 'Hero of the Frostwolf Clan',
    AD_FROSTWOLF_CLAN = 'Gain exalted reputation with the Frostwolf Clan.',
    AN_WARSONG_OUTRIDERS = 'Warsong Outrider',
    AD_WARSONG_OUTRIDERS = 'Gain exalted reputation with the Warsong Outriders.',
    AN_HORDE_PVP_FRACTIONS = 'The Conqueror',
    AD_HORDE_PVP_FRACTIONS = 'Raise your reputation values in Warsong Gulch, Arathi Basin and Alterac Valley to Exalted.',

    AN_LEAGUE_OF_ARATHOR = 'Knight of Arathor',
    AD_LEAGUE_OF_ARATHOR = 'Gain exalted reputation with The League of Arathor.',
    AN_STORMSPIKE_GUARD = 'Hero of the Stormpike Guard',
    AD_STORMSPIKE_GUARD = 'Gain exalted reputation with the Stormpike Guard.',
    AN_SILVERWING_SENTINELS = 'Silverwing Sentinel',
    AD_SILVERWING_SENTINELS = 'Gain exalted reputation with the Silverwing Sentinels.',
    AN_ALLIANCE_PVP_FRACTIONS = 'The Justicar',
    AD_ALLIANCE_PVP_FRACTIONS = 'Raise your reputation values in Warsong Gulch, Arathi Basin and Alterac Valley to Exalted.',

    AN_BOLVAR_SLAYER = 'Storming Stormwind',
    AD_BOLVAR_SLAYER = 'Kill Highlord Bolvar Fordragon.',
    AN_MAGNI_SLAYER = 'Death to the King!',
    AD_MAGNI_SLAYER = 'Kill King Magni Bronzebeard.',
    AN_TYRANDE_SLAYER = 'Immortal No More',
    AD_TYRANDE_SLAYER = 'Kill High Priestess Tyrande Whisperwind.',
    AN_VELEN_SLAYER = 'Putting Out the Light',
    AD_VELEN_SLAYER = 'Kill Prophet Velen.',

    AN_ALLIANCE_KINGS_SLAYER = 'For the Horde!',
    AD_ALLIANCE_KINGS_SLAYER = 'Slay the leaders of the Alliance.',

    AN_THRALL_SLAYER = 'Death to the Warchief!',
    AD_THRALL_SLAYER = 'Kill Thrall.',
    AN_SYLVANAS_SLAYER = 'Downing the Dark Lady',
    AD_SYLVANAS_SLAYER = 'Kill Lady Sylvanas Windrunner.',
    AN_CAIRNE_SLAYER = 'Bleeding Bloodhoof',
    AD_CAIRNE_SLAYER = 'Kill Cairne Bloodhoof.',
    AN_LORTHEMAR_SLAYER = 'Killed in Quel\'Thalas',
    AD_LORTHEMAR_SLAYER = 'Kill Lor\'themar Theron.',

    AN_HORDE_KINGS_SLAYER = 'For The Alliance!',
    AD_HORDE_KINGS_SLAYER = 'Slay the leaders of the Horde.',

    AN_RACES_KILLER = 'Know Thy Enemy',
    AD_ALLIANCE_RACES_KILLER = 'Get an honorable, killing blow on five different races.',
    AD_HORDE_RACES_KILLER = 'Get an honorable, killing blow on five different races.',
    AC_HUMAN_KILLED = 'Human',
    AC_NIGHTELF_KILLED = 'Night Elf',
    AC_DWARF_KILLED = 'Dwarf',
    AC_GNOME_KILLED = 'Gnome',
    AC_ORC_KILLED = 'Orc',
    AC_TROLL_KILLED = 'Troll',
    AC_SCOURGE_KILLED = 'Undead',
    AC_TAUREN_KILLED = 'Tauren',
    AC_DRAENEI_KILLED = 'Draenei',
    AC_BLOODELF_KILLED = 'Blood Elf',

    AN_CLASSES_KILLER = 'That Takes Class',
    AD_CLASSES_KILLER = 'Get an honorable, killing blow on one of each class.',
    AC_WARRIOR_KILLED = 'Warrior',
    AC_HUNTER_KILLED = 'Hunter',
    AC_ROGUE_KILLED = 'Rogue',
    AC_PRIEST_KILLED = 'Priest',
    AC_MAGE_KILLED = 'Mage',
    AC_WARLOCK_KILLED = 'Warlock',
    AC_DRUID_KILLED = 'Druid',
    AC_PALADIN_KILLED = 'Paladin',
    AC_SHAMAN_KILLED = 'Shaman',

    AN_ALTERAC_WIN = 'Victory in the Alterac Valley',
    AD_ALTERAC_WIN = 'Win the battle for Alterac Valley.',
    AN_ALTERAC_WINS = 'Alterac Valley Veteran',
    AD_ALTERAC_WINS = 'Win %d battles for Alterac Valley.',
    AN_WARSONG_WIN = 'Warsong Gulch Victory',
    AD_WARSONG_WIN = 'Win Warsong Gulch.',
    AN_WARSONG_WINS = 'Warsong Gulch Veteran',
    AD_WARSONG_WINS = 'Complete %d victories in Warsong Gulch.',
    AN_ARATHI_WIN = 'Arathi Basin Victory',
    AD_ARATHI_WIN = 'Win Arathi Basin.',
    AN_ARATHI_WINS = 'Arathi Basin Veteran',
    AD_ARATHI_WINS = 'Complete %d victories in Arathi Basin.',
    AN_EYE_WIN = 'Eye of the Storm Victory',
    AD_EYE_WIN = 'Win Eye of the Storm.',
    AN_EYE_WINS = 'Eye of the Storm Veteran',
    AD_EYE_WINS = 'Complete %d victories in Eye of the Storm.',

    AN_ALTERAC_KILLING_BLOWS = 'Valley Meat Grinder',
    AD_ALTERAC_KILLING_BLOWS = 'Make %d killing blows in one single battle for Alterac Valley and stay until it is over.',
    AN_ALTERAC_GRAVEYARD_ASSAULT = 'Undertaker',
    AD_ALTERAC_GRAVEYARD_ASSAULT = 'Assault a graveyard in one single battle for Alterac Valley and stay until it is over.',
    AN_ALTERAC_GRAVEYARD_ASSAULTS = 'There are never enough Coffins',
    AD_ALTERAC_GRAVEYARD_ASSAULTS = 'Assault %d graveyards in one single battle for Alterac Valley and stay until it is over.',
    AN_ALTERAC_GRAVEYARD_DEFEND = 'Guardian of the Deceased',
    AD_ALTERAC_GRAVEYARD_DEFEND = 'Defend a graveyard in one single battle for Alterac Valley and stay until it is over.',
    AN_ALTERAC_GRAVEYARD_DEFENDS = 'Guardian of all Dead',
    AD_ALTERAC_GRAVEYARD_DEFENDS = 'Defend %d graveyards in one single battle for Alterac Valley and stay until it is over.',
    AN_ALTERAC_TOWER_ASSAULT = 'Now it\'s mine!',
    AD_ALTERAC_TOWER_ASSAULT = 'Assault a tower in one single battle for Alterac Valley and stay until it is over.',
    AN_ALTERAC_TOWER_ASSAULTS = 'Now it\'s all mine!',
    AD_ALTERAC_TOWER_ASSAULTS = 'Assault %d towers in one single battle for Alterac Valley and stay to it is over.',
    AN_ALTERAC_TOWER_DEFEND = 'Tower Keeper',
    AD_ALTERAC_TOWER_DEFEND = 'Defend a tower in one single battle for Alterac Valley and stay until it is over.',
    AN_ALTERAC_TOWER_DEFENDS = 'Towers Keeper',
    AD_ALTERAC_TOWER_DEFENDS = 'Defend %d towers in one single battle for Alterac Valley and stay until it is over.',
    AN_ALTERAC_MINE_CAPTURE = 'Frozen Miner',
    AD_ALTERAC_MINE_CAPTURE = 'Assault a mine in one single battle for Alterac Valley and stay until it is over.',
    AN_ALTERAC_MINE_CAPTURES = 'Frozen Pikeman',
    AD_ALTERAC_MINE_CAPTURES = 'Assault %d mines in one single battle for Alterac Valley and stay until it is over.',

    AN_WARSONG_KILLS = 'Military Honor',
    AD_WARSONG_KILLS = 'Get %d honorable kills in one single battle for Warsong Gulch and stay until it is over.',
    AN_WARSONG_FLAG_CAPTURE = 'Capture the Flag',
    AD_WARSONG_FLAG_CAPTURE = 'Personally carry and capture the flag in one single battle for Warsong Gulch and stay until it is over.',
    AN_WARSONG_FLAG_CAPTURES = 'Great Flag Bearer',
    AD_WARSONG_FLAG_CAPTURES = 'Personally carry and capture %d flags in one single battle for Warsong Gulch and stay until it is over.',
    AN_WARSONG_FLAG_RETURN = 'Don\'t touch!',
    AD_WARSONG_FLAG_RETURN = 'Return a flag as a defender in one single battle for Warsong Gulch and stay until it is over.',
    AN_WARSONG_FLAG_RETURNS = 'Don\'t touch anything!',
    AD_WARSONG_FLAG_RETURNS = 'Return %d flags as a defender in one single battle for Warsong Gulch and stay until it is over.',

    AN_ARATHI_BASE_ASSAULT = 'Conquistador',
    AD_ARATHI_BASE_ASSAULT = 'Assault a flag in one single battle for Arathi Basin and stay until it is over.',
    AN_ARATHI_BASE_ASSAULTS = 'The famous conquistador',
    AD_ARATHI_BASE_ASSAULTS = 'Assault %d flags in one single battle for Arathi Basin and stay until it is over.',
    AN_ARATHI_BASE_DEFEND = 'Sentry',
    AD_ARATHI_BASE_DEFEND = 'Defend a flags in one single battle for Arathi Basin and stay until it is over.',
    AN_ARATHI_BASE_DEFENDS = 'Honorary sentry',
    AD_ARATHI_BASE_DEFENDS = 'Defend %d flags in one single battle for Arathi Basin and stay until it is over.',

    AN_EYE_CAPTURE = 'Storm Capper',
    AD_EYE_CAPTURE = 'Personally carry and capture the flag in Eye of the Storm and stay until the end of the battle.',
    AD_EYE_CAPTURES = 'Personally carry and capture %d flags in Eye of the Storm and stay until the end of the battle.',
    AN_EYE_GLORY = 'Bound for Glory',
    AD_EYE_GLORY = 'In a single Eye of the Storm match, capture the flag 3 times without dying.',
    AN_EYE_FAST_WIN = 'Flurry',
    AD_EYE_FAST_WIN = 'Win Eye of the Storm in under 6 minutes.',
    AN_EYE_BERSERK = 'Bloodthirsty Berserker',
    AD_EYE_BERSERK = 'Get a killing blow while under the effects of the berserker buff in Eye of the Storm.',
    AN_EYE_IDEAL_VICTORY = 'The Perfect Storm',
    AD_EYE_IDEAL_VICTORY = 'Win Eye of the Storm with a score of 1600 to 0.',

    AN_BGS_KILLING_BLOWS = 'Deathbringer',
    AD_BGS_KILLING_BLOWS = 'Make %d killing blows on any battleground.',
    AN_BGS_KILLS = 'Honor Aggregator',
    AD_BGS_KILLS = 'Get %d honorable kills on any battleground.',

    PROF_FIRST_AID = 'First Aid',
    PROF_FISHING = 'Fishing',
    PROF_COOKING = 'Cooking',
    PROF_ENCHANTING = 'Enchanting',
    PROF_TAILORING = 'Tailoring',
    PROF_ENGINEERING = 'Engineering',
    PROF_LEATHERWORKING = 'Leatherworking',
    PROF_ALCHEMY = 'Alchemy',
    PROF_BLACKSMITHING = 'Blacksmithing',
    PROF_HERBALISM = 'Herbalism',
    PROF_MINING = 'Mining',
    PROF_SKINNING = 'Skinning',
    PROF_JEWELCRAFTING = 'Jewelcrafting',
    SKILL_UNARMED = 'Unarmed',
    SKILL_RIDING = 'Riding',

    AN_PROFS_JOURNEYMAN = 'Professional Apprentice',
    AD_PROFS_JOURNEYMAN = 'Raise the skill of any main profession to 75.',
    AN_PROFS_EXPERT = 'Professional Journeyman',
    AD_PROFS_EXPERT = 'Raise the skill of any main profession to 150.',
    AN_PROFS_ARTISAN = 'Professional Expert',
    AD_PROFS_ARTISAN = 'Raise the skill of any main profession to 225.',
    AN_PROFS_ONE = 'Professional Artisan',
    AD_PROFS_ONE = 'Raise the skill of any main profession to 300.',
    AN_PROFS_ONE_OUTLAND = 'Professional Master',
    AD_PROFS_ONE_OUTLAND = 'Raise the skill of any main profession to 375.',
    AN_PROFS_TWO = 'Handyman',
    AD_PROFS_TWO = 'Raise the skill of two main professions to 300 at the same time.',
    AC_PROFS_TWO = 'Raise the skill of two main professions to 300 at the same time.',
    AN_PROFS_TWO_OUTLAND = 'Outlandish Handyman',
    AD_PROFS_TWO_OUTLAND = 'Raise the skill of two main professions to 375 at the same time.',
    AC_PROFS_TWO_OUTLAND = 'Raise the skill of two main professions to 375 at the same time.',

    AN_FIRST_AID_JOURNEYMAN = 'Apprentice in First Aid',
    AD_FIRST_AID_JOURNEYMAN = 'Raise the skill of first aid to 75.',
    AN_FIRST_AID_EXPERT = 'Journeyman in First Aid',
    AD_FIRST_AID_EXPERT = 'Raise the skill of first aid to 150.',
    AN_FIRST_AID_ARTISAN = 'Expert in First Aid',
    AD_FIRST_AID_ARTISAN = 'Raise the skill of first aid to 225.',
    AN_FIRST_AID_MASTER = 'Artisan in First Aid',
    AD_FIRST_AID_MASTER = 'Raise the skill of first aid to 300.',
    AN_FIRST_AID_OUTLAND_MASTER = 'Master in First Aid',
    AD_FIRST_AID_OUTLAND_MASTER = 'Raise the skill of first aid to 375.',
	
    AN_FISHING_JOURNEYMAN = 'Apprentice Fisherman',
    AD_FISHING_JOURNEYMAN = 'Raise the skill of fishing to 75.',
    AN_FISHING_EXPERT = 'Journeyman Fisherman',
    AD_FISHING_EXPERT = 'Raise the skill of fishing to 150.',
    AN_FISHING_ARTISAN = 'Expert Fisherman',
    AD_FISHING_ARTISAN = 'Raise the skill of fishing to 225.',
    AN_FISHING_MASTER = 'Artisan Fisherman',
    AD_FISHING_MASTER = 'Raise the skill of fishing to 300.',
    AN_FISHING_OUTLAND_MASTER = 'Master Fisherman',
    AD_FISHING_OUTLAND_MASTER = 'Raise the skill of fishing to 375.',
	
    AN_COOKING_JOURNEYMAN = 'Apprentice Cook',
    AD_COOKING_JOURNEYMAN = 'Raise the skill of cooking to 75.',
    AN_COOKING_EXPERT = 'Journeyman Cook',
    AD_COOKING_EXPERT = 'Raise the skill of cooking to 150.',
    AN_COOKING_ARTISAN = 'Expert Cook',
    AD_COOKING_ARTISAN = 'Raise the skill of cooking to 225.',
    AN_COOKING_MASTER = 'Artisan Cook',
    AD_COOKING_MASTER = 'Raise the skill of cooking to 300.',
    AN_COOKING_OUTLAND_MASTER = 'Master Cook',
    AD_COOKING_OUTLAND_MASTER = 'Raise the skill of cooking to 375.',
	
    AN_PROFS_SECONDARY = 'Skills to Pay the Bills',
    AD_PROFS_SECONDARY = 'Become a Artisan in fishing, first aid and cooking.',
    AN_PROFS_SECONDARY_OUTLAND = 'Skills to Pay the Bills, also in Outland',
    AD_PROFS_SECONDARY_OUTLAND = 'Become a Master in fishing, first aid and cooking.',
    AN_PROFS_FIVE = 'Genius means brilliant in everything',
    AN_PROFS_FIVE_OUTLAND = 'Outlandish Genius',
    AD_PROFS_FIVE = 'Complete the profession achievements listed below.',
    AN_UNARMED_SKILL = 'Did Somebody Order a Knuckle Sandwich?',
    AD_UNARMED_SKILL = 'Raise your unarmed skill to 300.',

    AN_EXPLORE_AZEROTH = 'World Explorer',
    AD_EXPLORE_AZEROTH = 'Explore Eastern Kingdoms, Kalimdor and Outland.',
	AR_EXPLORER = 'Explorer',
    AN_EXPLORE_KALIMDOR = 'Explore Kalimdor',
    AD_EXPLORE_KALIMDOR = 'Explore the regions of Kalimdor.',
    AN_EXPLORE_EASTERN_KINGDOMS = 'Explore Eastern Kingdoms',
    AD_EXPLORE_EASTERN_KINGDOMS = 'Explore the regions of Eastern Kingdoms.',
	AN_EXPLORE = 'Explore %s',
    AD_EXPLORE = 'Explore %s, revealing the covered areas of the world map.',

    AN_SULFURAS = 'Sulfuras, Hand of Ragnaros',
    AD_SULFURAS = 'Wielder of Sulfuras, Hand of Ragnaros.',
    AN_THUNDER_FURY = 'Thunderfury, Blessed Blade of the Windseeker',
    AD_THUNDER_FURY = 'Wielder of Thunderfury, Blessed Blade of the Windseeker.',
    AN_ATIESH = 'Atiesh, Greatstaff of the Guardian',
    AD_ATIESH = 'Wielder of Atiesh, Greatstaff of the Guardian.',
    AN_BLACK_SCARAB = 'Scarab Lord',
    AD_BLACK_SCARAB = 'Opened the gates of Ahn\'Qiraj.',
    AN_RED_SCARAB = 'Why? Because It\'s Red',
    AD_RED_SCARAB = 'Obtain a Red Qiraji Resonating Crystal.',
	AN_TIGER_MOUNT = 'Swift Zulian Tiger',
    AD_TIGER_MOUNT = 'Obtain the Swift Zulian Tiger from High Priest Thekal in Zul\'Gurub.',
	AN_RAPTOR_MOUNT = 'Swift Razzashi Raptor',
    AD_RAPTOR_MOUNT = 'Obtain the Swift Razzashi Raptor from Bloodlord Mandokir in Zul\'Gurub.',
	AN_BARON_MOUNT = 'Deathcharger\'s Reins',
    AD_BARON_MOUNT = 'Obtain the Deathcharger\'s Reins from Rivendare in Stratholme.',
	AN_SABER_MOUNT = 'Winterspring Frostsaber',
    AD_SABER_MOUNT = 'Obtain a Winterspring Frostsaber.',
    
    AN_UNCOMMON_GEAR = 'Not so ordinary anymore',
    AD_UNCOMMON_GEAR = 'Equip yourself with items of uncommon or higher quality.',
    AN_RARE_GEAR = 'Superior',
    AD_RARE_GEAR = 'Equip a superior item in every slot',
    AN_EPIC_GEAR = 'Epic',
    AD_EPIC_GEAR = 'Equip an epic item in every slot ',

    AN_STOCKING_UP = 'Stocking Up',
    AD_STOCKING_UP = 'Craft 100 Heavy Runecloth Bandages.',
    AC_STOCKING_UP = 'Craft 100 Heavy Runecloth Bandages.',
    AN_STOCKING_UP_2 = 'Stocking Up',
    AD_STOCKING_UP_2 = 'Craft 500 Heavy Runecloth Bandages.',
    AC_STOCKING_UP_2 = 'Craft 500 Heavy Runecloth Bandages.',
    AN_STOCKING_UP_OUTLAND = 'Preparing for the Void',
    AD_STOCKING_UP_OUTLAND = 'Craft 100 Heavy Netherweave Bandages.',
    AC_STOCKING_UP_OUTLAND = 'Craft 100 Heavy Netherweave Bandage.',
    AN_STOCKING_UP_2_OUTLAND = 'Preparing for the Void',
    AD_STOCKING_UP_2_OUTLAND = 'Craft 500 Heavy Netherweave Bandages.',
    AC_STOCKING_UP_2_OUTLAND = 'Craft 500 Heavy Netherweave Bandages.',

    AN_BOOTY_BAY_CONTEST = 'I choose the best for Fishing',
    AD_BOOTY_BAY_CONTEST = 'Win the Booty Bay fishing contest and choose the Arcanite Fishing Pole or the Hook of the Master Angler as your reward.',
    AN_BOOTY_BAY_FISH = 'Real Fish Lover',
    AD_BOOTY_BAY_FISH = 'Fish up one of the rare fish during the Booty Bay fishing contest.',

    AN_FISHING_COLLECTION = 'Fish Collection',
    AD_FISHING_COLLECTION = 'Catch the following fishes in Azeroth.',
    AN_FISHING_OUTLAND_COLLECTION = 'Outlandish Fish Collection',
    AD_FISHING_OUTLAND_COLLECTION = 'Catch the following species in Outland.',
    AN_FISHING_WATER = 'Water from Water',
    AD_FISHING_WATER = 'Fish up an Essence of Water.',
    AN_FISHING_RUM = 'Captain’s Choice',
    AD_FISHING_RUM = 'Fish up the following types of rum.',
    AN_FISHING_RING = 'Gift of Mordor',
    AD_FISHING_RING = 'Fish up The 1 Ring.',
    AN_FISHING_SKULL = 'Harbinger of a Sad End',
    AD_FISHING_SKULL = 'Fish up Old Teamster\'s Skull.',
    AN_FISHING_SNAPPER = 'Great Snapper Catcher',
    AD_FISHING_SNAPPER = 'Fish Snappers of the following sizes.',
    AC_FISHING_SNAPPER = '%d Pound Mud Snapper',
    AN_FISHING_SEA_BASS = 'Thunderstorm of Perches',
    AD_FISHING_SEA_BASS = 'Fish Groupers of the following sizes.',
    AC_FISHING_SEA_BASS = '%d Pound Grouper',
    AN_FISHING_SALMON = 'Salmon Lover',
    AD_FISHING_SALMON = 'Fish Salmons of the following sizes.',
    AC_FISHING_SALMON = '%d Pound Salmon',
    AN_FISHING_LOBSTER = 'Lobster Hunter',
    AD_FISHING_LOBSTER = 'Fish Lobsters of the following sizes.',
    AC_FISHING_LOBSTER = '%d Pound Lobster',
    AN_FISHING_BIG_SIZE = 'Azeroth\'s Greatest Angler',
    AD_FISHING_BIG_SIZE = 'Complete the following fishing achievements listed below.',
    AR_FISHING_BIG_SIZE = 'Azeroth\'s Greatest Angler',
	
	AN_FISHING_COUNT = '%d Fish',
	AC_FISHING_COUNT = 'Fish up %d items.',
	AD_FISHING_COUNT = 'Fish up %d items.',

    AN_COOKING_RECIPES_5 = 'Lunch Lady',
    AN_COOKING_RECIPES_10 = 'Short Order Cook',
    AN_COOKING_RECIPES_25 = 'Chef de Partie',
    AN_COOKING_RECIPES_50 = 'Sous Chef',
    AN_COOKING_RECIPES_75 = 'Chef de Cuisine',
    AR_COOKING_RECIPES = 'Chef',
    AD_COOKING_RECIPES = 'Learn %d cooking recipes.',
    AC_COOKING_RECIPES = 'Learn %d cooking recipes.',

    AN_COOKING_SOUP = 'Soupmaster',
    AN_COOKING_DESSERT = 'Pastry Cook',
    AN_COOKING_SQUID = 'Catch of the Day',
    AN_COOKING_DUMPLINGS = 'Grandma\'s Dumplings',
    AN_COOKING_CHOPS = 'Super Nutritious Chops',
    AD_COOKING_CREATE = 'Cook %s %d times.',
    AC_COOKING_CREATE = 'Cook %s %d times.',
    AN_COOKING_BIG_TABLE = 'Large Festive Feast',
    AD_COOKING_BIG_TABLE = 'Complete the cooking achievements listed below.',

    AN_COOKING_FISHERMANS_FEAST = 'Fisherman\'s Feast',
    AN_COOKING_SPICY_HOT_TALBUK = 'Spicy Hot Talbuk',
    AN_COOKING_SKULLFISH_SOUP = 'Skullfish Soup',
    AN_COOKING_RAVAGER_DOG = 'Ravager Dog',

    AN_WB_AZUREGOS = 'The Secret of the Blue Dragon',
    AD_WB_AZUREGOS = 'Defeat Azuregos.',
    AN_WB_KAZZAK = 'Demons shall not pass',
    AD_WB_KAZZAK = 'Defeat Lord Kazzak.',
    AN_WB_KAZZAK_OUTLAND = 'I\'m the Master of my Fate',
    AD_WB_KAZZAK_OUTLAND = 'Defeat Doom Lord Kazzak in Hellfire Peninsula.',
    AN_WB_DOOMWALKER = 'Broken Doomwalker',
    AD_WB_DOOMWALKER = 'Defeat Doomwalker in Shadowmoon Valley.',
    AN_WB_YSONDRE = 'No room for girls in a nightmare',
    AD_WB_YSONDRE = 'Defeat Ysondre.',
    AN_WB_LETHON = 'Child of the Emerald Nightmare',
    AD_WB_LETHON = 'Defeat Lethon.',
    AN_WB_EMERISS = 'Emeriss, Traitor to Life',
    AD_WB_EMERISS = 'Defeat Emeriss.',
    AN_WB_TAERAR = 'Nightmarish Taerar',
    AD_WB_TAERAR = 'Defeat Taerar.',
    AN_WB_EMERALD_DRAGONS = 'Emerald Keeper',
    AD_WB_EMERALD_DRAGONS = 'Defeat all Dragons of the Emerald Nightmare.',
    AR_WB_EMERALD_DRAGONS = 'Emerald Keeper',

    AN_DUEL = 'Duel-icious',
    AD_DUEL = 'Win a duel against another player.',
    AN_DUELS_10 = 'Duelist',
    AN_DUELS_25 = 'Skilled Duelist',
    AN_DUELS_100 = 'Master Duelist',
    AD_DUELS = 'Win in %d duels.',
    AC_DUELS = 'Win in %d duels',
    AN_GURUBASHI_1 = 'Gurubashi Arena Master',
    AD_GURUBASHI_1 = 'Loot the Arena Master trinket from the Gurubashi Arena.',
    AN_GURUBASHI_2 = 'Gurubashi Arena Grand Master',
    AD_GURUBASHI_2 = 'Complete Short John Mithril\'s quest to obtain the Arena Grand Master trinket.',
    AN_PARTICIPATE_IN_BGS = 'Call to Arms!',
    AD_PARTICIPATE_IN_BGS = 'Complete %d battlegrounds.',
    AC_PARTICIPATE_IN_BGS = 'Complet %d battlegrounds.',

    EMOTE_LOVE1 = 'You love %s.',
    AN_LOVE = 'To All The Squirrels I\'ve Loved Before',
    AD_LOVE = 'Show the critters of Azeroth how much you /love them.',
    EMOTE_PAT1 = 'You gently pat %s.',
    AN_ARATHI_CATS = 'Cats first, then everything else',
    AD_ARATHI_CATS = 'Pat (/pat) the designated felines in Arathi Basin.',

    AN_ALTERAC_FAST_WIN = 'The Alterac Blitz',
    AD_ALTERAC_FAST_WIN = 'Win Alterac Valley in 6 minutes.',
    AN_WARSONG_FAST_WIN = 'Warsong Expedience',
    AD_WARSONG_FAST_WIN = 'Win Warsong Gulch in under 7 minutes.',
    AN_ARATHI_FAST_WIN = 'Let\'s Get This Done',
    AD_ARATHI_FAST_WIN = 'Win Arathi Basin in 6 minutes.',

    AN_ALTERAC_TOWER_DEFEND_TOTAL = 'Tower Defense',
    AD_ALTERAC_TOWER_DEFEND_TOTAL = 'Defend %d towers in Alterac Valley.',
    AN_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Alterac Grave Robber',
    AD_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Take %d graveyards in Alterac Valley.',
    AN_WARSONG_FLAG_CAPTURE_TOTAL = 'Flags Capturer',
    AD_WARSONG_FLAG_CAPTURE_TOTAL = 'Personally carry and capture %d flags in Warsong Gulch.',
    AN_WARSONG_FLAG_RETURN_TOTAL = 'Persistent Defender',
    AD_WARSONG_FLAG_RETURN_TOTAL = 'Return %d flags as a defender in Warsong Gulch.',
    AN_ARATHI_BASE_ASSAULT_TOTAL = 'Me and the Cappin\' Makin\' it Happen',
    AD_ARATHI_BASE_ASSAULT_TOTAL = 'Take %d flags in Arathi Basin.',
    AN_ARATHI_BASE_DEFEND_TOTAL = 'To The Rescue!',
    AD_ARATHI_BASE_DEFEND_TOTAL = 'Come to the defense of a base in Arathi Basin %d times by recapping the flag.',
    AN_ALTERAC_MOUNT_HORDE = 'Frostwolf Howler',
    AD_ALTERAC_MOUNT_HORDE = 'Obtain a Frostwolf Howler.',
    AN_ALTERAC_MOUNT_ALLIANCE = 'Stormpike Battle Charger',
    AD_ALTERAC_MOUNT_ALLIANCE = 'Obtain a Stormpike Battle Charger.',

    AN_ALTERAC_BOSS = 'Master of Alterac Valley',
    AD_ALTERAC_BOSS = 'Complete the Alterac Valley achievements listed below.',
    AN_WARSONG_BOSS = 'Master of Warsong Gulch',
    AD_WARSONG_BOSS = 'Complete the Warsong Gulch achievements listed below.',
    AN_ARATHI_BOSS = 'Master of Arathi Basin',
    AD_ARATHI_BOSS = 'Complete the Arathi Basin achievements listed below.',
    AN_EYE_BOSS = 'Master of Eye of the Storm',
    AD_EYE_BOSS = 'Complete the Eye of the Storm achievements listed below.',
    AN_BATTLEMASTER = 'Battlemaster',
    AD_BATTLEMASTER = 'Complete the battleground achievements listed below.',
    AR_BATTLEMASTER = 'Battlemaster',

    AN_LEEROY = 'Leeeeeeeeeeeeeroy!',
    AD_LEEROY = 'Kill 50 rookery whelps within 15 seconds.',
    AR_LEEROY = 'Jenkins',
    AN_BWL_DUO = 'Double Breathing',
    AD_BWL_DUO = 'Kill Ebonroc and Flamegor within 45 seconds.',
    AN_ANUBREKHAN_WITHOUT_MOBS = 'The Crypt Lord',
    AD_ANUBREKHAN_WITHOUT_MOBS = 'Slay Anub\'Rekhan, leaving both Crypt Guards alive.',
    AN_FAERLINA_WITHOUT_MOBS = 'Momma Said Knock You Out',
    AD_FAERLINA_WITHOUT_MOBS = 'Slay Grand Widow Faerlina, leaving all the worshipers and followers of Naxxramas alive.',
    AN_SAPPHIRONE_WITH_ALL_ALIVE = 'We won\'t submit to ice',
    AD_SAPPHIRONE_WITH_ALL_ALIVE = 'Defeat Sapphiron while all 40 raid members remain alive.',
    AN_ARACHNOPHOBIA = 'Arachnophobia',
    AD_ARACHNOPHOBIA = 'Kill Maexxna in Naxxramas within 20 minutes of Anub\'Rekhan\'s death in 25-player mode.',
    AN_FOUR_TOGETHER = 'And they would all go down together',
    AD_FOUR_TOGETHER = 'Defeat the 4 Horsemen in Naxxramas, ensuring that they all die within 15 seconds of each other.',
	
	AN_PIRATES_HAT = 'Avast Ye, Admiral!',
	AD_PIRATES_HAT = 'Obtain the Bloodsail Admiral\'s Hat... and try to get some fresh air every now and then.',
	AR_PIRATES_HAT = 'Bloodsail Admiral',	
	AN_PALADIN_MOUNT = 'Charger',
	AD_PALADIN_MOUNT = 'Completed the paladin quest to obtain a Charger.',
	AN_WARLOCK_MOUNT = 'Dreadsteed of Xoroth',
	AD_WARLOCK_MOUNT = 'Completed the Dreadsteed of Xoroth warlock quest.',
	
	AN_HALLOWSEND = 'Hallowed Be Thy Name',
	AD_HALLOWSEND = 'Complete the Hallow\'s End achievements listed below.',
	AR_HALLOWSEND = 'The Hallowed',
	
	AN_PUMPKIN = 'Pumpkinmania',
	AD_PUMPKIN = 'Obtain a Pumpkin Bag during Hallow\'s End.',
	AN_HALLOWSEND_ALLIANCE_QUEST1 = 'Rotten Hallow',
	AD_HALLOWSEND_ALLIANCE_QUEST1 = 'Ruin Hallow\'s End for the Horde by completing Sergeant Hartman\'s quests which involve crashing the wickerman festival and cleaning up the stinkbombs from Southshore.',
	AC_HALLOWSEND_ALLIANCE_QUEST1_CRITERIA1 = 'Crashing the Wickerman Festival',
	AC_HALLOWSEND_ALLIANCE_QUEST1_CRITERIA2 = 'The Power of Pine',
	AN_HALLOWSEND_HORDE_QUEST1 = 'Rotten Hallow',
	AD_HALLOWSEND_HORDE_QUEST1 = 'Ruin Hallow\'s End for the Alliance by completing Darkcaller Yanka\'s quests which involve going to Southshore, ruining the kegs with rotten eggs and tossing stinkbombs into the town.',
	AC_HALLOWSEND_HORDE_QUEST1_CRITERIA1 = 'Rotten Eggs and Ruined Kegs',
	AC_HALLOWSEND_HORDE_QUEST1_CRITERIA2 = 'Stinking Up Southshore',
	
	AN_HALLOWSEND_ALLIANCE_QUEST2 = 'Hallow\'s End Treats for Jesper!',
	AD_HALLOWSEND_ALLIANCE_QUEST2 = 'Collect the the requested treats for Jesper.',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA1 = 'Stormwind Nougat',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA2 = '	Gnomeregan Gumdrop',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA3 = 'Ironforge Mint',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA4 = 'Darnassus Marzipan',
	AN_HALLOWSEND_HORDE_QUEST2 = 'Hallow\'s End Treats for Spoops!',
	AD_HALLOWSEND_HORDE_QUEST2 = 'Collect the the requested treats for Spoops.',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA1 = 'Orgrimmar Nougat',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA2 = 'Darkspear Gumdrop',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA3 = 'Undercity Mint',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA4 = 'Thunder Bluff Marzipan',
	
	AN_HALLOWSEND_INVOCATION_BUFF = 'Invocation of the Wickerman',
	AD_HALLOWSEND_INVOCATION_BUFF = 'Receive the buff "Invocation of the Wickerman" during Hallow\'s End.',
	
	AN_HALLOWSEND_TREATS = 'Trick or Treat!',
	AD_HALLOWSEND_TREATS = 'Receive a Treat Bag from an innkeeper.',
	
	AN_HALLOWSEND_MASK = 'The Mask Task',
	AD_HALLOWSEND_MASK = 'Obtain a Flimsy Mask during Hallow\'s End.',
	
	AN_HALLOWSEND_MASKS = 'A Mask for All Occasions',
	AD_HALLOWSEND_MASKS = 'Collect the 16 unique Flimsy Masks listed below.',
	
	AN_HALLOWSEND_TRANSFORM = 'The Masquerade',
	AD_HALLOWSEND_TRANSFORM = 'Get transformed by the Hallowed Wands listed below.',
	AC_HALLOWSEND_GHOST = 'Transformed by Hallowed Wand - Ghost',
	AC_HALLOWSEND_GNOME = 'Transformed by Hallowed Wand - Leper Gnome',
	AC_HALLOWSEND_WISP = 'Transformed by Hallowed Wand - Wisp',
	AC_HALLOWSEND_NINJA = 'Transformed by Hallowed Wand - Ninja',
	AC_HALLOWSEND_SKELETON = 'Transformed by Hallowed Wand - Skeleton',
	AC_HALLOWSEND_PIRATE = 'Transformed by Hallowed Wand - Pirate',
	AC_HALLOWSEND_BAT = 'Transformed by Hallowed Wand - Bat',

	--TBC
    AN_QUESTS_HELLFIRE_PENINSULA = 'To Hellfire and Back',
    AD_QUESTS_HELLFIRE_PENINSULA = 'Complete the Hellfire Peninsula storylines listed below.',
    TBC_QUEST_10388 = 'Disrupt the Burning Legion',
    TBC_QUEST_10389 = 'Cruel\'s Intentions',
    TBC_QUEST_10876 = 'The Hand of Kargath',
    TBC_QUEST_10258 = 'Spinebreaker Post',
    TBC_QUEST_9406 = 'The Mag\'har',
    TBC_QUEST_9370 = 'Falcon Watch',
    TBC_QUEST_10351 = 'Cenarion Post',

    TBC_QUEST_10397 = 'Disrupt the Burning Legion',
    TBC_QUEST_10400 = 'Overthrow the Overlord',
    TBC_QUEST_9545 = 'In Search of Sedai',
    TBC_QUEST_10935 = 'The Exorcism of Colonel Jules',
    TBC_QUEST_10937 = 'Drill the Drillmaster',
    TBC_QUEST_9383 = 'Temple of Telhamat',
    TBC_QUEST_10630 = 'Green, But Not Orcs',
    
    AN_QUESTS_ZANGARMASH = 'Mysteries of the Marsh',
    AD_QUESTS_ZANGARMASH = 'Complete the Zangarmarsh storylines listed below.',
    TBC_QUEST_9772 = 'Swamprat Post',
    TBC_QUEST_9904 = 'Zabra\'jin',
    TBC_QUEST_10118 = 'The Defense of Zabra\'jin',
    TBC_QUEST_9803 = 'Draenei Diplomacy',
    TBC_QUEST_9783 = 'Telredor',
    TBC_QUEST_9902 = 'Orebor Harborage',
    TBC_QUEST_9709 = 'Don\'t Eat THOSE Mushrooms!',
    TBC_QUEST_9732 = 'Draining the Marsh',
    TBC_QUEST_9788 = 'Saving the Sporeloks',
    TBC_QUEST_9726 = 'A Trip With the Sporelings',
    
    AN_QUESTS_TERROKAR = 'Terror of Terokkar',
    AD_QUESTS_TERROKAR = 'Complete the Terokkar Forest storylines listed below.',
    TBC_QUEST_10879 = 'The Skettis Offensive',
    TBC_QUEST_10881 = 'Refugee Caravan',
    TBC_QUEST_10915 = 'Sha\'tari Base Camp',
    TBC_QUEST_9951 = 'The Warden\'s Secret',
    TBC_QUEST_10042 = 'Allerian Stronghold',
    TBC_QUEST_10043 = 'Stonebreaker Hold',
    
    AN_QUESTS_NAGRAND = 'Nagrand Slam',
    AD_QUESTS_NAGRAND = 'Complete the Nagrand storylines listed below.',
    TBC_QUEST_10172 = 'Birth of a Warchief',
    TBC_QUEST_9977 = 'The Ring of Blood',
    TBC_QUEST_9853 = 'Throne of the Elements',
    TBC_QUEST_9934 = 'Lantresor of the Blade',
    TBC_QUEST_9868 = 'The Murkblood',
    TBC_QUEST_9937 = 'Threats to Nagrand',
    TBC_QUEST_9852 = 'The Ultimate Bloodsport',
    TBC_QUEST_9925 = 'Encountering the Ethereals',
    TBC_QUEST_9955 = 'The Adventures of Corki',
    TBC_QUEST_9933 = 'Lantresor of the Blade',
    TBC_QUEST_9873 = 'The Murkblood',
    TBC_QUEST_10011 = 'Threats to Nagrand',
    
    AN_QUESTS_BLADES_EDGE_MTNS = 'On the Blade\'s Edge',
    AD_QUESTS_BLADES_EDGE_MTNS = 'Complete the Blade\'s Edge Mountains storylines listed below..',
    TBC_QUEST_10504 = 'Sylvanaar',
    TBC_QUEST_10671 = 'Toshley\'s Station',
    TBC_QUEST_10806 = 'The Gronn Threat',
    TBC_QUEST_10505 = 'Thunderlord Stronghold',
    TBC_QUEST_10742 = 'Reunion',
    TBC_QUEST_10867 = 'The Mok\'Nathal',
    TBC_QUEST_10748 = 'Ruuan Weald',
    
    AN_QUESTS_NETHERSTORM = 'Into the Nether',
    AD_QUESTS_NETHERSTORM = 'Complete the Netherstorm storylines listed below.',
    TBC_QUEST_10409 = 'Socrethar',
    TBC_QUEST_10240 = 'The Violet Tower',
    TBC_QUEST_10249 = 'Protect Area 52!',
    TBC_QUEST_10439 = 'Destroying the All-Devouring',
    TBC_QUEST_10221 = 'Building the X-52 Nether-Rocket',
    TBC_QUEST_10276 = 'The Consortium',
    
    AN_QUESTS_SHADOWMOON = 'Shadow of the Betrayer',
    AD_QUESTS_SHADOWMOON = 'Complete the Shadowmoon Valley storylines listed below.',
    TBC_QUEST_10744 = 'News of Victory',
    TBC_QUEST_11041 = 'Netherwing Ledge',
    TBC_QUEST_10645 = 'The First Death Knight',
    TBC_QUEST_10651 = 'Borrowed Power',
    TBC_QUEST_11052 = 'Akama\'s Promise',
    TBC_QUEST_10588 = 'The Cipher of Damnation',
    TBC_QUEST_10679 = 'Anti-Demon Weapons',
    TBC_QUEST_10808 = 'The Dark Conclave',
	
	AN_HEMET_QUESTS_NAGRAND = 'Hills Like White Elekk',
	AD_HEMET_QUESTS_NAGRAND = 'Complete all of Hemet Nesingwary quests in Nagrand up to and including The Ultimate Bloodsport.',

    HEROIC_NAME_PATTERN = 'Heroic: %s',
    HEROIC_DESCRIPTION_PATTERN = '%s on Heroic Difficulty',

    AN_HELLFIRE_RAMPARTS = 'Hellfire Ramparts',
    AD_HELLFIRE_RAMPARTS = 'Defeat the leaders of Hellfire Ramparts',
    AC_BOSS_17308 = 'Omor the Unscarred',
    AC_BOSS_17537 = 'Vazruden the Herald',
	AC_BOSS_17536 = 'Nazan',

    AN_BLOOD_FURNACE = 'The Blood Furnace',
    AD_BLOOD_FURNACE = 'Defeat Keli\'dan the Breaker',

    AN_SLAVE_PENS = 'The Slave Pens',
    AD_SLAVE_PENS = 'Defeat Quagmirran',

    AN_UNDERBOG = 'Underbog',
    AD_UNDERBOG = 'Defeat The Black Stalker',

    AN_MANA_TOMBS = 'Mana-Tombs',
    AD_MANA_TOMBS = 'Defeat Nexus-Prince Shaffar',

    AN_AUCHENAI_CRYPTS = 'Auchenai Crypts',
    AD_AUCHENAI_CRYPTS = 'Defeat Exarch Maladaar',

    AN_OLD_HILLSBRAD = 'The Escape From Durnholde',
    AD_OLD_HILLSBRAD = 'Defeat Epoch Hunter',

    AN_SETHEKK_HALLS = 'Sethekk Halls',
    AD_SETHEKK_HALLS = 'Defeat Talon King Ikiss',

    AN_STEAMVAULT = 'The Steamvault',
    AD_STEAMVAULT = 'Defeat Warlord Kalithresh',

    AN_SHADOW_LABYRINTH = 'Shadow Labyrinth',
    AD_SHADOW_LABYRINTH = 'Defear Murmur',

    AN_SHATTERED_HALLS = 'The Shattered Halls',
    AD_SHATTERED_HALLS = 'Defeat Warchief Kargath Bladefist',

    AN_BLACK_MORASS = 'Opening of the Dark Portal',
    AD_BLACK_MORASS = 'Defeat Aeonus',

    AN_BOTANICA = 'The Botanica',
    AD_BOTANICA = 'Defeat Warp Splinter',

    AN_MECHANAR = 'The Mechanar',
    AD_MECHANAR = 'Defeat Pathaleon the Calculator',

    AN_ARCATRAZ = 'The Arcatraz',
    AD_ARCATRAZ = 'Defeat Harbringer Skyriss',
	
	AN_MAGISTERS_TERRACE = 'Magisters\' Terrace',
    AD_MAGISTERS_TERRACE = 'Defeat Kael\'thas Sunstrider',
	
	AN_TBC_DUNGEONS = 'Outland Dungeonmaster',
    AD_TBC_DUNGEONS = 'Complete the Burning Crusade dungeon achievements listed below.',

    AN_TBC_DUNGEONS_HERO = 'Outland Dungeon Hero',
    AD_TBC_DUNGEONS_HERO = 'Complete the heroic Burning Crusade dungeon achievements listed below.',

    AN_RAVEN_LORD = 'Reins of the Raven Lord',
    AD_RAVEN_LORD = 'Obtain the Reins of the Raven Lord from Anzu in Sethekk Halls.',

    AN_KARAZHAN = 'Karazhan',
    AD_KARAZHAN = 'Defeat Prince Malchezaar in Karazhan.',

    AN_GRUUL = 'Gruul\'s Lair',
    AD_GRUUL = 'Defeat Gruul the Dragonkiller in Gruul\'s Lair.',

    AN_MAGTHERIDON = 'Magtheridon\'s Lair',
    AD_MAGTHERIDON = 'Defeat Magtheridon in Magtheridon\'s Lair.',
	
	AN_ZULAMAN = 'Zul\'Aman',
	AD_ZULAMAN = 'Defeat Zul\'jin in Zul\'Aman.',
	
	AN_SUNWELL = 'Sunwell Plateau',
	AD_SUNWELL = 'Defeat Kil\'jaeden in Sunwell Plateau.',

    AN_TBC_PHASE_1 = 'Outland Raider - Phase 1',
    AD_TBC_PHASE_1 = 'Complete the Burning Crusade raid achievements listed below.',
    AN_TBC_PHASE_2 = 'Outland Raider - Phase 2',
    AD_TBC_PHASE_2 = 'Complete the Burning Crusade raid achievements listed below.',
    AN_TBC_PHASE_3 = 'Outland Raider - Phase 3',
    AD_TBC_PHASE_3 = 'Complete the Burning Crusade raid achievements listed below.',
	AN_TBC_PHASE_4 = 'Outland Raider - Phase 4',
    AD_TBC_PHASE_4 = 'Complete the Burning Crusade raid achievements listed below.',
	AN_TBC_PHASE_5 = 'Outland Raider - Phase 5',
    AD_TBC_PHASE_5 = 'Complete the Burning Crusade raid achievements listed below.',

    FACTION_946 = 'Honor Hold',
    FACTION_947 = 'Thrallmar',
    FACTION_942 = 'Cenarion Expedition',
    FACTION_1011 = 'Lower City',
    FACTION_989 = 'Keepers of Time',
    FACTION_935 = 'The Sha\'tar',
    FACTION_609 = 'Cenarion Circle',

    AN_TBC_DUNGEON_REPUTATIONS = 'The Burning Crusader',
    AD_TBC_DUNGEON_REPUTATIONS = 'Raise all of The Burning Crusade dungeon reputations to Exalted.',
	
	AN_CENARION_CIRCLE = 'Guardian of Cenarius',
    AD_CENARION_CIRCLE = 'Earn exalted status with the Cenarion Circle and Cenarion Expedition.',

    AN_SHATTRATH_REP = 'Shattrath Divided',
    AD_SHATTRATH_REP = 'Earn exalted status with The Scryers or The Aldor.',

    AN_OGRILA = 'A Quest a Day Keeps the Ogres at Bay',
    AD_OGRILA = 'Earn exalted status within Ogri\'la.',

    AN_SPOREGGAR = 'The Czar of Sporeggar',
    AD_SPOREGGAR = 'Earn exalted status with Sporeggar.',

    AN_CONSORTIUM = 'Chief Exalted Officer',
    AD_CONSORTIUM = 'Earn exalted status with The Consortium.',

    AN_MAGHAR = 'Mag\'har of Draenor',
    AD_MAGHAR = 'Earn exalted status with The Mag\'har.',

    AN_KURENAI = 'Oh My, Kurenai',
    AD_KURENAI = 'Earn exalted status with the Kurenai.',

    AN_NETHERWINGS = 'On Wings of Nether',
    AD_NETHERWINGS = 'Earn exalted status with Netherwing.',

    AN_SKYSHATTERED = 'Skyshattered',
    AD_SKYSHATTERED = 'Defeat Captain Skyshatter in the Dragonmaw race on Netherwing Ledge.',

    AN_AMETHYST_EYE = 'The Violet Eye',
    AD_AMETHYST_EYE = 'Earn exalted status with The Violet Eye.',

    AN_SCALE_OF_THE_SANDS = 'The Scale of the Sands',
    AD_SCALE_OF_THE_SANDS = 'Earn exalted status with The Scale of the Sands.',

    AN_ASHTONGUE_DEATHSWORN = 'Sworn to the Deathsworn',
    AD_ASHTONGUE_DEATHSWORN = 'Earn exalted status with the Ashtongue Deathsworn.',

    AN_SHATTERED_SUN = 'You\'re So Offensive',
    AD_SHATTERED_SUN = 'Earn exalted status with the Shattered Sun Offensive.',

    AN_MR_PINCHY = 'Mr. Pinchy!',
    AD_MR_PINCHY = 'Fish up Mr. Pinchy in Outland.',

    AN_EXPLORE_OUTLAND = 'Explore Outland',
    AD_EXPLORE_OUTLAND = 'Explore the regions of Outland.',
    AN_EXPLORER = 'Universal Explorer',
    AD_EXPLORER = 'Explore Eastern Kingdoms, Kalimdor and Outland,',

    AN_MIDDLE_RARE = 'Medium Rare',
    AD_MIDDLE_RARE = 'Kill one of the extremely rare and hard to find Outland creatures listed below.',
    AN_BLOODY_RARE = 'Bloody Rare',
    AD_BLOODY_RARE = 'Kill all of the extremely rare and hard to find Outland creatures listed below.',
    TBC_NPC_18695 = 'Ambassador Jerrikar',
    TBC_NPC_18682 = 'Bog Lurker',
    TBC_NPC_18697 = 'Chief Engineer Lorthander',
    TBC_NPC_18681 = 'Coilfang Emissary',
    TBC_NPC_18694 = 'Collidus the Warp-Watcher',
    TBC_NPC_18689 = 'Crippler',
    TBC_NPC_18686 = 'Doomsayer Jurim',
    TBC_NPC_18698 = 'Ever-Core the Punisher',
    TBC_NPC_18678 = 'Fulgorge',
    TBC_NPC_17144 = 'Goretooth',
    TBC_NPC_18692 = 'Hemathion',
    TBC_NPC_18696 = 'Kraator',
    TBC_NPC_18680 = 'Marticar',
    TBC_NPC_18677 = 'Mekthorg the Wild',
    TBC_NPC_18690 = 'Morcrush',
    TBC_NPC_20932 = 'Nuramoc',
    TBC_NPC_18685 = 'Okrek',
    TBC_NPC_18693 = 'Speaker Mar\'grom',
    TBC_NPC_18683 = 'Voidhunter Yar',
    TBC_NPC_18679 = 'Vorakem Doomspeaker',

    AN_PREPATCH_QUEST = 'Into the Breach',
    AD_PREPATCH_QUEST = 'Participant in the Battle for the Dark Portal. Wielder of the Tabard of the Protector.',

    AN_RIDING_75 = 'Giddy Up!',
    AD_RIDING_75 = 'Learn the Apprentice riding skill.',
    AN_RIDING_150 = 'Fast and Furious',
    AD_RIDING_150 = 'Learn the Journeyman riding skill.',
    AN_RIDING_225 = 'Into The Wild Blue Yonder',
    AD_RIDING_225 = 'Learn the Expert riding skill.',
    AN_RIDING_300 = 'The Right Stuff',
    AD_RIDING_300 = 'Learn the Artisan riding skill.',

    AN_ATTUNE_SHATTERED_HALLS = 'Hotter than Hell',
    AD_ATTUNE_SHATTERED_HALLS = 'Obtain the Shattered Halls Key.',
    AN_ATTUNE_ARCATRAZ = 'How to Break Into the Arcatraz',
    AD_ATTUNE_ARCATRAZ = 'Obtain the Key to the Arcatraz.',
    AN_ATTUNE_KARAZHAN = 'The Master\'s Touch',
    AD_ATTUNE_KARAZHAN = 'Obtain The Master\'s Key.',
    AN_ATTUNE_NIGHT_BANE = 'Digging Up the Past',
    AD_ATTUNE_NIGHT_BANE = 'Obtain the Blackened Urn.',
    AN_ATTUNE_SSC = 'The Cudgel of Kar\'desh',
    AD_ATTUNE_SSC = 'Get access to the Serpentshrine Cavern.',
    AN_ATTUNE_EYE = 'The Tempest Key',
    AD_ATTUNE_EYE = 'Obtain The Tempest Key.',
    AN_ATTUNE_HYJAL = 'The Vials of Eternity',
    AD_ATTUNE_HYJAL = 'Soridormi at Caverns of Time wants you to retrieve Vashj\'s Vial Remnant from Lady Vashj at Coilfang Reservoir and Kael\'s Vial Remnant from Kael\'thas Sunstrider at Tempest Keep.',
    AN_ATTUNE_BLACK_TEMPLE = 'A Distraction for Akama',
    AD_ATTUNE_BLACK_TEMPLE = 'Obtain the Medallion of Karabor.',

    AN_SSC = 'Serpentshrine Cavern',
    AD_SSC = 'Defeat the bosses listed below inside Serpentshrine Cavern.',
    AC_KILL_HYDROS = 'Hydross the Unstable',
    AC_KILL_LURKER = 'The Lurker Below',
    AC_KILL_LEOTHERAS = 'Leotheras the Blind',
    AC_KILL_KARATHRESS = 'Fathom-Lord Karathress',
    AC_KILL_MOROGRIM = 'Morogrim Tidewalker',
    AC_KILL_VASHJ = 'Lady Vashj',
    AN_TK = 'Tempest Keep',
    AD_TK = 'Defeat the bosses listed below inside The Eye.',
    AC_KILL_ALAR = 'Al\'ar',
    AC_KILL_VOID_REAVER = 'Void Reader',
    AC_KILL_SOLARIAN = 'High Astromancer Solarian',
    AC_KILL_KAELTHAS = 'Kael\'thas Sunstrider',

    AN_HYJAL = 'The Battle for Mount Hyjal',
    AD_HYJAL = 'Defeat Archimonde in The Battle for Mount Hyjal.',

    AN_BT_ENTRANCE = 'Infiltration',
    AD_BT_ENTRANCE = 'Make your way inside the Black Temple via the Sewers of Karabor by defeating the bosses listed below.',
    AC_KILL_NAJENTUS = 'High Warlord Naj\'entus',
    AC_KILL_SUPREMUS = 'Supremus',

    AN_BT_SECOND_WING = 'Acolyte of Karabor',
    AD_BT_SECOND_WING = 'Cleanse the main halls of the Black Temple from the evil that has settled in there by defeating the bosses listed below.',
    AC_KILL_SHADOW_OF_AKAMA = 'Shade of Akama',
    AC_KILL_THERON = 'Teron Gorefiend',
    AC_KILL_GURTOGG = 'Gurtogg Bloodboil',
    AC_KILL_RELIQUARY = 'Reliquary of Souls',

    AN_BT_LAST_WING = 'Top of the Temple',
    AD_BT_LAST_WING = 'Infiltrate the upper floors of the Black Temple and defeat the bosses listed below.',
    AC_KILL_MOTHER_SHAHRAZ = 'Mother Shahraz',
    AC_KILL_BT_COUNCIL = 'The Illidari Council',
    AC_KILL_ILLIDAN = 'Illidan Stormrage',

    AN_BLACK_TEMPLE = 'The Black Temple',
    AD_BLACK_TEMPLE = 'Earn the achievements listed below by defeating all bosses in the Black Temple.',
    AR_BLACK_TEMPLE = 'Conqueror of the Black Temple',

    AN_AZZINOTH = 'Warglaives of Azzinoth',
    AD_AZZINOTH = 'Wielder of a set of Warglaives of Azzinoth.',
	AN_THORIDAL = 'Thori\'dal, the Stars\' Fury',
    AD_THORIDAL = 'Wielder of Thori\'dal, the Stars\' Fury.',
    AC_OBTAIN_MAINHAND_AZZINOTH = 'Right Warglaive of Azzinoth',
    AC_OBTAIN_OFFHAND_AZZINOTH = 'Left Warglaive of Azzinoth',
	AN_BEAR_MOUNT = 'Amani War Bear',
    AD_BEAR_MOUNT = 'Owner of Amani War Bear.',
	AN_HAWK_MOUNT = 'Swift White Hawkstrider',
    AD_HAWK_MOUNT = 'Obtain the Swift White Hawkstrider from Kael\'thas Sunstrider in Magister\'s Terrace.',
	AN_ALAR_MOUNT = 'Ashes of Al\'ar',
    AD_ALAR_MOUNT = 'Obtain the Ashes of Al\'ar from Kael\'thas Sunstrider in Tempest Keep.',
	AN_HORSEMAN_MOUNT = 'The Horseman\'s Reins',
	AD_HORSEMAN_MOUNT = 'Obtain The Horseman\'s Reins from The Headless Horseman in the Scarlet Monastery during Hallow\'s End.',
	AN_HERO_SHATTRATH = 'Hero of Shattrath',
	AD_HERO_SHATTRATH = 'Gained exalted status with The Scryers and The Aldor.',
	AN_HERO_SCRYER = 'The Scryers',
	AN_HERO_ALDOR = 'The Aldor',
	AN_CHAMPION_NAARU = 'Champion of the Naaru',
	AD_CHAMPION_NAARU = 'Earned the title, "Champion of the Naaru".',
	AR_CHAMPION_NAARU = 'Champion of the Naaru',
	AN_HAND_ADAL = 'Hand of  A\'dal',
	AD_HAND_ADAL = 'Earned the title, "Hand of A\'dal".',
	AR_HAND_ADAL = 'Hand of  A\'dal',

    AN_P3_FIRST_WEEK = 'Conqueror of the Outland',
    AD_P3_FIRST_WEEK = 'Defeat Archimonde and Illidan Stormrage in their respective raids within the first week of the release of Phase Three.',
    AC_KILL_ARCHIMONDE = 'Archimonde',
    AR_P3_FIRST_WEEK = 'Conqueror of Outland',
	
	AN_FLIGHFORM = 'Swift Flight Form',
	AD_FLIGHFORM = 'Completed the druid quest to obtain Swift Flight Form.'
})