if GetLocale() ~= 'esES' then return end
SexyLib:InitLocalization('Anniversary Achievements', {
    achievement_earned = '&aLogro obtenido por %s el %d.%d.%d',
    achievement_in_progress = '&aLogro en progreso por %s',

    ICON_DESCRIPTION = '&7Clic izquierdo: &eAbrir/Ocultar ventana de logros\n&7Clic derecho: &eAbrir ajustes de Anniversary Achievements',

    OPTION_SHARING = 'Compartir logros',
    OPTION_SHARING_DESC = 'Compartir nuevos logros en el chat. Visible solo para ti.',
    OPTION_MICROBUTTON = 'Botón de micro menú',
    OPTION_MICROBUTTON_DESC = 'Si está habilitado, se añadirá un botón de complemento al micromenú. La interfaz podría fallar si se usa algún complemento para modificarla. Si está deshabilitado, el icono se añadirá al minimapa.',
    OPTION_UPDATE_MAP_EXPLORATION = 'Verificar áreas exploradas',
    OPTION_UPDATE_MAP_EXPLORATION_DESC = 'Cuenta las áreas ya exploradas para logros.',
    OPTION_RESET_ACHIEVEMENTS = 'Restablecer logros',
    OPTION_RESET_ACHIEVEMENTS_DESC = 'Restablecer todos los logros de este personaje. ¡Esto no se puede deshacer!',
    OPTION_TRACKER = 'Rastrear objetivos',
    OPTION_TRACKER_DESC = 'Habilitar o deshabilitar el rastreador de logros y misiones.',
    OPTION_RELOAD = "Los cambios requieren una recarga de la interfaz",
    OPTION_DISABLED = 'Opción deshabilitada debido a addons de IU cargados',

    GOT_ACHIEVEMENT_MESSAGE_MALE = 'Has conseguido el logro %s!',
    GOT_ACHIEVEMENT_MESSAGE_FEMALE = 'Has conseguido el logro %s!',

    UPDATING_EXPLORED_AREAS = 'Actualizando datos de exploración de áreas. Esta acción tardará unos segundos.',
    UPDATED_EXPLORED_AREAS = '&a¡Se ha actualizado la información sobre las áreas exploradas!',

    UI_COMBAT_ERROR = '¡Anniversary Achievements no se puede abrir durante el combate!',

    GEAR_SLOT_HEAD = 'Cabeza',
    GEAR_SLOT_NECK = 'Cuello',
    GEAR_SLOT_SHOULDER = 'Hombros',
    GEAR_SLOT_CHEST = 'Pecho',
    GEAR_SLOT_WAIST = 'Cintura',
    GEAR_SLOT_LEGS = 'Piernas',
    GEAR_SLOT_FEET = 'Pies',
    GEAR_SLOT_WRIST = 'Muñecas',
    GEAR_SLOT_HANDS = 'Manos',
    GEAR_SLOT_FIRST_RING = 'Anillo derecho',
    GEAR_SLOT_SECOND_RING = 'Anillo izquierdo',
    GEAR_SLOT_FIRST_TRINKET = 'Primer abalorio',
    GEAR_SLOT_SECOND_TRINKET = 'Segundo abalorio',
    GEAR_SLOT_CLOAK = 'Capa',
    GEAR_SLOT_WEAPON = 'Arma',

    NPC_3444 = 'Rata de madriguera',
    NPC_620 = 'Pollo',
    NPC_1420 = 'Sapo',
    NPC_13321 = 'Rana pequeña',
    NPC_2620 = 'Perro de la pradera',
    NPC_9600 = 'Loro',
    NPC_883 = 'Ciervo',
    NPC_9699 = 'Alfazaque de fuego',
    NPC_4953 = 'Moccasin',
    NPC_721 = 'Conejo',
    NPC_9700 = 'Cangrejo de lava',
    NPC_15476 = 'Escorpión',
    NPC_2914 = 'Víbora',
    NPC_16030 = 'Gusano',
    NPC_4075 = 'Rata',
    NPC_1412 = 'Ardilla',
    NPC_7390 = 'Cocatiel',
    NPC_15475 = 'Alfazaque',
    NPC_15010 = 'Sapo de la selva',
    NPC_4076 = 'Cucaracha',
    NPC_13016 = 'Rata del subterráneo',
    NPC_14881 = 'Araña',
    NPC_2110 = 'Rata negra',
    NPC_4166 = 'Gazelle',
    NPC_1933 = 'Oveja',
    NPC_890 = 'Cervatillo',
    NPC_2098 = 'Carnero',
    NPC_2442 = 'Vaca',
    NPC_6368 = 'Gato',
    NPC_6271 = 'Ratón',
    NPC_385 = 'Caballo',
    NPC_10685 = 'Puerco',
    NPC_3300 = 'Agregador',
    NPC_15065 = 'Lady',
    NPC_15066 = 'Cleo',
    NPC_15071 = 'Bajapata',
    NPC_15072 = 'Pinchos',

    CATEGORY_GENERAL = 'General',
    CATEGORY_QUESTS = 'Misiones',
	CATEGORY_PVP = 'Jugador contra Jugador',
    CATEGORY_KALIMDOR = 'Kalimdor',
    CATEGORY_EASTERN_KINGDOMS = 'Reinos del este',
    CATEGORY_OUTLAND = 'Terrallende',
    CATEGORY_VANILLA = 'Classic',
    CATEGORY_TBC = 'The Burning Crusade',
    CATEGORY_EXPLORATION = 'Exploración',
    CATEGORY_PVE = 'Mazmorras y bandas',
    CATEGORY_ARENA = 'Arena',
    CATEGORY_BG_ALTERAC = 'Valle de Alterac',
    CATEGORY_BG_WARSONG = 'Garganta Grito de Guerra',
    CATEGORY_BG_ARATHI = 'Cuenca de Arathi',
    CATEGORY_BG_EYE = 'Ojo de la tormenta',
    CATEGORY_PROFESSIONS = 'Profesiones',
    CATEGORY_REPUTATION = 'Reputación',
	CATEGORY_EVENTS = 'Eventos de mundo',
	CATEGORY_HALLOWSEND = 'Halloween',
    CATEGORY_WINTERVEIL = 'Festival del invierno',
    CATEGORY_VALENTINES = 'Amor en el aire',
    CATEGORY_FEATS_OF_STRENGTH = 'Proezas de fuerza',
	
	AN_DRUID_T1 = 'Vestiduras Cenarion',
	AN_WARLOCK_T1 = 'Vestiduras Corazón Oscuro',
	AN_PRIEST_T1 = 'Vestimentas de la Profecía',
	AN_MAGE_T1 = 'Atavío de Arcanista',
	AN_ROGUE_T1 = 'Armadura de Destripador Nocturno',
	AN_HUNTER_T1 = 'Armadura de Zancudo Gigante',
	AN_PALADIN_T1 = 'Armadura de Justiciero',
	AN_WARRIOR_T1 = 'Equipo de batalla de Poderío',
	AN_SHAMAN_T1 = 'La Furia Terrenal',
	
	AN_DRUID_T2 = 'Vestiduras Tempestira',
	AN_WARLOCK_T2 = 'Vestiduras de la Némesis',
	AN_PRIEST_T2 = 'Vestimentas de Trascendencia',
	AN_MAGE_T2 = 'Atavío Ventobisal',
	AN_ROGUE_T2 = 'Armadura Colmillo de Sangre',
	AN_HUNTER_T2 = 'Armadura de Acechadragón',
	AN_PALADIN_T2 = 'Armadura de la Sentencia',
	AN_WARRIOR_T2 = 'Equipo de batalla de la Cólera',
	AN_SHAMAN_T2 = 'Las Diez Tormentas',

	AN_DRUID_T3 = 'Vestiduras de Oninámbulo',
	AN_WARLOCK_T3 = 'Vestidura Corazón de la Peste',
	AN_PRIEST_T3 = 'Vestimentas de la Fe',
	AN_MAGE_T3 = 'Ropajes de Fuegoescarcha',
	AN_ROGUE_T3 = 'Armadura de Segahuesos',
	AN_HUNTER_T3 = 'Armadura de Acechadripta',
	AN_PALADIN_T3 = 'Armadura de la Redencción',
	AN_WARRIOR_T3 = 'Equipo de batalla de Acorator',
	AN_SHAMAN_T3 = 'El Trizaterrador',	
	
	AD_SET = 'Reúne todos los objetos del conjunto mencionado.',
	
	AN_SKELETON_KEY = 'La llave de Scholomance',
	AD_SKELETON_KEY = 'Consigue la Llave esqueleto.',

    AN_LVL = 'Nivel %d',
    AD_LVL = 'Alcanza el nivel %d.',

    AN_BANK = 'Depósito seguro',
    AD_BANK = 'Compra 7 ranuras bancarias adicionales.',
    AC_BANK = 'Compra 7 ranuras bancarias adicionales.',

    AN_QUESTS = '%d misiones completadas',
    AD_QUESTS = 'Completa %d misiones.',
    AC_QUESTS = 'Completa %d misiones.',

    AN_DAILY_QUESTS = '%d misiones diarias completadas',
    AD_DAILY_QUESTS = 'Completa %d misiones diarias.',
    AC_DAILY_QUESTS = 'Completa %d misiones diarias.',

    AN_QUEST_GOLD5 = 'Recompensa brillante',
    AN_QUEST_GOLD10 = 'Coleccionista de monedas acuñadas',
    AN_QUEST_GOLD25 = 'Sostén de la familia',
    AN_QUEST_GOLD50 = 'Oro bien merecido',
    AN_QUEST_GOLD100 = 'Ganado con sudor y sangre',
    AN_QUEST_GOLD250 = 'Impresora dorada',
    AN_QUEST_GOLD500 = 'Soy menta yo mismo',
    AD_QUEST_GOLD = 'Gana %d oro con las recompensas de misiones.',
    AC_QUEST_GOLD = 'Gana %d oro con las recompensas de misiones.',

    AN_QUESTS_ZONE = 'Maestro cultura de %s',
    AD_QUESTS_ZONE = 'Completa la misión "%s" en %s.',
    AD_QUESTS_ZONE_MULTI = 'Completa las siguientes misiones en %s.',
    AC_QUESTS_ZONE = 'Completó la misión "%s".',

    AZSHARA_1 = 'Azshara',
    AZSHARA_2 = 'Azshara',
    QUEST_3602 = 'Azsharita',

    FELWOOD_1 = 'Frondavil',
    FELWOOD_2 = 'Frondavil',
    QUEST_5165 = 'Sofocar las llamas de protección',
    QUEST_5385 = 'Restos de Trey Forjaluz',

    DESOLACE_1 = 'Desolace',
    DESOLACE_2 = 'Desolace',
    QUEST_6027 = 'El Libro de los Ancestros',

    DUSTWALLOW_1 = 'Marjal Revolcafango',
    DUSTWALLOW_2 = 'Marjal Revolcafango',
    QUEST_1203 = 'Jarl necesita una hoja',

    SILITHUS_1 = 'Silithus',
    SILITHUS_2 = 'Silithus',
    QUEST_8287 = 'Un propósito terrible',
    QUEST_8352 = 'Cetro del Consejo',
    QUEST_8321 = 'Vyral el Vil',
    QUEST_8281 = 'Intensificar la seguridad',

    DUROTAR_1 = 'Durotar',
    DUROTAR_2 = 'Durotar',
    QUEST_835 = 'Asegurar las rutas',

    BARRENS_1 = 'Los Baldíos',
    BARRENS_2 = 'Los Baldíos',
    QUEST_888 = 'El botín robado',
    QUEST_902 = 'El churumbele',

    WINTERSPRING_1 = 'Cuna del Invierno',
    WINTERSPRING_2 = 'Cuna del Invierno',
    QUEST_975 = 'Alijo de Mau\'ari',
    QUEST_5082 = 'La amenaza de los Nevada',
    QUEST_5121 = 'Alto Jefe Nevada',
    QUEST_5163 = 'Yeti... ¿ya hemos llegado?',
    QUEST_4842 = 'Fuentes extrañas',

    TANARIS_1 = 'Tanaris',
    TANARIS_2 = 'Tanaris',
    QUEST_2662 = 'El elixir de Tragonublo',
    QUEST_2874 = 'Un envío para MacKinley',
    QUEST_1691 = 'Más justicia para bandidos',
    QUEST_113 = 'Análisis de trozos de insecto',

    STONETALON_1 = 'Sierra Espolón',
    STONETALON_2 = 'Sierra Espolón',
    QUEST_1096 = 'Gerenzo Silbillave',

    UNGORO_1 = 'Cráter de Un\'Goro',
    UNGORO_2 = 'Cráter de Un\'Goro',
    QUEST_3962 = 'Ir solo es peligroso',
    QUEST_4245 = 'Buscando a Memo 01',
    QUEST_4292 = 'El cebo para Lar\'korwi',

    THOUSAND_NEEDLES_1 = 'Las mil agujas',
    THOUSAND_NEEDLES_2 = 'Las mil agujas',
    QUEST_1189 = 'La seguridad primero',

    ARATHI_1 = 'Tierras Altas de Arathi',
    ARATHI_2 = 'Tierras Altas de Arathi',
    QUEST_652 = 'Desbloquear la piedra angular',

    BADLANDS_1 = 'Tierras Inhóspitas',
    BADLANDS_2 = 'Tierras Inhóspitas',
    QUEST_737 = 'El saber prohibido',
    QUEST_778 = 'Lo tienes crudo',
    QUEST_656 = 'Invocar a la princesa',
	QUEST_793 = 'Alianzas rotas',
	QUEST_717 = 'Terremotos',
    
    EASTERN_PLAGUELANDS_1 = 'Tierras de la Peste del Este',
    EASTERN_PLAGUELANDS_2 = 'Tierras de la Peste del Este',
    QUEST_5942 = 'Tesoros ocultos',
    QUEST_6148 = 'El Oráculo Escarlata, Demetria',
    QUEST_6187 = 'Restaurar el orden',
    QUEST_5265 = 'El Bastión Argenta',

    BLASTED_LANDS_1 = 'Las Tierras Devastadas',
    BLASTED_LANDS_2 = 'Las Tierras Devastadas',
    QUEST_3628 = 'Eres Rakh\'likh, demonio',

    STRANGLETHORN_VALLEY_1 = 'Vega de Tuercespina',
    STRANGLETHORN_VALLEY_2 = 'Vega de Tuercespina',
    QUEST_208 = 'Caza mayor',
    QUEST_600 = 'La minería de Ventura y Cía.',
    QUEST_613 = 'El pie roto de Maury',
    QUEST_628 = 'Borceguí',
    QUEST_338 = 'Las verdes colinas de Tuercespina',
	
	AN_NESINGWARY = 'Las verdes colinas de Tuercespina',
	AD_NESINGWARY = 'Completa todas las misiones de Hemet Nesingwary en la Vega de Tuercespina hasta Las verdes colinas de Tuercespina y Caza mayor incluidas.',

    WESTERN_PLAGUELANDS_1 = 'Tierras de la Peste del Oeste',
    WESTERN_PLAGUELANDS_2 = 'Tierras de la Peste del Oeste',
    QUEST_5944 = 'En sueños',
    QUEST_5051 = 'Dos mitades hacen una',
    QUEST_4985 = 'La naturaleza también sufre',

    SEARING_GORGE_1 = 'La Garganta de Fuego',
    SEARING_GORGE_2 = 'La Garganta de Fuego',
    QUEST_3481 = 'Abalarios...',

    BLACK_ROCK_1 = 'Montaña Roca Negra',
    BLACK_ROCK_2 = 'Montaña Roca Negra',
    QUEST_8996 = 'Vuelve con Bodley',

    AN_WISDOM_KEEPER = 'El maestro cultural',
    AD_WISDOM_KEEPER = 'Completa los logros de misiones listados a continuación.',
    AN_WISDOM_KEEPER_AZEROTH = 'Maestro cultural de Azeroth',
    AD_WISDOM_KEEPER_AZEROTH = 'Completa los logros de misiones listados a continuación.',
    AN_WISDOM_KEEPER_KALIMDOR = 'Maestro cultural de Kalimdor',
    AD_WISDOM_KEEPER_KALIMDOR = 'Completa los logros de misiones listados a continuación.',
    AN_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Maestro cultural de los Reinos del Este',
    AD_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Completa los logros de misiones listados a continuación.',
    AN_WISDOM_KEEPER_OUTLAND = 'Maestro cultural de Terrallende',
    AD_WISDOM_KEEPER_OUTLAND = 'Completa los logros de misiones listados a continuación.',
    AR_WISDOM_KEEPER = 'El maestro cultural',

    AN_RAGEFIRE_CHASM = 'Sima Ígnea',
    AD_RAGEFIRE_CHASM = 'Derrota a Taragaman el Hambriento.',
    AN_WAILING_CAVERNS = 'Cuevas de los Lamentos',
    AD_WAILING_CAVERNS = 'Derrota a Mutanus el Devorador.',
    AN_DEAD_MINES = 'Minas de la Muerte',
    AD_DEAD_MINES = 'Derrota a Edwin VanCleef.',
    AN_SHADOWFANG_KEEP = 'Castillo de Colmillo Oscuro',
    AD_SHADOWFANG_KEEP = 'Derrota al archimago Arugal.',
    AN_BLACKFATHOM_DEEPS = 'Cavernas de Brazanegra',
    AD_BLACKFATHOM_DEEPS = 'Derrota a Aku\'mai.',
    AN_JAIL = 'Mazmorras de Ventormenta',
    AD_JAIL = 'Derrota a Bazil Thredd.',
    AN_GNOMREGAN = 'Gnomeregan',
    AD_GNOMREGAN = 'Derrota al mekigeniero Termochufe.',
    AN_RAZORFEN_KRAUL = 'Horado Rajacieno',
    AD_RAZORFEN_KRAUL = 'Derrota a Charlga Filonavaja.',
    AN_SCARLET_MONASTERY = 'Monasterio Escarlata',
    AD_SCARLET_MONASTERY = 'Derrota a la Cruzada Escarlata en el Monasterio Escarlata.',
    AC_SCARLET_MONASTERY1 = 'Mago sangriento Thalnos',
    AC_SCARLET_MONASTERY2 = 'Arcanista Doan',
    AC_SCARLET_MONASTERY3 = 'Herod',
    AC_SCARLET_MONASTERY4 = 'Alta inquisidora Melenablanca',
	AC_SCARLET_MONASTERY5 = 'Comandante Escarlata Mograine',
	
    AN_RAZORFEN_DOWNS = 'Zahúrda Rajacienos',
    AD_RAZORFEN_DOWNS = 'Derrota a Amnennar el Gélido.',
    AN_ULDAMAN = 'Uldaman',
    AD_ULDAMAN = 'Derrota a Archaedas.',
    AN_ZULFARRAK = 'Zul\'Farrak',
    AD_ZULFARRAK = 'Derrota al jefe Ukorz Cabellarena.',
    AN_MARAUDON = 'Maraudon',
    AD_MARAUDON = 'Derrota a la princesa Theradras.',
    AN_SUNKEN_TEMPLE = 'Templo Sumergido',
    AD_SUNKEN_TEMPLE = 'Derrota a la Sombra de Eranikus.',
	
    AN_NEW_EMPEROR = 'Profundidades de Roca Negra',
    AD_NEW_EMPEROR = 'Derrota al emperador Dagran Thaurissan.',
    AN_BLACKROCK_DEPTHS = 'Limpiando las profundidades',
    AD_BLACKROCK_DEPTHS = 'Derrota a los siguientes jefes en Profundidades de Roca Negra.',
    AC_BLACKROCK_DEPTHS1 = 'Alta interrogadora Gerstahn matada',
    AC_BLACKROCK_DEPTHS2 = 'Maestro de canes Grebmar',
    AC_BLACKROCK_DEPTHS3 = 'General Forjainquina',
    AC_BLACKROCK_DEPTHS4 = 'Señor Gólem Argelmach',
    AC_BLACKROCK_DEPTHS5 = 'Lord Incendius',
    AC_BLACKROCK_DEPTHS6 = 'Depositario Stilgiss',
    AC_BLACKROCK_DEPTHS7 = 'Bael\'Gar',
    AN_BLACKROCK_PARTY = 'Fiesta en la Tragapenas',
    AD_BLACKROCK_PARTY = 'Derrota a todos los oponentes enumerados en la Tragapenas.',
    AC_BLACKROCK_PARTY1 = 'Ribbly Llavenrosca',
    AC_BLACKROCK_PARTY2 = 'Plugger Aropatoso',
    AC_BLACKROCK_PARTY3 = 'Hurley Negrálito',
    AC_BLACKROCK_PARTY4 = 'Falange',
    AN_BLACKROCK_DEPTHS_FULL = 'Maestro de las Profundidades de Roca Negra',
    AD_BLACKROCK_DEPTHS_FULL = 'Consigue los siguientes logros relacionados con Profundidades de Roca Negra.',
    AN_ARMOR_SWORD = 'La mejor defensa es un ataque',
    AD_ARMOR_SWORD = 'Saquea la Piedra de la Tierra del cuerpo del derrotado Panzor el Invencible en las Profundidades de Roca Negra.',
	
    AN_BLACKROCK_SPIRE_BOTTOM = 'Cumbre de Roca Negra inferior',
    AD_BLACKROCK_SPIRE_BOTTOM = 'Derrota al señor supremo Vermiothalak.',
    AN_BLACKROCK_SPIRE_UPPER = 'Cumbre de Roca Negra superior',
    AD_BLACKROCK_SPIRE_UPPER = 'Derrota al General Drakkisath.',
    AN_BLACKROCK_SPIRE = 'Invasor de la Cumbre de Roca Negra',
    AD_BLACKROCK_SPIRE = 'Consigue los siguientes logros relacionados con Cumbre de Roca Negra.',
    AN_DIRE_MAUL = 'Rey de La Masacre',
    AD_DIRE_MAUL = 'Derrota cada ala de La Masacre.',
    AC_DIRE_MAUL1 = 'Alzzin el Formaferal',
    AC_DIRE_MAUL2 = 'Immol\'thar',
    AC_DIRE_MAUL3 = 'Rey Gordok',
    AN_STRATHOLME = 'Stratholme',
    AD_STRATHOLME = 'Derrota a los diabólicos organizadores que habitan en Stratholme.',
	AC_STRATHOLME1 = 'Barón Osahendido',
	AC_STRATHOLME2 = 'Balnazzar',	
    AN_SCHOLOMANCE = 'Scholomance',
    AD_SCHOLOMANCE = 'Derrota a los líderes de Scholomance.',
	AC_SCHOLOMANCE1 = 'Maestro oscuro Gandling',
	AC_SCHOLOMANCE2 = 'Ras Murmuhielo',
    AN_YOUNG_DEFENDER = 'Joven defensor de Azeroth',
    AD_YOUNG_DEFENDER = 'Obtén los logros de mazmorras de bajo nivel que se enumeran a continuación.',
    AN_DEFENDER = 'Defensor de Azeroth',
    AD_DEFENDER = 'Consigue los logros de mazmorra que se enumeran a continuación.',
    AR_DEFENDER = 'Defensor de Azeroth',

    AN_ONYXIA = 'Guarida de Onyxia',
    AD_ONYXIA = 'Derrota a Onyxia.',
    AN_AQ20 = 'Ruinas de Ahn\'Qiraj',
    AD_AQ20 = 'Derrota a Osirio el Sinmarcas.',
    AN_ZULGURUB = 'Zul\'Gurub',
    AD_ZULGURUB = 'Derrota a Hakkar.',
    AN_RAGNAROS = 'Núcleo de Magma',
    AD_RAGNAROS = 'Derrota a Ragnaros.',
    AN_BLACK_WING_LAIR = 'Guarida de Alanegra',
    AD_BLACK_WING_LAIR = 'Derrota a Nefarian.',
    AN_AQ40 = 'Templo de Ahn\'Qiraj',
    AD_AQ40 = 'Derrota a C\'Thun.',
    AN_NAXXRAMAS_SPIDERS = 'El Arrabal Arácnido',
    AD_NAXXRAMAS_SPIDERS = 'Derrota a los jefes de El Arrabal Arácnido de Naxxramas.',
    AC_NAXXRAMAS_SPIDERS1 = 'Anub\'Rekhan',
    AC_NAXXRAMAS_SPIDERS2 = 'Gran Viuda Faerlina',
    AC_NAXXRAMAS_SPIDERS3 = 'Maexxna',
    AN_NAXXRAMAS_PLAGUE = 'El Arrabal de la Peste',
    AD_NAXXRAMAS_PLAGUE = 'Derrota a los jefes de El Arrabal de la Peste de Naxxramas.',
    AC_NAXXRAMAS_PLAGUE1 = 'Noth el Pesteador',
    AC_NAXXRAMAS_PLAGUE2 = 'Heigan el Impuro',
    AC_NAXXRAMAS_PLAGUE3 = 'Loatheb',    
    AN_NAXXRAMAS_MILITARY = 'El Arrabal Militar',
    AD_NAXXRAMAS_MILITARY = 'Derrota a los jefes de El Arrabal Militar de Naxxramas.',
    AC_NAXXRAMAS_MILITARY1 = 'Instructor Razuvious',
    AC_NAXXRAMAS_MILITARY2 = 'Gothik el Cosechador',
    AC_NAXXRAMAS_MILITARY3 = 'Los Cuatro Jinetes',
    AN_NAXXRAMAS_CONSTRUCT = 'El Arrabal de los Ensamblajes',
    AD_NAXXRAMAS_CONSTRUCT = 'Derrota a los jefes de El Arrabal de los Ensamblajes de Naxxramas.',
    AC_NAXXRAMAS_CONSTRUCT1 = 'Remendejo',
    AC_NAXXRAMAS_CONSTRUCT2 = 'Grobbulus',
    AC_NAXXRAMAS_CONSTRUCT3 = 'Gluth',
    AC_NAXXRAMAS_CONSTRUCT4 = 'Thaddius',  
    AN_NAXXRAMAS_SAPPHIRON = 'La muerte de Sapphiron',
    AD_NAXXRAMAS_SAPPHIRON = 'Derrota a Sapphiron en Naxxramas.',
    AN_NAXXRAMAS_LAIR = 'La derrota de Kel\'Thuzad',
    AD_NAXXRAMAS_LAIR = 'Derrota a Kel\'Thuzad en Naxxramas.',
    AN_NAXXRAMAS = 'La caída de Naxxramas',
    AD_NAXXRAMAS = 'Consigue los siguientes logros relacionados con Naxxramas.',
    AN_YOUNG_HERO = 'Joven héroe de Azeroth',
    AD_YOUNG_HERO = 'Consigue los logros de banda que se enumeran a continuación.',
    AN_BLACKROCK_MASTER = 'Señor de la Roca Negra',
    AD_BLACKROCK_MASTER = 'Obtén los siguientes logros relacionados con las mazmorras y bandas de Roca Negra.',
    AN_HERO = 'Héroe de Azeroth',
    AD_HERO = 'Consigue los logros de banda que se enumeran a continuación.',
    AR_HERO = 'Héroe de Azeroth',
    AN_GREAT_HERO = 'Gran héroe de Azeroth',
    AD_GREAT_HERO = 'Obtén los logros de banda y mazmorra que se enumeran a continuación.',
    AR_GREAT_HERO = 'Gran héroe de Azeroth',

    AN_PVP_RANK_A1 = 'Soldado',
    AN_PVP_RANK_A2 = 'Cabo',
    AN_PVP_RANK_A3 = 'Capataz',
    AN_PVP_RANK_A4 = 'Sargento primero',
    AN_PVP_RANK_A5 = 'Alférez',
    AN_PVP_RANK_A6 = 'Caballero',
    AN_PVP_RANK_A7 = 'Teniente caballero',
    AN_PVP_RANK_A8 = 'Capitán caballero',
    AN_PVP_RANK_A9 = 'Campeón caballero',
    AN_PVP_RANK_A10 = 'Teniente coronel',
    AN_PVP_RANK_A11 = 'Comandante',
    AN_PVP_RANK_A12 = 'Mariscal',
    AN_PVP_RANK_A13 = 'Mariscal de campo',
    AN_PVP_RANK_A14 = 'Gran mariscal',
    AN_PVP_RANK_H1 = 'Rastreador',
    AN_PVP_RANK_H2 = 'Bruto',
    AN_PVP_RANK_H3 = 'Capataz',
    AN_PVP_RANK_H4 = 'Capataz primero',
    AN_PVP_RANK_H5 = 'Gran capataz',
    AN_PVP_RANK_H6 = 'Guardia de piedra',
    AN_PVP_RANK_H7 = 'Guardia de sangre',
    AN_PVP_RANK_H8 = 'Legionario',
    AN_PVP_RANK_H9 = 'Centurión',
    AN_PVP_RANK_H10 = 'Campeón',
    AN_PVP_RANK_H11 = 'General',
    AN_PVP_RANK_H12 = 'Gran general',
    AN_PVP_RANK_H13 = 'Señor de la Guerra',
    AN_PVP_RANK_H14 = 'Gran Señor de la Guerra',
    AD_PVP_RANK = 'Ganó el título, "%s".',
    AN_PVP_FIRST_KILL = 'Una muerte con honor',
    AD_PVP_FIRST_KILL = 'Consigue una muerte con honor.',
    AC_PVP_FIRST_KILL = 'Consigue una muerte con honor.',
    AN_PVP_KILLS = '%d muertes con honor.',
    AD_PVP_KILLS = 'Obtén %d muertes con honor.',
    AC_PVP_KILLS = 'Obtén %d muertes con honor.',

    AN_MOB_KILLS_1 = 'Asesino',
    AN_MOB_KILLS_2 = 'Destructor',
    AN_MOB_KILLS_3 = 'Triturador',
    AN_MOB_KILLS_4 = 'Rebanacabezas',
    AN_MOB_KILLS_5 = 'Tormenta de los monstruos',
    AN_MOB_KILLS_6 = 'Tormenta de todos los seres vivos',
    AN_MOB_KILLS_7 = 'Muerte omnipresente',
    AD_MOB_KILLS = 'Mata a %d monstruos.',
    AC_MOB_KILLS = 'Mata a %d monstruos.',

    AN_REPS_1 = 'A alguien le gusto',
    AD_REPS_1 = 'Eleva una reputación a Exaltado.',
    AC_REPS_1 = 'Eleva una reputación a Exaltado.',
    AN_REPS_X = ' Reputaciones exaltadas',
    AD_REPS = 'Elevar %d reputaciones a Exaltado.',
    AC_REPS = 'Elevó la reputación de %d a Exaltado.',
    AR_REPS = 'El Exaltado',

    AN_HORDE_REPS = 'Embajador de la Horda',
    AD_HORDE_REPS = 'Alcanza la reputación Exaltado con las 5 facciones de la Horda.',
    AC_HORDE_REPS_1 = 'Exaltado con Orgrimmar.',
    AC_HORDE_REPS_2 = 'Exaltado con los trols Lanza Negra.',
    AC_HORDE_REPS_3 = 'Exaltado con Entrañas.',
    AC_HORDE_REPS_4 = 'Exaltado con Cima del Trueno.',
    AC_HORDE_REPS_5 = 'Exaltado con la Ciudad de Lunargenta.',

    AN_ALLIANCE_REPS = 'Embajador de la Alianza',
    AD_ALLIANCE_REPS = 'Alcanza la reputación Exaltado con las 5 facciones de la Alianza.',
    AC_ALLIANCE_REPS_1 = 'Exaltado con Ventormenta.',
    AC_ALLIANCE_REPS_2 = 'Exaltado con Darnassus.',
    AC_ALLIANCE_REPS_3 = 'Exaltado con los Exiliados de Gnomeregan.',
    AC_ALLIANCE_REPS_4 = 'Exaltado con Forjaz.',
    AC_ALLIANCE_REPS_5 = 'Exaltado con El Exodar.',

    AN_ARGENT_DAWN = 'El Alba Argenta',
    AD_ARGENT_DAWN = 'Alcanza la reputación Exaltado con El Alba Argenta.',
    AN_BROOD_OF_NOZDORMU = 'Linaje de Nozdormu',
    AD_BROOD_OF_NOZDORMU = 'Alcanza la reputación Exaltado con el Linaje de Nozdormu.',
    AN_DARKMOON_FAIRE = 'Feria de la Luna Negra',
    AD_DARKMOON_FAIRE = 'Alcanza la reputación Exaltado con la Feria de la Luna Negra.',
    AN_ZANDALAR_TRIBE = 'Héroe de la tribu Zandalar',
    AD_ZANDALAR_TRIBE = 'Alcanza la reputación Exaltado con la tribu Zandalar.',
    AN_HYDRAXIANS = 'Srs. del Agua de Hydraxis',
    AD_HYDRAXIANS = 'Alcanza la reputación Exaltado con los Srs. del Agua de Hydraxis.',
    AN_TIMBERMAW_HOLD = 'En ese túnel me adoran',
    AD_TIMBERMAW_HOLD = 'Alcanza la reputación Exaltado con el Bastión Fauces de Madera.',
    AN_THORIUM = 'Hermandad del Torio',
    AD_THORIUM = 'Alcanza la reputación Exaltado con la Hermandad del Torio.',
    AN_SHENDRALAR = 'Agente de los Shen\'dralar',
    AD_SHENDRALAR = 'Alcanza la reputación Exaltado con los Shen\'dralar.',
    AN_CENARION = 'Círculo Cenarion',
    AD_CENARION = 'Alcanza la reputación Exaltado con el Círculo Cenarion.',

    AN_DEFILERS = 'El Rapiñador',
    AD_DEFILERS = 'Alcanza la reputación Exaltado con los Rapiñadores renegados.',
    AN_FROSTWOLF_CLAN = 'Héroe del clan Lobo Gélido',
    AD_FROSTWOLF_CLAN = 'Alcanza la reputación Exaltado con el clan Lobo Gélido.',
    AN_WARSONG_OUTRIDERS = 'Escolta Grito de Guerra',
    AD_WARSONG_OUTRIDERS = 'Alcanza la reputación Exaltado con los escoltas Grito de Guerra.',
    AN_HORDE_PVP_FRACTIONS = 'El conquistador',
    AD_HORDE_PVP_FRACTIONS = 'Eleva tu nivel de reputación en la Garganta Grito de Guerra, la Cuenca de Arathi y el Valle de Alterac a Exaltado.',

    AN_LEAGUE_OF_ARATHOR = 'Caballero de Arathor',
    AD_LEAGUE_OF_ARATHOR = 'Alcanza la reputación Exaltado con la Liga de Arathor.',
    AN_STORMSPIKE_GUARD = 'Héroe de la Guardia Pico Tormenta',
    AD_STORMSPIKE_GUARD = 'Alcanza la reputación Exaltado con la Guardia Pico Tormenta.',
    AN_SILVERWING_SENTINELS = 'Centinela Ala de Plata',
    AD_SILVERWING_SENTINELS = 'Alcanza la reputación Exaltado con los Centinelas Ala de Plata.',
    AN_ALLIANCE_PVP_FRACTIONS = 'El justicar',
    AD_ALLIANCE_PVP_FRACTIONS = 'Eleva tu nivel de reputación en la Garganta Grito de Guerra, la Cuenca de Arathi y el Valle de Alterac a Exaltado.',

    AN_BOLVAR_SLAYER = 'Asaltar Ventormenta',
    AD_BOLVAR_SLAYER = 'Asesina al Alto señor Bolvar Fordragón.',
    AN_MAGNI_SLAYER = '¡Muerte al Rey!',
    AD_MAGNI_SLAYER = 'Mata al rey Magni Barbabronce.',
    AN_TYRANDE_SLAYER = 'Ya no es inmortal',
    AD_TYRANDE_SLAYER = 'Mata a la suma sacerdotisa Tyrande Susurravientos.',
    AN_VELEN_SLAYER = 'Apagar la luz',
    AD_VELEN_SLAYER = 'Mata al profeta Velen.',

    AN_ALLIANCE_KINGS_SLAYER = '¡Por la Horda!',
    AD_ALLIANCE_KINGS_SLAYER = 'Mata a los líderes de la Alianza.',

    AN_THRALL_SLAYER = '¡Muerte al Jefe de Guerra!',
    AD_THRALL_SLAYER = 'Mata a Thrall.',
    AN_SYLVANAS_SLAYER = 'Abajo con la Dama Oscura',
    AD_SYLVANAS_SLAYER = 'Mata a Lady Sylvanas Brisaveloz.',
    AN_CAIRNE_SLAYER = 'Pezuña de Sangre sangrante',
    AD_CAIRNE_SLAYER = 'Mata a Cairne Pezuña de Sangre.',
    AN_LORTHEMAR_SLAYER = 'Asesinado en Quel\'Thalas',
    AD_LORTHEMAR_SLAYER = 'Mata a Lor\'themar Theron.',

    AN_HORDE_KINGS_SLAYER = '¡Por la Alianza!',
    AD_HORDE_KINGS_SLAYER = 'Mata a los líderes de la Horda.',

    AN_RACES_KILLER = 'Conoce a tu enemigo',
    AD_ALLIANCE_RACES_KILLER = 'Consigue un golpe de gracia con honor con cinco razas diferentes.',
    AD_HORDE_RACES_KILLER = 'Consigue un golpe de gracia con honor con cinco razas diferentes.',
    AC_HUMAN_KILLED = 'Humano',
    AC_NIGHTELF_KILLED = 'Elfo de la noche',
    AC_DWARF_KILLED = 'Enano',
    AC_GNOME_KILLED = 'Gnomo',
    AC_ORC_KILLED = 'Orco',
    AC_TROLL_KILLED = 'Trol',
    AC_SCOURGE_KILLED = 'No-muerto',
    AC_TAUREN_KILLED = 'Tauren',
    AC_DRAENEI_KILLED = 'Draenei',
    AC_BLOODELF_KILLED = 'Elfo de sangre',

    AN_CLASSES_KILLER = 'Hace falta clase',
    AD_CLASSES_KILLER = 'Asesta un golpe de gracia con honor a cada clase.',
    AC_WARRIOR_KILLED = 'Guerrero',
    AC_HUNTER_KILLED = 'Cazador',
    AC_ROGUE_KILLED = 'Pícaro',
    AC_PRIEST_KILLED = 'Sacerdote',
    AC_MAGE_KILLED = 'Mago',
    AC_WARLOCK_KILLED = 'Brujo',
    AC_DRUID_KILLED = 'Druida',
    AC_PALADIN_KILLED = 'Paladín',
    AC_SHAMAN_KILLED = 'Chaman',

    AN_ALTERAC_WIN = 'Victoria en el Valle de Alterac',
    AD_ALTERAC_WIN = 'Gana en el Valle de Alterac.',
    AN_ALTERAC_WINS = 'Veterano del Valle de Alterac',
    AD_ALTERAC_WINS = 'Consigue %d victorias en el Valle de Alterac.',
    AN_WARSONG_WIN = 'Victoria en la Garganta Grito de Guerra',
    AD_WARSONG_WIN = 'Gana en la Garganta Grito de Guerra.',
    AN_WARSONG_WINS = 'Veterano de la Garganta Grito de Guerra',
    AD_WARSONG_WINS = 'Completa %d victorias en la Garganta Grito de Guerra.',
    AN_ARATHI_WIN = 'Victoria en la Cuenca de Arathi',
    AD_ARATHI_WIN = 'Gana en la Cuenca de Arathi.',
    AN_ARATHI_WINS = 'Veterano de la Cuenca de Arathi',
    AD_ARATHI_WINS = 'Completa %d victorias en la Cuenca de Arathi.',
    AN_EYE_WIN = 'Victoria en el Ojo de la Tormenta',
    AD_EYE_WIN = 'Gana en el Ojo de la Tormenta.',
    AN_EYE_WINS = 'Veterano del Ojo de la Tormenta',
    AD_EYE_WINS = 'Completa %d victorias en el Ojo de la Tormenta.',

    AN_ALTERAC_KILLING_BLOWS = 'Picadora de carne del valle',
    AD_ALTERAC_KILLING_BLOWS = 'Realiza %d golpes de gracia en una sola batalla por el Valle de Alterac y quédate hasta que termine.',
    AN_ALTERAC_GRAVEYARD_ASSAULT = 'Funerario',
    AD_ALTERAC_GRAVEYARD_ASSAULT = 'Asalta un cementerio en una sola batalla por el Valle de Alterac y quédate hasta que termine.',
    AN_ALTERAC_GRAVEYARD_ASSAULTS = 'Nunca hay suficientes ataúdes',
    AD_ALTERAC_GRAVEYARD_ASSAULTS = 'Asalta %d cementerios en una sola batalla por el Valle de Alterac y quédate hasta que termine.',
    AN_ALTERAC_GRAVEYARD_DEFEND = 'Guardián del difunto',
    AD_ALTERAC_GRAVEYARD_DEFEND = 'Defiende un cementerio en una sola batalla por el Valle de Alterac y quédate hasta que termine.',
    AN_ALTERAC_GRAVEYARD_DEFENDS = 'Guardián de todos los muertos',
    AD_ALTERAC_GRAVEYARD_DEFENDS = 'Defiende %d cementerios en una sola batalla por el Valle de Alterac y quédate hasta que termine.',
    AN_ALTERAC_TOWER_ASSAULT = '¡Ahora es mío!',
    AD_ALTERAC_TOWER_ASSAULT = 'Asalta una torre en una sola batalla por el Valle de Alterac y quédate hasta que termine.',
    AN_ALTERAC_TOWER_ASSAULTS = '¡Ahora es todo mío!',
    AD_ALTERAC_TOWER_ASSAULTS = 'Asalta %d torres en una sola batalla por el Valle de Alterac y quédate hasta que haya terminado.',
    AN_ALTERAC_TOWER_DEFEND = 'Guardián de la torre',
    AD_ALTERAC_TOWER_DEFEND = 'Defiende una torre en una sola batalla por el Valle de Alterac y quédate hasta que termine.',
    AN_ALTERAC_TOWER_DEFENDS = 'Encargado de torres',
    AD_ALTERAC_TOWER_DEFENDS = 'Defiende %d torres en una sola batalla por el Valle de Alterac y quédate hasta que termine.',
    AN_ALTERAC_MINE_CAPTURE = 'Minero congelado',
    AD_ALTERAC_MINE_CAPTURE = 'Asalta una mina en una sola batalla por el Valle de Alterac y quédate hasta que termine.',
    AN_ALTERAC_MINE_CAPTURES = 'Piquero congelado',
    AD_ALTERAC_MINE_CAPTURES = 'Asalta %d minas en una sola batalla por el Valle de Alterac y quédate hasta que termine.',
    AN_ALTERAC_AUTOGRAPH = 'El saqueador va el botín',
    AD_ALTERAC_AUTOGRAPH = 'Despoja la fotografía autografiada de Tigule en el valle de Alterac.',

    AN_WARSONG_KILLS = 'Honor militar',
    AD_WARSONG_KILLS = 'Obtén %d muertes con honor en una sola batalla por Garganta Grito de Guerra y quédate hasta que termine.',
    AN_WARSONG_FLAG_CAPTURE = 'Captura la bandera',
    AD_WARSONG_FLAG_CAPTURE = 'Lleva y captura personalmente la bandera en una sola batalla por Garganta Grito de Guerra y quédate hasta que termine.',
    AN_WARSONG_FLAG_CAPTURES = 'Gran Abanderado',
    AD_WARSONG_FLAG_CAPTURES = 'Lleva y captura personalmente %d banderas en una sola batalla por Garganta Grito de Guerra y quédate hasta que termine.',
    AN_WARSONG_FLAG_RETURN = '¡No tocar!',
    AD_WARSONG_FLAG_RETURN = 'Devuelve una bandera como defensor en una sola batalla por Garganta Grito de Guerra y quédate hasta que termine.',
    AN_WARSONG_FLAG_RETURNS = '¡No toques nada!',
    AD_WARSONG_FLAG_RETURNS = 'Devuelve %d banderas como defensor en una sola batalla por Garganta Grito de Guerra y quédate hasta que termine.',

    AN_ARATHI_BASE_ASSAULT = 'Conquistador',
    AD_ARATHI_BASE_ASSAULT = 'Asalta una bandera en una sola batalla por la Cuenca de Arathi y quédate hasta que termine.',
    AN_ARATHI_BASE_ASSAULTS = 'Campo de pruebas',
    AD_ARATHI_BASE_ASSAULTS = 'Asalta %d banderas en una sola batalla por la Cuenca de Arathi y quédate hasta que termine.',
    AN_ARATHI_BASE_DEFEND = 'Guardián',
    AD_ARATHI_BASE_DEFEND = 'Defiende una bandera en una sola batalla por la Cuenca de Arathi y quédate hasta que termine.',
    AN_ARATHI_BASE_DEFENDS = 'Centinela',
    AD_ARATHI_BASE_DEFENDS = 'Defiende %d banderas en una sola batalla por la Cuenca de Arathi y quédate hasta que termine.',
    AN_ARATHI_CLOSE = 'La victoria estaba clara *ejem*',
    AD_ARATHI_CLOSE = 'Gana Cuenca de Arathi por 10 puntos (2000 a 1990).',
    AN_ARATHI_PERFECT = 'Perfección en la Cuenca de Arathi',
    AD_ARATHI_PERFECT = 'Gana en la Cuenca de Arathi con una puntuación de 2000 a 0.',

    AN_EYE_CAPTURE = 'Rematar la tormenta',
    AD_EYE_CAPTURE = 'Lleva y captura personalmente la bandera en Ojo de la Tormenta y quédate hasta el final de la batalla.',
    AD_EYE_CAPTURES = 'Lleva y captura personalmente %d banderas en Ojo de la Tormenta y quédate hasta el final de la batalla.',
    AN_EYE_GLORY = 'Destinado a la gloria',
    AD_EYE_GLORY = 'En una sola batalla por el Ojo de la Tormenta, captura la bandera 3 veces sin morir.',
    AN_EYE_FAST_WIN = 'Aluvión',
    AD_EYE_FAST_WIN = 'Gana en el Ojo de la Tormenta en menos de 6 minutos.',
    AN_EYE_BERSERK = 'Rabioso sanguinario',
    AD_EYE_BERSERK = 'Consigue un golpe de gracia bajo los efectos de la ventaja rabiosa en el Ojo de la Tormenta.',
    AN_EYE_IDEAL_VICTORY = 'La tormenta perfecta',
    AD_EYE_IDEAL_VICTORY = 'Gana en el Ojo de la Tormenta con una puntuación de 1500 a 0.',

    AN_BGS_KILLING_BLOWS = 'Portador de la muerte',
    AD_BGS_KILLING_BLOWS = 'Realiza %d golpe de gracia en cualquier campo de batalla.',
    AN_BGS_KILLS = 'Agregador de honor',
    AD_BGS_KILLS = 'Obtén %d muertes con honor en cualquier campo de batalla.',

    PROF_FIRST_AID = 'Primeros auxilios',
    PROF_FISHING = 'Pesca',
    PROF_COOKING = 'Cocina',
    PROF_ENCHANTING = 'Encantamiento',
    PROF_TAILORING = 'Costura',
    PROF_ENGINEERING = 'Ingeniería',
    PROF_LEATHERWORKING = 'Marroquinería',
    PROF_ALCHEMY = 'Minería',
    PROF_BLACKSMITHING = 'Herrería',
    PROF_HERBALISM = 'Botánica',
    PROF_MINING = 'Minería',
    PROF_SKINNING = 'Desollar',
    PROF_JEWELCRAFTING = 'Joyería',
    SKILL_UNARMED = 'Sin armas',
    SKILL_RIDING = 'Equitación',

    AN_PROFS_JOURNEYMAN = 'Aprendiz profesional',
    AD_PROFS_JOURNEYMAN = 'Aumenta la habilidad de cualquier profesión principal a 75.',
    AN_PROFS_EXPERT = 'Oficial profesional',
    AD_PROFS_EXPERT = 'Aumenta la habilidad de cualquier profesión principal a 150.',
    AN_PROFS_ARTISAN = 'Experto profesional',
    AD_PROFS_ARTISAN = 'Aumenta la habilidad de cualquier profesión principal a 225.',
    AN_PROFS_ONE = 'Oficial profesional',
    AD_PROFS_ONE = 'Aumenta la habilidad de cualquier profesión principal a 300.',
    AN_PROFS_ONE_OUTLAND = 'Maestro profesional',
    AD_PROFS_ONE_OUTLAND = 'Aumenta la habilidad de cualquier profesión principal a 375.',
    AN_PROFS_TWO = 'Manitas',
    AD_PROFS_TWO = 'Aumenta la habilidad de dos profesiones principales a 300 al mismo tiempo.',
    AC_PROFS_TWO = 'Aumenta la habilidad de dos profesiones principales a 300 al mismo tiempo.',
    AN_PROFS_TWO_OUTLAND = 'Manitas extravagante',
    AD_PROFS_TWO_OUTLAND = 'Aumenta la habilidad de dos profesiones principales a 375 al mismo tiempo.',
    AC_PROFS_TWO_OUTLAND = 'Aumenta la habilidad de dos profesiones principales a 375 al mismo tiempo.',

    AN_FIRST_AID_JOURNEYMAN = 'Aprendiz de primeros auxilios',
    AD_FIRST_AID_JOURNEYMAN = 'Aumenta la habilidad de primeros auxilios a 75.',
    AN_FIRST_AID_EXPERT = 'Oficial en primeros auxilios',
    AD_FIRST_AID_EXPERT = 'Aumenta la habilidad de primeros auxilios a 150.',
    AN_FIRST_AID_ARTISAN = 'Experto en primeros auxilios',
    AD_FIRST_AID_ARTISAN = 'Aumenta la habilidad de primeros auxilios a 225.',
    AN_FIRST_AID_MASTER = 'Artesano profesional',
    AD_FIRST_AID_MASTER = 'Aumenta la habilidad de primeros auxilios a 300.',
    AN_FIRST_AID_OUTLAND_MASTER = 'Maestro en primeros auxilios',
    AD_FIRST_AID_OUTLAND_MASTER = 'Aumenta la habilidad de primeros auxilios a 375.',
	
    AN_FISHING_JOURNEYMAN = 'Aprendiz de pescador',
    AD_FISHING_JOURNEYMAN = 'Aumenta la habilidad de pesca a 75.',
    AN_FISHING_EXPERT = 'Oficial pescador',
    AD_FISHING_EXPERT = 'Aumenta la habilidad de pesca a 150.',
    AN_FISHING_ARTISAN = 'Pescador experto',
    AD_FISHING_ARTISAN = 'Aumenta la habilidad de pesca a 225.',
    AN_FISHING_MASTER = 'Pescador artesano',
    AD_FISHING_MASTER = 'Aumenta la habilidad de pesca a 300.',
    AN_FISHING_OUTLAND_MASTER = 'Maestro pescador',
    AD_FISHING_OUTLAND_MASTER = 'Aumenta la habilidad de pesca a 375.',
	
    AN_COOKING_JOURNEYMAN = 'Aprendiz de cocinero',
    AD_COOKING_JOURNEYMAN = 'Aumenta la habilidad de cocina a 75.',
    AN_COOKING_EXPERT = 'Oficial cocinero',
    AD_COOKING_EXPERT = 'Aumenta la habilidad de cocina a 150.',
    AN_COOKING_ARTISAN = 'Cocinero experto',
    AD_COOKING_ARTISAN = 'Aumenta la habilidad de cocina a 225.',
    AN_COOKING_MASTER = 'Cocinero artesano',
    AD_COOKING_MASTER = 'Aumenta la habilidad de cocina a 300.',
    AN_COOKING_OUTLAND_MASTER = 'Maestro cocinero',
    AD_COOKING_OUTLAND_MASTER = 'Aumenta la habilidad de cocina a 375.',
	
    AN_PROFS_SECONDARY = 'Habilidades que pagan las facturas',
    AD_PROFS_SECONDARY = 'Conviértete en artesano en pesca, primeros auxilios y cocina.',
    AN_PROFS_SECONDARY_OUTLAND = 'Habilidades para pagar las facturas, también en Terrallende',
    AD_PROFS_SECONDARY_OUTLAND = 'Conviértete en un maestro en pesca, primeros auxilios y cocina.',
    AN_PROFS_FIVE = 'Genio en cada oficio',
    AN_PROFS_FIVE_OUTLAND = 'Genio extravagante',
    AD_PROFS_FIVE = 'Completa los logros de profesión que se enumeran a continuación.',
    AN_UNARMED_SKILL = '¿Alguien ha pedido un bocadillo de nudillos?',
    AD_UNARMED_SKILL = 'Eleva tu habilidad sin armas a 350.',

    AN_EXPLORE_AZEROTH = 'Explorador del mundo',
    AD_EXPLORE_AZEROTH = 'Explora los Reinos del Este, Kalimdor y Terrallende. ',
	AR_EXPLORER = 'Explorador',
    AN_EXPLORE_KALIMDOR = 'Explora Kalimdor',
    AD_EXPLORE_KALIMDOR = 'Explora las regiones de Kalimdor.',
    AN_EXPLORE_EASTERN_KINGDOMS = 'Explora los Reinos del Este',
    AD_EXPLORE_EASTERN_KINGDOMS = 'Explora las regiones de los Reinos del Este.',
	AN_EXPLORE = 'Explora %s',
    AD_EXPLORE = 'Explora %s, revelando las áreas cubiertas del mapa de mundo.',

    AN_SULFURAS = 'Sulfuras, Mano de Ragnaros',
    AD_SULFURAS = 'Portador de Sulfuras, Mano de Ragnaros.',
    AN_THUNDER_FURY = 'Trueno Furioso, espada bendita del Hijo del Viento',
    AD_THUNDER_FURY = 'Portador de Trueno Furioso, espada bendita del Hijo del Viento.',
    AN_ATIESH = 'Atiesh, gran báculo del Guardián',
    AD_ATIESH = 'Portador de Atiesh, gran báculo del Guardián.',
    AN_BLACK_SCARAB = 'Señor Escarabajo',
    AD_BLACK_SCARAB = 'Has abierto las puertas de Ahn\'Qiraj.',
    AN_RED_SCARAB = '¿Por qué? Porque es rojo',
    AD_RED_SCARAB = 'Consigue un cristal resonador qiraji rojo.',
	AN_TIGER_MOUNT = 'Tigre Zulian presto',
    AD_TIGER_MOUNT = 'Consigue el tigre Zulian presto del sumo sacerdote Thekal en Zul\'Gurub.',
	AN_RAPTOR_MOUNT = 'Raptor Razzashi presto',
    AD_RAPTOR_MOUNT = 'Consigue el raptor Razzashi presto del señor sangriento Mandokir en Zul\'Gurub.',
	AN_BARON_MOUNT = 'Riendas de destrero de la muerte',
    AD_BARON_MOUNT = 'Consigue las riendas de destrero de la muerte del Barón Osahendido en Stratholme.',
	AN_SABER_MOUNT = 'Sable de hielo de Cuna del Invierno',
    AD_SABER_MOUNT = 'Obtén un Sable de Hielo de Cuna del Invierno.',
    AN_ARGENT_DAWN_TABARD = 'Tabardo de El Alba Argenta',
    AD_ARGENT_DAWN_TABARD = 'Has conseguido un Tabardo de El Alba Argenta del evento Invasión de la Plaga.',
    
    AN_UNCOMMON_GEAR = 'Ya no es tan ordinario',
    AD_UNCOMMON_GEAR = 'Equípate con objetos poco comunes o de calidad superior.',
    AN_RARE_GEAR = 'Superior',
    AD_RARE_GEAR = 'Equipa un objeto superior en cada ranura',
    AN_EPIC_GEAR = 'Épico',
    AD_EPIC_GEAR = 'Equipa un objeto épico en cada ranura ',

    AN_STOCKING_UP = 'Abastecerse',
    AD_STOCKING_UP = 'Fabrica 100 Venda de paño rúnico gruesa.',
    AC_STOCKING_UP = 'Fabrica 100 Venda de paño rúnico gruesa.',
    AN_STOCKING_UP_2 = 'Abastecerse',
    AD_STOCKING_UP_2 = 'Fabrica 500 Venda de paño rúnico gruesa.',
    AC_STOCKING_UP_2 = 'Fabrica 500 Venda de paño rúnico gruesa.',
    AN_STOCKING_UP_OUTLAND = 'Preparándose para el vacío',
    AD_STOCKING_UP_OUTLAND = 'Fabrica 100 Venda de tejido abisal gruesa.',
    AC_STOCKING_UP_OUTLAND = 'Fabrica 100 Venda de tejido abisal gruesa.',
    AN_STOCKING_UP_2_OUTLAND = 'Preparándose para el vacío',
    AD_STOCKING_UP_2_OUTLAND = 'Fabrica 500 Venda de tejido abisal gruesa.',
    AC_STOCKING_UP_2_OUTLAND = 'Fabrica 500 Venda de tejido abisal gruesa.',

    AN_BOOTY_BAY_CONTEST = 'Elijo lo mejor para la pesca.',
    AD_BOOTY_BAY_CONTEST = 'Gana el concurso de pesca de Bahía del Botín y elige la Caña de pescar de arcanita o el Anzuelo de Maestro pescador como recompensa.',
    AN_BOOTY_BAY_FISH = 'Un verdadero amante del pescado',
    AD_BOOTY_BAY_FISH = 'Pesque uno de los peces más raros durante el concurso de pesca de Bahía del Botín.',

    AN_FISHING_COLLECTION = 'Colección de peces',
    AD_FISHING_COLLECTION = 'Captura los siguientes peces en Azeroth.',
    AN_FISHING_OUTLAND_COLLECTION = 'Colección de peces extravagantes',
    AD_FISHING_OUTLAND_COLLECTION = 'Captura las siguientes especies en Terrallende.',
    AN_FISHING_WATER = 'Agua del agua',
    AD_FISHING_WATER = 'Pesca una Esencia de agua.',
    AN_FISHING_RUM = 'La elección del capitán',
    AD_FISHING_RUM = 'Pesca los siguientes tipos de ron.',
    AN_FISHING_RING = 'El regalo de Mordor',
    AD_FISHING_RING = 'Pesca El anillo 1.',
    AN_FISHING_SKULL = 'Presagio de un final triste',
    AD_FISHING_SKULL = 'Pesca la Calavera de camionero vieja.',
    AN_FISHING_SNAPPER = 'Gran atrapador de pargos',
    AD_FISHING_SNAPPER = 'Pesca Pargos de los siguientes tamaños.',
    AC_FISHING_SNAPPER = 'Pargo de lodo de %d kilos',
    AN_FISHING_SEA_BASS = 'Tormenta eléctrica de perchas',
    AD_FISHING_SEA_BASS = 'Pesca Meros de los siguientes tamaños.',
    AC_FISHING_SEA_BASS = 'Mero de %d kilos',
    AN_FISHING_SALMON = 'Amante del salmón',
    AD_FISHING_SALMON = 'Pesca salmones de los siguientes tamaños.',
    AC_FISHING_SALMON = 'Salmón de %d kilos',
    AN_FISHING_LOBSTER = 'Cazador de langostas',
    AD_FISHING_LOBSTER = 'Pesca langostas de los siguientes tamaños.',
    AC_FISHING_LOBSTER = 'Langosta de %d kilos',
    AN_FISHING_BIG_SIZE = 'El mejor pescador de Azeroth',
    AD_FISHING_BIG_SIZE = 'Completa los siguientes logros de pesca que se enumeran a continuación.',
    AR_FISHING_BIG_SIZE = 'El mejor pescador de Azeroth',
	
	AN_FISHING_COUNT = '%d Peces',
	AC_FISHING_COUNT = 'Pescaste %d objetos.',
	AD_FISHING_COUNT = 'Pescaste %d objetos.',

    AN_COOKING_RECIPES_5 = 'La señora del comedor',
    AN_COOKING_RECIPES_10 = 'Cocinero de comida rápida',
    AN_COOKING_RECIPES_25 = 'Chef de Partie',
    AN_COOKING_RECIPES_50 = 'Sous Chef',
    AN_COOKING_RECIPES_75 = 'Chef de Cuisine',
    AR_COOKING_RECIPES = 'Chef',
    AD_COOKING_RECIPES = 'Aprende %d recetas de cocina.',
    AC_COOKING_RECIPES = 'Aprende %d recetas de cocina.',

    AN_COOKING_SOUP = 'Especialista en sopas',
    AN_COOKING_DESSERT = 'Maestro de los tubérculos',
    AN_COOKING_SQUID = 'La pesca del día',
    AN_COOKING_DUMPLINGS = 'Albóndigas de la abuela',
    AN_COOKING_CAKE = 'La tarta es de verdad',
    AD_COOKING_CAKE = 'Hornea un delicioso pastel de chocolate.',
    AD_COOKING_CREATE = 'Cocinar %s %d veces.',
    AC_COOKING_CREATE = 'Cocinar %s %d veces.',
    AN_COOKING_BIG_TABLE = 'Gran banquete festivo',
    AD_COOKING_BIG_TABLE = 'Completa los logros culinarios que se enumeran a continuación.',

    AN_COOKING_FISHERMANS_FEAST = 'Festín de pescador',
    AN_COOKING_SPICY_HOT_TALBUK = 'Talbuk con guindillas',
    AN_COOKING_SKULLFISH_SOUP = 'Sopa de pez calavera',
    AN_COOKING_RAVAGER_DOG = 'Perro devastador',

    AN_WB_AZUREGOS = 'El secreto del dragón azul',
    AD_WB_AZUREGOS = 'Derrota a Azuregos.',
    AN_WB_KAZZAK = 'Los demonios no pasarán',
    AD_WB_KAZZAK = 'Derrota al Señor Kazzak.',
    AN_WB_KAZZAK_OUTLAND = 'Soy el dueño de mi destino.',
    AD_WB_KAZZAK_OUTLAND = 'Derrota al Señor Apocalíptico Kazzak en la Península del Fuego Infernal.',
    AN_WB_DOOMWALKER = 'Caminante del Destino roto',
    AD_WB_DOOMWALKER = 'Derrota a Caminante del Destino en el Valle Sombraluna.',
    AN_WB_YSONDRE = 'No hay lugar para chicas en una pesadilla',
    AD_WB_YSONDRE = 'Derrota a Ysondre.',
    AN_WB_LETHON = 'Hijo de la Pesadilla Esmeralda',
    AD_WB_LETHON = 'Derrota a Lethon.',
    AN_WB_EMERISS = 'Emeriss, traidora a la vida',
    AD_WB_EMERISS = 'Derrota a Emeriss.',
    AN_WB_TAERAR = 'Taerar de pesadilla',
    AD_WB_TAERAR = 'Derrota a Taerar.',
    AN_WB_EMERALD_DRAGONS = 'Guardián esmeralda',
    AD_WB_EMERALD_DRAGONS = 'Derrota a todos los Dragones de la Pesadilla Esmeralda.',
    AR_WB_EMERALD_DRAGONS = 'Guardián esmeralda',

    AN_DUEL = 'Duelicioso',
    AD_DUEL = 'Gana un duelo contra otro jugador.',
    AN_DUELS_10 = 'Duelista',
    AN_DUELS_25 = 'Duelista experto',
    AN_DUELS_100 = 'Maestro duelista',
    AD_DUELS = 'Gana en %d duelos.',
    AC_DUELS = 'Gana en %d duelos',
    AN_GURUBASHI_1 = 'Maestro de la Arena Gurubashi',
    AD_GURUBASHI_1 = 'Despoja el abalorio del maestro de arena en la Arena Gurubashi.',
    AN_GURUBASHI_2 = 'Gran Maestro de la Arena Gurubashi',
    AD_GURUBASHI_2 = 'Completa la misión del Corto John Mitril para obtener el abalorio de gran maestro de arena.',
    AN_PARTICIPATE_IN_BGS = '¡Llamamiento a las armas!',
    AD_PARTICIPATE_IN_BGS = 'Completa %d campos de batalla.',
    AC_PARTICIPATE_IN_BGS = 'Completa %d campos de batalla.',

    EMOTE_LOVE1 = 'Te amas a %s.',
    AN_LOVE = 'A todas las ardillas que he amado',
    AD_LOVE = 'Demuestra todo tu /amor a las alimañas de Azeroth.',
    EMOTE_PAT1 = 'Das una palmadita a %s.',
    AN_ARATHI_CATS = 'Primero los gatos, luego todo lo demás.',
    AD_ARATHI_CATS = 'Dale una palmada (/palmada) a las mascotas designadas en la Cuenca de Arathi.',

    AN_ALTERAC_FAST_WIN = 'El rayo de Alterac',
    AD_ALTERAC_FAST_WIN = 'Gana en el Valle de Alterac en 6 minutos.',
    AN_WARSONG_FAST_WIN = 'Conveniencia Grito de Guerra',
    AD_WARSONG_FAST_WIN = 'Gana en la Garganta Grito de Guerra en menos de 7 minutos.',
    AN_ARATHI_FAST_WIN = 'Hagámoslo',
    AD_ARATHI_FAST_WIN = 'Gana en la Cuenca de Arathi en 6 minutos.',

    AN_ALTERAC_TOWER_DEFEND_TOTAL = 'Defensa de torres',
    AD_ALTERAC_TOWER_DEFEND_TOTAL = 'Defiende %d torres en el Valle de Alterac.',
    AN_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Ladrón de tumbas de Alterac',
    AD_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Toma %d cementerios en el Valle de Alterac.',
    AN_WARSONG_FLAG_CAPTURE_TOTAL = 'Capturador de banderas',
    AD_WARSONG_FLAG_CAPTURE_TOTAL = 'Llevar y capturar personalmente las banderas %d en Garganta Grito de Guerra.',
    AN_WARSONG_FLAG_RETURN_TOTAL = 'Defensor persistente',
    AD_WARSONG_FLAG_RETURN_TOTAL = 'Devuelve %d banderas como defensor en Garganta Grito de Guerra.',
    AN_ARATHI_BASE_ASSAULT_TOTAL = 'El Capitán y yo lo conseguimos',
    AD_ARATHI_BASE_ASSAULT_TOTAL = 'Coge %d banderas en la Cuenca de Arathi.',
    AN_ARATHI_BASE_DEFEND_TOTAL = '¡Al rescate!',
    AD_ARATHI_BASE_DEFEND_TOTAL = 'Defiende una base en la Cuenca de Arathi %d veces volviendo a capturar la bandera.',
    AN_ALTERAC_MOUNT_HORDE = 'Aullador Lobo Gélido',
    AD_ALTERAC_MOUNT_HORDE = 'Consigue un aullador Lobo Gélido.',
    AN_ALTERAC_MOUNT_ALLIANCE = 'Carnero de batalla Pico Tormenta',
    AD_ALTERAC_MOUNT_ALLIANCE = 'Consigue un carnero de batalla Pico Tormenta.',

    AN_ALTERAC_BOSS = 'Maestro del Valle de Alterac',
    AD_ALTERAC_BOSS = 'Completa los logros del Valle de Alterac listados a continuación.',
    AN_WARSONG_BOSS = 'Maestro de la Garganta Grito de Guerra',
    AD_WARSONG_BOSS = 'Completa los logros de la Garganta Grito de Guerra listados a continuación.',
    AN_ARATHI_BOSS = 'Maestro de la Cuenca de Arathi',
    AD_ARATHI_BOSS = 'Completa los logros de la Cuenca de Arathi listados a continuación.',
    AN_EYE_BOSS = 'Maestro del Ojo de la Tormenta',
    AD_EYE_BOSS = 'Completa los logros del Ojo de la Tormenta listados a continuación.',
    AN_BATTLEMASTER = 'Maestro de batalla',
    AD_BATTLEMASTER = 'Completa los logros de campos de batalla listados a continuación.',
    AR_BATTLEMASTER = 'Maestro de batalla',

    AN_LEEROY = 'Leeeeeeeeeeeeeroy!',
    AD_LEEROY = 'Mata a 50 crías de El Grajero en 15 segundos.',
    AR_LEEROY = 'Jenkins',
    AN_BWL_DUO = 'Respiración doble',
    AD_BWL_DUO = 'Mata a Ebanorroca y a Flamagor en 45 segundos.',
    AN_ANUBREKHAN_WITHOUT_MOBS = 'El Señor de la Cripta',
    AD_ANUBREKHAN_WITHOUT_MOBS = 'Mata a Anub\'Rekhan, dejando vivos a ambos guardias de la cripta.',
    AN_FAERLINA_WITHOUT_MOBS = 'Mamá me dijo que te pegara',
    AD_FAERLINA_WITHOUT_MOBS = 'Mata a la Gran Viuda Faerlina, dejando con vida a todos los adoradores y seguidores de Naxxramas.',
    AN_SAPPHIRONE_WITH_ALL_ALIVE = 'Nosotros no sucumbiremos al hielo',
    AD_SAPPHIRONE_WITH_ALL_ALIVE = 'Derrota a Sapphiron en Naxxramas sin que muera ningún miembro de la banda.',
    AN_ARACHNOPHOBIA = 'Aracnofobia',
    AD_ARACHNOPHOBIA = 'Mata a Maexxna en Naxxramas en los 20 minutos posteriores a la muerte de Anub\'Rekhan en el modo de 25 jugadores.',
    AN_FOUR_TOGETHER = 'Y todos caerán a la misma vez',
    AD_FOUR_TOGETHER = 'Derrota a los 4 Jinetes en Naxxramas, asegurándote de que mueren con menos de 15 segundos de diferencia.',
    AN_HEIGAN_DANCE = 'Baila por tu vida',
    AD_HEIGAN_DANCE = 'Derrota a Heigan el Impuro en Naxxramas sin que muera nadie de tu banda.',
    AN_PATCHWERK = 'Hazle un buen remiendo',
    AD_PATCHWERK = 'Derrota a Remendejo en Naxxramas en menos de 3 minutos',
    AN_KELTHUZAD_ABOMINATIONS = 'Nunca es suficiente',
    AD_KELTHUZAD_ABOMINATIONS = 'Derrota a Kel\'Thuzad en Naxxramas mientras matas al menos 18 abominaciones en su cámara.',
	
	AN_PIRATES_HAT = '¡Adelante, Almirante!',
	AD_PIRATES_HAT = 'Consigue el Sombrero de almirante Velasangre... e intenta tomar un poco de aire fresco de vez en cuando.',
	AR_PIRATES_HAT = 'Almirante Velasangre',	
	AN_PALADIN_MOUNT = 'Destrero',
	AD_PALADIN_MOUNT = 'Completá la misión del paladín para obtener un Cargador.',
	AN_WARLOCK_MOUNT = 'Corcel nefasto xorothiano',
	AD_WARLOCK_MOUNT = 'Has completado la misión de brujo Corcel nefasto xorothiano.',
	
	AN_HALLOWSEND = 'Santificado sea tu nombre',
	AD_HALLOWSEND = 'Completa los logros de Halloween listados a continuación.',
	AR_HALLOWSEND = 'El Santificado',
	
	AN_PUMPKIN = 'Calabazamanía',
	AD_PUMPKIN = 'Consigue una Bolsa de calabazas durante Halloween.',
	AN_HALLOWSEND_ALLIANCE_QUEST1 = 'Santificación podrida',
	AD_HALLOWSEND_ALLIANCE_QUEST1 = 'Arruina la fiesta de Halloween de la Horda completando las misiones del Sargento Hartman que implican fastidiar el Festival del Hombre de Mimbre y limpiar las bombas fétidas de Costasur.',
	AC_HALLOWSEND_ALLIANCE_QUEST1_CRITERIA1 = 'Arruinar el Festival del Hombre de Mimbre',
	AC_HALLOWSEND_ALLIANCE_QUEST1_CRITERIA2 = 'El poder del pino',
	AN_HALLOWSEND_HORDE_QUEST1 = 'Santificación podrida',
	AD_HALLOWSEND_HORDE_QUEST1 = 'Arruina la fiesta de Halloween de la Alianza completando las misiones de Clamasombra Yanka que implican ir a Costasur, estropear los barriles con huevos podridos y lanzar bombas fétidas en la ciudad.',
	AC_HALLOWSEND_HORDE_QUEST1_CRITERIA1 = 'Los barriles dañados',
	AC_HALLOWSEND_HORDE_QUEST1_CRITERIA2 = 'Apesta Costasur',
	
	AN_HALLOWSEND_ALLIANCE_QUEST2 = 'Golosinas de Halloween para Jesper',
	AD_HALLOWSEND_ALLIANCE_QUEST2 = 'Recoge los dulces solicitados para Jesper.',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA1 = 'Turrón de Ventormenta',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA2 = '	Gominola de Gnomeregan',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA3 = 'Menta de Forjaz',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA4 = 'Mazapán de Darnassus',
	AN_HALLOWSEND_HORDE_QUEST2 = 'Golosinas de Halloween para Pupas',
	AD_HALLOWSEND_HORDE_QUEST2 = 'Recoge los dulces solicitados para Pupas.',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA1 = 'Almendrados de Orgrimmar',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA2 = 'Pastilla de goma Lanza Negra',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA3 = 'Menta de Entrañas',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA4 = 'Mazapanes de Cima del Trueno',
	
	AN_HALLOWSEND_INVOCATION_BUFF = 'Invocación del Hombre de Mimbre',
	AD_HALLOWSEND_INVOCATION_BUFF = 'Recibe la mejora "Invocación del Hombre de Mimbre" durante Halloween.',
	
	AN_HALLOWSEND_TREATS = '¡Truco o trato!',
	AD_HALLOWSEND_TREATS = 'Recibe un puñado de caramelos de un tabernero.',
	
	AN_HALLOWSEND_MASK = 'La tarea de la máscara',
	AD_HALLOWSEND_MASK = 'Consigue una máscara durante Halloween.',
	
	AN_HALLOWSEND_MASKS = 'Una máscara para todas las ocasiones',
	AD_HALLOWSEND_MASKS = 'Colecciona las 16 máscaras endebles únicas que se enumeran a continuación.',
	
	AN_HALLOWSEND_TRANSFORM = 'La Mascarada',
	AD_HALLOWSEND_TRANSFORM = 'Haz que te transformen con las varitas de Halloween listadas a continuación.',
	AC_HALLOWSEND_GHOST = 'Transformado en fantasma por la varita de Halloween',
	AC_HALLOWSEND_GNOME = '	Transformado en gnomo paria por la varita de Halloween',
	AC_HALLOWSEND_WISP = '	Transformado en fuego fatuo por la varita de Halloween',
	AC_HALLOWSEND_NINJA = '	Transformado en ninja por la varita de Halloween',
	AC_HALLOWSEND_SKELETON = 'Transformado en esqueleto por la varita de Halloween',
	AC_HALLOWSEND_PIRATE = 'Transformado en pirata por la varita de Halloween',
	AC_HALLOWSEND_BAT = '	Transformado en murciélago por la varita de Halloween',

    --WINTERVEIL
    AN_WINTERVEIL = 'Juerguista',
	AD_WINTERVEIL = 'Completa los logros del Festival de Invierno listados a continuación.',
	AR_WINTERVEIL = 'Juerguista',

    AN_WINTERVEIL_METZEN = '¡Vamos, Metzen!',
	AD_WINTERVEIL_METZEN = 'Salva a Metzen el Reno.',

    AN_WINTERVEIL_SMOKEYWOOD = 'Simplemente abominable',
	AD_WINTERVEIL_SMOKEYWOOD = 'Completa la misión para recuperar los regalitos robados de los Pastos de Bosquehumeante y recibe Un agradecimiento de los Pastos de Bosquehumeante.',

    AN_WINTERVEIL_GOURMET = 'El Gourmet del Festival de Invierno',
	AD_WINTERVEIL_GOURMET = 'Durante el festín del Festival de Invierno Festival de Invierno, usa tu habilidad culinaria para crear una galleta de jengibre y un ponche de huevo.',
    AC_WINTERVEIL_GOURMET_CRITERIA1 = 'Galleta de jengibre', 
    AC_WINTERVEIL_GOURMET_CRITERIA2 = 'Ponche de huevo',

    AN_WINTERVEIL_PRESENTS = 'Sabrá si has sido malo',
	AD_WINTERVEIL_PRESENTS = 'Cuando estén disponibles, abre uno de los regalos que hay bajo el árbol del Festival de Invierno.',

    AN_WINTERVEIL_SNOWBALL_ALLIANCE = 'Avaricioso',
	AD_WINTERVEIL_SNOWBALL_ALLIANCE = 'Lanza una bola de nieve al rey Magni Barbabronce durante el festín del Festival de Invierno.',

    AN_WINTERVEIL_SNOWBALL_HORDE = 'Avaricioso',
	AD_WINTERVEIL_SNOWBALL_HORDE = 'Lanza una bola de nieve a Cairne Pezuña de Sangre en el festín del Festival de Invierno. ',

    AN_WINTERVEIL_PVP = 'Con un poco de ayuda de mis amigos',
    AD_WINTERVEIL_PVP = 'Consigue 50 muertes con honor como pequeño ayudante de la máquina del Maravoltio Invernal.',

    --VALENTINES
    AN_VALENTINES = 'Loco de amor',
	AD_VALENTINES = 'Completa los logros de Amor en el aire listados a continuación.',
	AR_VALENTINES = 'el Loco de amor',

    AN_VALENTINES_ROSES = 'Mi amor es como una rosa roja',
    AD_VALENTINES_ROSES = 'Consigue un ramo de rosas rojas o un ramo de rosas de ébano durante la celebración del Amor en el aire.',

    AN_VALENTINES_QUEST = 'Amor peligroso',
    AD_VALENTINES_QUEST = 'Ayuda al Cártel Bonvapor a detener el complot de la siniestra empresa Químicos La Corona, S.L..',

    AN_VALENTINES_CHOCOLATES = 'Goloso',
    AD_VALENTINES_CHOCOLATES = 'Prueba las golosinas del Amor en el aire listadas a continuación.',
    AC_VALENTINES_CHOCOLATES_CRITERIA1 = 'Deseo oscuro',
    AC_VALENTINES_CHOCOLATES_CRITERIA2 = 'Delicia de leche',
    AC_VALENTINES_CHOCOLATES_CRITERIA3 = 'Dulce sorpresa',
    AC_VALENTINES_CHOCOLATES_CRITERIA4 = 'Crema de frutos cremosa',

    AN_VALENTINES_DRESS = 'La preciosa suerte está de tu lado',
    AD_VALENTINES_DRESS = 'Abre una caja de vestido precioso y recibe un vestido negro precioso.',

    AN_VALENTINES_PIDO = 'Pies Rápidos permanentes',
    AD_VALENTINES_PIDO = 'Consigue una mascota Pies Rápidos permanente obteniendo una flecha con astil de veraplata.',

	--TBC
    AN_QUESTS_HELLFIRE_PENINSULA = 'Ida a Fuego Infernal y vuelta',
    AD_QUESTS_HELLFIRE_PENINSULA = 'Completa las siguientes tramas de la Península del Fuego Infernal.',
    TBC_QUEST_10388 = 'Interrumpe a la Legión Ardiente',
    TBC_QUEST_10389 = 'Crueles intenciones',
    TBC_QUEST_10876 = 'La Mano de Kargath',
    TBC_QUEST_10258 = 'Avanzada Rompeloma',
    TBC_QUEST_9406 = 'Los Mag\'har',
    TBC_QUEST_9370 = 'Avanzada del Halcón',
    TBC_QUEST_10351 = 'Puesto Cenarion',

    TBC_QUEST_10397 = 'Interrumpe a la Legión Ardiente',
    TBC_QUEST_10400 = 'Derroca al Señor supremo',
    TBC_QUEST_9545 = 'En busca de Sedai',
    TBC_QUEST_10935 = 'El exorcismo del coronel Jules',
    TBC_QUEST_10937 = 'Acaba con el maestro de maniobras',
    TBC_QUEST_9383 = 'Templo de Telhamat',
    TBC_QUEST_10630 = 'Verdes, pero orcos no',
    
    AN_QUESTS_ZANGARMASH = 'Misterios de la Marisma',
    AD_QUESTS_ZANGARMASH = 'Completa las siguientes tramas de la Marisma de Zangar.',
    TBC_QUEST_9772 = 'Avanzada Rata del Pantano',
    TBC_QUEST_9904 = 'Zabra\'jin',
    TBC_QUEST_10118 = 'La defensa de Zabra\'jin',
    TBC_QUEST_9803 = 'Diplomacia draenei',
    TBC_QUEST_9783 = 'Telredor',
    TBC_QUEST_9902 = 'Puerto Orebor',
    TBC_QUEST_9709 = '¡No comas ESOS champiñones!',
    TBC_QUEST_9732 = 'Drenar el marjal',
    TBC_QUEST_9788 = 'Salvemos a los esporotes',
    TBC_QUEST_9726 = 'Un viaje con los esporinos',
    
    AN_QUESTS_TERROKAR = 'Terror de Terokkar',
    AD_QUESTS_TERROKAR = 'Completa las siguientes tramas del Bosque de Terokkar.',
    TBC_QUEST_10879 = 'La ofensiva de Skettis',
    TBC_QUEST_10881 = '	Caravana de Refugiados',
    TBC_QUEST_10915 = 'Campamento Sha\'tari',
    TBC_QUEST_9951 = 'El secreto del celador',
    TBC_QUEST_10042 = 'Bastión Allerian',
    TBC_QUEST_10043 = 'Bastión Rompepedras',
    
    AN_QUESTS_NAGRAND = 'Embate de Nagrand',
    AD_QUESTS_NAGRAND = 'Completa las siguientes tramas de Nagrand.',
    TBC_QUEST_10172 = 'Nacimiento de un Jefe de Guerra',
    TBC_QUEST_9977 = 'El Círculo de Sangre',
    TBC_QUEST_9853 = 'El Trono de los Elementos',
    TBC_QUEST_9934 = 'Lantresor del Filo',
    TBC_QUEST_9868 = 'Los Sangreoscura',
    TBC_QUEST_9937 = 'Amenazas para Nagrand',
    TBC_QUEST_9852 = 'El deporte sangriento definitivo',
    TBC_QUEST_9925 = 'Encuentro con los etéreos',
    TBC_QUEST_9955 = 'Las aventuras de Corki',
    TBC_QUEST_9933 = 'Lantresor del Filo',
    TBC_QUEST_9873 = 'Los Sangreoscura',
    TBC_QUEST_10011 = 'Amenazas para Nagrand',
    
    AN_QUESTS_BLADES_EDGE_MTNS = 'Sobre el filo de la espada',
    AD_QUESTS_BLADES_EDGE_MTNS = 'Completa las siguientes tramas de las Montañas Filospada.',
    TBC_QUEST_10504 = 'Sylvanaar',
    TBC_QUEST_10671 = 'Estación de Toshley',
    TBC_QUEST_10806 = 'La amenaza gronn',
    TBC_QUEST_10505 = 'Bastión Señor del Trueno',
    TBC_QUEST_10742 = 'Reunión',
    TBC_QUEST_10867 = 'Los Mok\'Nathal',
    TBC_QUEST_10748 = 'La Foresta Ruuan',
    
    AN_QUESTS_NETHERSTORM = 'A la tormenta',
    AD_QUESTS_NETHERSTORM = 'Completa las siguientes tramas de Tormenta Abisal.',
    TBC_QUEST_10409 = 'Socrethar',
    TBC_QUEST_10240 = 'Torre Violeta',
    TBC_QUEST_10249 = '¡Protege el Área 52!',
    TBC_QUEST_10439 = 'Acabar con el Devoratodo',
    TBC_QUEST_10221 = 'Construir el cohete abisal X-52',
    TBC_QUEST_10276 = 'El Consorcio',
    
    AN_QUESTS_SHADOWMOON = 'Sombra de El Traidor',
    AD_QUESTS_SHADOWMOON = 'Completa las siguientes tramas del Valle Sombraluna.',
    TBC_QUEST_10744 = 'Noticias victoriosas',
    TBC_QUEST_11041 = 'Arrecife del Ala Abisal',
    TBC_QUEST_10645 = 'El primer caballero de la Muerte',
    TBC_QUEST_10651 = 'Poder prestado',
    TBC_QUEST_11052 = 'La promesa de Akama',
    TBC_QUEST_10588 = 'La Clave de Condenación',
    TBC_QUEST_10679 = 'Armas antidemonios',
    TBC_QUEST_10808 = 'El cónclave oscuro',
	
	AN_HEMET_QUESTS_NAGRAND = 'Montes como elekk blancos',
	AD_HEMET_QUESTS_NAGRAND = 'Completa todas las misiones de Hemet Nesingwary en Nagrand hasta El deporte sangriento definitivo incluida.',

    HEROIC_NAME_PATTERN = 'Heroico: %s',
    HEROIC_DESCRIPTION_PATTERN = '%s en Dificultad Heroica',

    AN_HELLFIRE_RAMPARTS = 'Murallas del Fuego Infernal',
    AD_HELLFIRE_RAMPARTS = 'Derrota a los líderes de las Murallas del Fuego Infernal',
    AC_BOSS_17308 = 'Omor el Sinmarcas',
    AC_BOSS_17537 = 'Nazan y Vazruden',
	AC_BOSS_17306 = 'Guardián vigía Gargolmar',

    AN_BLOOD_FURNACE = 'El Horno de Sangre',
    AD_BLOOD_FURNACE = 'Derrota a Keli\'dan el Ultrajador.',

    AN_SLAVE_PENS = 'Recinto de los Esclavos',
    AD_SLAVE_PENS = 'Derrota a Quagmirran',

    AN_UNDERBOG = 'La Sotiénaga',
    AD_UNDERBOG = 'Derrota a la Acechadora Negra',

    AN_MANA_TOMBS = 'Tumbas de Maná',
    AD_MANA_TOMBS = 'Derrota al príncipe-nexo Shaffar',

    AN_AUCHENAI_CRYPTS = 'Criptas Auchenai',
    AD_AUCHENAI_CRYPTS = 'Derrota al exarca Maladaar',

    AN_OLD_HILLSBRAD = 'La Fuga de Durnholde',
    AD_OLD_HILLSBRAD = 'Derrota al cazador de Época',

    AN_SETHEKK_HALLS = 'Salas Sethekk',
    AD_SETHEKK_HALLS = 'Derrota al Rey Garra Ikiss',

    AN_STEAMVAULT = 'La Cámara de Vapor',
    AD_STEAMVAULT = 'Derrota al señor de la guerra Kalithresh',

    AN_SHADOW_LABYRINTH = 'Laberinto de las Sombras',
    AD_SHADOW_LABYRINTH = 'Derrota a Murmullo',

    AN_SHATTERED_HALLS = 'Las Salas Arrasadas',
    AD_SHATTERED_HALLS = 'Derrota al Jefe de Guerra Kargath Garrafilada',

    AN_BLACK_MORASS = 'Apertura del Portal Oscuro',
    AD_BLACK_MORASS = 'Derrota a Aeonus',

    AN_BOTANICA = 'El Invernáculo',
    AD_BOTANICA = 'Derrota al disidente de distorsión',

    AN_MECHANAR = 'El Mechanar',
    AD_MECHANAR = 'Derrota a Pathaleon el Calculador',

    AN_ARCATRAZ = 'El Arcatraz',
    AD_ARCATRAZ = 'Derrota al presagista Cieloriss',
	
	AN_MAGISTERS_TERRACE = 'Bancal del Magister',
    AD_MAGISTERS_TERRACE = 'Derrota a Kael\'thas Caminante del Sol',
	
	AN_TBC_DUNGEONS = 'Maestro de mazmorras de Terrallende',
    AD_TBC_DUNGEONS = 'Completa los logros de mazmorra de The Burning Crusade listados a continuación.',

    AN_TBC_DUNGEONS_HERO = 'Héroe de mazmorra de Terrallende',
    AD_TBC_DUNGEONS_HERO = 'Completa los logros de mazmorra heroica de The Burning Crusade listados a continuación.',

    AN_RAVEN_LORD = 'Riendas del lord Cuervo',
    AD_RAVEN_LORD = 'Consigue las riendas del lord Cuervo de Anzu en las Salas Sethekk.',

    AN_KARAZHAN = 'Karazhan',
    AD_KARAZHAN = 'Derrota al príncipe Malchezaar en Karazhan.',

    AN_GRUUL = 'Guarida de Gruul',
    AD_GRUUL = 'Derrota a Gruul el Asesino de Dragones en la Guarida de Gruul.',

    AN_MAGTHERIDON = 'Guarida de Magtheridon',
    AD_MAGTHERIDON = 'Derrota a Magtheridon en la Guarida de Magtheridon.',
	
	AN_ZULAMAN = 'Zul\'Aman',
	AD_ZULAMAN = 'Derrota a Zul\'jin en Zul\'Aman.',
	
	AN_SUNWELL = 'Meseta de La Fuente del Sol',
	AD_SUNWELL = 'Derrota a Kil\'jaeden en la Meseta de La Fuente del Sol.',

    AN_TBC_PHASE_1 = 'Asaltante de Terrallende - Fase 1',
    AD_TBC_PHASE_1 = 'Completa los logros de banda de Burning Crusade que se enumeran a continuación.',
    AN_TBC_PHASE_2 = 'Asaltante de Terrallende - Fase 2',
    AD_TBC_PHASE_2 = 'Completa los logros de banda de Burning Crusade que se enumeran a continuación.',
    AN_TBC_PHASE_3 = 'Asaltante de Terrallende - Fase 3',
    AD_TBC_PHASE_3 = 'Completa los logros de banda de Burning Crusade que se enumeran a continuación.',
	AN_TBC_PHASE_4 = 'Asaltante de Terrallende - Fase 4',
    AD_TBC_PHASE_4 = 'Completa los logros de banda de Burning Crusade que se enumeran a continuación.',
	AN_TBC_PHASE_5 = 'Asaltante de Terrallende - Fase 5',
    AD_TBC_PHASE_5 = 'Completa los logros de banda de Burning Crusade que se enumeran a continuación.',

    FACTION_946 = 'Bastión del Honor',
    FACTION_947 = 'Thrallmar',
    FACTION_942 = 'Expedición Cenarion',
    FACTION_1011 = 'Bajo Arrabal',
    FACTION_989 = 'Vigilantes del Tiempo',
    FACTION_935 = 'Los Sha\'tar',
    FACTION_609 = 'Círculo Cenarion',

    AN_TBC_DUNGEON_REPUTATIONS = 'El cruzado ardiente',
    AD_TBC_DUNGEON_REPUTATIONS = 'Eleva todas las reputaciones de mazmorras de The Burning Crusade a Exaltado.',
	
	AN_CENARION_CIRCLE = 'Guardián de Cenarius',
    AD_CENARION_CIRCLE = 'Alcanza la reputación Exaltado con el Círculo Cenarion y la Expedición Cenarion.',

    AN_SHATTRATH_REP = 'Shattrath dividida',
    AD_SHATTRATH_REP = 'Alcanza la reputación Exaltado con los Arúspices o los Aldor.',

    AN_OGRILA = 'Una misión al día llena a los ogros de alegría',
    AD_OGRILA = 'Alcanza la reputación Exaltado con Ogri\'la.',

    AN_SPOREGGAR = 'El zar de Esporaggar',
    AD_SPOREGGAR = 'EAlcanza la reputación Exaltado con Esporaggar.',

    AN_CONSORTIUM = 'Oficial jefe Exaltado',
    AD_CONSORTIUM = 'Alcanza la reputación Exaltado con El Consorcio.',

    AN_MAGHAR = 'Mag\'har de Draenor',
    AD_MAGHAR = 'Alcanza la reputación Exaltado con los Mag\'har.',

    AN_KURENAI = 'Qué guay, Kurenai',
    AD_KURENAI = 'Alcanza la reputación Exaltado con los Kurenai.',

    AN_NETHERWINGS = 'Sobre alas abisales',
    AD_NETHERWINGS = 'Alcanza la reputación Exaltado con el Ala Abisal.',

    AN_SKYSHATTERED = 'Devastado',
    AD_SKYSHATTERED = 'Derrota al capitán Devastador del Cielo en la carrera de Faucedracos del Arrecife del Ala Abisal.',

    AN_AMETHYST_EYE = 'El Ojo Violeta',
    AD_AMETHYST_EYE = 'Alcanza la reputación Exaltado con El Ojo Violeta.',

    AN_SCALE_OF_THE_SANDS = 'La Escama de las Arenas',
    AD_SCALE_OF_THE_SANDS = 'Alcanza la reputación Exaltado con La Escama de las Arenas.',

    AN_ASHTONGUE_DEATHSWORN = 'Pleitesía para los Juramorte',
    AD_ASHTONGUE_DEATHSWORN = 'Alcanza la reputación Exaltado con los Juramorte Lengua de Ceniza.',

    AN_SHATTERED_SUN = 'Resultas muy ofensivo',
    AD_SHATTERED_SUN = 'Alcanza la reputación Exaltado con la Ofensiva Sol Devastado.',

    AN_SKYGUARD = 'Sobrevolando Skettis',
    AD_SKYGUARD = 'Alcanza la reputación Exaltado con la Guardia del cielo Sha'tari.',

    AN_HIPPOGRYPH = 'Hipogrifo de guerra Cenarion',
    AD_HIPPOGRYPH = 'Consigue un hipogrifo de guerra Cenarion de la Expedición Cenarion en las Marismas de Zangar.',

    AN_DIPLOMAT = 'El diplomático',
    AD_DIPLOMAT_ALLIANCE = 'Eleva tu nivel de reputación desde Adverso a Exaltado con el Bastión Fauces de Madera, Esporaggar y los Kurenai.',
    AD_DIPLOMAT_HORDE = 'Eleva tu nivel de reputación desde Adverso a Exaltado con el Bastión Fauces de Madera, Esporaggar y los Mag\'har.',
    AC_DIPLOMAT_576 = 'Exaltado con el Bastión Fauces de Madera',
    AC_DIPLOMAT_970 = 'Exaltado con Esporaggar',
    AC_DIPLOMAT_978 = '	Exaltado con los Kurenai',
    AC_DIPLOMAT_941 = 'Exaltado con los Mag\'har',

    AN_MR_PINCHY = 'Tenacitas',
    AD_MR_PINCHY = 'Pesca a Tenacitas en Terrallende.',

    AN_FISHING_BOOK = 'Los peces no dejan huellas',
    AD_FISHING_BOOK = 'Aprende la facultad de buscar pescado.',

    AN_ACCOMPLISHED_ANGLER = 'El mejor pescador',
    AD_ACCOMPLISHED_ANGLER = 'Completa los logros de pesca listados a continuación.',

    AN_TBC_DAILY_FISH = 'Superar al Viejo Barlo',
    AD_TBC_DAILY_FISH = 'Completa las 5 misiones diarias de pesca del viejo Barlo listadas a continuación.',
    AC_TBC_DAILY_FISH1 = 'Crocoliscos en la ciudad',
    AC_TBC_DAILY_FISH2 = 'Pilluelos de cebo',
    AC_TBC_DAILY_FISH3 = 'Filete de sangrevil',
    AC_TBC_DAILY_FISH4 = 'Aquel que se escapó',
    AC_TBC_DAILY_FISH5 = 'No es fácil pescar gambas',

    AN_OLD_IRONJAW = 'El viejo Quijahierro',
    AD_OLD_IRONJAW = 'Pesca al viejo Quijahierro en Forjaz.',

    AN_OLD_CRAFTY = 'El viejo Astuto',
    AD_OLD_CRAFTY = 'Pesca al viejo Astuto en Orgrimmar.',

    AN_FISHING_DIPLOMAT = 'El diplomático pescador',
    AD_FISHING_DIPLOMAT = 'Pesca algo en Orgrimmar y Ventormenta.',
    AC_FISHING_DIPLOMAT1 = 'Orgrimmar',
    AC_FISHING_DIPLOMAT2 = 'Ventormenta',

    AN_CAPTAIN_RUMSEY = 'Cerveza del capitán Rumsey',
    AD_CAPTAIN_RUMSEY = 'Prepara un poco de cerveza del capitán Rumsey.',

    AN_TBC_DAILY_COOKING = '¡Dale caña!',
    AD_TBC_DAILY_COOKING = 'Completa las 4 misiones diarias de cocina de El Rokk listadas a continuación.',
    AC_TBC_DAILY_COOKING1 = 'Manalicioso',
    AC_TBC_DAILY_COOKING2 = 'Sopa para el alma',
    AC_TBC_DAILY_COOKING3 = 'La venganza es sabrosa',
    AC_TBC_DAILY_COOKING4 = 'Un estofado superpicante',

    AN_TBC_COOKING_RECIPES = 'El gourmet de Terrallende',
    AD_TBC_COOKING_RECIPES = 'Cocina todas las recetas de Terrallende listadas a continuación.',

    AN_HAIL_CHEF = 'Felicita al cocinero',
    AD_HAIL_CHEF = 'Completa los logros de cocina listados a continuación.',

    AN_EXPLORE_OUTLAND = 'Explorador de Terrallende',
    AD_EXPLORE_OUTLAND = 'Explora las regiones de Terrallende.',

    AN_MIDDLE_RARE = 'Bastante exótica',
    AD_MIDDLE_RARE = 'Mata a una de las criaturas extremadamente exóticas y difíciles de encontrar de Terrallende listadas a continuación.',
    AN_BLOODY_RARE = 'Sangrientamente exóticas',
    AD_BLOODY_RARE = 'Mata a todas las criaturas extremadamente exóticas y difíciles de encontrar de Terrallende listadas a continuación.',
    TBC_NPC_18695 = 'Embajador Jerrikar',
    TBC_NPC_18682 = 'Rondador de ciénaga',
    TBC_NPC_18697 = 'Ingeniero jefe Lorthander',
    TBC_NPC_18681 = 'Emisaria Colmillo Torcido',
    TBC_NPC_18694 = 'Collidus el Vigía',
    TBC_NPC_18689 = 'Lisiador',
    TBC_NPC_18686 = 'Orador del Sino Jurim',
    TBC_NPC_18698 = 'Núcleo eterno el Castigador',
    TBC_NPC_18678 = 'Atiborrador',
    TBC_NPC_17144 = 'Dientegore',
    TBC_NPC_18692 = 'Hemathion',
    TBC_NPC_18696 = 'Kraator',
    TBC_NPC_18680 = 'Marticar',
    TBC_NPC_18677 = 'Mekthorg el Salvaje',
    TBC_NPC_18690 = 'Morchaca',
    TBC_NPC_20932 = 'Nuramoc',
    TBC_NPC_18685 = 'Okrek',
    TBC_NPC_18693 = 'Portavoz Mar\'grom',
    TBC_NPC_18683 = 'Cazador del Vacío Yar',
    TBC_NPC_18679 = 'Vorakem Augurador',

    AN_PREPATCH_QUEST = 'En la brecha',
    AD_PREPATCH_QUEST = 'Participante en la Batalla por el Portal Oscuro. Portador del Tabardo del Protector.',

    AN_RIDING_75 = '¡Arre!',
    AD_RIDING_75 = 'Aprende la habilidad Aprendiz jinete.',
    AN_RIDING_150 = 'A todo gas',
    AD_RIDING_150 = 'Aprende la habilidad Oficial jinete.',
    AN_RIDING_225 = 'Hacia la azul y salvaje lejanía',
    AD_RIDING_225 = 'Aprende la habilidad Experto jinete.',
    AN_RIDING_300 = 'Elegido para la gloria',
    AD_RIDING_300 = 'Aprende la habilidad Artesano jinete.',

    AN_ATTUNE_SHATTERED_HALLS = 'Más caliente que el infierno',
    AD_ATTUNE_SHATTERED_HALLS = 'Obtén la Llave de Las Salas Arrasadas.',
    AN_ATTUNE_ARCATRAZ = 'Cómo infiltrarse en El Arcatraz',
    AD_ATTUNE_ARCATRAZ = 'Obtén la Llave de El Arcatraz.',
    AN_ATTUNE_KARAZHAN = 'El toque del maestro',
    AD_ATTUNE_KARAZHAN = 'Obtén La llave del maestro.',
    AN_ATTUNE_NIGHT_BANE = 'Resucitar el pasado',
    AD_ATTUNE_NIGHT_BANE = 'Obtén la Urna ennegrecida.',
    AN_ATTUNE_SSC = 'La cayada de Kar\'desh',
    AD_ATTUNE_SSC = 'Obtén acceso a la Caverna Santuario Serpiente.',
    AN_ATTUNE_EYE = 'La llave de la tempestad',
    AD_ATTUNE_EYE = 'Obtén La llave de la tempestad.',
    AN_ATTUNE_HYJAL = 'Los viales de la eternidad',
    AD_ATTUNE_HYJAL = 'Obtén acceso a Batalla de El Monte Hyjal.',
    AN_ATTUNE_BLACK_TEMPLE = 'Una distracción para Akama',
    AD_ATTUNE_BLACK_TEMPLE = 'Obtén el Medallón de Karabor.',

    AN_SSC = 'Caverna Santuario Serpiente',
    AD_SSC = 'Derrota a los jefes que se enumeran a continuación dentro de la Caverna Santuario Serpiente.',
    AC_KILL_HYDROS = 'Hydross el Inestable ',
    AC_KILL_LURKER = 'El Rondador de abajo',
    AC_KILL_LEOTHERAS = 'Leotheras el Ciego',
    AC_KILL_KARATHRESS = 'Señor de las profundidades Karathress',
    AC_KILL_MOROGRIM = 'Morogrim Levantamareas',
    AC_KILL_VASHJ = 'Lady Vashj',
    AN_TK = 'El Castillo de la Tempestad',
    AD_TK = 'DDerrota a los jefes que se enumeran a continuación dentro de El Castillo de la Tempestad.',
    AC_KILL_ALAR = 'Al\'ar',
    AC_KILL_VOID_REAVER = 'Atracador del Vacío',
    AC_KILL_SOLARIAN = 'Gran astromante Solarian',
    AC_KILL_KAELTHAS = 'Kael\'thas Caminante del Sol',

    AN_HYJAL = 'La Batalla del Monte Hyjal',
    AD_HYJAL = 'Derrota a Archimonde en la Batalla del Monte Hyjal.',

    AN_BT_ENTRANCE = 'Infiltración',
    AD_BT_ENTRANCE = 'Adéntrate en el Templo Oscuro a través de las Alcantarillas de Karabor derrotando a los jefes que se enumeran a continuación.',
    AC_KILL_NAJENTUS = 'Gran señor de la guerra Naj\'entus',
    AC_KILL_SUPREMUS = 'Supremus',

    AN_BT_SECOND_WING = 'Acólito de Karabor',
    AD_BT_SECOND_WING = 'Purifica los salones principales del Templo Oscuro del mal que se ha instalado en ellos derrotando a los jefes que se enumeran a continuación.',
    AC_KILL_SHADOW_OF_AKAMA = 'Sombra de Akama',
    AC_KILL_THERON = 'Teron Sanguino',
    AC_KILL_GURTOGG = 'Gurtogg Sangre Hirviente',
    AC_KILL_RELIQUARY = 'Relicario de Almas',

    AN_BT_LAST_WING = 'Cima del templo',
    AD_BT_LAST_WING = 'Infiltrate en los pisos superiores del Templo Oscuro y derrota a los jefes que se enumeran a continuación.',
    AC_KILL_MOTHER_SHAHRAZ = 'Madre Shahraz',
    AC_KILL_BT_COUNCIL = 'El Consejo Illidari',
    AC_KILL_ILLIDAN = 'Illidan Tempestira',

    AN_BLACK_TEMPLE = 'El Templo Oscuro',
    AD_BLACK_TEMPLE = 'Consigue los logros que se enumeran a continuación derrotando a todos los jefes del Templo Oscuro.',
    AR_BLACK_TEMPLE = 'Conquistador del Templo Oscuro',

    AN_ARENA_FIRST_WIN = 'Entra en la arena',
    AD_ARENA_FIRST_WIN = 'Gana una partida clasificatoria en la arena en el nivel 70.',
    AN_ARENA_WIN1 = 'Despiadadamente entregado',
    AD_ARENA_WIN1 = 'Gana 100 combates clasificatorios en la arena en el nivel 70.',
    AN_ARENA_WIN2 = 'Vengativamente entregado',
    AD_ARENA_WIN2 = 'Gana 200 combates clasificatorios en la arena en el nivel 70.',
    AN_ARENA_WIN3 = 'Brutalmente entregado',
    AD_ARENA_WIN3 = 'Gana 200 combates clasificatorios en la arena en el nivel 70.',

    AN_ARENA_TITLE1 = 'Gladiador',
    AN_ARENA_TITLE2 = 'Duelista',
    AN_ARENA_TITLE3 = 'Rival',
    AN_ARENA_TITLE4 = 'Contendiente',

    AN_ARENA_GLADIATOR = 'Gladiador',
    AD_ARENA_GLADIATOR = 'Consigue el título de Gladiador en una temporada de arena en el nivel 70.',
    AN_ARENA_DUELIST = 'Duelista',
    AD_ARENA_DUELIST = 'Consigue el título de Duelista en una temporada de arena en el nivel 70.',
    AN_ARENA_RIVAL = 'Rival',
    AD_ARENA_RIVAL = 'Consigue el título de Rival en una temporada de arena en el nivel 70.',
    AN_ARENA_CHALLENGER = 'Contendiente',
    AD_ARENA_CHALLENGER = 'Consigue el título de Contendiente en una temporada de arena en el nivel 70.',

    AN_ARENA_2_1550 = 'Entre tú y yo: 1550',
    AD_ARENA_2_1550 = 'Consigue un índice personal de 1550 en la rama de la arena 2c2 en el nivel 70.',
    AN_ARENA_2_1750 = 'Entre tú y yo: 1750',
    AD_ARENA_2_1750 = 'Consigue un índice personal de 1750 en la rama de la arena 2c2 en el nivel 70.',
    AN_ARENA_2_2000 = 'Entre tú y yo: 2000',
    AD_ARENA_2_2000 = 'Consigue un índice personal de 2000 en la rama de la arena 2c2 en el nivel 70.',
    AN_ARENA_2_2200 = 'Entre tú y yo: 2200',
    AD_ARENA_2_2200 = 'Consigue un índice personal de 2200 en la rama de la arena 2c2 en el nivel 70.',

    AN_ARENA_3_1550 = 'Tres son multitud: 1550',
    AD_ARENA_3_1550 = 'Consigue un índice personal de 1550 en la rama de la arena 3c3 en el nivel 70..',
    AN_ARENA_3_1750 = 'Tres son multitud: 1750',
    AD_ARENA_3_1750 = 'Consigue un índice personal de 1750 en la rama de la arena 3c3 en el nivel 70.',
    AN_ARENA_3_2000 = 'Tres son multitud: 2000',
    AD_ARENA_3_2000 = 'Consigue un índice personal de 2000 en la rama de la arena 3c3 en el nivel 70.',
    AN_ARENA_3_2200 = 'Tres son multitud: 2200',
    AD_ARENA_3_2200 = 'Consigue un índice personal de 2200 en la rama de la arena 3c3 en el nivel 70.',

    AN_ARENA_5_1550 = 'Choca esos cinco: 1550',
    AD_ARENA_5_1550 = 'Consigue un índice personal de 1550 en la rama de la arena 5c5 en el nivel 70.',
    AN_ARENA_5_1750 = 'Choca esos cinco: 1750',
    AD_ARENA_5_1750 = 'Consigue un índice personal de 1750 en la rama de la arena 5c5 en el nivel 70.',
    AN_ARENA_5_2000 = 'Choca esos cinco: 2000',
    AD_ARENA_5_2000 = 'Consigue un índice personal de 2000 en la rama de la arena 5c5 en el nivel 70.',
    AN_ARENA_5_2200 = 'Choca esos cinco: 2200',
    AD_ARENA_5_2200 = 'Consigue un índice personal de 2200 en la rama de la arena 5c5 en el nivel 70.',

    AN_ARENA_STREAK = 'Buena racha',
    AD_ARENA_STREAK = 'Gana diez encuentros puntuados seguidos en el nivel 70.',

    AN_ARENA_HOTSTREAK = 'Una racha mejor',
    AD_ARENA_HOTSTREAK = 'Gana diez encuentros puntuados seguidos con un índice personal superior a 1800 en el nivel 70. ',

    AN_ARENA_LASTMAN = 'El último hombre en pie',
    AD_ARENA_LASTMAN = 'Sé el único superviviente al final de un encuentro puntuado de 5c5 en el nivel 70.',

    AN_ARENA_MAPS = 'Ganador mundial',
    AD_ARENA_MAPS = 'Gana un encuentro de arena puntuado en las Montañas Filospada, Nagrand, las Ruinas de Lordaeron en el nivel 70.',    
    AC_ARENA_MAPS1 = 'Arena de Filospada',
    AC_ARENA_MAPS2 = 'Arena de Nagrand',
    AC_ARENA_MAPS3 = 'Ruinas de Lordaeron',

    AN_ARENA_MASTER = 'El maestro de la arena',
    AD_ARENA_MASTER = 'Completa los logros de arena listados a continuación.',

    AN_AZZINOTH = 'Gujas de guerra de Azzinoth',
    AD_AZZINOTH = 'Portador de un conjunto de Gujas de guerra de Azzinoth.',
	AN_THORIDAL = 'Thori\'dal, la furia de las estrellas',
    AD_THORIDAL = 'Portador de Thori\'dal, la furia de las estrellas.',
    AC_OBTAIN_MAINHAND_AZZINOTH = 'Guja de guerra de Azzinoth derecha',
    AC_OBTAIN_OFFHAND_AZZINOTH = 'Guja de guerra de Azzinoth izquierda',
	AN_BEAR_MOUNT = 'Oso de guerra Amani',
    AD_BEAR_MOUNT = 'Poseedor del oso de guerra Amani.',
	AN_HAWK_MOUNT = 'Halcón zancudo blanco presto',
    AD_HAWK_MOUNT = 'Consigue el halcón zancudo blanco presto de Kael\'thas Caminante del Sol en el Bancal del Magister.',
	AN_ALAR_MOUNT = 'Cenizas de Al\'ar',
    AD_ALAR_MOUNT = 'Consigue las cenizas de Al\'ar de Kael\'thas Caminante del Sol en El Castillo de la Tempestad.',
	AN_HORSEMAN_MOUNT = 'Riendas del Jinete decapitado',
	AD_HORSEMAN_MOUNT = 'Consigue las Riendas del Jinete decapitado del Jinete decapitado en el Monasterio Escarlata durante Halloween.',
	AN_HERO_SHATTRATH = 'Héroe de Shattrath',
	AD_HERO_SHATTRATH = 'Alcanza la reputación Exaltado con los Arúspices y los Aldor.',
	AN_HERO_SCRYER = 'Los Arúspices',
	AN_HERO_ALDOR = 'Los Aldor',
	AN_CHAMPION_NAARU = 'Campeón de los naaru',
	AD_CHAMPION_NAARU = 'Recibido el título "Campeón de los naaru".',
	AR_CHAMPION_NAARU = 'Campeón de los naaru',
	AN_HAND_ADAL = 'Mano de A\'dal',
	AD_HAND_ADAL = 'Recibido el título "Mano de A\'dal".',
	AR_HAND_ADAL = 'Mano de A\'dal',

    AN_P3_FIRST_WEEK = 'Conquistador de Terrallende',
    AD_P3_FIRST_WEEK = 'Derrota a Archimonde e Illidan Tempestira en sus respectivas bandas durante la primera semana del lanzamiento de la Fase Tres.',
    AC_KILL_ARCHIMONDE = 'Archimonde',
    AR_P3_FIRST_WEEK = 'Conquistador de Terrallende',
	
	AN_FLIGHFORM = 'Forma de vuelo presto',
	AD_FLIGHFORM = 'Has completado la misión de druida para obtener la forma de vuelo presto.',

    AN_KRUUL = '...¡otro Señor de la fatalidad no!',
	AD_KRUUL = 'Derrota al Alto señor Kruul durante la Batalla por el Portal Oscuro.'
})