
if GetLocale() ~= 'ptBR' then return end
SexyLib:InitLocalization('Anniversary Achievements', {
	achievement_earned = '&aConquista obtida por %s em %d.%d.%d',
	achievement_in_progress = '&aConquista em andamento por %s',

	OPTION_SHARING = 'Compartilhar conquistas',
	OPTION_SHARING_DESC = 'Compartilhar novas conquistas no chat. Visível apenas para você.',
	OPTION_MICROBUTTON = 'Botão do micromenu',
	OPTION_MICROBUTTON_DESC = 'Se ativado, um botão do addon será adicionado ao micromenu, e a interface pode quebrar se você estiver usando algum addon para modificá-la. Se desativado, o ícone será adicionado ao minimapa.',
	OPTION_UPDATE_MAP_EXPLORATION = 'Verificar áreas exploradas',
	OPTION_UPDATE_MAP_EXPLORATION_DESC = 'Conta áreas já exploradas para conquistas.',
	OPTION_RESET_ACHIEVEMENTS = 'Redefinir conquistas',
	OPTION_RESET_ACHIEVEMENTS_DESC = 'Redefinir todo o progresso de conquistas neste personagem. Isso não pode ser desfeito!',
	OPTION_TRACKER = 'Rastrear Objetivos',
	OPTION_TRACKER_DESC = 'Ativar ou desativar o rastreador de conquistas e missões.',
	OPTION_RELOAD = 'As alterações exigem uma recarga da interface',
	OPTION_DISABLED = 'Opção desativada devido a addons de UI carregados',

	GOT_ACHIEVEMENT_MESSAGE_MALE = 'Você obteve a conquista %s!',
	GOT_ACHIEVEMENT_MESSAGE_FEMALE = 'Você obteve a conquista %s!',

	UPDATING_EXPLORED_AREAS = 'Atualizando dados de exploração de áreas. Esta ação levará alguns segundos.',
	UPDATED_EXPLORED_AREAS = '&aAs informações sobre áreas exploradas foram atualizadas!',

	UI_COMBAT_ERROR = 'Anniversary Achievements não pode ser aberto durante combate!',

	GEAR_SLOT_HEAD = 'Cabeça',
	GEAR_SLOT_NECK = 'Pescoço',
	GEAR_SLOT_SHOULDER = 'Ombro',
	GEAR_SLOT_CHEST = 'Peito',
	GEAR_SLOT_WAIST = 'Cintura',
	GEAR_SLOT_LEGS = 'Pernas',
	GEAR_SLOT_FEET = 'Pés',
	GEAR_SLOT_WRIST = 'Pulsos',
	GEAR_SLOT_HANDS = 'Mãos',
	GEAR_SLOT_FIRST_RING = 'Anel Direito',
	GEAR_SLOT_SECOND_RING = 'Anel Esquerdo',
	GEAR_SLOT_FIRST_TRINKET = 'Primeiro Berloque',
	GEAR_SLOT_SECOND_TRINKET = 'Segundo Berloque',
	GEAR_SLOT_CLOAK = 'Capa',
	GEAR_SLOT_WEAPON = 'Arma',

	NPC_3444 = 'Rato Tocaieiro',
	NPC_620 = 'Galinha',
	NPC_1420 = 'Sapo',
	NPC_13321 = 'Rã',
	NPC_2620 = 'Cão da Pradaria',
	NPC_9600 = 'Papagaio',
	NPC_883 = 'Cervo',
	NPC_9699 = 'Besouro de Fogo',
	NPC_4953 = 'Naja',
	NPC_721 = 'Coelho',
	NPC_9700 = 'Caranguejo de Lava',
	NPC_15476 = 'Escorpião',
	NPC_2914 = 'Cobra',
	NPC_16030 = 'Larva',
	NPC_4075 = 'Rato',
	NPC_1412 = 'Esquilo',
	NPC_7390 = 'Calopsita',
	NPC_15475 = 'Besouro',
	NPC_15010 = 'Sapo da Selva',
	NPC_4076 = 'Barata',
	NPC_13016 = 'Rato de Corre Fundo',
	NPC_14881 = 'Aranha',
	NPC_2110 = 'Rato Negro',
	NPC_4166 = 'Gazela',
	NPC_1933 = 'Ovelha',
	NPC_890 = 'Filhote de Cervo',
	NPC_2098 = 'Carneiro',
	NPC_2442 = 'Vaca',
	NPC_6368 = 'Gato',
	NPC_6271 = 'Camundongo',
	NPC_385 = 'Cavalo',
	NPC_10685 = 'Porco',
	NPC_3300 = 'Víbora',
	NPC_15065 = 'Dama',
	NPC_15066 = 'Cleo',
	NPC_15071 = 'Patinha',
	NPC_15072 = 'Espinho',

	CATEGORY_GENERAL = 'Geral',
	CATEGORY_QUESTS = 'Missões',
	CATEGORY_PVP = 'Jogador vs. Jogador',
	CATEGORY_KALIMDOR = 'Kalimdor',
	CATEGORY_EASTERN_KINGDOMS = 'Reinos do Leste',
	CATEGORY_OUTLAND = 'Terralém',
	CATEGORY_VANILLA = 'Classic',
	CATEGORY_TBC = 'The Burning Crusade',
	CATEGORY_EXPLORATION = 'Exploração',
	CATEGORY_PVE = 'Masmorras e Raides',
	CATEGORY_ARENA = 'Arena',
	CATEGORY_BG_ALTERAC = 'Vale Alterac',
	CATEGORY_BG_WARSONG = 'Garganta Grito de Guerra',
	CATEGORY_BG_ARATHI = 'Bacia Arathi',
	CATEGORY_BG_EYE = 'Olho da Tempestade',
	CATEGORY_PROFESSIONS = 'Profissões',
	CATEGORY_REPUTATION = 'Reputação',
	CATEGORY_EVENTS = 'Eventos Mundiais',
	CATEGORY_VALENTINES = 'O Amor Está no Ar',
	CATEGORY_LUNAR = 'Festival Lunar',
	CATEGORY_NOBLEGARDEN = 'Jardim Nobre',
	CATEGORY_CHILDREN = 'Semana das Crianças',
	CATEGORY_MIDSUMMER = 'Solstício',
	CATEGORY_BREWFEST = 'Festança',
	CATEGORY_HALLOWSEND = 'Véspera das Bruxas',
	CATEGORY_WINTERVEIL = 'Inverno',
	CATEGORY_FEATS_OF_STRENGTH = 'Feitos de Força',
	
	AN_DRUID_T1 = 'Traje Cenariano',
	AN_WARLOCK_T1 = 'Traje Coração Maligno',
	AN_PRIEST_T1 = 'Vestimentas da Profecia',
	AN_MAGE_T1 = 'Regalia Arcanista',
	AN_ROGUE_T1 = 'Armadura do Canto Noturno',
	AN_HUNTER_T1 = 'Armadura do Perseguidor Gigante',
	AN_PALADIN_T1 = 'Armadura do Julgamento Divino',
	AN_WARRIOR_T1 = 'Armadura do Poderio',
	AN_SHAMAN_T1 = 'A Fúria da Terra',
	
	AN_DRUID_T2 = 'Traje de Tempesfúria',
	AN_WARLOCK_T2 = 'Traje da Nêmesis',
	AN_PRIEST_T2 = 'Vestimentas da Transcendência',
	AN_MAGE_T2 = 'Regalia do Vento Nexo',
	AN_ROGUE_T2 = 'Armadura do Pres Sangrenta',
	AN_HUNTER_T2 = 'Armadura do Perseguidor de Dragões',
	AN_PALADIN_T2 = 'Armadura do Julgamento',
	AN_WARRIOR_T2 = 'Armadura da Ira',
	AN_SHAMAN_T2 = 'As Dez Tempestades',

	AN_DRUID_T3 = 'Traje do Andarilho dos Sonhos',
	AN_WARLOCK_T3 = 'Traje do Coração Pestilento',
	AN_PRIEST_T3 = 'Vestimentas da Fé',
	AN_MAGE_T3 = 'Regalia do Gelo e Fogo',
	AN_ROGUE_T3 = 'Armadura da Lâminada Mortal',
	AN_HUNTER_T3 = 'Armadura do Perseguidor das Criptas',
	AN_PALADIN_T3 = 'Armadura da Redenção',
	AN_WARRIOR_T3 = 'Armadura do Pavor',
	AN_SHAMAN_T3 = 'A Racha-Terra',	
	
	AD_SET = 'Colete todos os itens do conjunto mencionado.',
	
	AN_SKELETON_KEY = 'A Chave de Scholomance',
	AD_SKELETON_KEY = 'Obtenha a Chave Esqueleto.',

	AN_LVL = 'Nível %d',
	AD_LVL = 'Alcance o nível %d.',

	AN_BANK = 'Depósito Seguro',
	AD_BANK = 'Compre 7 espaços adicionais no banco.',
	AC_BANK = 'Compre 7 espaços adicionais no banco.',

	AN_QUESTS = '%d Missões Concluídas',
	AD_QUESTS = 'Complete %d missões.',
	AC_QUESTS = 'Complete %d missões.',

	AN_DAILY_QUESTS = '%d Missões Diárias Concluídas',
	AD_DAILY_QUESTS = 'Complete %d missões diárias.',
	AC_DAILY_QUESTS = 'Complete %d missões diárias.',

	AN_QUEST_GOLD5 = 'Recompensa Cintilante',
	AN_QUEST_GOLD10 = 'Colecionador de Moedas Cunhadas',
	AN_QUEST_GOLD25 = 'Sustento da Família',
	AN_QUEST_GOLD50 = 'Ouro Bem Merescido',
	AN_QUEST_GOLD100 = 'Ganho com Suor e Sangue',
	AN_QUEST_GOLD250 = 'Impressora de Ouro',
	AN_QUEST_GOLD500 = 'Eu Sou o Próprio Ouro',
	AD_QUEST_GOLD = 'Ganhe %d de ouro em recompensas de missões.',
	AC_QUEST_GOLD = 'Ganhe %d de ouro em recompensas de missões.',

	AN_QUESTS_ZONE = 'Mestre das Lendas de %s',
	AD_QUESTS_ZONE = 'Complete a missão "%s" em %s.',
	AD_QUESTS_ZONE_MULTI = 'Complete as seguintes missões em %s.',
	AC_QUESTS_ZONE = 'Completou a missão "%s".',

	AZSHARA_1 = 'Azshara',
	AZSHARA_2 = 'Azshara',
	QUEST_3602 = 'Azsharita',

	FELWOOD_1 = 'Bruma Negra',
	FELWOOD_2 = 'Bruma Negra',
	QUEST_5165 = 'Apagando as Chamas da Proteção',
	QUEST_5385 = 'Os Restos de Trey Lightforge',

	DESOLACE_1 = 'Desolação',
	DESOLACE_2 = 'Desolação',
	QUEST_6027 = 'Livro dos Antigos',

	DUSTWALLOW_1 = 'Pântano Ventoempoeirado',
	DUSTWALLOW_2 = 'Pântano Ventoempoeirado',
	QUEST_1203 = 'Jarl Precisa de uma Lâmina',

	SILITHUS_1 = 'Silithus',
	SILITHUS_2 = 'Silithus',
	QUEST_8287 = 'Um Propósito Terrível',
	QUEST_8352 = 'Cetro do Conselho',
	QUEST_8321 = 'Vyral, o Perverso',
	QUEST_8281 = 'Reforçando a Segurança',

	DUROTAR_1 = 'Durotar',
	DUROTAR_2 = 'Durotar',
	QUEST_835 = 'Protegendo as Linhas',

	BARRENS_1 = 'As Esteras',
	BARRENS_2 = 'As Esteras',
	QUEST_888 = 'Pilhagem Roubada',
	QUEST_902 = 'Maquinário Samophlange',

	WINTERSPRING_1 = 'Helmgar',
	WINTERSPRING_2 = 'Helmgar',
	QUEST_975 = 'Cache de Mau\'ari',
	QUEST_5082 = 'Ameaça do Winterfall',
	QUEST_5121 = 'Grão-Chefe Winterfall',
	QUEST_5163 = 'Já Chegamos, Yeti?',
	QUEST_4842 = 'Fontes Estranhas',

	TANARIS_1 = 'Tanaris',
	TANARIS_2 = 'Tanaris',
	QUEST_2662 = 'Elixir Noggenfogger',
	QUEST_2874 = 'Entregar para MacKinley',
	QUEST_1691 = 'Mais Justiça aos Errantes',
	QUEST_113 = 'Análise de Peça de Inspeção',

	STONETALON_1 = 'Montanhas Pedra Coberta',
	STONETALON_2 = 'Montanhas Pedra Coberta',
	QUEST_1096 = 'Gerenzo Wrenchwhistle',

	UNGORO_1 = 'Cratera de Un\'Goro',
	UNGORO_2 = 'Cratera de Un\'Goro',
	QUEST_3962 = 'É Perigoso Ir Sozinho',
	QUEST_4245 = 'Rastreado de A-Me 01',
	QUEST_4292 = 'A Isca para Lar\'korwi',

	THOUSAND_NEEDLES_1 = 'Mil Agulhas',
	THOUSAND_NEEDLES_2 = 'Mil Agulhas',
	QUEST_1189 = 'Segurança em Primeiro Lugar',

	ARATHI_1 = 'Planalto de Arathi',
	ARATHI_2 = 'Planalto de Arathi',
	QUEST_652 = 'Quebrando a Pedra-Chave',

	BADLANDS_1 = 'Terras Inóspitas',
	BADLANDS_2 = 'Terras Inóspitas',
	QUEST_737 = 'Conhecimento Proibido',
	QUEST_778 = 'Isso Vai Ser Difícil',
	QUEST_656 = 'Invocando a Princesa',
	QUEST_793 = 'Alianças Quebradas',
	QUEST_717 = 'Tremores da Terra',
	
	EASTERN_PLAGUELANDS_1 = 'Terras Pestilentas Orientais',
	EASTERN_PLAGUELANDS_2 = 'Terras Pestilentas Orientais',
	QUEST_5942 = 'Tesouros Escondidos',
	QUEST_6148 = 'O Oráculo Escarlate, Demetria',
	QUEST_6187 = 'A Ordem Deve Ser Restaurada',
	QUEST_5265 = 'O Bastião Argentus',

	BLASTED_LANDS_1 = 'Terras Devastadas',
	BLASTED_LANDS_2 = 'Terras Devastadas',
	QUEST_3628 = 'Você é Rakh\'likh, Demônio',

	STRANGLETHORN_VALLEY_1 = 'Selva do Espinhaço',
	STRANGLETHORN_VALLEY_2 = 'Selva do Espinhaço',
	QUEST_208 = 'Grande Caçador',
	QUEST_600 = 'Mineração da Companhia Mercantil',
	QUEST_613 = 'Quebrando o Pé de Maury',
	QUEST_628 = 'Excelsior',
	QUEST_338 = 'As Colinas Verdes da Selva do Espinhaço',
	
	AN_NESINGWARY = 'As Colinas Verdes da Selva do Espinhaço',
	AD_NESINGWARY = 'Complete todas as missões de Hemet Nesingwary na Selva do Espinhaço, incluindo As Colinas Verdes da Selva do Espinhaço e Grande Caçador.',

	WESTERN_PLAGUELANDS_1 = 'Terras Pestilentas Ocidentais',
	WESTERN_PLAGUELANDS_2 = 'Terras Pestilentas Ocidentais',
	QUEST_5944 = 'Em Sonhos',
	QUEST_5051 = 'Duas Metades se Tornam Uma',
	QUEST_4985 = 'A Vida Selvagem Também Sofre',

	SEARING_GORGE_1 = 'Garganta Abrasadora',
	SEARING_GORGE_2 = 'Garganta Abrasadora',
	QUEST_3481 = 'Bugigangas...',

	BLACK_ROCK_1 = 'Montanha de Roccanevro',
	BLACK_ROCK_2 = 'Montanha de Roccanevro',
	QUEST_8996 = 'Retorno a Bodley',

	AN_WISDOM_KEEPER = 'O Mestre das Lendas',
	AD_WISDOM_KEEPER = 'Complete as conquistas de missões listadas abaixo.',
	AN_WISDOM_KEEPER_AZEROTH = 'Mestre das Lendas de Azeroth',
	AD_WISDOM_KEEPER_AZEROTH = 'Complete as conquistas de missões listadas abaixo.',
	AN_WISDOM_KEEPER_KALIMDOR = 'Mestre das Lendas de Kalimdor',
	AD_WISDOM_KEEPER_KALIMDOR = 'Complete as conquistas de missões de Kalimdor listadas abaixo.',
	AN_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Mestre das Lendas dos Reinos do Leste',
	AD_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Complete as conquistas de missões dos Reinos do Leste listadas abaixo.',
	AN_WISDOM_KEEPER_OUTLAND = 'Mestre das Lendas de Terralém',
	AD_WISDOM_KEEPER_OUTLAND = 'Complete as conquistas de missões de Terralém listadas abaixo.',
	AR_WISDOM_KEEPER = 'O Mestre das Lendas',

	AN_RAGEFIRE_CHASM = 'Fenda de Fogo',
	AD_RAGEFIRE_CHASM = 'Derrote Taragaman, o Esfaimado.',
	AN_WAILING_CAVERNS = 'Cavernas Uivantes',
	AD_WAILING_CAVERNS = 'Derrote Mutanus, o Devorador.',
	AN_DEAD_MINES = 'Minas da Morte',
	AD_DEAD_MINES = 'Derrote Edwin VanCleef.',
	AN_SHADOWFANG_KEEP = 'Fortaleza Sombria',
	AD_SHADOWFANG_KEEP = 'Derrote o Arquimago Arugal.',
	AN_BLACKFATHOM_DEEPS = 'Abismo Aquanegro',
	AD_BLACKFATHOM_DEEPS = 'Derrote Aku\'mai.',
	AN_JAIL = 'Masmorra de Ventobravo',
	AD_JAIL = 'Derrote Bazil Thredd.',
	AN_GNOMREGAN = 'Gnomeregan',
	AD_GNOMREGAN = 'Derrote o Mecângulo Thermaplugg.',
	AN_RAZORFEN_KRAUL = 'Urze do Pântano',
	AD_RAZORFEN_KRAUL = 'Derrote Charlga Lâmina de Pântano.',
	AN_SCARLET_MONASTERY = 'Monastério Escarlate',
	AD_SCARLET_MONASTERY = 'Derrote a Cruzada Escarlate dentro do Monastério Escarlate.',
	AC_SCARLET_MONASTERY1 = 'Mago de Sangue Thalnos',
	AC_SCARLET_MONASTERY2 = 'Arcanista Doan',
	AC_SCARLET_MONASTERY3 = 'Herod',
	AC_SCARLET_MONASTERY4 = 'Grã-Inquisidora Brancapé',
	AC_SCARLET_MONASTERY5 = 'Comandante Escarlate Mograine',
	
	AN_RAZORFEN_DOWNS = 'Colinas dos Pântanos',
	AD_RAZORFEN_DOWNS = 'Derrote Amnennar, o Trazgeada.',
	AN_ULDAMAN = 'Uldaman',
	AD_ULDAMAN = 'Derrote Archaedas.',
	AN_ZULFARRAK = 'Zul\'Farrak',
	AD_ZULFARRAK = 'Derrote o Chefe Ukorz Cabelera.',
	AN_MARAUDON = 'Maraudon',
	AD_MARAUDON = 'Derrote a Princesa Theradras.',
	AN_SUNKEN_TEMPLE = 'Templo Afundado',
	AD_SUNKEN_TEMPLE = 'Derrote o Espectro de Eranikus.',
	
	AN_NEW_EMPEROR = 'Profundezas de Roccanevro',
	AD_NEW_EMPEROR = 'Derrote o Imperador Dagran Thaurissan.',
	AN_BLACKROCK_DEPTHS = 'Limpando as Profundezas',
	AD_BLACKROCK_DEPTHS = 'Derrote os seguintes chefes nas Profundezas de Roccanevro.',
	AC_BLACKROCK_DEPTHS1 = 'Alto Interrogador Gerstahn morto',
	AC_BLACKROCK_DEPTHS2 = 'Mestre dos Cães Grebmar',
	AC_BLACKROCK_DEPTHS3 = 'General Forja-Ira',
	AC_BLACKROCK_DEPTHS4 = 'Senhor dos Golems Argelmach',
	AC_BLACKROCK_DEPTHS5 = 'Lorde Incêndio',
	AC_BLACKROCK_DEPTHS6 = 'Guarda Stilgiss',
	AC_BLACKROCK_DEPTHS7 = 'Bael\'Gar',
	AN_BLACKROCK_PARTY = 'Festa no Caneca de Cerveja',
	AD_BLACKROCK_PARTY = 'Derrote todos os oponentes listados no Caneca de Cerveja Sombrio.',
	AC_BLACKROCK_PARTY1 = 'Ribbly Parafusoredido',
	AC_BLACKROCK_PARTY2 = 'Plugger Spazzring',
	AC_BLACKROCK_PARTY3 = 'Hurley Bafo Negro',
	AC_BLACKROCK_PARTY4 = 'Phalanx',
	AN_BLACKROCK_DEPTHS_FULL = 'Mestre das Profundezas de Roccanevro',
	AD_BLACKROCK_DEPTHS_FULL = 'Obtenha as seguintes conquistas relacionadas às Profundezas de Roccanevro.',
	AN_ARMOR_SWORD = 'A Melhor Defesa É um Ataque',
	AD_ARMOR_SWORD = 'Derrote Panzor, o Invencível, nas Profundezas de Roccanevro.',
	
	AN_BLACKROCK_SPIRE_BOTTOM = 'Baixo Pico de Roccanevro',
	AD_BLACKROCK_SPIRE_BOTTOM = 'Derrote o Suserano Wyrmthalak.',
	AN_BLACKROCK_SPIRE_UPPER = 'Alto Pico de Roccanevro',
	AD_BLACKROCK_SPIRE_UPPER = 'Derrote o General Drakkisath.',
	AN_BLACKROCK_SPIRE = 'Invasor do Pico de Roccanevro',
	AD_BLACKROCK_SPIRE = 'Obtenha as seguintes conquistas relacionadas ao Pico de Roccanevro.',
	AN_DIRE_MAUL = 'Rei de Martelo Sinistro',
	AD_DIRE_MAUL = 'Derrote cada ala de Martelo Sinistro.',
	AC_DIRE_MAUL1 = 'Alzzin, o Modelador Selvagem',
	AC_DIRE_MAUL2 = 'Immol\'thar',
	AC_DIRE_MAUL3 = 'Rei Gordok',
	AN_STRATHOLME = 'Stratholme',
	AD_STRATHOLME = 'Derrote os gênios do mal que habitam Stratholme.',
	AC_STRATHOLME1 = 'Barão Rivendare',
	AC_STRATHOLME2 = 'Balnazzar',	
	AN_SCHOLOMANCE = 'Scholomance',
	AD_SCHOLOMANCE = 'Derrote os líderes de Scholomance.',
	AC_SCHOLOMANCE1 = 'Mestre Sombrio Gandling',
	AC_SCHOLOMANCE2 = 'Ras Sussurro Gélido',
	AN_YOUNG_DEFENDER = 'Jovem Defensor de Azeroth',
	AD_YOUNG_DEFENDER = 'Obtenha as conquistas de masmorras de nível baixo listadas abaixo.',
	AN_DEFENDER = 'Defensor de Azeroth',
	AD_DEFENDER = 'Obtenha as conquistas de masmorras listadas abaixo.',
	AR_DEFENDER = 'Defensor de Azeroth',

	AN_ONYXIA = 'Covil de Onyxia',
	AD_ONYXIA = 'Derrote Onyxia.',
	AN_AQ20 = 'Ruínas de Ahn\'Qiraj',
	AD_AQ20 = 'Derrote Ossirian, o Intacto.',
	AN_ZULGURUB = 'Zul\'Gurub',
	AD_ZULGURUB = 'Derrote Hakkar.',
	AN_RAGNAROS = 'Núcleo Derretido',
	AD_RAGNAROS = 'Derrote Ragnaros.',
	AN_BLACK_WING_LAIR = 'Covil Asanegra',
	AD_BLACK_WING_LAIR = 'Derrote Nefarian.',
	AN_AQ40 = 'Templo de Ahn\'Qiraj',
	AD_AQ40 = 'Derrote C\'Thun.',
	AN_NAXXRAMAS_SPIDERS = 'A Ala das Aracnídeos',
	AD_NAXXRAMAS_SPIDERS = 'Derrote os chefes da Ala dos Aracnídeos de Naxxramas.',
	AC_NAXXRAMAS_SPIDERS1 = 'Anub\'Rekhan',
	AC_NAXXRAMAS_SPIDERS2 = 'Grã-Viúva Faerlina',
	AC_NAXXRAMAS_SPIDERS3 = 'Maexxna',
	AN_NAXXRAMAS_PLAGUE = 'A Ala da Peste',
	AD_NAXXRAMAS_PLAGUE = 'Derrote os chefes da Ala da Peste de Naxxramas.',
	AC_NAXXRAMAS_PLAGUE1 = 'Noth, o Trazpraga',
	AC_NAXXRAMAS_PLAGUE2 = 'Heigan, o Impuro',
	AC_NAXXRAMAS_PLAGUE3 = 'Loatheb',    
	AN_NAXXRAMAS_MILITARY = 'A Ala Militar',
	AD_NAXXRAMAS_MILITARY = 'Derrote os chefes da Ala Militar de Naxxramas.',
	AC_NAXXRAMAS_MILITARY1 = 'Instrutor Razuvious',
	AC_NAXXRAMAS_MILITARY2 = 'Gothik, o Colhedor',
	AC_NAXXRAMAS_MILITARY3 = 'Os Quatro Cavaleiros',
	AN_NAXXRAMAS_CONSTRUCT = 'A Ala da Construção ',
	AD_NAXXRAMAS_CONSTRUCT = 'Derrote os chefes da Ala da Construção de Naxxramas.',
	AC_NAXXRAMAS_CONSTRUCT1 = 'Patchwerk',
	AC_NAXXRAMAS_CONSTRUCT2 = 'Grobbulus',
	AC_NAXXRAMAS_CONSTRUCT3 = 'Gluth',
	AC_NAXXRAMAS_CONSTRUCT4 = 'Thaddius',  
	AN_NAXXRAMAS_SAPPHIRON = 'Derrote Sapphiron.',
	AD_NAXXRAMAS_SAPPHIRON = 'Derrote Sapphiron em Naxxramas.',
	AN_NAXXRAMAS_LAIR = 'Derrota de Kel\'Thuzad',
	AD_NAXXRAMAS_LAIR = 'Derrote Kel\'Thuzad em Naxxramas.',
	AN_NAXXRAMAS = 'A Queda de Naxxramas',
	AD_NAXXRAMAS = 'Obtenha as seguintes conquistas relacionadas a Naxxramas.',
	AN_YOUNG_HERO = 'Jovem Herói de Azeroth',
	AD_YOUNG_HERO = 'Obtenha as conquistas de raides listadas abaixo.',
	AN_BLACKROCK_MASTER = 'Senhor do Roccanevro',
	AD_BLACKROCK_MASTER = 'Obtenha as seguintes conquistas relacionadas às masmorras e raides de Roccanevro.',
	AN_HERO = 'Herói de Azeroth',
	AD_HERO = 'Obtenha as conquistas de raides listadas abaixo.',
	AR_HERO = 'Herói de Azeroth',
	AN_GREAT_HERO = 'Grande Herói de Azeroth',
	AD_GREAT_HERO = 'Obtenha as conquistas de raides e masmorras listadas abaixo.',
	AR_GREAT_HERO = 'Grande Herói de Azeroth',

	AN_PVP_RANK_A1 = 'Soldado',
	AN_PVP_RANK_A2 = 'Cabo',
	AN_PVP_RANK_A3 = 'Sargento',
	AN_PVP_RANK_A4 = 'Mestre Sargento',
	AN_PVP_RANK_A5 = 'Sargento-Mor',
	AN_PVP_RANK_A6 = 'Cavaleiro',
	AN_PVP_RANK_A7 = 'Cavaleiro-Tenente',
	AN_PVP_RANK_A8 = 'Cavaleiro-Capitão',
	AN_PVP_RANK_A9 = 'Cavaleiro-Campeão',
	AN_PVP_RANK_A10 = 'Tenente-Comandante',
	AN_PVP_RANK_A11 = 'Comandante',
	AN_PVP_RANK_A12 = 'Marechal',
	AN_PVP_RANK_A13 = 'Marechal de Campo',
	AN_PVP_RANK_A14 = 'Grão-Marechal',
	AN_PVP_RANK_H1 = 'Batedor',
	AN_PVP_RANK_H2 = 'Bruto',
	AN_PVP_RANK_H3 = 'Sargento',
	AN_PVP_RANK_H4 = 'Sargento Sênior',
	AN_PVP_RANK_H5 = 'Primeiro-Sargento',
	AN_PVP_RANK_H6 = 'Guarda de Pedra',
	AN_PVP_RANK_H7 = 'Guarda de Sangue',
	AN_PVP_RANK_H8 = 'Legionário',
	AN_PVP_RANK_H9 = 'Centurião',
	AN_PVP_RANK_H10 = 'Campeão',
	AN_PVP_RANK_H11 = 'Tenente-General',
	AN_PVP_RANK_H12 = 'General',
	AN_PVP_RANK_H13 = 'Senhor da Guerra',
	AN_PVP_RANK_H14 = 'Alto Senhor da Guerra',
	AD_PVP_RANK = 'Obteve o título, "%s".',
	AN_PVP_FIRST_KILL = 'Uma Morte Honrosa',
	AD_PVP_FIRST_KILL = 'Conquiste uma morte honrosa.',
	AC_PVP_FIRST_KILL = 'Conquiste uma morte honrosa.',
	AN_PVP_KILLS = '%d Mortes Honrosas',
	AD_PVP_KILLS = 'Consiga %d mortes honrosas.',
	AC_PVP_KILLS = 'Consiga %d mortes honrosas',

	AN_MOB_KILLS_1 = 'Matador',
	AN_MOB_KILLS_2 = 'Destruidor',
	AN_MOB_KILLS_3 = 'Esmagador',
	AN_MOB_KILLS_4 = 'Caçador de Cabeças',
	AN_MOB_KILLS_5 = 'Tempestade dos Monstros',
	AN_MOB_KILLS_6 = 'Tempestade de Todas as Coisas Vivas',
	AN_MOB_KILLS_7 = 'Morte Onipresente',
	AD_MOB_KILLS = 'Mate %d monstros.',
	AC_MOB_KILLS = 'Mate %d monstros.',

	AN_REPS_1 = 'Alguém Me Quer Bem',
	AD_REPS_1 = 'Eleve uma reputação para Exaltado.',
	AC_REPS_1 = 'Elevou uma reputação para Exaltado.',
	AN_REPS_X = ' Reputações Exaltadas',
	AD_REPS = 'Eleve %d reputações para Exaltado.',
	AC_REPS = 'Elevou %d reputações para Exaltado.',
	AR_REPS = 'O Exaltado',

	AN_HORDE_REPS = 'Embaixador da Horda',
	AD_HORDE_REPS = 'Alcance reputação exaltado com 5 cidades-capital.',
	AC_HORDE_REPS_1 = 'Exaltado com Orgrimmar.',
	AC_HORDE_REPS_2 = 'Exaltado com a Tribo dos Senhores Neles.',
	AC_HORDE_REPS_3 = 'Exaltado com a Cidade Baixa.',
	AC_HORDE_REPS_4 = 'Exaltado com Penhalo do Trovão.',
	AC_HORDE_REPS_5 = 'Exaltado com Luaprata.',

	AN_ALLIANCE_REPS = 'Embaixador da Aliança',
	AD_ALLIANCE_REPS = 'Alcance reputação exaltado com 5 cidades-capital.',
	AC_ALLIANCE_REPS_1 = 'Exaltado com Ventobravo.',
	AC_ALLIANCE_REPS_2 = 'Exaltado com Darnassus.',
	AC_ALLIANCE_REPS_3 = 'Exaltado com os Exilados de Gnomeregan.',
	AC_ALLIANCE_REPS_4 = 'Exaltado com Altaforja.',
	AC_ALLIANCE_REPS_5 = 'Exaltado com o Exodar.',

	AN_ARGENT_DAWN = 'A Alvorada Argenta',
	AD_ARGENT_DAWN = 'Alcance status exaltado com a Alvorada Argenta.',
	AN_BROOD_OF_NOZDORMU = 'Ninhada de Nozdormu',
	AD_BROOD_OF_NOZDORMU = 'Alcance status exaltado com a Ninhada de Nozdormu.',
	AN_DARKMOON_FAIRE = 'Feira de Negraluna',
	AD_DARKMOON_FAIRE = 'Alcance Exaltado com a facção da Feira de Negraluna.',
	AN_ZANDALAR_TRIBE = 'Herói da Tribo Zandalari',
	AD_ZANDALAR_TRIBE = 'Alcance status exaltado com a Tribo Zandalari.',
	AN_HYDRAXIANS = 'Senhores da Água Hidraxianos',
	AD_HYDRAXIANS = 'Alcance status exaltado com os Senhores da Água Hidraxianos.',
	AN_TIMBERMAW_HOLD = 'Eles Me Amam Naquele Túnel',
	AD_TIMBERMAW_HOLD = 'Alcance status exaltado com o Balde Madeira de Pinho.',
	AN_THORIUM = 'Irmandade do Tório',
	AD_THORIUM = 'Alcance status exaltado com a Irmandade do Tório.',
	AN_SHENDRALAR = 'Agente dos Shen\'dralar',
	AD_SHENDRALAR = 'Alcance status exaltado com os Shen\'dralar.',
	AN_CENARION = 'Círculo Cenariano',
	AD_CENARION = 'Alcance status exaltado com o Círculo Cenariano.',

	AN_DEFILERS = 'O Profanador',
	AD_DEFILERS = 'Ganhe reputação exaltado com os Profanadores Renegados.',
	AN_FROSTWOLF_CLAN = 'Herói do Clã Lobo Gélido',
	AD_FROSTWOLF_CLAN = 'Ganhe reputação exaltado com o Clã Lobo Gélido.',
	AN_WARSONG_OUTRIDERS = 'Batedor Grito de Guerra',
	AD_WARSONG_OUTRIDERS = 'Ganhe reputação exaltado com os Batedores Grito de Guerra.',
	AN_HORDE_PVP_FRACTIONS = 'O Conquistador',
	AD_HORDE_PVP_FRACTIONS = 'Eleve seus valores de reputação na Garganta Grito de Guerra, Bacia Arathi e Vale Alterac para Exaltado.',

	AN_LEAGUE_OF_ARATHOR = 'Cavaleiro de Arathor',
	AD_LEAGUE_OF_ARATHOR = 'Ganhe reputação exaltado com a Liga de Arathor.',
	AN_STORMSPIKE_GUARD = 'Herói da Guarda Cravopico',
	AD_STORMSPIKE_GUARD = 'Ganhe reputação exaltado com a Guarda Cravopico.',
	AN_SILVERWING_SENTINELS = 'Sentinela Asaprata',
	AD_SILVERWING_SENTINELS = 'Ganhe reputação exaltado com as Sentinelas Asaprata.',
	AN_ALLIANCE_PVP_FRACTIONS = 'O Justicar',
	AD_ALLIANCE_PVP_FRACTIONS = 'Eleve seus valores de reputação na Garganta Grito de Guerra, Bacia Arathi e Vale Alterac para Exaltado.',

	AN_BOLVAR_SLAYER = 'Invadindo Ventobravo',
	AD_BOLVAR_SLAYER = 'Mate o Alto-Lorde Bolvar Fordragon.',
	AN_MAGNI_SLAYER = 'Morte ao Rei!',
	AD_MAGNI_SLAYER = 'Mate o Rei Magni Barba de Bronze.',
	AN_TYRANDE_SLAYER = 'Imortal Não Mais',
	AD_TYRANDE_SLAYER = 'Mate a Alta-Sacerdotisa Tyrande Teixobrisa.',
	AN_VELEN_SLAYER = 'Apagando a Luz',
	AD_VELEN_SLAYER = 'Mate o Profeta Velen.',

	AN_ALLIANCE_KINGS_SLAYER = 'Pela Horda!',
	AD_ALLIANCE_KINGS_SLAYER = 'Mate os líderes da Aliança.',

	AN_THRALL_SLAYER = 'Morte ao Líder da Guerra!',
	AD_THRALL_SLAYER = 'Mate Thrall.',
	AN_SYLVANAS_SLAYER = 'Derrubando a Dama Negra',
	AD_SYLVANAS_SLAYER = 'Mate a Lady Sylvanas Correvento.',
	AN_CAIRNE_SLAYER = 'Sangue Casco de Sangue',
	AD_CAIRNE_SLAYER = 'Mate Cairne Casco de Sangue.',
	AN_LORTHEMAR_SLAYER = 'Morto em Quel\'Thalas',
	AD_LORTHEMAR_SLAYER = 'Mate Lor\'themar Theron.',

	AN_HORDE_KINGS_SLAYER = 'Pela Aliança!',
	AD_HORDE_KINGS_SLAYER = 'Mate os líderes da Horda.',

	AN_RACES_KILLER = 'Conheça Teu Inimigo',
	AD_ALLIANCE_RACES_KILLER = 'Dê um golpe de morte honroso em cinco raças diferentes.',
	AD_HORDE_RACES_KILLER = 'Dê um golpe de morte honroso em cinco raças diferentes.',
	AC_HUMAN_KILLED = 'Humano',
	AC_NIGHTELF_KILLED = 'Elfo Noturno',
	AC_DWARF_KILLED = 'Anão',
	AC_GNOME_KILLED = 'Gnomo',
	AC_ORC_KILLED = 'Orc',
	AC_TROLL_KILLED = 'Troll',
	AC_SCOURGE_KILLED = 'Morto-Vivo',
	AC_TAUREN_KILLED = 'Tauren',
	AC_DRAENEI_KILLED = 'Draenei',
	AC_BLOODELF_KILLED = 'Elfo Sangrento',

	AN_CLASSES_KILLER = 'Que Classe, hein',
	AD_CLASSES_KILLER = 'Dê um golpe de morte honroso em um de cada classe.',
	AC_WARRIOR_KILLED = 'Guerreiro',
	AC_HUNTER_KILLED = 'Caçador',
	AC_ROGUE_KILLED = 'Ladino',
	AC_PRIEST_KILLED = 'Sacerdote',
	AC_MAGE_KILLED = 'Mago',
	AC_WARLOCK_KILLED = 'Bruxo',
	AC_DRUID_KILLED = 'Druida',
	AC_PALADIN_KILLED = 'Paladino',
	AC_SHAMAN_KILLED = 'Xamã',

	AN_ALTERAC_WIN = 'Vitória no Vale Alterac',
	AD_ALTERAC_WIN = 'Vença a batalha pelo Vale Alterac.',
	AN_ALTERAC_WINS = 'Veterano do Vale Alterac',
	AD_ALTERAC_WINS = 'Vença %d batalhas pelo Vale Alterac.',
	AN_WARSONG_WIN = 'Vitória na Garganta Grito de Guerra',
	AD_WARSONG_WIN = 'Vença a Garganta Grito de Guerra.',
	AN_WARSONG_WINS = 'Veterano da Garganta Grito de Guerra',
	AD_WARSONG_WINS = 'Complete %d vitórias na Garganta Grito de Guerra.',
	AN_ARATHI_WIN = 'Vitória na Bacia Arathi',
	AD_ARATHI_WIN = 'Vença a Bacia Arathi.',
	AN_ARATHI_WINS = 'Veterano da Bacia Arathi',
	AD_ARATHI_WINS = 'Complete %d vitórias na Bacia Arathi.',
	AN_EYE_WIN = 'Vitória no Olho da Tempestade',
	AD_EYE_WIN = 'Vença o Olho da Tempestade.',
	AN_EYE_WINS = 'Veterano do Olho da Tempestade',
	AD_EYE_WINS = 'Complete %d vitórias no Olho da Tempestade.',

	AN_ALTERAC_KILLING_BLOWS = 'Moedor de Carne do Vale',
	AD_ALTERAC_KILLING_BLOWS = 'Dê %d golpes mortais em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_GRAVEYARD_ASSAULT = 'Coveiro',
	AD_ALTERAC_GRAVEYARD_ASSAULT = 'Assalte um cemitério em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_GRAVEYARD_ASSAULTS = 'Nunca Há Caixões Suficientes',
	AD_ALTERAC_GRAVEYARD_ASSAULTS = 'Assalte %d cemitérios em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_GRAVEYARD_DEFEND = 'Guardião dos Defuntos',
	AD_ALTERAC_GRAVEYARD_DEFEND = 'Defenda um cemitério em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_GRAVEYARD_DEFENDS = 'Guardião de Todos os Mortos',
	AD_ALTERAC_GRAVEYARD_DEFENDS = 'Defenda %d cemitérios em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_TOWER_ASSAULT = 'Agora É Meu!',
	AD_ALTERAC_TOWER_ASSAULT = 'Assalte uma torre em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_TOWER_ASSAULTS = 'Agora É Tudo Meu!',
	AD_ALTERAC_TOWER_ASSAULTS = 'Assalte %d torres em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_TOWER_DEFEND = 'Guardião das Torres',
	AD_ALTERAC_TOWER_DEFEND = 'Defenda uma torre em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_TOWER_DEFENDS = 'Guardião das Torres',
	AD_ALTERAC_TOWER_DEFENDS = 'Defenda %d torres em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_MINE_CAPTURE = 'Mineiro Congelado',
	AD_ALTERAC_MINE_CAPTURE = 'Assalte uma mina em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_MINE_CAPTURES = 'Piqueiro Congelado',
	AD_ALTERAC_MINE_CAPTURES = 'Assalte %d minas em uma única batalha pelo Vale Alterac e fique até o fim.',
	AN_ALTERAC_AUTOGRAPH = 'Ao Ladrão Vão os Espólios',
	AD_ALTERAC_AUTOGRAPH = 'Pegue a Foto Autografada do Tigule no Vale Alterac.',

	AN_WARSONG_KILLS = 'Honra Militar',
	AD_WARSONG_KILLS = 'Consiga %d mortes honrosas em uma única batalha na Garganta Grito de Guerra e fique até o fim.',
	AN_WARSONG_FLAG_CAPTURE = 'Capture a Bandeira',
	AD_WARSONG_FLAG_CAPTURE = 'Carregue e capture a bandeira pessoalmente em uma única batalha na Garganta Grito de Guerra e fique até o fim.',
	AN_WARSONG_FLAG_CAPTURES = 'Grande Portador de Bandeira',
	AD_WARSONG_FLAG_CAPTURES = 'Carregue e capture %d bandeiras pessoalmente em uma única batalha na Garganta Grito de Guerra e fique até o fim.',
	AN_WARSONG_FLAG_RETURN = 'Não Toca!',
	AD_WARSONG_FLAG_RETURN = 'Devolva uma bandeira como defensor em uma única batalha na Garganta Grito de Guerra e fique até o fim.',
	AN_WARSONG_FLAG_RETURNS = 'Não Toca em Nada!',
	AD_WARSONG_FLAG_RETURNS = 'Devolva %d bandeiras como defensor em uma única batalha na Garganta Grito de Guerra e fique até o fim.',

	AN_ARATHI_BASE_ASSAULT = 'Conquistador',
	AD_ARATHI_BASE_ASSAULT = 'Assalte uma bandeira em uma única batalha na Bacia Arathi e fique até o fim.',
	AN_ARATHI_BASE_ASSAULTS = 'Campo de Provas',
	AD_ARATHI_BASE_ASSAULTS = 'Assalte %d bandeiras em uma única batalha na Bacia Arathi e fique até o fim.',
	AN_ARATHI_BASE_DEFEND = 'Guardião',
	AD_ARATHI_BASE_DEFEND = 'Defenda uma bandeira em uma única batalha na Bacia Arathi e fique até o fim.',
	AN_ARATHI_BASE_DEFENDS = 'Sentinela',
	AD_ARATHI_BASE_DEFENDS = 'Defenda %d bandeiras em uma única batalha na Bacia Arathi e fique até o fim.',
	AN_ARATHI_CLOSE = 'Tínhamos Tudo Desde o Começo *cof*',
	AD_ARATHI_CLOSE = 'Vença a Bacia Arathi por 10 pontos (2000 a 1990).',
	AN_ARATHI_PERFECT = 'Perfeição na Bacia Arathi',
	AD_ARATHI_PERFECT = 'Vença a Bacia Arathi com placar de 2000 a 0.',

	AN_EYE_CAPTURE = 'Capturador da Tempestade',
	AD_EYE_CAPTURE = 'Carregue e capture a bandeira pessoalmente no Olho da Tempestade e fique até o fim da batalha.',
	AD_EYE_CAPTURES = 'Carregue e capture %d bandeiras pessoalmente no Olho da Tempestade e fique até o fim da batalha.',
	AN_EYE_GLORY = 'Destinado à Glória',
	AD_EYE_GLORY = 'Em uma única partida do Olho da Tempestade, capture a bandeira 3 vezes sem morrer.',
	AN_EYE_FAST_WIN = 'Revezão',
	AD_EYE_FAST_WIN = 'Vença o Olho da Tempestade em menos de 6 minutos.',
	AN_EYE_BERSERK = 'Berserker Sanguinário',
	AD_EYE_BERSERK = 'Dê um golpe mortal sob os efeitos do buff berserker no Olho da Tempestade.',
	AN_EYE_IDEAL_VICTORY = 'A Tempestade Perfeita',
	AD_EYE_IDEAL_VICTORY = 'Vença o Olho da Tempestade com placar de 2000 a 0.',

	AN_BGS_KILLING_BLOWS = 'Portador da Morte',
	AD_BGS_KILLING_BLOWS = 'Dê %d golpes mortais em qualquer campo de batalha.',
	AN_BGS_KILLS = 'Agregador de Honra',
	AD_BGS_KILLS = 'Consiga %d mortes honrosas em qualquer campo de batalha.',

	PROF_FIRST_AID = 'Primeiros Socorros',
	PROF_FISHING = 'Pescaria',
	PROF_COOKING = 'Culinária',
	PROF_ENCHANTING = 'Encantamento',
	PROF_TAILORING = 'Alfaiataria',
	PROF_ENGINEERING = 'Engenharia',
	PROF_LEATHERWORKING = 'Couro',
	PROF_ALCHEMY = 'Alquimia',
	PROF_BLACKSMITHING = 'Ferraria',
	PROF_HERBALISM = 'Herborismo',
	PROF_MINING = 'Mineração',
	PROF_SKINNING = 'Esfolamento',
	PROF_JEWELCRAFTING = 'Joalheria',
	SKILL_UNARMED = 'Desarmado',
	SKILL_RIDING = 'Montaria',

	AN_PROFS_JOURNEYMAN = 'Aprendiz Profissional',
	AD_PROFS_JOURNEYMAN = 'Eleve a perícia de qualquer profissão principal para 75.',
	AN_PROFS_EXPERT = 'Profissional Competente',
	AD_PROFS_EXPERT = 'Eleve a perícia de qualquer profissão principal para 150.',
	AN_PROFS_ARTISAN = 'Profissional Especialista',
	AD_PROFS_ARTISAN = 'Eleve a perícia de qualquer profissão principal para 225.',
	AN_PROFS_ONE = 'Profissional Artesão',
	AD_PROFS_ONE = 'Eleve a perícia de qualquer profissão principal para 300.',
	AN_PROFS_ONE_OUTLAND = 'Profissional Mestre',
	AD_PROFS_ONE_OUTLAND = 'Eleve a perícia de qualquer profissão principal para 375.',
	AN_PROFS_TWO = 'Faz-Tudo',
	AD_PROFS_TWO = 'Eleve a perícia de duas profissões principais para 300 ao mesmo tempo.',
	AC_PROFS_TWO = 'Eleve a perícia de duas profissões principais para 300 ao mesmo tempo.',
	AN_PROFS_TWO_OUTLAND = 'Faz-Tudo Terralémico',
	AD_PROFS_TWO_OUTLAND = 'Eleve a perícia de duas profissões principais para 375 ao mesmo tempo.',
	AC_PROFS_TWO_OUTLAND = 'Eleve a perícia de duas profissões principais para 375 ao mesmo tempo.',

	AN_FIRST_AID_JOURNEYMAN = 'Aprendiz em Primeiros Socorros',
	AD_FIRST_AID_JOURNEYMAN = 'Eleve a perícia de primeiros socorros para 75.',
	AN_FIRST_AID_EXPERT = 'Competente em Primeiros Socorros',
	AD_FIRST_AID_EXPERT = 'Eleve a perícia de primeiros socorros para 150.',
	AN_FIRST_AID_ARTISAN = 'Especialista em Primeiros Socorros',
	AD_FIRST_AID_ARTISAN = 'Eleve a perícia de primeiros socorros para 225.',
	AN_FIRST_AID_MASTER = 'Artesão em Primeiros Socorros',
	AD_FIRST_AID_MASTER = 'Eleve a perícia de primeiros socorros para 300.',
	AN_FIRST_AID_OUTLAND_MASTER = 'Mestre em Primeiros Socorros',
	AD_FIRST_AID_OUTLAND_MASTER = 'Eleve a perícia de primeiros socorros para 375.',
	
	AN_FISHING_JOURNEYMAN = 'Aprendiz Pescador',
	AD_FISHING_JOURNEYMAN = 'Eleve a perícia de pescaria para 75.',
	AN_FISHING_EXPERT = 'Pescador Competente',
	AD_FISHING_EXPERT = 'Eleve a perícia de pescaria para 150.',
	AN_FISHING_ARTISAN = 'Pescador Especialista',
	AD_FISHING_ARTISAN = 'Eleve a perícia de pescaria para 225.',
	AN_FISHING_MASTER = 'Pescador Artesão',
	AD_FISHING_MASTER = 'Eleve a perícia de pescaria para 300.',
	AN_FISHING_OUTLAND_MASTER = 'Mestre Pescador',
	AD_FISHING_OUTLAND_MASTER = 'Eleve a perícia de pescaria para 375.',
	
	AN_COOKING_JOURNEYMAN = 'Aprendiz Cozinheiro',
	AD_COOKING_JOURNEYMAN = 'Eleve a perícia de culinária para 75.',
	AN_COOKING_EXPERT = 'Cozinheiro Competente',
	AD_COOKING_EXPERT = 'Eleve a perícia de culinária para 150.',
	AN_COOKING_ARTISAN = 'Cozinheiro Especialista',
	AD_COOKING_ARTISAN = 'Eleve a perícia de culinária para 225.',
	AN_COOKING_MASTER = 'Cozinheiro Artesão',
	AD_COOKING_MASTER = 'Eleve a perícia de culinária para 300.',
	AN_COOKING_OUTLAND_MASTER = 'Mestre Cozinheiro',
	AD_COOKING_OUTLAND_MASTER = 'Eleve a perícia de culinária para 375.',
	
	AN_PROFS_SECONDARY = 'Perícias Para Pagar as Contas',
	AD_PROFS_SECONDARY = 'Torne-se Artesão em pescaria, primeiros socorros e culinária.',
	AN_PROFS_SECONDARY_OUTLAND = 'Perícias Para Pagar as Contas, também em Terralém',
	AD_PROFS_SECONDARY_OUTLAND = 'Torne-se Mestre em pescaria, primeiros socorros e culinária.',
	AN_PROFS_FIVE = 'Gênio em Todo Ofício',
	AN_PROFS_FIVE_OUTLAND = 'Gênio Terralémico',
	AD_PROFS_FIVE = 'Complete as conquistas de profissão listadas abaixo.',
	AN_UNARMED_SKILL = 'Alguém Pediu Soca?',
	AD_UNARMED_SKILL = 'Eleve sua perícia de desarmado para 350.',

	AN_EXPLORE_AZEROTH = 'Explorador do Mundo',
	AD_EXPLORE_AZEROTH = 'Explore os Reinos do Leste, Kalimdor e Terralém.',
	AR_EXPLORER = 'Explorador',
	AN_EXPLORE_KALIMDOR = 'Explorar Kalimdor',
	AD_EXPLORE_KALIMDOR = 'Explore as regiões de Kalimdor.',
	AN_EXPLORE_EASTERN_KINGDOMS = 'Explorar os Reinos do Leste',
	AD_EXPLORE_EASTERN_KINGDOMS = 'Explore as regiões dos Reinos do Leste.',
	AN_EXPLORE = 'Explorar %s',
	AD_EXPLORE = 'Explore %s, revelando as áreas cobertas do mapa-múndi.',

	AN_SULFURAS = 'Sulfuras, Mão de Ragnaros',
	AD_SULFURAS = 'Portador de Sulfuras, Mão de Ragnaros.',
	AN_THUNDER_FURY = 'Thunderfury, Lâmina Benta do Buscador do Vento',
	AD_THUNDER_FURY = 'Portador de Thunderfury, Lâmina Benta do Buscador do Vento.',
	AN_ATIESH = 'Atiesh, Bastão do Guardião',
	AD_ATIESH = 'Portador de Atiesh, Bastão do Guardião.',
	AN_BLACK_SCARAB = 'Senhor dos Escaravelhos',
	AD_BLACK_SCARAB = 'Abriu os portões de Ahn\'Qiraj.',
	AN_RED_SCARAB = 'Por quê? Porque É Vermelho',
	AD_RED_SCARAB = 'Obtenha um Cristal Ressonante Qiraji Vermelho.',
	AN_TIGER_MOUNT = 'Tigre Zuliano Veloz',
	AD_TIGER_MOUNT = 'Obtenha o Tigre Zuliano Veloz do Alto-Sacerdote Thekal em Zul\'Gurub.',
	AN_RAPTOR_MOUNT = 'Raptor Razzashi Veloz',
	AD_RAPTOR_MOUNT = 'Obtenha o Raptor Razzashi Veloz do Senhor do Sangue Mandokir em Zul\'Gurub.',
	AN_BARON_MOUNT = 'Rédeas da Montaria da Morte',
	AD_BARON_MOUNT = 'Obtenha as Rédeas da Montaria da Morte de Rivendare em Stratholme.',
	AN_SABER_MOUNT = 'Sabre Gélido de Helmgar',
	AD_SABER_MOUNT = 'Obtenha um Sabre Gélido de Helmgar.',
	AN_ARGENT_DAWN_TABARD = 'Tabardo da Alvorada Argenta',
	AD_ARGENT_DAWN_TABARD = 'Obteve um Tabardo da Alvorada Argenta do evento Invasão do Flagelo.',
	
	AN_UNCOMMON_GEAR = 'Não Tão Comum Assim',
	AD_UNCOMMON_GEAR = 'Equipe-se com itens de qualidade incomum ou superior.',
	AN_RARE_GEAR = 'Superior',
	AD_RARE_GEAR = 'Equipe um item superior em todos os espaços',
	AN_EPIC_GEAR = 'Épico',
	AD_EPIC_GEAR = 'Equipe um item épico em todos os espaços ',

	AN_STOCKING_UP = 'Estocando',
	AD_STOCKING_UP = 'Crie 100 Bandagens Pesadas de Tecrunit.',
	AC_STOCKING_UP = 'Crie 100 Bandagens Pesadas de Tecrunit.',
	AN_STOCKING_UP_2 = 'Estocando',
	AD_STOCKING_UP_2 = 'Crie 500 Bandagens Pesadas de Tecrunit.',
	AC_STOCKING_UP_2 = 'Crie 500 Bandagens Pesadas de Tecrunit.',
	AN_STOCKING_UP_OUTLAND = 'Preparando-se para o Vazio',
	AD_STOCKING_UP_OUTLAND = 'Crie 100 Bandagens Pesadas de Etério.',
	AC_STOCKING_UP_OUTLAND = 'Crie 100 Bandagens Pesadas de Etério.',
	AN_STOCKING_UP_2_OUTLAND = 'Preparando-se para o Vazio',
	AD_STOCKING_UP_2_OUTLAND = 'Crie 500 Bandagens Pesadas de Etério.',
	AC_STOCKING_UP_2_OUTLAND = 'Crie 500 Bandagens Pesadas de Etério.',

	AN_BOOTY_BAY_CONTEST = 'Eu Escolho o Melhor para Pescaria',
	AD_BOOTY_BAY_CONTEST = 'Vença o concurso de pesca da Baia do Butim e escolha a Vara de Pescaria de Arcanita ou o Anzol do Mestre Pescador como recompensa.',
	AN_BOOTY_BAY_FISH = 'Amante de Peixes de Verdade',
	AD_BOOTY_BAY_FISH = 'Pesque um dos peixes raros durante o concurso de pesca da Baia do Butim.',

	AN_FISHING_COLLECTION = 'Coleção de Peixes',
	AD_FISHING_COLLECTION = 'Pesque os seguintes peixes em Azeroth.',
	AN_FISHING_OUTLAND_COLLECTION = 'Coleção de Peixes Terralémicos',
	AD_FISHING_OUTLAND_COLLECTION = 'Pesque as seguintes espécies em Terralém.',
	AN_FISHING_WATER = 'Água de Água',
	AD_FISHING_WATER = 'Pesque uma Essência de Água.',
	AN_FISHING_RUM = 'Escolha do Capitão',
	AD_FISHING_RUM = 'Pesque os seguintes tipos de rum.',
	AN_FISHING_RING = 'Presente de Mordor',
	AD_FISHING_RING = 'Pesque o Anel 1.',
	AN_FISHING_SKULL = 'Presságio de um Fim Triste',
	AD_FISHING_SKULL = 'Pesque o Crânio do Velho Teamster.',
	AN_FISHING_SNAPPER = 'Grande Pescador de Sargo',
	AD_FISHING_SNAPPER = 'Pesque Sargos dos seguintes tamanhos.',
	AC_FISHING_SNAPPER = 'Sargo de Lama de %d Quilos',
	AN_FISHING_SEA_BASS = 'Tempestade de Percas',
	AD_FISHING_SEA_BASS = 'Pesque Garoupas dos seguintes tamanhos.',
	AC_FISHING_SEA_BASS = 'Garoupa de %d Quilos',
	AN_FISHING_SALMON = 'Amante de Salmão',
	AD_FISHING_SALMON = 'Pesque Salmões dos seguintes tamanhos.',
	AC_FISHING_SALMON = 'Salmão de %d Quilos',
	AN_FISHING_LOBSTER = 'Caçador de Lagostas',
	AD_FISHING_LOBSTER = 'Pesque Lagostas dos seguintes tamanhos.',
	AC_FISHING_LOBSTER = 'Lagosta de %d Quilos',
	AN_FISHING_BIG_SIZE = 'Maior Pescador de Azeroth',
	AD_FISHING_BIG_SIZE = 'Complete as conquistas de pesca listadas abaixo.',
	AR_FISHING_BIG_SIZE = 'Maior Pescador de Azeroth',
	
	AN_FISHING_COUNT = '%d Peixes',
	AC_FISHING_COUNT = 'Pesque %d itens.',
	AD_FISHING_COUNT = 'Pesque %d itens.',

	AN_COOKING_RECIPES_5 = 'Senhora do Almoço',
	AN_COOKING_RECIPES_10 = 'Cozinheiro de Plantão',
	AN_COOKING_RECIPES_25 = 'Chefe de Partida',
	AN_COOKING_RECIPES_50 = 'Subchefe',
	AN_COOKING_RECIPES_75 = 'Chefe de Cozinha',
	AR_COOKING_RECIPES = 'Chefe',
	AD_COOKING_RECIPES = 'Aprenda %d receitas de culinária.',
	AC_COOKING_RECIPES = 'Aprenda %d receitas de culinária.',

	AN_COOKING_SOUP = 'Especialista em Sopa',
	AN_COOKING_DESSERT = 'Mestre das Tubérculos',
	AN_COOKING_SQUID = 'Pescado do Dia',
	AN_COOKING_DUMPLINGS = 'Bolinhos da Vovó',
	AN_COOKING_CAKE = 'O Bolo Não É Mentira',
	AD_COOKING_CAKE = 'Asse um Bolo de Chocolate Delicioso.',
	AD_COOKING_CREATE = 'Cozinhe %s %d vezes.',
	AC_COOKING_CREATE = 'Cozinhe %s %d vezes.',
	AN_COOKING_BIG_TABLE = 'Grande Banquete Festivo',
	AD_COOKING_BIG_TABLE = 'Complete as conquistas de culinária listadas abaixo.',

	AN_COOKING_FISHERMANS_FEAST = 'Banquete do Pescador',
	AN_COOKING_SPICY_HOT_TALBUK = 'Talbuk Apimentado Quente',
	AN_COOKING_SKULLFISH_SOUP = 'Sopa de Peixe Caveira',
	AN_COOKING_RAVAGER_DOG = 'Cão Devastador',

	AN_WB_AZUREGOS = 'O Segredo do Dragão Azul',
	AD_WB_AZUREGOS = 'Derrote Azuregos.',
	AN_WB_KAZZAK = 'Demônios Não Passarão',
	AD_WB_KAZZAK = 'Derrote o Senhor Kazzak.',
	AN_WB_KAZZAK_OUTLAND = 'Sou o Mestre do Meu Destino',
	AD_WB_KAZZAK_OUTLAND = 'Derrote o Senhor da Perdição Kazzak na Península do Fogo do Inferno.',
	AN_WB_DOOMWALKER = 'Anda-Escravo Quebrado',
	AD_WB_DOOMWALKER = 'Derrote o Anda-Escravo no Vale da Lua Negra.',
	AN_WB_YSONDRE = 'Sem Lugar para Garotas em um Pesadelo',
	AD_WB_YSONDRE = 'Derrote Ysondre.',
	AN_WB_LETHON = 'Filho do Pesadelo Esmeralda',
	AD_WB_LETHON = 'Derrote Lethon.',
	AN_WB_EMERISS = 'Emeriss, Traidor da Vida',
	AD_WB_EMERISS = 'Derrote Emeriss.',
	AN_WB_TAERAR = 'Taerar, o Assustador',
	AD_WB_TAERAR = 'Derrote Taerar.',
	AN_WB_EMERALD_DRAGONS = 'Guardião Esmeralda',
	AD_WB_EMERALD_DRAGONS = 'Derrote todos os Dragões do Pesadelo Esmeralda.',
	AR_WB_EMERALD_DRAGONS = 'Guardião Esmeralda',

	AN_DUEL = 'Dueliicioso',
	AD_DUEL = 'Vença um duelo contra outro jogador.',
	AN_DUELS_10 = 'Duelista',
	AN_DUELS_25 = 'Duelista Habilidoso',
	AN_DUELS_100 = 'Mestre Duelista',
	AD_DUELS = 'Vença %d duelos.',
	AC_DUELS = 'Vença %d duelos',
	AN_GURUBASHI_1 = 'Mestre da Arena Gurubashi',
	AD_GURUBASHI_1 = 'Pegue o berloque Mestre da Arena na Arena Gurubashi.',
	AN_GURUBASHI_2 = 'Grão-Mestre da Arena Gurubashi',
	AD_GURUBASHI_2 = 'Complete a missão de Short John Mithril para obter o berloque Grão-Mestre da Arena.',
	AN_PARTICIPATE_IN_BGS = 'Chamado às Armas!',
	AD_PARTICIPATE_IN_BGS = 'Complete %d campos de batalha.',
	AC_PARTICIPATE_IN_BGS = 'Complete %d campos de batalha.',

	EMOTE_LOVE1 = 'Você ama %s.',
	AN_LOVE = 'Para Todos os Esquilos Que Já Amei',
	AD_LOVE = 'Mostre às criaturas de Azeroth o quanto você os ama com /love.',
	EMOTE_PAT1 = 'Você faz carinho em %s gentilmente.',
	AN_ARATHI_CATS = 'Primeiro os Gatos, Depois o Resto',
	AD_ARATHI_CATS = 'Faça carinho (/pat) nos animais de estimação designados na Bacia Arathi.',

	AN_ALTERAC_FAST_WIN = 'O Blitz de Alterac',
	AD_ALTERAC_FAST_WIN = 'Vença o Vale Alterac em 6 minutos.',

	AN_WARSONG_FAST_WIN = 'Eficiência Grito de Guerra',
	AD_WARSONG_FAST_WIN = 'Vença a Garganta Grito de Guerra em menos de 7 minutos.',
	AN_ARATHI_FAST_WIN = 'Vamos Acabar com Isso',
	AD_ARATHI_FAST_WIN = 'Vença a Bacia Arathi em 6 minutos.',

	AN_ALTERAC_TOWER_DEFEND_TOTAL = 'Defesa da Torre',
	AD_ALTERAC_TOWER_DEFEND_TOTAL = 'Defenda %d torres no Vale Alterac.',
	AN_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Ladrão de Túmulos de Alterac',
	AD_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Tome %d cemitérios no Vale Alterac.',
	AN_WARSONG_FLAG_CAPTURE_TOTAL = 'Capturador de Bandeiras',
	AD_WARSONG_FLAG_CAPTURE_TOTAL = 'Carregue e capture %d bandeiras pessoalmente na Garganta Grito de Guerra.',
	AN_WARSONG_FLAG_RETURN_TOTAL = 'Defensor Persistente',
	AD_WARSONG_FLAG_RETURN_TOTAL = 'Devolva %d bandeiras como defensor na Garganta Grito de Guerra.',
	AN_ARATHI_BASE_ASSAULT_TOTAL = 'Eu e o Capitão Fizendo Acontecer',
	AD_ARATHI_BASE_ASSAULT_TOTAL = 'Tome %d bandeiras na Bacia Arathi.',
	AN_ARATHI_BASE_DEFEND_TOTAL = 'Ao Resgate!',
	AD_ARATHI_BASE_DEFEND_TOTAL = 'Venha em defesa de uma base na Bacia Arathi %d vezes recapturando a bandeira.',
	AN_ALTERAC_MOUNT_HORDE = 'Uivador Lobo Gélido',
	AD_ALTERAC_MOUNT_HORDE = 'Obtenha um Uivador Lobo Gélido.',
	AN_ALTERAC_MOUNT_ALLIANCE = 'Corcel de Batalha Cravopico',
	AD_ALTERAC_MOUNT_ALLIANCE = 'Obtenha um Corcel de Batalha Cravopico.',

	AN_ALTERAC_BOSS = 'Mestre do Vale Alterac',
	AD_ALTERAC_BOSS = 'Complete as conquistas do Vale Alterac listadas abaixo.',
	AN_WARSONG_BOSS = 'Mestre da Garganta Grito de Guerra',
	AD_WARSONG_BOSS = 'Complete as conquistas da Garganta Grito de Guerra listadas abaixo.',
	AN_ARATHI_BOSS = 'Mestre da Bacia Arathi',
	AD_ARATHI_BOSS = 'Complete as conquistas da Bacia Arathi listadas abaixo.',
	AN_EYE_BOSS = 'Mestre do Olho da Tempestade',
	AD_EYE_BOSS = 'Complete as conquistas do Olho da Tempestade listadas abaixo.',
	AN_BATTLEMASTER = 'Mestre de Batalha',
	AD_BATTLEMASTER = 'Complete as conquistas de campos de batalha listadas abaixo.',
	AR_BATTLEMASTER = 'Mestre de Batalha',

	AN_LEEROY = 'Leeeeeeeeeeeeeroy!',
	AD_LEEROY = 'Mate 50 filhotes do ninho em 15 segundos.',
	AR_LEEROY = 'Jenkins',
	AN_BWL_DUO = 'Respiração Dupla',
	AD_BWL_DUO = 'Mate Ebonroc e Flamegor em 45 segundos.',
	AN_ANUBREKHAN_WITHOUT_MOBS = 'O Senhor da Cripta',
	AD_ANUBREKHAN_WITHOUT_MOBS = 'Mate Anub\'Rekhan, deixando ambos os Guardiões da Cripta vivos.',
	AN_FAERLINA_WITHOUT_MOBS = 'Mamãe Disse Te Nocautear',
	AD_FAERLINA_WITHOUT_MOBS = 'Mate a Grã-Viúva Faerlina, deixando todos os adoradores e seguidores de Naxxramas vivos.',
	AN_SAPPHIRONE_WITH_ALL_ALIVE = 'Não Vamos Sucumbir ao Gelo',
	AD_SAPPHIRONE_WITH_ALL_ALIVE = 'Derrote Sapphiron em Naxxramas sem que ninguém na raide morra.',
	AN_ARACHNOPHOBIA = 'Aracnofobia',
	AD_ARACHNOPHOBIA = 'Mate Maexxna em Naxxramas em até 20 minutos após a morte de Anub\'Rekhan no modo 25 jogadores.',
	AN_FOUR_TOGETHER = 'E Eles Cairiam Todos Juntos',
	AD_FOUR_TOGETHER = 'Derrote os 4 Cavaleiros em Naxxramas, garantindo que todos morram em até 15 segundos entre si.',
	AN_HEIGAN_DANCE = 'A Dança da Segurança',
	AD_HEIGAN_DANCE = 'Derrote Heigan, o Impuro, em Naxxramas sem que ninguém na raide morra.',
	AN_PATCHWERK = 'Dê um Fim Rápido a Ele',
	AD_PATCHWERK = 'Derrote Patchwerk em Naxxramas em 3 minutos ou menos.',
	AN_KELTHUZAD_ABOMINATIONS = 'Simplesmente Não Tenho o Suficiente',
	AD_KELTHUZAD_ABOMINATIONS = 'Derrote Kel\'Thuzad em Naxxramas matando pelo menos 18 abominações em sua câmara.',
	
	AN_PIRATES_HAT = 'Olá, Almirante!',
	AD_PIRATES_HAT = 'Obtenha o Chapéu do Almirante Velassangue... e tente tomar um ar fresco de vez em quando.',
	AR_PIRATES_HAT = 'Almirante Velassangue',	
	AN_PALADIN_MOUNT = 'Corcel',
	AD_PALADIN_MOUNT = 'Completou a missão de paladino para obter um Corcel.',
	AN_WARLOCK_MOUNT = 'Cavalo Medonho de Xoroth',
	AD_WARLOCK_MOUNT = 'Completou a missão de bruxo do Cavalo Medonho de Xoroth.',
	
	AN_HALLOWSEND = 'Santificado Seja o Teu Nome',
	AD_HALLOWSEND = 'Complete as conquistas da Véspera das Bruxas listadas abaixo.',
	AR_HALLOWSEND = 'O Santificado',
	
	AN_PUMPKIN = 'Aboboromania',
	AD_PUMPKIN = 'Obtenha uma Saco de Abóbora durante a Véspera das Bruxas.',
	AN_HALLOWSEND_ALLIANCE_QUEST1 = 'Véspera Podre',
	AD_HALLOWSEND_ALLIANCE_QUEST1 = 'Arruíne a Véspera das Bruxas para a Horda completando as missões do Sargento Hartman, que envolvem derrubar o festival do Boneco de Palha e limpar as bombas fétidas de Colina do Sul.',
	AC_HALLOWSEND_ALLIANCE_QUEST1_CRITERIA1 = 'Derrubando o Festival do Boneco de Palha',
	AC_HALLOWSEND_ALLIANCE_QUEST1_CRITERIA2 = 'O Poder do Pinho',
	AN_HALLOWSEND_HORDE_QUEST1 = 'Véspera Podre',
	AD_HALLOWSEND_HORDE_QUEST1 = 'Arruíne a Véspera das Bruxas para a Aliança completando as missões da Chamadora Sombria Yanka, que envolvem ir a Colina do Sul, arruinar os barris com ovos podres e jogar bombas fétidas na cidade.',
	AC_HALLOWSEND_HORDE_QUEST1_CRITERIA1 = 'Ovos Podres e Barris Arruinados',
	AC_HALLOWSEND_HORDE_QUEST1_CRITERIA2 = 'Esvaziando Colina do Sul',
	
	AN_HALLOWSEND_ALLIANCE_QUEST2 = 'Guloseimas da Véspera das Bruxas para Jesper!',
	AD_HALLOWSEND_ALLIANCE_QUEST2 = 'Colete as guloseimas pedidas para Jesper.',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA1 = 'Nougat de Ventobravo',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA2 = 'Pirulito de Gnomeregan',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA3 = 'Menta de Altaforja',
	AC_HALLOWSEND_ALLIANCE_QUEST2_CRITERIA4 = 'Marzipan de Darnassus',
	AN_HALLOWSEND_HORDE_QUEST2 = 'Guloseimas da Véspera das Bruxas para Spoops!',
	AD_HALLOWSEND_HORDE_QUEST2 = 'Colete as guloseimas pedidas para Spoops.',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA1 = 'Nougat de Orgrimmar',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA2 = 'Pirulito dos Senhores Neles',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA3 = 'Menta da Cidade Baixa',
	AC_HALLOWSEND_HORDE_QUEST2_CRITERIA4 = 'Marzipan de Penhalo do Trovão',
	
	AN_HALLOWSEND_INVOCATION_BUFF = 'Invocação do Boneco de Palha',
	AD_HALLOWSEND_INVOCATION_BUFF = 'Receba o buff "Invocação do Boneco de Palha" durante a Véspera das Bruxas.',
	
	AN_HALLOWSEND_TREATS = 'Doce ou Travessura!',
	AD_HALLOWSEND_TREATS = 'Receba uma Saco de Doces de um estalajadeiro.',
	
	AN_HALLOWSEND_MASK = 'A Tarefa das Máscaras',
	AD_HALLOWSEND_MASK = 'Obtenha uma Máscara Frágil durante a Véspera das Bruxas.',
	
	AN_HALLOWSEND_MASKS = 'Uma Máscara Para Cada Ocasião',
	AD_HALLOWSEND_MASKS = 'Colete as 16 Máscaras Frágeis únicas listadas abaixo.',
	
	AN_HALLOWSEND_TRANSFORM = 'O Mascarado',
	AD_HALLOWSEND_TRANSFORM = 'Seja transformado pelas Varinhas Consagradas listadas abaixo.',
	AC_HALLOWSEND_GHOST = 'Transformado por Varinha Consagrada - Fantasma',
	AC_HALLOWSEND_GNOME = 'Transformado por Varinha Consagrada - Gnomo Leproso',
	AC_HALLOWSEND_WISP = 'Transformado por Varinha Consagrada - Fagulha',
	AC_HALLOWSEND_NINJA = 'Transformado por Varinha Consagrada - Ninja',
	AC_HALLOWSEND_SKELETON = 'Transformado por Varinha Consagrada - Esqueleto',
	AC_HALLOWSEND_PIRATE = 'Transformado por Varinha Consagrada - Pirata',
	AC_HALLOWSEND_BAT = 'Transformado por Varinha Consagrada - Morcego',

	--WINTERVEIL
	AN_WINTERVEIL = 'Festeiro',
	AD_WINTERVEIL = 'Complete as conquistas do Inverno listadas abaixo.',
	AR_WINTERVEIL = 'Festeiro',

	AN_WINTERVEIL_METZEN = 'Salve o Metzen!',
	AD_WINTERVEIL_METZEN = 'Salve Metzen, a Rena.',

	AN_WINTERVEIL_SMOKEYWOOD = 'Simplesmente Abominável',
	AD_WINTERVEIL_SMOKEYWOOD = 'Complete a missão para recuperar as guloseimas roubadas dos Pastos Salsifumaça e receba um Obrigado dos Pastos Salsifumaça.',

	AN_WINTERVEIL_GOURMET = 'O Gourmet do Inverno',
	AD_WINTERVEIL_GOURMET = 'Durante a Festa de Inverno, use sua perícia culinária para produzir um Biscoito de Gengibre e uma Gemada.',
	AC_WINTERVEIL_GOURMET_CRITERIA1 = 'Biscoito de Gengibre', 
	AC_WINTERVEIL_GOURMET_CRITERIA2 = 'Gemada',

	AN_WINTERVEIL_PRESENTS = 'Ele Sabe Se Você Foi Mal Comportado',
	AD_WINTERVEIL_PRESENTS = 'Abra um dos presentes sob a Árvore de Inverno quando estiverem disponíveis.',

	AN_WINTERVEIL_SNOWBALL_ALLIANCE = 'Avarento',
	AD_WINTERVEIL_SNOWBALL_ALLIANCE = 'Jogue uma bola de neve no Rei Magni Barba de Bronze durante a Festa de Inverno.',

	AN_WINTERVEIL_SNOWBALL_HORDE = 'Avarento',
	AD_WINTERVEIL_SNOWBALL_HORDE = 'Jogue uma bola de neve em Cairne Casco de Sangue durante a Festa de Inverno.',

	AN_WINTERVEIL_PVP = 'Com Uma Pequena Ajuda dos Meus Amigos',
	AD_WINTERVEIL_PVP = 'Consiga 50 mortes honrosas como um Ajudante da máquina Wondervolt de Inverno.',

	--VALENTINES
	AN_VALENTINES = 'Tolo Apaixonado',
	AD_VALENTINES = 'Complete as conquistas de O Amor Está no Ar listadas abaixo.',
	AR_VALENTINES = 'O Tolo Apaixonado',

	AN_VALENTINES_ROSES = 'Meu Amor É Como uma Rosa Vermelha, Vermelha',
	AD_VALENTINES_ROSES = 'Obtenha um Buquê de Rosas Vermelhas durante a celebração de O Amor Está no Ar.',

	AN_VALENTINES_QUEST = 'Amor Perigoso',
	AD_VALENTINES_QUEST = 'Ajude o Cartel Borraquidada a deter o sinistro plano da Coroa Química S.A.',

	AN_VALENTINES_CHOCOLATES = 'Dente Doce',
	AD_VALENTINES_CHOCOLATES = 'Experimente as guloseimas de O Amor Está no Ar listadas abaixo.',
	AC_VALENTINES_CHOCOLATES_CRITERIA1 = 'Desejo Sombrio',
	AC_VALENTINES_CHOCOLATES_CRITERIA2 = 'Delícia de Leite',
	AC_VALENTINES_CHOCOLATES_CRITERIA3 = 'Surpresa Doce',
	AC_VALENTINES_CHOCOLATES_CRITERIA4 = 'Creme Muito Frutado',

	AN_VALENTINES_DRESS = 'Sorte Amorosa Está do Seu Lado',
	AD_VALENTINES_DRESS = 'Abra uma Caixa de Vestido Elegante e receba um Vestido Preto Elegante.',

	AN_VALENTINES_PIDO = 'Pernapedais Permanente',
	AD_VALENTINES_PIDO = 'Obtenha um animal de estimação Pedalpés permanente adquirindo uma Flecha de Prata Verdadeira.',

	--LUNAR
	AN_LUNAR = 'Honrar os Anciãos',
	AD_LUNAR = 'Complete as conquistas do Festival Lunar listadas abaixo.',
	AR_LUNAR = 'Ancião',

	AN_LUNAR_COIN = 'Uma Moeda de Ancestralidade',
	AD_LUNAR_COIN = 'Receba uma Moeda de Ancestralidade.',

	AN_LUNAR_COINS = '%d Moedas de Ancestralidade',
	AD_LUNAR_COINS = 'Receba %d Moedas de Ancestralidade.',

	AN_LUNAR_QUEST = 'A Bênção de Elune',
	AD_LUNAR_QUEST = 'Complete a missão A Bênção de Elune derrotando Omen.',

	AN_LUNAR_CLOTHES = 'Elegância do Festival Lunar',
	AD_LUNAR_CLOTHES = 'Compre um terno festivo ou vestido festivo com Moedas de Ancestralidade.',

	AN_LUNAR_ELDERS_DUNGEONS = 'Anciãos das Masmorras',
	AD_LUNAR_ELDERS_DUNGEONS = 'Honre os Anciãos que estão dentro das masmorras.',
	AC_LUNAR_ELDERS_DUNGEONS_8727 = 'Ancião Sussurrodistante',
	AC_LUNAR_ELDERS_DUNGEONS_8619 = 'Ancião Manhã Profunda',
	AC_LUNAR_ELDERS_DUNGEONS_8635 = 'Ancião Pedra Rachada',
	AC_LUNAR_ELDERS_DUNGEONS_8713 = 'Ancião Cantoda Estrela',
	AC_LUNAR_ELDERS_DUNGEONS_8644 = 'Ancião Forte Pedra',
	AC_LUNAR_ELDERS_DUNGEONS_8676 = 'Ancião Homem Selvagem',

	AN_LUNAR_ELDERS_HORDE = 'Anciãos da Horda',
	AD_LUNAR_ELDERS_HORDE = 'Honre os Anciãos que estão nas capitais da Horda.',
	AC_LUNAR_ELDERS_HORDE_8678 = 'Ancião Casco de Trigo em Penhalo do Trovão',
	AC_LUNAR_ELDERS_HORDE_8648 = 'Ancião Núcleo Negro na Cidade Baixa',
	AC_LUNAR_ELDERS_HORDE_8677 = 'Ancião Chifre Negro em Orgrimmar',

	AN_LUNAR_ELDERS_ALLIANCE = 'Anciãos da Aliança',
	AD_LUNAR_ELDERS_ALLIANCE = 'Honre os Anciãos que estão nas capitais da Aliança.',
	AC_LUNAR_ELDERS_ALLIANCE_8718 = 'Ancião Lâmina Veloz em Darnassus',
	AC_LUNAR_ELDERS_ALLIANCE_8866 = 'Ancião Barba de Bronze em Altaforja',
	AC_LUNAR_ELDERS_ALLIANCE_8646 = 'Ancião Grito de Martelo em Ventobravo',

	AN_LUNAR_ELDERS_EASTERN_KINGDOMS = 'Anciãos dos Reinos do Leste',
	AD_LUNAR_ELDERS_EASTERN_KINGDOMS = 'Honre os Anciãos que estão nos Reinos do Leste',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8636 = 'Ancião Pedra Estrondo em Stepes Ardentes',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8651 = 'Ancião Faixa de Ferro em Garganta Abrasadora',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8652 = 'Ancião Nascido na Cova em Brill',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8674 = 'Ancião Casco Invernal na Baia do Butim',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8716 = 'Ancião Clareira Estelar em Zul\'Gurub',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8643 = 'Ancião Pico Alto nas Terras Intrínsecas',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8675 = 'Ancião Caçador do Céu em Colina Sentinela',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8649 = 'Ancião Sobrancelha de Tempestade em Vila do Ouro',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8650 = 'Ancião Coroa de Neve na Capela da Esperança da Luz',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8642 = 'Ancião Veio de Prata em Thelsamar',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8645 = 'Ancião Obsidiana no Sepulcro',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8722 = 'Ancião Corre Prados nas Terras Pestilentas Ocidentais',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8647 = 'Ancião Ira Sino em Terras Devastadas',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8653 = 'Ancião Poco Bom em Kharanos',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8714 = 'Ancião Golpe Lunar em Scholomance',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8688 = 'Ancião Corre Ventos nas Terras Pestilentas Orientais',
	AC_LUNAR_ELDERS_EASTERN_KINGDOMS_8683 = 'Ancião Andarilho da Aurora em Crista das Chamas',

	AN_LUNAR_ELDERS_KALIMDOR = 'Anciãos de Kalimdor',
	AD_LUNAR_ELDERS_KALIMDOR = 'Honre os Anciãos que estão em Kalimdor.',
	AC_LUNAR_ELDERS_KALIMDOR_8673 = 'Ancião Casco de Sangue na Vila Casco de Sangue',
	AC_LUNAR_ELDERS_KALIMDOR_8723 = 'Ancião Vento Noturno em Bruma Negra',
	AC_LUNAR_ELDERS_KALIMDOR_8684 = 'Ancião Vidente de Sonhos em Gadgetzan',
	AC_LUNAR_ELDERS_KALIMDOR_8726 = 'Ancião Lança Brilhante em Helmgar',
	AC_LUNAR_ELDERS_KALIMDOR_8725 = 'Ancião Canção do Rio em Astranaar',
	AC_LUNAR_ELDERS_KALIMDOR_8715 = 'Ancião Folha Lâmina em Dolanaar',
	AC_LUNAR_ELDERS_KALIMDOR_8681 = 'Ancião Chifre do Trovão em Un\'Goro',
	AC_LUNAR_ELDERS_KALIMDOR_8680 = 'Ancião Totem do Vento em Anzóis',
	AC_LUNAR_ELDERS_KALIMDOR_8720 = 'Ancião Brilho do Céu em Azshara',
	AC_LUNAR_ELDERS_KALIMDOR_8670 = 'Ancião Runa Total em Colina Rasteira',
	AC_LUNAR_ELDERS_KALIMDOR_8672 = 'Ancião Pico de Pedra em Everlook',
	AC_LUNAR_ELDERS_KALIMDOR_8686 = 'Ancião Montanha Alta em Acampamento Taurajo',
	AC_LUNAR_ELDERS_KALIMDOR_8654 = 'Ancião Pedra de Brasa em Silithus',
	AC_LUNAR_ELDERS_KALIMDOR_8671 = 'Ancião Totem de Raiva em Tanaris',
	AC_LUNAR_ELDERS_KALIMDOR_8724 = 'Ancião Orvalho Matinal na Pista de Corrida Miragem',
	AC_LUNAR_ELDERS_KALIMDOR_8685 = 'Ancião Andarilho da Névoa em Martelo Sinistro',
	AC_LUNAR_ELDERS_KALIMDOR_8721 = 'Ancião Teceluade Estrelas em Auberdine',
	AC_LUNAR_ELDERS_KALIMDOR_8717 = 'Ancião Guardião da Lua no Cruzamento',
	AC_LUNAR_ELDERS_KALIMDOR_8719 = 'Ancião Lâmina Cantante no Posto Cenariano',
	AC_LUNAR_ELDERS_KALIMDOR_8682 = 'Ancião Vidente do Céu no Posto Vento Livre',
	AC_LUNAR_ELDERS_KALIMDOR_8679 = 'Ancião Totem Sombrio em Feralas',

	--NOBLEGARDEN
	AN_NOBLEGARDEN_CLOTHES = 'O Melhor de Domingo',
	AD_NOBLEGARDEN_CLOTHES = 'Descubra a Camiseta de Smokingue Branco e Calça de Smokingue Preto abrindo Ovos Coloridos Brilhantes durante a celebração do Jardim Nobre.',
	AC_NOBLEGARDEN_CLOTHES_CRITERIA1 = 'Camiseta de Smokingue Branco',
	AC_NOBLEGARDEN_CLOTHES_CRITERIA2 = 'Calça de Smokingue Preto',

	AN_NOBLEGARDEN_DRESS = 'Vestida para a Ocasião',
	AD_NOBLEGARDEN_DRESS = 'Descubra um Vestido Elegante abrindo Ovos Coloridos Brilhantes durante a celebração do Jardim Nobre.',

	--CHILDRENS WEEK
	AN_CHILDREN = 'Pelas Crianças',
	AD_CHILDREN = 'Complete as conquistas da Semana das Crianças listadas abaixo.',
	AR_CHILDREN = 'Patrocinador',
	
	AN_CHILDREN_PET = 'Ah, Não É Fofo?',
	AD_CHILDREN_PET = 'Obtenha um dos animais de estimação de recompensa da Semana das Crianças.',

	AN_CHILDREN_PETS = 'Babá Veterana',
	AD_CHILDREN_PETS = 'Adquira o Ovo de Egbert, o Sono do Willy e a Coleira de Treino de Elekk em um personagem.',
	AC_CHILDREN_PETS1 = 'Coleira de Treino de Elekk',
	AC_CHILDREN_PETS2 = 'Sono do Willy',
	AC_CHILDREN_PETS3 = 'Ovo de Egbert',

	--MIDSUMMER
	AN_MIDSUMMER = 'O Guardião das Chamas',
	AD_MIDSUMMER = 'Complete as conquistas do Solstício listadas abaixo.',
	AR_MIDSUMMER = 'Guardião das Chamas',

	AN_MIDSUMMER_QUEST1 = 'Rei do Festival do Fogo',
	AD_MIDSUMMER_QUEST1 = 'Complete a missão, "Recompensa de um Ladrão", roubando as chamas das capitais inimigas.',

	AN_MIDSUMMER_AHUNE = 'Gelando o Senhor do Gelo',
	AD_MIDSUMMER_AHUNE = 'Mate Ahune nos Currais.',

	AN_MIDSUMMER_DESECRATION_HORDE = 'Profanação da Aliança',
	AD_MIDSUMMER_DESECRATION_HORDE = 'Complete as conquistas Apagando os Reinos do Leste, Kalimdor e Terralém.',
	
	AN_MIDSUMMER_DESECRATION_HORDE_KALIMDOR = 'Apagando Kalimdor',
	AD_MIDSUMMER_DESECRATION_HORDE_KALIMDOR = 'Profane as fogueiras da Aliança em Kalimdor.',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11744 = 'Pântano Ventoempoeirado',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11734 = 'Vale dos Espinhos',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11738 = 'Ilha da Névoa Sangrenta',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11740 = 'Costa Negra',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11746 = 'Feralas',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11760 = 'Silithus',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11753 = 'Teldrassil',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11762 = 'Tanaris',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11741 = 'Desolação',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11763 = 'Helmgar',
	AC_MIDSUMMER_DESECRATION_HORDE_KALIMDOR_CRITERIA_11735 = 'Ilha Névoa Lazúli',

	AN_MIDSUMMER_DESECRATION_HORDE_OUTLAND = 'Apagando Terralém',
	AD_MIDSUMMER_DESECRATION_HORDE_OUTLAND = 'Profane as fogueiras da Aliança em Terralém.',
	AC_MIDSUMMER_DESECRATION_HORDE_OUTLAND_CRITERIA_11736 = 'Montanhas da Lâmina',
	AC_MIDSUMMER_DESECRATION_HORDE_OUTLAND_CRITERIA_11750 = 'Nagrand',
	AC_MIDSUMMER_DESECRATION_HORDE_OUTLAND_CRITERIA_11759 = 'Tempestade Etérea',
	AC_MIDSUMMER_DESECRATION_HORDE_OUTLAND_CRITERIA_11752 = 'Vale da Lua Negra',
	AC_MIDSUMMER_DESECRATION_HORDE_OUTLAND_CRITERIA_11754 = 'Floresta Terokkar',
	AC_MIDSUMMER_DESECRATION_HORDE_OUTLAND_CRITERIA_11758 = 'Pântano Zangar',
	AC_MIDSUMMER_DESECRATION_HORDE_OUTLAND_CRITERIA_11747 = 'Península do Fogo do Inferno',

	AN_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS = 'Apagando os Reinos do Leste',
	AD_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS = 'Profane as fogueiras da Aliança nos Reinos do Leste.',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11751 = 'Montanhas Cristinas',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11742 = 'Dun Morogh',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11745 = 'Floresta de Elwynn',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11749 = 'Loch Modan',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11732 = 'Planalto de Arathi',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11739 = 'Stepes Ardentes',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11761 = 'Selva do Espinhaço',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11755 = 'Terras Intrínsecas',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11756 = 'Terras Pestilentas Ocidentais',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11581 = 'Costa Negra',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11748 = 'Colinas Brazeadas',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11737 = 'Terras Devastadas',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11743 = 'Floresta do Crepúsculo',
	AC_MIDSUMMER_DESECRATION_HORDE_EASTERN_KINGDOMS_CRITERIA_11757 = 'Brejal',

	AN_MIDSUMMER_DESECRATION_ALLIANCE = 'Profanação da Horda',
	AD_MIDSUMMER_DESECRATION_ALLIANCE = 'Complete as conquistas Apagando os Reinos do Leste, Kalimdor e Terralém.',

	AN_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR = 'Apagando Kalimdor',
	AD_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR = 'Profane as fogueiras da Horda em Kalimdor.',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11803 = 'Helmgar',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11785 = 'Mil Agulhas',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11765 = 'Vale dos Espinhos',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11769 = 'Desolação',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11773 = 'Feralas',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11777 = 'Mulgore',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11800 = 'Silithus',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11780 = 'Montanhas Pedra Coberta',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11802 = 'Tanaris',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11783 = 'As Esteras',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11770 = 'Durotar',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_KALIMDOR_CRITERIA_11771 = 'Pântano Ventoempoeirado',

	AN_MIDSUMMER_DESECRATION_ALLIANCE_OUTLAND = 'Apagando Terralém',
	AD_MIDSUMMER_DESECRATION_ALLIANCE_OUTLAND = 'Profane as fogueiras da Horda em Terralém.',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_OUTLAND_CRITERIA_11767 = 'Montanhas da Lâmina',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_OUTLAND_CRITERIA_11799 = 'Tempestade Etérea',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_OUTLAND_CRITERIA_11782 = 'Floresta Terokkar',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_OUTLAND_CRITERIA_11775 = 'Península do Fogo do Inferno',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_OUTLAND_CRITERIA_11787 = 'Pântano Zangar',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_OUTLAND_CRITERIA_11778 = 'Nagrand',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_OUTLAND_CRITERIA_11779 = 'Vale da Lua Negra',

	AN_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS = 'Apagando os Reinos do Leste',
	AD_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS = 'Profane as fogueiras da Horda nos Reinos do Leste.',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11766 = 'Terras Inóspitas',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11772 = 'Bosque do Cantar Eterno',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11774 = 'Terras Fantasma',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11776 = 'Colinas Brazeadas',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11768 = 'Stepes Ardentes',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11781 = 'Pântano das Mágoas',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11764 = 'Planalto de Arathi',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11580 = 'Floresta de Pinho Prateado',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11801 = 'Selva do Espinhaço',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11784 = 'Terras Intrínsecas',
	AC_MIDSUMMER_DESECRATION_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11786 = 'Clareira Tirisfal',

	AN_MIDSUMMER_FLAME_KEEPER_HORDE = 'As Chamas de Azeroth',
	AD_MIDSUMMER_FLAME_KEEPER_HORDE = 'Complete as conquistas Guardião das Chamas dos Reinos do Leste, Kalimdor e Terralém.',

	AN_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR = 'Guardião das Chamas de Kalimdor',
	AD_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR = 'Honre as chamas de Kalimdor.',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11841 = 'Vale dos Espinhos',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11845 = 'Desolação',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11846 = 'Durotar',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11847 = 'Pântano Ventoempoeirado',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11849 = 'Feralas',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11852 = 'Mulgore',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11859 = 'As Esteras',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11839 = 'Helmgar',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11836 = 'Silithus',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11856 = 'Montanhas Pedra Coberta',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11861 = 'Mil Agulhas',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_KALIMDOR_CRITERIA_11838 = 'Tanaris',

	AN_MIDSUMMER_FLAME_KEEPER_HORDE_OUTLAND = 'Guardião das Chamas de Terralém',
	AD_MIDSUMMER_FLAME_KEEPER_HORDE_OUTLAND = 'Honre as chamas de Terralém.',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_OUTLAND_CRITERIA_11851 = 'Península do Fogo do Inferno',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_OUTLAND_CRITERIA_11835 = 'Tempestade Etérea',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_OUTLAND_CRITERIA_11855 = 'Vale da Lua Negra',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_OUTLAND_CRITERIA_11858 = 'Floresta Terokkar',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_OUTLAND_CRITERIA_11854 = 'Nagrand',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_OUTLAND_CRITERIA_11863 = 'Pântano Zangar',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_OUTLAND_CRITERIA_11843 = 'Montanhas da Lâmina',

	AN_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS = 'Guardião das Chamas dos Reinos do Leste',
	AD_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS = 'Honre as chamas dos Reinos do Leste.',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11844 = 'Stepes Ardentes',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11840 = 'Planalto de Arathi',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11584 = 'Floresta de Pinho Prateado',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11837 = 'Selva do Espinhaço',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11860 = 'Terras Intrínsecas',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11850 = 'Terras Fantasma',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11862 = 'Clareira Tirisfal',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11853 = 'Colinas Brazeadas',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11848 = 'Bosque do Cantar Eterno',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11857 = 'Pântano das Mágoas',
	AC_MIDSUMMER_FLAME_KEEPER_HORDE_EASTERN_KINGDOMS_CRITERIA_11842 = 'Terras Inóspitas',

	AN_MIDSUMMER_FLAME_KEEPER_ALLIANCE = 'As Chamas de Azeroth',
	AD_MIDSUMMER_FLAME_KEEPER_ALLIANCE = 'Complete as conquistas Guardião das Chamas dos Reinos do Leste, Kalimdor e Terralém.',

	AN_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR = 'Guardião das Chamas de Kalimdor',
	AD_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR = 'Honre as chamas de Kalimdor.',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11833 = 'Tanaris',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11805 = 'Vale dos Espinhos',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11809 = 'Ilha da Névoa Sangrenta',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11812 = 'Desolação',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11817 = 'Feralas',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11824 = 'Teldrassil',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11806 = 'Ilha Névoa Lazúli',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11834 = 'Helmgar',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11831 = 'Silithus',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11815 = 'Pântano Ventoempoeirado',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_KALIMDOR_CRITERIA_11811 = 'Costa Negra',

	AN_MIDSUMMER_FLAME_KEEPER_ALLIANCE_OUTLAND = 'Guardião das Chamas de Terralém',
	AD_MIDSUMMER_FLAME_KEEPER_ALLIANCE_OUTLAND = 'Honre as chamas de Terralém.',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_OUTLAND_CRITERIA_11807 = 'Montanhas da Lâmina',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_OUTLAND_CRITERIA_11830 = 'Tempestade Etérea',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_OUTLAND_CRITERIA_11823 = 'Vale da Lua Negra',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_OUTLAND_CRITERIA_11829 = 'Pântano Zangar',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_OUTLAND_CRITERIA_11818 = 'Península do Fogo do Inferno',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_OUTLAND_CRITERIA_11821 = 'Nagrand',   
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_OUTLAND_CRITERIA_11825 = 'Floresta Terokkar',  

	AN_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS = 'Guardião das Chamas dos Reinos do Leste',
	AD_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS = 'Honre as chamas dos Reinos do Leste.',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11816 = 'Floresta de Elwynn',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11810 = 'Stepes Ardentes',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11813 = 'Dun Morogh',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11822 = 'Montanhas Cristanas',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11832 = 'Selva do Espinhaço',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11826 = 'Terras Intrínsecas',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11583 = 'Costa Negra',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11827 = 'Terras Pestilentas Ocidentais',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11808 = 'Terras Devastadas',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11819 = 'Colinas Brazeadas',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11814 = 'Floresta do Crepúsculo',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11820 = 'Loch Modan',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11804 = 'Planalto de Arathi',
	AC_MIDSUMMER_FLAME_KEEPER_ALLIANCE_EASTERN_KINGDOMS_CRITERIA_11828 = 'Brejal',

	--BREWFEST
	AN_BREWFEST = 'Mestre Cervejeiro',
	AD_BREWFEST = 'Complete as conquistas da Festança listadas abaixo.',
	AR_BREWFEST = 'Mestre Cervejeiro',

	AN_BREWFEST_WOLPERTINGER = 'Seu Wolpertinger Demora?',
	AD_BREWFEST_WOLPERTINGER = 'Obtenha um animal de estimação Wolpertinger.',

	AN_BREWFEST_COREN_DIREBREW = 'Festança Cerveja Negra',
	AD_BREWFEST_COREN_DIREBREW = 'Mate Coren Cerveja Negra.',

	AN_BREWFEST_QUEST1 = 'Abaixo o Ferro Negro',
	AD_BREWFEST_QUEST1 = 'Defenda o acampamento da Festança do ataque do Ferro Negro e complete a missão, "Esta Vez, Quando Eu Estava Bêbado..."',

	AN_BREWFEST_BEER_CLUB = 'Cerveja do Mês',
	AD_BREWFEST_BEER_CLUB = 'Junte-se ao clube Cerveja do Mês.',

	AN_BREWFEST_MOUNT = 'Tenho Barril, Vou Viajar',
	AD_BREWFEST_MOUNT = 'Obtenha uma montaria da Festança.',

	--LONG TRIP
	AC_WORLDEVENTS_TRIP = 'Que Viagem Longa e Estranha',
	AD_WORLDEVENTS_TRIP = 'Complete as conquistas de eventos mundiais listadas abaixo.',

	--TBC
	AN_DOLCE = 'Meu Armazenamento É "Gigantique"',
	AD_DOLCE = 'Equipe a Bolsa "Gigantique" de Haris Pilton.',

	AN_QUESTS_HELLFIRE_PENINSULA = 'Ao Fogo do Inferno e de Volta',
	AD_QUESTS_HELLFIRE_PENINSULA = 'Complete as histórias da Península do Fogo do Inferno listadas abaixo.',
	TBC_QUEST_10388 = 'Disrupt a Legião Ardente',
	TBC_QUEST_10389 = 'Intenções Cruéis',
	TBC_QUEST_10876 = 'A Mão de Kargath',
	TBC_QUEST_10258 = 'Posto Quebra-Espinha',
	TBC_QUEST_9406 = 'Os Mag\'har',
	TBC_QUEST_9370 = 'Torre do Falcão',
	TBC_QUEST_10351 = 'Posto Cenariano',

	TBC_QUEST_10397 = 'Disrupt a Legião Ardente',
	TBC_QUEST_10400 = 'Destitua o Suserano',
	TBC_QUEST_9545 = 'Em Busca de Sedai',
	TBC_QUEST_10935 = 'O Exorcismo do Coronel Jules',
	TBC_QUEST_10937 = 'Treine o Mestre-de-Armas',
	TBC_QUEST_9383 = 'Templo de Telhamat',
	TBC_QUEST_10630 = 'Verdes, Mas Não Orcs',
	

	AN_QUESTS_ZANGARMASH = 'Mistérios do Pântano',
	AD_QUESTS_ZANGARMASH = 'Complete as histórias de Pântano Zangar listadas abaixo.',
	TBC_QUEST_9772 = 'Posto Rato do Pântano',
	TBC_QUEST_9904 = 'Zabra\'jin',
	TBC_QUEST_10118 = 'A Defesa de Zabra\'jin',
	TBC_QUEST_9803 = 'Diplomacia Draenei',
	TBC_QUEST_9783 = 'Telredor',
	TBC_QUEST_9902 = 'Porto de Orebor',
	TBC_QUEST_9709 = 'Não Coma ESSES Cogumelos!',
	TBC_QUEST_9732 = 'Drenando o Pântano',
	TBC_QUEST_9788 = 'Salvando os Sporeloks',
	TBC_QUEST_9726 = 'Uma Viagem com os Esporolinos',
	
	AN_QUESTS_TERROKAR = 'Terror de Terokkar',
	AD_QUESTS_TERROKAR = 'Complete as histórias da Floresta Terokkar listadas abaixo.',
	TBC_QUEST_10879 = 'A Ofensiva de Skettis',
	TBC_QUEST_10881 = 'Caravana de Refugiados',
	TBC_QUEST_10915 = 'Acampamento Base Sha\'tari',
	TBC_QUEST_9951 = 'O Segredo do Guardião',
	TBC_QUEST_10042 = 'Forte de Alleria',
	TBC_QUEST_10043 = 'Forte Quebra-Pedra',
	
	AN_QUESTS_NAGRAND = 'Pancada de Nagrand',
	AD_QUESTS_NAGRAND = 'Complete as histórias de Nagrand listadas abaixo.',
	TBC_QUEST_10172 = 'Nascimento de um Líder de Guerra',
	TBC_QUEST_9977 = 'O Anel de Sangue',
	TBC_QUEST_9853 = 'Trono dos Elementos',
	TBC_QUEST_9934 = 'Lantresor da Lâmina',
	TBC_QUEST_9868 = 'Os Sangue Negro',
	TBC_QUEST_9937 = 'Ameaças a Nagrand',
	TBC_QUEST_9852 = 'O Combate de Sangue Definitivo',
	TBC_QUEST_9925 = 'Encontrando os Etéreos',
	TBC_QUEST_9955 = 'As Aventuras de Corki',
	TBC_QUEST_9933 = 'Lantresor da Lâmina',
	TBC_QUEST_9873 = 'Os Sangue Negro',
	TBC_QUEST_10011 = 'Ameaças a Nagrand',
	
	AN_QUESTS_BLADES_EDGE_MTNS = 'Na Lâmina',
	AD_QUESTS_BLADES_EDGE_MTNS = 'Complete as histórias das Montanhas da Lâmina listadas abaixo..',
	TBC_QUEST_10504 = 'Sylvanaar',
	TBC_QUEST_10671 = 'Estação Toshley',
	TBC_QUEST_10806 = 'A Ameaça dos Gronn',
	TBC_QUEST_10505 = 'Fortaleza Senhor do Trovão',
	TBC_QUEST_10742 = 'Reencontro',
	TBC_QUEST_10867 = 'Os Mok\'Nathal',
	TBC_QUEST_10748 = 'Floresta Ruuan',
	
	AN_QUESTS_NETHERSTORM = 'Adentrando o Nether',
	AD_QUESTS_NETHERSTORM = 'Complete as histórias da Tempestade Etérea listadas abaixo.',
	TBC_QUEST_10409 = 'Socrethar',
	TBC_QUEST_10240 = 'A Torre Violeta',
	TBC_QUEST_10249 = 'Proteja a Área 52!',
	TBC_QUEST_10439 = 'Destruindo o Devorador de Tudo',
	TBC_QUEST_10221 = 'Construindo o Foguete Nether X-52',
	TBC_QUEST_10276 = 'O Consórcio',
	
	AN_QUESTS_SHADOWMOON = 'Sombra do Traidor',
	AD_QUESTS_SHADOWMOON = 'Complete as histórias do Vale da Lua Negra listadas abaixo.',
	TBC_QUEST_10744 = 'Notícias de Vitória',
	TBC_QUEST_11041 = 'Pico Etereal',
	TBC_QUEST_10645 = 'O Primeiro Cavaleiro da Morte',
	TBC_QUEST_10651 = 'Poder Emprestado',
	TBC_QUEST_11052 = 'A Promessa de Akama',
	TBC_QUEST_10588 = 'A Cifra da Perdição',
	TBC_QUEST_10679 = 'Armas Antidemônio',
	TBC_QUEST_10808 = 'O Conclave Sombrio',
	
	AN_HEMET_QUESTS_NAGRAND = 'Colinas Como Elekk Brancos',
	AD_HEMET_QUESTS_NAGRAND = 'Complete todas as missões de Hemet Nesingwary em Nagrand, incluindo O Combate de Sangue Definitivo.',

	HEROIC_NAME_PATTERN = 'Heroico: %s',
	HEROIC_DESCRIPTION_PATTERN = '%s em Dificuldade Heroica',

	AN_HELLFIRE_RAMPARTS = 'Amuralhadas do Inferno',
	AD_HELLFIRE_RAMPARTS = 'Derrote os líderes das Amuralhadas do Inferno',
	AC_BOSS_17308 = 'Omor, o Intacto',
	AC_BOSS_17537 = 'Nazan & Vazruden',
	AC_BOSS_17306 = 'Guardião Gargolmar',

	AN_BLOOD_FURNACE = 'A Forja de Sangue',
	AD_BLOOD_FURNACE = 'Derrote Keli\'dan, o Quebrador',

	AN_SLAVE_PENS = 'Os Currais',
	AD_SLAVE_PENS = 'Derrote Quagmirran',

	AN_UNDERBOG = 'Pântano Subterrâneo',
	AD_UNDERBOG = 'Derrote a Espreitadora Negra',

	AN_MANA_TOMBS = 'Tumbas de Mana',
	AD_MANA_TOMBS = 'Derrote o Príncipe-Nexus Shaffar',

	AN_AUCHENAI_CRYPTS = 'Criptas Auchenai',
	AD_AUCHENAI_CRYPTS = 'Derrote o Exarca Maladaar',

	AN_OLD_HILLSBRAD = 'A Fuga de Durnholde',
	AD_OLD_HILLSBRAD = 'Derrote o Caçador de Eras',

	AN_SETHEKK_HALLS = 'Salões Sethekk',
	AD_SETHEKK_HALLS = 'Derrote o Rei Talon Ikiss',

	AN_STEAMVAULT = 'A Câmara de Vapor',
	AD_STEAMVAULT = 'Derrote o Senhor da Guerra Kalithresh',

	AN_SHADOW_LABYRINTH = 'Labirinto Sombrio',
	AD_SHADOW_LABYRINTH = 'Derrote Murmur',

	AN_SHATTERED_HALLS = 'Os Salões Estilhaçados',
	AD_SHATTERED_HALLS = 'Derrote o Líder de Guerra Kargath Lâminaferra',

	AN_BLACK_MORASS = 'A Abertura do Portal Negro',
	AD_BLACK_MORASS = 'Derrote Aeonus',

	AN_BOTANICA = 'A Botânica',
	AD_BOTANICA = 'Derrote o Ressonante Distorcido',

	AN_MECHANAR = 'O Maquinário',
	AD_MECHANAR = 'Derrote Pathaleon, o Calculista',

	AN_ARCATRAZ = 'O Arcatraz',
	AD_ARCATRAZ = 'Derrote o Arauto Skyriss',
	
	AN_MAGISTERS_TERRACE = 'Terraço dos Magísteres',
	AD_MAGISTERS_TERRACE = 'Derrote Kael\'thas Sumidouro do Sol',
	
	AN_TBC_DUNGEONS = 'Mestre das Masmorras de Terralém',
	AD_TBC_DUNGEONS = 'Complete as conquistas de masmorras de The Burning Crusade listadas abaixo.',

	AN_TBC_DUNGEONS_HERO = 'Herói das Masmorras de Terralém',
	AD_TBC_DUNGEONS_HERO = 'Complete as conquistas de masmorras heroicas de The Burning Crusade listadas abaixo.',

	AN_OUTLAND_HERO = 'Herói de Terralém',
	AD_OUTLAND_HERO = 'Obtenha as conquistas de raides listadas abaixo.',
	AR_OUTLAND_HERO = 'Herói de Terralém',
	
	AN_OUTLAND_GREAT_HERO = 'Grande Herói de Terralém',
	AD_OUTLAND_GREAT_HERO = 'Obtenha as conquistas de raides e masmorras listadas abaixo.',
	AR_OUTLAND_GREAT_HERO = 'Grande Herói de Terralém',

	AN_RAVEN_LORD = 'Rédeas do Senhor Corvo',
	AD_RAVEN_LORD = 'Obtenha as Rédeas do Senhor Corvo de Anzu nos Salões Sethekk.',

	AN_KARAZHAN = 'Karazhan',
	AD_KARAZHAN = 'Derrote o Príncipe Malchezaar em Karazhan.',

	AN_GRUUL = 'Covil de Gruul',
	AD_GRUUL = 'Derrote Gruul, o Matador de Dragões, no Covil de Gruul.',

	AN_MAGTHERIDON = 'Covil de Magtheridon',
	AD_MAGTHERIDON = 'Derrote Magtheridon no Covil de Magtheridon.',
	
	AN_ZULAMAN = 'Zul\'Aman',
	AD_ZULAMAN = 'Derrote Zul\'jin em Zul\'Aman.',
	
	AN_SUNWELL = 'Planalto Nascente do Sol',
	AD_SUNWELL = 'Derrote Kil\'jaeden no Planalto Nascente do Sol.',

	AN_TBC_PHASE_1 = 'Invasor de Terralém - Fase 1',
	AD_TBC_PHASE_1 = 'Complete as conquistas de raides de The Burning Crusade listadas abaixo.',
	AN_TBC_PHASE_2 = 'Invasor de Terralém - Fase 2',
	AD_TBC_PHASE_2 = 'Complete as conquistas de raides de The Burning Crusade listadas abaixo.',
	AN_TBC_PHASE_3 = 'Invasor de Terralém - Fase 3',
	AD_TBC_PHASE_3 = 'Complete as conquistas de raides de The Burning Crusade listadas abaixo.',
	AN_TBC_PHASE_4 = 'Invasor de Terralém - Fase 4',
	AD_TBC_PHASE_4 = 'Complete as conquistas de raides de The Burning Crusade listadas abaixo.',
	AN_TBC_PHASE_5 = 'Invasor de Terralém - Fase 5',
	AD_TBC_PHASE_5 = 'Complete as conquistas de raides de The Burning Crusade listadas abaixo.',

	FACTION_946 = 'Fortaleza da Honra',
	FACTION_947 = 'Thrallmar',
	FACTION_942 = 'Expedição Cenariana',
	FACTION_1011 = 'Cidade Baixa',
	FACTION_989 = 'Guardiões do Tempo',
	FACTION_935 = 'Os Sha\'tar',
	FACTION_609 = 'Círculo Cenariano',

	AN_TBC_DUNGEON_REPUTATIONS = 'O Cruzado de The Burning Crusade',
	AD_TBC_DUNGEON_REPUTATIONS = 'Eleve todas as reputações de masmorras de The Burning Crusade para Exaltado.',
	
	AN_CENARION_CIRCLE = 'Guardião de Cenarius',
	AD_CENARION_CIRCLE = 'Alcance status exaltado com o Círculo Cenariano e a Expedição Cenariana.',

	AN_SHATTRATH_REP = 'Shattrath Dividida',
	AD_SHATTRATH_REP = 'Alcance status exaltado com Os Aureus ou Os Aldor.',

	AN_OGRILA = 'Uma Missão por Dia Mantém os Ogros Longe',
	AD_OGRILA = 'Alcance status exaltado com Ogri\'la.',

	AN_SPOREGGAR = 'O Czar de Esporolino',
	AD_SPOREGGAR = 'Alcance status exaltado com Esporolino.',

	AN_CONSORTIUM = 'Chefe Oficial Exaltado',
	AD_CONSORTIUM = 'Alcance status exaltado com O Consórcio.',

	AN_MAGHAR = 'Mag\'har de Draenor',
	AD_MAGHAR = 'Alcance status exaltado com Os Mag\'har.',

	AN_KURENAI = 'Oh Meu, Kurenai',
	AD_KURENAI = 'Alcance status exaltado com os Kurenai.',

	AN_NETHERWINGS = 'Nas Asas de Nether',
	AD_NETHERWINGS = 'Alcance status exaltado com Etereal Asa.',

	AN_SKYSHATTERED = 'Esmorecador do Céu',
	AD_SKYSHATTERED = 'Derrote o Capitão Esmoreça o Céu na corrida do Clã Fogacho no Pico Etereal.',

	AN_AMETHYST_EYE = 'O Olho Violeta',
	AD_AMETHYST_EYE = 'Alcance status exaltado com O Olho Violeta.',

	AN_SCALE_OF_THE_SANDS = 'A Balança das Areias',
	AD_SCALE_OF_THE_SANDS = 'Alcance status exaltado com A Balança das Areias.',

	AN_ASHTONGUE_DEATHSWORN = 'Jurado aos Lançadores de Morte',
	AD_ASHTONGUE_DEATHSWORN = 'Alcance status exaltado com os Lançadores de Morte Cinza-Arvore.',

	AN_SHATTERED_SUN = 'Você É Tão Ofensivo',
	AD_SHATTERED_SUN = 'Alcance status exaltado com a Ofensiva do Sol Estilhaçado.',

	AN_SKYGUARD = 'Voando Alto Sobre Skettis',
	AD_SKYGUARD = 'Alcance status exaltado com a Guarda do Céu Sha\'tari.',

	AN_HIPPOGRYPH = 'Hipogrifo de Guerra Cenariano',
	AD_HIPPOGRYPH = 'Obtenha o Hipogrifo de Guerra Cenariano da Expedição Cenariana em Pântano Zangar.',

	AN_DIPLOMAT = 'O Diplomata',
	AD_DIPLOMAT_ALLIANCE = 'Eleve seu nível de reputação de indiferente para exaltado com Balde Madeira de Pinho, Esporolino e os Kurenai.',
	AD_DIPLOMAT_HORDE = 'Eleve seu nível de reputação de indiferente para exaltado com Balde Madeira de Pinho, Esporolino e Os Mag\'har.',
	AC_DIPLOMAT_576 = 'Exaltado com Balde Madeira de Pinho',
	AC_DIPLOMAT_970 = 'Exaltado com os Esporolino',
	AC_DIPLOMAT_978 = 'Exaltado com os Kurenai',
	AC_DIPLOMAT_941 = 'Exaltado com Os Mag\'har',

	AN_MR_PINCHY = 'Sr. Pinchy!',
	AD_MR_PINCHY = 'Pesque Sr. Pinchy em Terralém.',

	AN_FISHING_BOOK = 'Peixes Não Deixam Pegadas',
	AD_FISHING_BOOK = 'Aprenda a habilidade de encontrar peixes.',

	AN_ACCOMPLISHED_ANGLER = 'Pescador Realizado',
	AD_ACCOMPLISHED_ANGLER = 'Complete as conquistas de pescaria listadas abaixo.',

	AN_TBC_DAILY_FISH = 'O Velho Barlo Que Todos Dono São',
	AD_TBC_DAILY_FISH = 'Complete cada uma das 5 missões diárias de pescaria do Velho Barlo listadas abaixo.',
	AC_TBC_DAILY_FISH1 = 'Crocoliscos na Cidade',
	AC_TBC_DAILY_FISH2 = 'Ladrões de Isca',
	AC_TBC_DAILY_FISH3 = 'Filé de Sangue Profano',
	AC_TBC_DAILY_FISH4 = 'O Que Escapou',
	AC_TBC_DAILY_FISH5 = 'Pescar Camarão Não É Fácil',

	AN_OLD_IRONJAW = 'Velho Queixo de Ferro',
	AD_OLD_IRONJAW = 'Pesque o Velho Queixo de Ferro em Altaforja.',

	AN_OLD_CRAFTY = 'Velho Habilidoso',
	AD_OLD_CRAFTY = 'Pesque o Velho Habilidoso em Orgrimmar.',

	AN_FISHING_DIPLOMAT = 'O Diplomata da Pescaria',
	AD_FISHING_DIPLOMAT = 'Pesque algo em Orgrimmar e Ventobravo.',
	AC_FISHING_DIPLOMAT1 = 'Orgrimmar',
	AC_FISHING_DIPLOMAT2 = 'Ventobravo',

	AN_CAPTAIN_RUMSEY = 'Lager do Capitão Rumsey',
	AD_CAPTAIN_RUMSEY = 'Cerveje um pouco do Lager do Capitão Rumsey.',

	AN_SECOND_RING = 'O Anel 2',
	AD_SECOND_RING = 'Obtenha O Anel 2 de um Saco de Tesouros de Pesca.',

	AN_TBC_DAILY_COOKING = 'Aumentando o Nível',
	AD_TBC_DAILY_COOKING = 'Complete cada uma das 4 missões diárias de culinária do Rokk listadas abaixo.',
	AC_TBC_DAILY_COOKING1 = 'Manalicioso',
	AC_TBC_DAILY_COOKING2 = 'Sopa para a Alma',
	AC_TBC_DAILY_COOKING3 = 'Vingança É Saborosa',
	AC_TBC_DAILY_COOKING4 = 'Ensopado Super Quente',

	AN_TBC_COOKING_RECIPES = 'O Gourmet de Terralém',
	AD_TBC_COOKING_RECIPES = 'Cozinhe cada uma das receitas de culinária de Terralém listadas abaixo.',

	AN_HAIL_CHEF = 'Salve o Chefe',
	AD_HAIL_CHEF = 'Complete as conquistas de culinária listadas abaixo.',

	AN_EXPLORE_OUTLAND = 'Explorar Terralém',
	AD_EXPLORE_OUTLAND = 'Explore as regiões de Terralém.',

	AN_MIDDLE_RARE = 'Mal Passada',
	AD_MIDDLE_RARE = 'Mate uma das criaturas extremamente raras e difíceis de encontrar de Terralém listadas abaixo.',
	AN_BLOODY_RARE = 'Raro Sangrento',
	AD_BLOODY_RARE = 'Mate todas as criaturas extremamente raras e difíceis de encontrar de Terralém listadas abaixo.',
	TBC_NPC_18695 = 'Embaixador Jerrikar',
	TBC_NPC_18682 = 'Espreitador do Pântano',
	TBC_NPC_18697 = 'Engenheiro Chefe Lorthander',
	TBC_NPC_18681 = 'Emissário Serpentina',
	TBC_NPC_18694 = 'Collidus, o Observador das Distorções',
	TBC_NPC_18689 = 'Aleijador',
	TBC_NPC_18686 = 'Pregador da Perdição Jurim',
	TBC_NPC_18698 = 'Ever-Core, o Punidor',
	TBC_NPC_18678 = 'Fulgorge',
	TBC_NPC_17144 = 'Goredente',
	TBC_NPC_18692 = 'Hemathion',
	TBC_NPC_18696 = 'Kraator',
	TBC_NPC_18680 = 'Marticar',
	TBC_NPC_18677 = 'Mekthorg, o Selvagem',
	TBC_NPC_18690 = 'Morcrush',
	TBC_NPC_20932 = 'Nuramoc',
	TBC_NPC_18685 = 'Okrek',
	TBC_NPC_18693 = 'Orador Mar\'grom',
	TBC_NPC_18683 = 'Caçador do Vazio Yar',
	TBC_NPC_18679 = 'Vorakem, o Orador da Perdição',

	AN_PREPATCH_QUEST = 'Adentrando a Brecha',
	AD_PREPATCH_QUEST = 'Participante da Batalha pelo Portal Negro. Portador do Tabardo do Protetor.',

	AN_RIDING_75 = 'Bora Bora!',
	AD_RIDING_75 = 'Aprenda a perícia de montaria de Aprendiz.',
	AN_RIDING_150 = 'Rápido e Furioso',
	AD_RIDING_150 = 'Aprenda a perícia de montaria de Competente.',
	AN_RIDING_225 = 'Adentrando o Azul Selvagem Além',
	AD_RIDING_225 = 'Aprenda a perícia de montaria de Especialista.',
	AN_RIDING_300 = 'A Coisa Certa',
	AD_RIDING_300 = 'Aprenda a perícia de montaria de Artesão.',

	AN_ATTUNE_SHATTERED_HALLS = 'Mais Quente Que o Inferno',
	AD_ATTUNE_SHATTERED_HALLS = 'Obtenha a Chave dos Salões Estilhaçados.',
	AN_ATTUNE_ARCATRAZ = 'Como Invadir o Arcatraz',
	AD_ATTUNE_ARCATRAZ = 'Obtenha a Chave do Arcatraz.',
	AN_ATTUNE_KARAZHAN = 'O Toque do Mestre',
	AD_ATTUNE_KARAZHAN = 'Obtenha A Chave do Mestre.',
	AN_ATTUNE_NIGHT_BANE = 'Escavando o Passado',
	AD_ATTUNE_NIGHT_BANE = 'Obtenha a Urna Enegrecida e derrote a Desgraça Noturna em Karazhan.',
	AN_ATTUNE_SSC = 'A Clava de Kar\'desh',
	AD_ATTUNE_SSC = 'Ganhe acesso à Caverna Serpentária.',
	AN_ATTUNE_EYE = 'A Chave da Tempestade',
	AD_ATTUNE_EYE = 'Obtenha A Chave da Tempestade.',
	AN_ATTUNE_HYJAL = 'Os Frascos da Eternidade',
	AD_ATTUNE_HYJAL = 'Ganhe acesso à Batalha do Monte Hyjal.',
	AN_ATTUNE_BLACK_TEMPLE = 'Uma Distracão para Akama',
	AD_ATTUNE_BLACK_TEMPLE = 'Obtenha o Medalhão de Karabor.',

	AN_SSC = 'Caverna Serpentária',
	AD_SSC = 'Derrote os chefes listados abaixo dentro da Caverna Serpentária.',
	AC_KILL_HYDROS = 'Hydross, o Instável',
	AC_KILL_LURKER = 'A Espreitadora Abaixo',
	AC_KILL_LEOTHERAS = 'Leotheras, o Cego',
	AC_KILL_KARATHRESS = 'Senhor-Abismal Karathress',
	AC_KILL_MOROGRIM = 'Morogrim Caminhamaré',
	AC_KILL_VASHJ = 'Lady Vashj',
	AN_TK = 'Fortaleza da Tempestade',
	AD_TK = 'Derrote os chefes listados abaixo dentro do Olho.',
	AC_KILL_ALAR = 'Al\'ar',
	AC_KILL_VOID_REAVER = 'Leitor do Vazio',
	AC_KILL_SOLARIAN = 'Alta-Astromante Solarian',
	AC_KILL_KAELTHAS = 'Kael\'thas Sumidouro do Sol',

	AN_HYJAL = 'A Batalha do Monte Hyjal',
	AD_HYJAL = 'Derrote Archimonde na Batalha do Monte Hyjal.',

	AN_BT_ENTRANCE = 'Infiltração',
	AD_BT_ENTRANCE = 'Abra caminho dentro do Templo Negro pelos Esgotos de Karabor derrotando os chefes listados abaixo.',
	AC_KILL_NAJENTUS = 'Alto Senhor da Guerra Naj\'entus',
	AC_KILL_SUPREMUS = 'Supremus',

	AN_BT_SECOND_WING = 'Acólito de Karabor',
	AD_BT_SECOND_WING = 'Purifique os salões principais do Templo Negro do mal que se instalou lá derrotando os chefes listados abaixo.',
	AC_KILL_SHADOW_OF_AKAMA = 'Espectro de Akama',
	AC_KILL_THERON = 'Teron Espírito Sangrento',
	AC_KILL_GURTOGG = 'Gurtogg Fervor Sangüíneo',
	AC_KILL_RELIQUARY = 'Relicário das Almas',

	AN_BT_LAST_WING = 'Topo do Templo',
	AD_BT_LAST_WING = 'Infiltre os andares superiores do Templo Negro e derrote os chefes listados abaixo.',
	AC_KILL_MOTHER_SHAHRAZ = 'Mãe Shahraz',
	AC_KILL_BT_COUNCIL = 'O Conselho Illidari',
	AC_KILL_ILLIDAN = 'Illidan Tempesfúria',

	AN_BLACK_TEMPLE = 'O Templo Negro',
	AD_BLACK_TEMPLE = 'Obtenha as conquistas listadas abaixo derrotando todos os chefes do Templo Negro.',
	AR_BLACK_TEMPLE = 'Conquistador do Templo Negro',

	AN_ARENA_FIRST_WIN = 'Entre na Arena',
	AD_ARENA_FIRST_WIN = 'Vença uma partida de arena classificada no nível 70.',
	AN_ARENA_WIN1 = 'Dedicado Impiedosamente',
	AD_ARENA_WIN1 = 'Vença 100 partidas de arena classificadas no nível 70.',
	AN_ARENA_WIN2 = 'Dedicado Vingativamente',
	AD_ARENA_WIN2 = 'Vença 200 partidas de arena classificadas no nível 70.',
	AN_ARENA_WIN3 = 'Dedicado Brutalmente',
	AD_ARENA_WIN3 = 'Vença 300 partidas de arena classificadas no nível 70.',

	AN_ARENA_TITLE1 = 'Gladiador',
	AN_ARENA_TITLE2 = 'Duelista',
	AN_ARENA_TITLE3 = 'Rival',
	AN_ARENA_TITLE4 = 'Desafiante',

	AN_ARENA_GLADIATOR = 'Gladiador',
	AD_ARENA_GLADIATOR = 'Obtenha o título de Gladiador em uma temporada de arena no nível 70.',
	AN_ARENA_DUELIST = 'Duelista',
	AD_ARENA_DUELIST = 'Obtenha o título de Duelista em uma temporada de arena no nível 70.',
	AN_ARENA_RIVAL = 'Rival',
	AD_ARENA_RIVAL = 'Obtenha o título de Rival em uma temporada de arena no nível 70.',
	AN_ARENA_CHALLENGER = 'Desafiante',
	AD_ARENA_CHALLENGER = 'Obtenha o título de Desafiante em uma temporada de arena no nível 70.',

	AN_ARENA_2_1550 = 'Só Nós Dois: 1550',
	AD_ARENA_2_1550 = 'Alcance uma classificação pessoal de 1550 na categoria 2v2 da arena no nível 70.',
	AN_ARENA_2_1750 = 'Só Nós Dois: 1750',
	AD_ARENA_2_1750 = 'Alcance uma classificação pessoal de 1750 na categoria 2v2 da arena no nível 70.',
	AN_ARENA_2_2000 = 'Só Nós Dois: 2000',
	AD_ARENA_2_2000 = 'Alcance uma classicação pessoal de 2000 na categoria 2v2 da arena no nível 70.',
	AN_ARENA_2_2200 = 'Só Nós Dois: 2200',
	AD_ARENA_2_2200 = 'Alcance uma classificação pessoal de 2200 na categoria 2v2 da arena no nível 70.',

	AN_ARENA_3_1550 = 'Trio em Companhia: 1550',
	AD_ARENA_3_1550 = 'Alcance uma classificação pessoal de 1550 na categoria 3v3 da arena no nível 70.',
	AN_ARENA_3_1750 = 'Trio em Companhia: 1750',
	AD_ARENA_3_1750 = 'Alcance uma classificação pessoal de 1750 na categoria 3v3 da arena no nível 70.',
	AN_ARENA_3_2000 = 'Trio em Companhia: 2000',
	AD_ARENA_3_2000 = 'Alcance uma classificação pessoal de 2000 na categoria 3v3 da arena no nível 70.',
	AN_ARENA_3_2200 = 'Trio em Companhia: 2200',
	AD_ARENA_3_2200 = 'Alcance uma classificação pessoal de 2200 na categoria 3v3 da arena no nível 70.',

	AN_ARENA_5_1550 = 'Cinco em Alta: 1550',
	AD_ARENA_5_1550 = 'Alcance uma classificação pessoal de 1550 na categoria 5v5 da arena no nível 70.',
	AN_ARENA_5_1750 = 'Cinco em Alta: 1750',
	AD_ARENA_5_1750 = 'Alcance uma classificação pessoal de 1750 na categoria 5v5 da arena no nível 70.',
	AN_ARENA_5_2000 = 'Cinco em Alta: 2000',
	AD_ARENA_5_2000 = 'Alcance uma classificação pessoal de 2000 na categoria 5v5 da arena no nível 70.',
	AN_ARENA_5_2200 = 'Cinco em Alta: 2200',
	AD_ARENA_5_2200 = 'Alcance uma classificação pessoal de 2200 na categoria 5v5 da arena no nível 70.',

	AN_ARENA_STREAK = 'Sequência Quente',
	AD_ARENA_STREAK = 'Vença dez partidas classificadas seguidas no nível 70.',

	AN_ARENA_HOTSTREAK = 'Sequência Mais Quente',
	AD_ARENA_HOTSTREAK = 'Vença dez partidas classificadas seguidas com classificação acima de 1800 no nível 70.',

	AN_ARENA_LASTMAN = 'Último em Pé',
	AD_ARENA_LASTMAN = 'Seja o único sobrevivente ao final de uma partida classificada 5v5 no nível 70.',

	AN_ARENA_MAPS = 'Vencedor Mundial',
	AD_ARENA_MAPS = 'Vença uma partida de arena classificada na Lâmina, Nagrand e nas Ruínas de Lordaeron no nível 70.',    
	AC_ARENA_MAPS1 = 'Arena da Lâmina',
	AC_ARENA_MAPS2 = 'Arena de Nagrand',
	AC_ARENA_MAPS3 = 'Ruínas de Lordaeron',

	AN_ARENA_MASTER = 'O Mestre da Arena',
	AD_ARENA_MASTER = 'Complete as conquistas de arena listadas abaixo.',

	AN_AZZINOTH = 'Gládios de Azzinoth',
	AD_AZZINOTH = 'Portador de um par de Gládios de Azzinoth.',
	AN_THORIDAL = 'Thori\'dal, a Fúria das Estrelas',
	AD_THORIDAL = 'Portador de Thori\'dal, a Fúria das Estrelas.',
	AC_OBTAIN_MAINHAND_AZZINOTH = 'Glaive Direito de Azzinoth',
	AC_OBTAIN_OFFHAND_AZZINOTH = 'Glaive Esquerdo de Azzinoth',
	AN_BEAR_MOUNT = 'Urso de Guerra Amani',
	AD_BEAR_MOUNT = 'Dono do Urso de Guerra Amani.',
	AN_HAWK_MOUNT = 'Falcossauro Branco Veloz',
	AD_HAWK_MOUNT = 'Obtenha o Falcossauro Branco Veloz de Kael\'thas Sumidouro do Sol no Terraço dos Magísteres.',
	AN_ALAR_MOUNT = 'Cinzas de Al\'ar',
	AD_ALAR_MOUNT = 'Obtenha as Cinzas de Al\'ar de Kael\'thas Sumidouro do Sol na Fortaleza da Tempestade.',
	AN_HORSEMAN_MOUNT = 'Rédeas do Cavaleiro',
	AD_HORSEMAN_MOUNT = 'Obtenha as Rédeas do Cavaleiro do Cavaleiro Sem Cabeça no Monastério Escarlate durante a Véspera das Bruxas.',
	AN_HERO_SHATTRATH = 'Herói de Shattrath',
	AD_HERO_SHATTRATH = 'Alcançou status exaltado com Os Aureus e Os Aldor.',
	AN_HERO_SCRYER = 'Os Aureus',
	AN_HERO_ALDOR = 'Os Aldor',
	AN_CHAMPION_NAARU = 'Campeão do Naaru',
	AD_CHAMPION_NAARU = 'Obteve o título, "Campeão do Naaru".',
	AR_CHAMPION_NAARU = 'Campeão do Naaru',
	AN_HAND_ADAL = 'Mão de A\'dal',
	AD_HAND_ADAL = 'Obteve o título, "Mão de A\'dal".',
	AR_HAND_ADAL = 'Mão de A\'dal',

	AN_P3_FIRST_WEEK = 'Conquistador de Terralém',
	AD_P3_FIRST_WEEK = 'Derrote Archimonde e Illidan Tempesfúria em suas respectivas raides dentro da primeira semana do lançamento da Fase Três.',
	AC_KILL_ARCHIMONDE = 'Archimonde',
	AR_P3_FIRST_WEEK = 'Conquistador de Terralém',
	
	AN_FLIGHFORM = 'Forma de Voo Veloz',
	AD_FLIGHFORM = 'Completou a missão de druida para obter a Forma de Voo Veloz.',

	AN_KRUUL = '...não outro Senhor Demônio!',
	AD_KRUUL = 'Derrote o Alto-Lorde Kruul durante a Batalha pelo Portal Negro.',

	AN_ATTUMEN_MOUNT = 'Rédeas do Cavalo de Guerra Flamejante',
	AD_ATTUMEN_MOUNT = 'Obtenha as Rédeas do Cavalo de Guerra Flamejante de Attumen, o Caçador, em Karazhan.'
})
